src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Quote from which this Contract was created.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Event.object
<CustomObject>
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <label>Event</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Briefing_Statement__c</fullName>
        <description>Additional information to the property management team.</description>
        <inlineHelpText>Additional information to the property management team.</inlineHelpText>
        <label>Briefing Statement</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <recordTypes>
        <fullName>Virtual</fullName>
        <active>true</active>
        <businessProcess>Virtual Sales Process</businessProcess>
        <label>Virtual</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Serviced_Space_Coordinator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Serviced Space Coordinator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Properties4</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Quotes (Contract)</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__PrimaryContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Primary contact for the quote. This person&apos;s name will appear on generated quote document.</description>
        <inlineHelpText>Primary contact for the quote. This person&apos;s name will appear on generated quote document.</inlineHelpText>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <recordTypes>
        <fullName>Virtual</fullName>
        <active>true</active>
        <label>Virtual</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__QuoteDocument__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteDocumentHelp</customHelpPage>
    <description>Particular version of a generated PDF document for the quote it&apos;s attached to. Ability to edit or delete this object should be taken away from all users (except administrators, of course) in order to preserve audit trail of all revisions.</description>
    <fields>
        <fullName>Opportunity_Owner_Id__c</fullName>
        <formula>SBQQ__Quote__r.SBQQ__Opportunity2__r.OwnerId</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity Owner Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this Quote Document belongs.</description>
        <inlineHelpText>Quote to which this Quote Document belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Documents</relationshipLabel>
        <relationshipName>R00N70000001lX7YEAU</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TaskService.cls
public with sharing class TaskService {
    public static final String PRIORITY_NORMAL = 'Normal';
    public static final String STATUS_OPEN = 'Open';
    public static final String TYPE_VIRTUAL_ONBOARDING = 'Virtual Customer on-boarding';
    public static final String TYPE_OTHER = 'Other';

    public static final String SUBJECT_SETUP_CD = 'Setup Director Contact';
    public static final String SUBJECT_REVIEW_PC = 'Please review new/updated contact on the Quote';
    public static final String SUBJECT_VIRTUAL_CUSTOMER_ID = 'Virtual Customer ID';
    public static final String SUBJECT_REVIEW_SUITE_CONDITION = 'Please review suite condition. Negative feedback recieved';

    public static final String PAY_BY_BACS_SYSTEM_CODE = 'PayByBACs';
    public static final String SETUP_CD_SYSTEM_CODE = 'SetupCD';
    public static final String REVIEW_POTENTIAL_CONTACT_SYSTEM_CODE = 'ReviewPC';

    public static final Id STANDARD_TASK_TYPE_ID;
    static {
        STANDARD_TASK_TYPE_ID = Schema.SObjectType.Task.getRecordTypeInfosByName().get('Standard Task').getRecordTypeId();
    }

    public static Task generateVirtualMeetingTask(Opportunity theOpportunity, Event theEvent) {
        return new Task(
                Priority = PRIORITY_NORMAL,
                Status = STATUS_OPEN,
                Type = TYPE_VIRTUAL_ONBOARDING,
                Subject = SUBJECT_VIRTUAL_CUSTOMER_ID,
                RecordTypeId = STANDARD_TASK_TYPE_ID,

                OwnerId = theEvent.Property__r.Serviced_Space_Coordinator__c,
                Opportunity__c = theOpportunity.Id, // Opportunity Name
                Property__c = theEvent.Property__c, // Property Name
                Description = theOpportunity.Briefing_Statement__c,
                WhoId = theEvent.WhoId, // Sales Contact
                WhatId = theOpportunity.AccountId // Account Name
        );
    }

    public static Task generateVirtualTask(Opportunity theOpportunity, SBQQ__Quote__c quote) {
        return new Task(
                Priority = PRIORITY_NORMAL,
                Status = STATUS_OPEN,
                Type = TYPE_VIRTUAL_ONBOARDING,
                RecordTypeId = STANDARD_TASK_TYPE_ID,

                Subject = quote.SBQQ__PrimaryContact__r.Name + ': New Virtual Customer to be on-boarded',
                OwnerId = quote.Property__r.Serviced_Space_Coordinator__c,
                Property__c = quote.Property__c, // Property Name
                Description = theOpportunity.Briefing_Statement__c,
                WhoId = quote.SBQQ__PrimaryContact__c, // Primary Contact
                WhatId = theOpportunity.AccountId, // Customer
                ActivityDate = quote.Contract__c != null ? quote.Contract__r.StartDate : null
        );
    }

    public static Task generateSetupCDTask(SBQQ__QuoteDocument__c theDocument) {
        return new Task(
            Priority = PRIORITY_NORMAL,
            Status = STATUS_OPEN,
            Type = TYPE_OTHER,
            Subject = SUBJECT_SETUP_CD,
            RecordTypeId = STANDARD_TASK_TYPE_ID,

            OwnerId = theDocument.Opportunity_Owner_Id__c,
            WhatId = theDocument.SBQQ__Quote__c,
            System_Code__c = SETUP_CD_SYSTEM_CODE
        );
    }

    public static Task generateReviewPCTask(Id ownerId, Id potentialContactId) {
        return new Task(
            Subject = SUBJECT_REVIEW_PC,
            WhatId = potentialContactId,
            Priority = PRIORITY_NORMAL,
            Status = STATUS_OPEN,
            Type = TYPE_OTHER,
            OwnerId = ownerId,
            RecordTypeId = STANDARD_TASK_TYPE_ID,
            System_Code__c = REVIEW_POTENTIAL_CONTACT_SYSTEM_CODE
        );
    }

    public static Task generatePropertyManagerNotification(Event theEvent, Id propertyManagerId, String suiteConditionComments) {
        return new Task(
            Priority = PRIORITY_NORMAL,
            Status = STATUS_OPEN,
            Type = TYPE_OTHER,
            Subject = SUBJECT_REVIEW_SUITE_CONDITION,
            RecordTypeId = STANDARD_TASK_TYPE_ID,

            Property__c = theEvent.Property__c,
            WhatId = theEvent.Property__c,
            Viewing_Id__c = theEvent.Id,
            Viewing_Name__c = theEvent.Subject,
            OwnerId = propertyManagerId,
            Description = suiteConditionComments
        );
    }
}