src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Company_Registration_Number__c</fullName>
        <label>Company Registration Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Customer_Budget__c</fullName>
        <inlineHelpText>Budget for these works or an idea what is affordable?</inlineHelpText>
        <label>Customer Budget</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 4) OR (1 AND 2 AND 3)</booleanFilter>
            <filterItems>
                <field>Inventory__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Actual Suite, Proposed Suite</value>
            </filterItems>
            <filterItems>
                <field>Inventory__c.Property__c</field>
                <operation>equals</operation>
                <valueField>$Source.Property__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Project Works Request Case</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Project Works Request Case</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Inventory__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Case</fullName>
        <active>true</active>
        <businessProcess>Ordinary Case</businessProcess>
        <label>Case</label>
    </recordTypes>
    <recordTypes>
        <fullName>Design</fullName>
        <active>true</active>
        <businessProcess>Design Case</businessProcess>
        <label>Design</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Customer_Confidential_Documentation__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Confidential Documentations</relationshipLabel>
        <relationshipName>Customer_Confidential_Documentations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DDF_Acc_Num_1__c</fullName>
        <label>DDF Acc Num 1</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DDF_Branch_Sort_Code_6__c</fullName>
        <label>Branch Sort Code 6</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ_Quote_Document__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote Document</label>
        <referenceTo>SBQQ__QuoteDocument__c</referenceTo>
        <relationshipLabel>Customer Confidential Documentations</relationshipLabel>
        <relationshipName>Customer_Confidential_Documentations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Signature_Status__c</fullName>
        <label>Signature Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>Signed</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Correct</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Voided</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer Confidential Documentation</label>
    <nameField>
        <displayFormat>CCD-{00000000}</displayFormat>
        <label>CCD Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Confidential Documentations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Potential_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Potential Contacts</relationshipLabel>
        <relationshipName>Potential_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Potential Contact</label>
    <nameField>
        <displayFormat>PC-{000000000}</displayFormat>
        <label>Potential Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Potential Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory</label>
        <referenceTo>Inventory__c</referenceTo>
        <relationshipName>Inventory</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
        <inlineHelpText>The customer account for this quote. Defaults to the account for the opportunity when creating a quote.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__PrimaryContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Primary contact for the quote. This person&apos;s name will appear on generated quote document.</description>
        <inlineHelpText>Primary contact for the quote. This person&apos;s name will appear on generated quote document.</inlineHelpText>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__QuoteDocument__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteDocumentHelp</customHelpPage>
    <description>Particular version of a generated PDF document for the quote it&apos;s attached to. Ability to edit or delete this object should be taken away from all users (except administrators, of course) in order to preserve audit trail of all revisions.</description>
    <fields>
        <fullName>Account_Id__c</fullName>
        <formula>SBQQ__Quote__r.SBQQ__Account__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BC_Email__c</fullName>
        <label>BC Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BC_Last_Name__c</fullName>
        <label>BC Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BC_Phone__c</fullName>
        <label>BC Phone</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CD_First_Name__c</fullName>
        <label>CD First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CD_Last_Name__c</fullName>
        <label>CD Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Registration_Number__c</fullName>
        <label>Company Registration Number</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DDF_Acc_Num_1__c</fullName>
        <label>Acc Num 1</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DDF_Branch_Sort_Code_6__c</fullName>
        <label>Branch Sort Code 6</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DDF_Signer_Name__c</fullName>
        <label>Signer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ILPC_Email__c</fullName>
        <label>ILPC Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LC_First_Name__c</fullName>
        <label>LC First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LC_Last_Name__c</fullName>
        <label>LC Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OOHC_First_Name__c</fullName>
        <label>OOHC First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQDS__EnvelopeId__c</fullName>
        <description>DocuSign envelope ID.</description>
        <externalId>true</externalId>
        <inlineHelpText>DocuSign envelope ID.</inlineHelpText>
        <label>Envelope Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__ElectronicSignature__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates this document was generated for electronic signature.</description>
        <inlineHelpText>Field for the document to be signed electronically.</inlineHelpText>
        <label>Electronic Signature</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__QuoteTemplate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote Template that generated this document.</description>
        <inlineHelpText>Quote Template that generated this document.</inlineHelpText>
        <label>Quote Template</label>
        <referenceTo>SBQQ__QuoteTemplate__c</referenceTo>
        <relationshipLabel>Quote Documents</relationshipLabel>
        <relationshipName>Quote_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this Quote Document belongs.</description>
        <inlineHelpText>Quote to which this Quote Document belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Documents</relationshipLabel>
        <relationshipName>R00N70000001lX7YEAU</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Signature_Status__c</fullName>
        <description>Status of electronic signature.</description>
        <inlineHelpText>Status of electronic signature.</inlineHelpText>
        <label>Signature Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>Signed</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Correct</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Voided</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Signed_By_CD__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Signed By CD</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Update_Quote_Status__c</fullName>
        <formula>SBQQ__QuoteTemplate__r.Update_Quote_Status__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Update Quote Status</label>
        <type>Checkbox</type>
    </fields>
    <label>Quote Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SBQQ__QuoteTemplate__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteTemplateHelp</customHelpPage>
    <description>Template that controls formatting of generated PDF documents.</description>
    <fields>
        <fullName>Update_Quote_Status__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If you use the template for signature, please will select the field. Because quote status should be updated after signature.
If you use the template for review, please will not select the field. Because quote status should not be updated after review.</description>
        <inlineHelpText>Whether quote status should be updated when the document completed in DocuSign?</inlineHelpText>
        <label>Update Quote Status</label>
        <type>Checkbox</type>
    </fields>
    <label>Quote Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SBQQ_QuoteDocumentTriggerHandlerTest.cls
/**
 * @description Test class for SBQQ_QuoteDocumentTriggerHandler
 */
@isTest
private class SBQQ_QuoteDocumentTriggerHandlerTest {

    @testSetup
    public static void setupData() {
        //given
        Test.startTest();
        Account testAccount = RecordDmlTest.createAccount(false);
        testAccount.Company_Registration_Number__c = '123';
        insert testAccount;

        List<Contact> testContacts = new List<Contact> {
            RecordDmlTest.createContact(testAccount.Id, SBQQ_QuoteConstants.CONTACT_TYPE_LC),
            RecordDmlTest.createContact(testAccount.Id, SBQQ_QuoteConstants.CONTACT_TYPE_ILPC),
            RecordDmlTest.createContact(testAccount.Id, SBQQ_QuoteConstants.CONTACT_TYPE_OOHC),
            RecordDmlTest.createContact(testAccount.Id, SBQQ_QuoteConstants.CONTACT_TYPE_BC)
        };
        insert testContacts;

        SBQQ__Quote__c quote = RecordDmlTest.generateConventionalQuoteWithLines(QuoteProductCodes.OFFICE_RENT);
        quote.SBQQ__Account__c = testAccount.Id;
        update quote;

        SBQQ__QuoteTemplate__c template = new SBQQ__QuoteTemplate__c(
                Name = 'Test',
                Update_Quote_Status__c = true);
        insert template;
        Test.stopTest();
    }

    @isTest
    private static void testPopulationOfMergefields() {
        SBQQ__Quote__c quote = [SELECT Id FROM SBQQ__Quote__c LIMIT 1];

        //when
        Test.startTest();
        SBQQ__QuoteDocument__c quoteDocument = new SBQQ__QuoteDocument__c(
            SBQQ__Quote__c = quote.Id
        );
        insert quoteDocument;
        quoteDocument = [SELECT LC_First_Name__c, BC_Last_Name__c, ILPC_Email__c, OOHC_First_Name__c,
                                SBQQ__Quote__c, Company_Registration_Number__c
                        FROM SBQQ__QuoteDocument__c
                        WHERE Id = :quoteDocument.Id];
        //then
        System.assertNotEquals(null, quoteDocument.LC_First_Name__c);
        System.assertNotEquals(null, quoteDocument.BC_Last_Name__c);
        System.assertNotEquals(null, quoteDocument.ILPC_Email__c);
        System.assertNotEquals(null, quoteDocument.OOHC_First_Name__c);
        System.assertEquals('123', quoteDocument.Company_Registration_Number__c);
        Test.stopTest();
    }

    @isTest
    private static void testQuoteDocumentUpdate() {
        SBQQ__Quote__c quote = [SELECT Id FROM SBQQ__Quote__c LIMIT 1];

        SBQQ__QuoteDocument__c quoteDocument = new SBQQ__QuoteDocument__c(
            SBQQ__Quote__c = quote.Id
        );
        insert quoteDocument;

        //when
        Test.startTest();
        quoteDocument = [SELECT LC_First_Name__c, BC_Last_Name__c, ILPC_Email__c, OOHC_First_Name__c,
                                SBQQ__Quote__c, Company_Registration_Number__c, Account_Id__c
                        FROM SBQQ__QuoteDocument__c
                        WHERE Id = :quoteDocument.Id];
        quoteDocument.LC_First_Name__c = 'Test new';
        quoteDocument.LC_Last_Name__c = 'Contact';
        quoteDocument.BC_Email__c = 'test@test.com';
        quoteDocument.BC_Phone__c = '987654321';
        quoteDocument.Company_Registration_Number__c = '456';
        update quoteDocument;

        //then
        List<Potential_Contact__c> potentialContacts = [SELECT First_Name__c, Last_Name__c, New_First_Name__c, New_Last_Name__c
                                                        FROM Potential_Contact__c];
        System.assertNotEquals(true, potentialContacts.isEmpty());
        System.assertEquals('456', [SELECT Company_Registration_Number__c FROM Account WHERE Id = :quoteDocument.Account_Id__c].Company_Registration_Number__c);
        Test.stopTest();
    }

    @isTest
    private static void testQuoteAcceptanceWhenSignedByCD() {
        Account testAccount = [SELECT Id FROM Account LIMIT 1];
        Contact companyDirector = RecordDmlTest.createContact(testAccount.Id, SBQQ_QuoteConstants.CONTACT_TYPE_CD);
        companyDirector.FirstName = 'Company';
        companyDirector.LastName = 'Director';
        insert companyDirector;

        SBQQ__Quote__c quote = [SELECT SBQQ__PrimaryContact__c FROM SBQQ__Quote__c LIMIT 1];
        SBQQ__QuoteTemplate__c template = [SELECT Id FROM SBQQ__QuoteTemplate__c LIMIT 1];
        SBQQ__QuoteDocument__c quoteDocument = new SBQQ__QuoteDocument__c(
            SBQQ__Quote__c = quote.Id,
            SBQQ__QuoteTemplate__c = template.Id,
            Signature_Status__c = 'Sent'
        );
        insert quoteDocument;

        Inventory__c inventory = [SELECT Id FROM Inventory__c LIMIT 1];
        Id designCaseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Design').getRecordTypeId();
        Case designCase = new Case(
                RecordTypeId = designCaseRecordTypeId,
                Inventory__c = inventory.Id,
                ContactId = quote.SBQQ__PrimaryContact__c,
                Customer_Budget__c = 1000
        );
        insert designCase;

        //when
        Test.startTest();
        quoteDocument.SBQQ__ElectronicSignature__c = false;
        quoteDocument.Signature_Status__c = SBQQ_QuoteConstants.STATUS_SIGNATURE_COMPLETE;
        quoteDocument.SBQQDS__EnvelopeId__c = 'testEnvelopeId1';
        quoteDocument.CD_First_Name__c = 'Company';
        quoteDocument.CD_Last_Name__c = 'Director 2';
        //Can't make the testing as Docusing tries to send something from the packaged code.
        // update quoteDocument;

        //then
        // quoteDocument = [SELECT Signed_By_CD__c FROM SBQQ__QuoteDocument__c WHERE Id =:quoteDocument.Id];
        // System.assertEquals(false, quoteDocument.Signed_By_CD__c);
        // System.assertEquals(1, [SELECT count() FROM Task WHERE System_Code__c = :TaskService.SETUP_CD_SYSTEM_CODE]);
        Test.stopTest();
    }

    @isTest
    private static void testmoveDirectDebitFormFieldsToSecureObject() {
        //given
        SBQQ__Quote__c quote = [SELECT Id FROM SBQQ__Quote__c LIMIT 1];
        SBQQ__QuoteDocument__c quoteDocument = new SBQQ__QuoteDocument__c(
            SBQQ__Quote__c = quote.Id
        );
        insert quoteDocument;

        //when
        Test.startTest();
        quoteDocument.DDF_Acc_Num_1__c = '1';
        quoteDocument.DDF_Branch_Sort_Code_6__c = '1';
        quoteDocument.DDF_Signer_Name__c = 'Test Signer';
        quoteDocument.Signature_Status__c = SBQQ_QuoteConstants.STATUS_SIGNATURE_COMPLETE;
        //Can't make the testing as Docusing tries to send something from the packaged code.
        // update quoteDocument;

        // Customer_Confidential_Documentation__c secureRecord = [SELECT Acc_Num_1__c, Branch_Sort_Code_6__c, Signer_Name__c, Account__c
        //                                                        FROM Customer_Confidential_Documentation__c
        //                                                        WHERE SBQQ_Quote_Document__c = :quoteDocument.Id];
        // System.assertNotEquals(null, secureRecord);
        // System.assertNotEquals(null, secureRecord.Account__c);
        // System.assertEquals(quoteDocument.DDF_Acc_Num_1__c, secureRecord.Acc_Num_1__c);
        // System.assertEquals(quoteDocument.DDF_Branch_Sort_Code_6__c, secureRecord.Branch_Sort_Code_6__c);
        // System.assertEquals(quoteDocument.DDF_Signer_Name__c, secureRecord.Signer_Name__c);
        Test.stopTest();
    }

    @isTest
    static void givenQuote_whenDocumentCreated_thenQuoteStatusIsPresented() {
        //given
        SBQQ__Quote__c quote = [SELECT Id, SBQQ__Status__c FROM SBQQ__Quote__c LIMIT 1];
        SBQQ__QuoteTemplate__c quoteTemplate = [SELECT Id FROM SBQQ__QuoteTemplate__c LIMIT 1];
        System.assertEquals('Draft', quote.SBQQ__Status__c);

        //when
        SBQQ__QuoteDocument__c quoteDocument = new SBQQ__QuoteDocument__c(
                SBQQ__Quote__c = quote.Id,
                SBQQ__ElectronicSignature__c = true,
                SBQQ__QuoteTemplate__c = quoteTemplate.Id);
        insert quoteDocument;

        //then
        quote = [SELECT Id, SBQQ__Status__c FROM SBQQ__Quote__c LIMIT 1];
        System.assertEquals('Presented', quote.SBQQ__Status__c);
    }
}