src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Agent_Broker</fullName>
        <active>true</active>
        <label>Agent/Broker</label>
    </recordTypes>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CustomerInactivitySettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Inactivity_Expiration_Time__c</fullName>
        <defaultValue>180</defaultValue>
        <description>This expiration time (in days) means closing Opportunity with no any customer activity after this count of days.</description>
        <label>Inactivity Expiration Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Customer Inactivity Settings</label>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Agent_Broker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agent/Broker</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Select Agent/Broker Account.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Agent/Broker</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Agent/Broker)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Lead_Channel</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Closed_Lost_Date__c</fullName>
        <label>Closed Lost Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Closed_Lost_Reason__c</fullName>
        <label>Closed Lost Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Too expensive</fullName>
                </value>
                <value>
                    <fullName>Space too big</fullName>
                </value>
                <value>
                    <fullName>Space too small</fullName>
                </value>
                <value>
                    <fullName>Unsuitable location</fullName>
                </value>
                <value>
                    <fullName>Feasibility study</fullName>
                </value>
                <value>
                    <fullName>Went to competitor</fullName>
                </value>
                <value>
                    <fullName>Requirement retracted</fullName>
                </value>
                <value>
                    <fullName>Lack of car parking</fullName>
                </value>
                <value>
                    <fullName>Unsuitable specification</fullName>
                </value>
                <value>
                    <fullName>See Closed Lost Comments</fullName>
                </value>
                <value>
                    <fullName>Inactivity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Region</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Region</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CustomerInactivityHandlerTest.cls
@isTest
public class CustomerInactivityHandlerTest {

    @isTest static void SingleActiveOpportunityNoClosingTest() {
        Test.startTest();

        Id recordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Agent_Broker' LIMIT 1].Id;

        Account testAccount = new Account(Name = 'Test Account', RecordTypeId = recordTypeId);
        insert testAccount;

        Property__c testProperty = new Property__c(Name = 'Test Property', Street__c = 'Test Address');
        insert testProperty;

        //Given
        Opportunity opportunity = new Opportunity();
        opportunity.Name = 'Customer inactivity test ' + String.valueOf(System.today());
        opportunity.StageName = 'Qualified';
        opportunity.Type = 'New Customer';
        opportunity.CloseDate = Date.valueOf('2019-01-01');
        opportunity.Region__c = 'Leeds';
        opportunity.LeadSource = 'Agent';
        opportunity.Channel__c = 'Email';
        opportunity.Agent_Broker__c = testAccount.Id;
        insert opportunity;

        CustomerInactivitySettings__c settings = new CustomerInactivitySettings__c();
        settings.Name = 'INACTIVITY_EXPIRATION_TIME';
        settings.Inactivity_Expiration_Time__c = 180;
        insert settings;

        //When
        String jobId = System.schedule('testBasicScheduleApex', '0 0 0 * * ?',
            new CustomerInactivityScheduledHandler());

        CronTrigger cronTrigger = [SELECT Id, CronExpression, TimesTriggered, NextFireTime
                                   FROM CronTrigger WHERE Id = :jobId];
        Time expectTime = Time.newInstance(0, 0, 0, 0);
        Datetime expectNextFireTime = Datetime.newInstance(System.now().date() + 1, expectTime);

        System.assertEquals(cronTrigger.CronExpression, '0 0 0 * * ?');
        System.assertEquals(0, cronTrigger.TimesTriggered);
        System.assertEquals(expectNextFireTime, cronTrigger.NextFireTime);

        Test.stopTest();

        Opportunity retrievedOpportunity = [SELECT Id, StageName, IsClosed, Name, CloseDate, Closed_Lost_Date__c, Closed_Lost_Reason__c
                       FROM Opportunity WHERE Id = :opportunity.Id];
        //Then
        System.assertEquals(opportunity.Id, retrievedOpportunity.Id);
        System.assertEquals(Opportunity.Name, retrievedOpportunity.Name);
        System.assertNotEquals(System.now().date(), retrievedOpportunity.CloseDate);
        System.assertNotEquals(System.now().date(), retrievedOpportunity.Closed_Lost_Date__c);
        System.assertNotEquals('Inactivity', retrievedOpportunity.Closed_Lost_Reason__c);
        System.assertNotEquals('Closed Lost', retrievedOpportunity.StageName);
        System.assertNotEquals(true, retrievedOpportunity.IsClosed);
    }
}