src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Legal</fullName>
        <active>true</active>
        <label>Legal</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Customer_Confidential_Documentation__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Confidential Documentations</relationshipLabel>
        <relationshipName>Customer_Confidential_Documentations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Signed__c</fullName>
        <label>Date Signed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Legal_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Legal Entity</label>
        <referenceTo>c2g__codaCompany__c</referenceTo>
        <relationshipLabel>Customer Confidential Documentations</relationshipLabel>
        <relationshipName>Customer_Confidential_Documentations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Master__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Master</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Send_Customer_Acknowledgement_Letter__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send Customer Acknowledgement Letter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Signature_Status__c</fullName>
        <label>Signature Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>Signed</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Correct</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Voided</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer Confidential Documentation</label>
    <nameField>
        <displayFormat>CCD-{00000000}</displayFormat>
        <label>CCD Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Confidential Documentations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CustomerConfDocumentationTriggerHandler.cls
public with sharing class CustomerConfDocumentationTriggerHandler extends TriggerHandler {

    @TestVisible
    private final static String ERROR_MSG_THERE_CAN_ONLY_BE_ONE_MASTER = 'There can only be one master document per salesforce account per legal entity.';
    private CustomerConfidentialDocumentationService confidentialService = new CustomerConfidentialDocumentationService();

    public override void beforeInsert() {
        customValidationCDD(Trigger.new);
    }

    public override void beforeUpdate() {
        customValidationCDD(Trigger.new);
        List<Customer_Confidential_Documentation__c> signedForms = getSignedForms(Trigger.new, (Map<Id, Customer_Confidential_Documentation__c>) Trigger.oldMap);
        confidentialService.updateDirectDebitFormCompiledFields(signedForms);
        updateSignedDate(signedForms);
    }

    public override void afterUpdate() {
        generateAcknowledgementLetters(Trigger.new, Trigger.oldMap);
    }

    private List<Customer_Confidential_Documentation__c> getSignedForms(List<Customer_Confidential_Documentation__c> newForms, Map<Id, Customer_Confidential_Documentation__c> oldMap) {
        List<Customer_Confidential_Documentation__c> signedForms = new List<Customer_Confidential_Documentation__c>();
        for (Customer_Confidential_Documentation__c ddForm : newForms) {
            Customer_Confidential_Documentation__c oldForm = oldMap.get(ddForm.Id);
            if (oldForm.Signature_Status__c != ddForm.Signature_Status__c && ddForm.Signature_Status__c == 'Completed') {
                signedForms.add(ddForm);
            }
        }
        return signedForms;
    }

    private void updateSignedDate(List<Customer_Confidential_Documentation__c> signedForms) {
        for (Customer_Confidential_Documentation__c ddForm : signedForms) {
            ddForm.Date_Signed__c = Date.today();
        }
    }

    private static void customValidationCDD(List<Customer_Confidential_Documentation__c> newForms) {
        Set<Id> skipFormForValidation = new Set<Id>();
        Set<Id> accountIds = SObjectUtils.getIdSetFromObjects(newForms, 'Account__c');
        for (Customer_Confidential_Documentation__c ccd : newForms) {
            if (ccd.Id != null) {
                skipFormForValidation.add(ccd.Id);
            }
        }
        Set<String> masterCCDs = new Set<String>();
        for (Customer_Confidential_Documentation__c cdd : [
                SELECT Id, Account__c, Legal_Entity__c
                FROM Customer_Confidential_Documentation__c
                WHERE Master__c = TRUE
                AND Legal_Entity__c != null
                AND Account__c IN :accountIds
        ]) {
            if (!skipFormForValidation.contains(cdd.Id)) {
                masterCCDs.add('' + cdd.Account__c + cdd.Legal_Entity__c);
            }
        }
        for (Customer_Confidential_Documentation__c cdd : newForms) {
            if (cdd.Master__c && masterCCDs.contains('' + cdd.Account__c + cdd.Legal_Entity__c)) {
                cdd.Master__c.addError(ERROR_MSG_THERE_CAN_ONLY_BE_ONE_MASTER);
            }
        }
    }

    private void generateAcknowledgementLetters(List<Customer_Confidential_Documentation__c> docs, Map<Id, sObject> oldMap) {
        Set<Id> customerConfDocIds = new Set<Id>();
        for (Customer_Confidential_Documentation__c doc: docs) {
            Customer_Confidential_Documentation__c oldDoc = (Customer_Confidential_Documentation__c)oldMap.get(doc.Id);
            if (doc.Send_Customer_Acknowledgement_Letter__c && !oldDoc.Send_Customer_Acknowledgement_Letter__c) {
                customerConfDocIds.add(doc.Id);
            }
        }
        generateAcknowledgementLetter(customerConfDocIds);
    }

    @future
    public static void generateAcknowledgementLetter(Set<Id> customerConfDocIds) {
        Id templateId = EmailHelper.getEmailTemplateId('CCD_Customer_Acknowledgement');

        if (templateId != null && !customerConfDocIds.isEmpty()) {
            List<Attachment> attachments = new List<Attachment>();
            for (Id ccdId: customerConfDocIds) {
                Messaging.SingleEmailMessage mail = Messaging.renderStoredEmailTemplate(templateId, UserInfo.getUserId(), ccdId);

                for (Messaging.EmailFileAttachment emailFileAttachment : mail.getFileAttachments()) {
                    attachments.add(new Attachment(
                        Body = emailFileAttachment.getBody(),
                        Name = emailFileAttachment.getFileName(),
                        ParentId = ccdId)
                    );
                }
            }
            upsert attachments;
        }
    }
}