src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Company_Registration_Number__c</fullName>
        <label>Company Registration Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>SBQQ__Status__c</fullName>
        <description>Status indicating where quote is in its lifecycle.</description>
        <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Presented</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Pending Approval - Offline Edit</fullName>
                </value>
                <value>
                    <fullName>Awaiting Approval - Offline Edit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <recordTypes>
        <fullName>Serviced</fullName>
        <active>true</active>
        <label>Serviced</label>
    </recordTypes>
    <recordTypes>
        <fullName>Virtual</fullName>
        <active>true</active>
        <label>Virtual</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__QuoteDocument__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteDocumentHelp</customHelpPage>
    <description>Particular version of a generated PDF document for the quote it&apos;s attached to. Ability to edit or delete this object should be taken away from all users (except administrators, of course) in order to preserve audit trail of all revisions.</description>
    <fields>
        <fullName>Account_Id__c</fullName>
        <formula>SBQQ__Quote__r.SBQQ__Account__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Registration_Number__c</fullName>
        <label>Company Registration Number</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DDF_Acc_Num_1__c</fullName>
        <label>Acc Num 1</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quote_Record_Type__c</fullName>
        <formula>SBQQ__Quote__r.RecordType.DeveloperName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Quote Record Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__ElectronicSignature__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates this document was generated for electronic signature.</description>
        <inlineHelpText>Field for the document to be signed electronically.</inlineHelpText>
        <label>Electronic Signature</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this Quote Document belongs.</description>
        <inlineHelpText>Quote to which this Quote Document belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Documents</relationshipLabel>
        <relationshipName>R00N70000001lX7YEAU</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SBQQ__SignatureStatus__c</fullName>
        <description>Status of electronic signature.</description>
        <inlineHelpText>Status of electronic signature.</inlineHelpText>
        <label>Signature Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>Signed</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Correct</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Voided</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Signature_Status__c</fullName>
        <description>Status of electronic signature.</description>
        <inlineHelpText>Status of electronic signature.</inlineHelpText>
        <label>Signature Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>Signed</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Correct</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Voided</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Update_Quote_Status__c</fullName>
        <formula>SBQQ__QuoteTemplate__r.Update_Quote_Status__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Update Quote Status</label>
        <type>Checkbox</type>
    </fields>
    <label>Quote Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SBQQ_QuoteDocumentTriggerHandler.cls
public with sharing class SBQQ_QuoteDocumentTriggerHandler extends TriggerHandler {

    private SBQQ_QuoteDocumentService theDocumentService = new SBQQ_QuoteDocumentService();
    private PotentialContactService thePotentialContactService = new PotentialContactService();
    private ContactService theContactService = new ContactService();
    private AccountService theAccountService = new AccountService();

    public override void beforeInsert() {
        prepopulateCustomerContactsFields(Trigger.new);
        prepopulateCustomerRegistrationNumber(Trigger.new);
        theDocumentService.populateUniqueDocumentsNumber(Trigger.new);
    }

    public override void afterInsert() {
        List<SBQQ__QuoteDocument__c> documents = (List<SBQQ__QuoteDocument__c>) Trigger.new;
        updateQuoteStatusWithPresented(documents);
    }

    public override void beforeUpdate() {
        syncSignatureStatusFields(Trigger.new);
        moveDirectDebitFormFieldsToSecureObject((Map<Id, SBQQ__QuoteDocument__c>)Trigger.oldMap, Trigger.new);
        verifyIfDocumentsSignedByCompanyDirector((Map<Id, SBQQ__QuoteDocument__c>)Trigger.oldMap, Trigger.new);
    }

    public override void afterUpdate() {
        Map<SBQQ__QuoteDocument__c, Set<String>> updatedDocumentsMap = theDocumentService.getDocumentsWithUpdatedContactInfo((Map<Id, SBQQ__QuoteDocument__c>)Trigger.oldMap, Trigger.new);
        thePotentialContactService.createPotentialContactsForUpdatedDocuments(updatedDocumentsMap, (Map<Id, SBQQ__QuoteDocument__c>)Trigger.oldMap);
        updateCompanyRegistrationNumbers((Map<Id, SBQQ__QuoteDocument__c>)Trigger.oldMap, Trigger.new);
        theDocumentService.updateParentOpportunities(Trigger.new);
    }

    private void prepopulateCustomerContactsFields(List<SBQQ__QuoteDocument__c> quoteDocuments) {
        Map<Id, Id> quoteToAccountMap = theDocumentService.getRelatedAccountIdsMap(quoteDocuments);
        Map<Id, List<Contact>> contactsMap = theContactService.getCustomerContactsMap(new Set<Id>(quoteToAccountMap.values()));
        for ( SBQQ__QuoteDocument__c theDocument : quoteDocuments ) {
            theDocumentService.populateQuoteDocumentFields(theDocument, contactsMap.get(quoteToAccountMap.get(theDocument.SBQQ__Quote__c)));
        }
    }

    private void prepopulateCustomerRegistrationNumber(List<SBQQ__QuoteDocument__c> quoteDocuments) {
        Map<Id, Id> quoteToAccountMap = theDocumentService.getRelatedAccountIdsMap(quoteDocuments);
        Map<Id, Account> relatedAccountsMap = new Map<Id, Account>([SELECT Company_Registration_Number__c FROM Account WHERE Id IN :quoteToAccountMap.values()]);
        for ( SBQQ__QuoteDocument__c theDocument : quoteDocuments ) {
            theDocument.Company_Registration_Number__c = relatedAccountsMap.get(theDocument.Account_Id__c).Company_Registration_Number__c;
        }
    }

    private void updateCompanyRegistrationNumbers(Map<Id, SBQQ__QuoteDocument__c> oldDocumentsMap, List<SBQQ__QuoteDocument__c> quoteDocuments) {
        Map<Id, String> accountIdToCompanyNumberMap = theDocumentService.getAccountIdsWithUpdatedCompanyNumber(oldDocumentsMap, quoteDocuments);
        theAccountService.updateCompanyRegistrationNumbers(accountIdToCompanyNumberMap);
    }

    private void verifyIfDocumentsSignedByCompanyDirector(Map<Id, SBQQ__QuoteDocument__c> oldDocumentsMap, List<SBQQ__QuoteDocument__c> quoteDocuments) {
        List<SBQQ__QuoteDocument__c> servicedDocuments = theDocumentService.getDocumentsWithRecordType(quoteDocuments, SBQQ_QuoteConstants.SERVICED_RECORD_TYPE);
        Map<Id, SBQQ__QuoteDocument__c> signedDocumentsMap = theDocumentService.getSignedDocumentsMap(servicedDocuments);
        Set<Id> accountIds = new Set<Id>();
        for ( SBQQ__QuoteDocument__c theDocument : signedDocumentsMap.values() ) {
            SBQQ__QuoteDocument__c oldDocument = oldDocumentsMap.get(theDocument.Id);
            if ( oldDocument.SBQQ__SignatureStatus__c != theDocument.SBQQ__SignatureStatus__c ) {
                accountIds.add(theDocument.Account_Id__c);
            }
        }
        Map<Id, List<Contact>> companyDirectorsMap = theContactService.getCompanyDirectorsMap(accountIds);
        theDocumentService.verifyIfDocumentsSignedByCompanyDirector(signedDocumentsMap.values(), companyDirectorsMap);
    }

    private void moveDirectDebitFormFieldsToSecureObject(Map<Id, SBQQ__QuoteDocument__c> oldDocumentsMap, List<SBQQ__QuoteDocument__c> quoteDocuments) {
        CustomerConfidentialDocumentationService ccdService = new CustomerConfidentialDocumentationService();
        Map<Id, SBQQ__QuoteDocument__c> signedDocumentsMap = theDocumentService.getSignedDocumentsMap(quoteDocuments);
        List<SBQQ__QuoteDocument__c> signedSecureDocuments = new List<SBQQ__QuoteDocument__c>();
        for ( SBQQ__QuoteDocument__c theDocument : signedDocumentsMap.values() ) {
            SBQQ__QuoteDocument__c oldDocument = oldDocumentsMap.get(theDocument.Id);
            if ( oldDocument.SBQQ__SignatureStatus__c != theDocument.SBQQ__SignatureStatus__c && String.isNotBlank(theDocument.DDF_Acc_Num_1__c) &&
                    (theDocument.Quote_Record_Type__c.startsWith('Serviced') || theDocument.Quote_Record_Type__c.startsWith('Virtual') )) {
                signedSecureDocuments.add(theDocument);
            }
        }
        ccdService.moveDirectDebitFormFieldsToSecureObject(signedSecureDocuments);
    }

    private void updateQuoteStatusWithPresented(List<SBQQ__QuoteDocument__c> documents) {
        Set<Id> quotesIds = new Set<Id>();
        for (SBQQ__QuoteDocument__c document : documents) {
            if (document.SBQQ__Quote__c != null && document.SBQQ__ElectronicSignature__c && document.Update_Quote_Status__c) {
                quotesIds.add(document.SBQQ__Quote__c);
            }
        }
        List<SBQQ__Quote__c> quotes = updateQuotesWithSpecifiedStatus([SELECT Id, SBQQ__Status__c FROM SBQQ__Quote__c WHERE Id IN :quotesIds], 'Presented');
        update quotes;
    }

    private List<SBQQ__Quote__c> updateQuotesWithSpecifiedStatus(List<SBQQ__Quote__c> quotes, String status) {
        for (SBQQ__Quote__c quote : quotes) {
            quote.SBQQ__Status__c = status;
        }
        return quotes;
    }

    private void syncSignatureStatusFields(List<SBQQ__QuoteDocument__c> newDocuments) {
        for ( SBQQ__QuoteDocument__c theDocument : newDocuments ) {
            theDocument.SBQQ__SignatureStatus__c = theDocument.Signature_Status__c;
        }
    }

}