src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>Text( Property__r.Region__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Quote from which this Contract was created.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Activated</fullName>
        <active>true</active>
        <label>Activated</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Event.object
<CustomObject>
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <label>Event</label>
    </recordTypes>
    <recordTypes>
        <fullName>Viewing</fullName>
        <active>true</active>
        <label>Viewing</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Region</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Virtual</fullName>
        <active>true</active>
        <businessProcess>Virtual Sales Process</businessProcess>
        <label>Virtual</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The quote where the order is created from.</description>
        <inlineHelpText>The quote where the order is created from.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Region</valueSetName>
        </valueSet>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>No_Viewing_Required_Comment__c</fullName>
        <description>Stores a comment of a sales user why he generates a quote with no a viewing</description>
        <label>No Viewing Required Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Opportunity2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity associated with this Quote.</description>
        <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__PrimaryContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Primary contact for the quote. This person&apos;s name will appear on generated quote document.</description>
        <inlineHelpText>Primary contact for the quote. This person&apos;s name will appear on generated quote document.</inlineHelpText>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Type__c</fullName>
        <description>Indicates the type of quote.</description>
        <inlineHelpText>Indicates the type of quote.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New_deal</fullName>
                    <default>true</default>
                    <label>New Deal</label>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Surrender_and_regrant</fullName>
                    <label>Surrender and regrant</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Surrender_Premium__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Surrender Premium</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Surrender_deed_due_date__c</fullName>
        <defaultValue>ADDMONTHS(TODAY(),1)</defaultValue>
        <label>Surrender deed due date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Surrender_deed_weeks__c</fullName>
        <defaultValue>4</defaultValue>
        <label>Surrender deed weeks</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <recordTypes>
        <fullName>Virtual</fullName>
        <active>true</active>
        <label>Virtual</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GenerateQuoteController.cls
public with sharing class GenerateQuoteController {

    public static final String NEW_DEAL = 'New_deal';
    public static final String CONTRACT_OPTIONS = 'contractOptions';
    public static final String SELECT_CONTRACTS = 'selectContracts';
    public static final String SELECT_MASTER_CONTRACT = 'selectMasterContract';
    public static final String VIEWING_SELECTION = 'viewingSelection';
    public static final String NO_VIEWING_COMMENT = 'noViewingComment';
    public static final String PROPERTY_CONTACT_SELECTION = 'propertyContactSelection';
    public static final String DONE = 'done';

    public Opportunity opportunity { get; set; }
    public View currentView { get; set; }
    public String contractOption { get; set; }
    public String[] selectedContractsIds { get; set; }
    public String selectMasterContract { get; set; }
    public Id selectedViewingId { get; set; }
    public String selectedProperty { get; set; }
    public Id selectedContactId { get; set; }
    public String noViewingComment { get; set; }

    private Map<Id, Contract> contractsMap;
    private Map<Id, Event> viewingsMap;
    private Map<String, Id> propertyMap;
    private Map<Id, Contact> contactMap;

    private SBQQ__Quote__c quote;


    public GenerateQuoteController() {
        String opportunityId = ApexPages.currentPage().getParameters().get('Id');
        opportunity = findOpportunityById(opportunityId);
        contractsMap = findActiveContracts(opportunityId);
        viewingsMap = findViewings(opportunityId);
        propertyMap = findProperties();
        contactMap = findContacts(opportunity);
        quote = null;
        contractOption = NEW_DEAL;
        setInitialView();
    }

    @TestVisible
    private static Opportunity findOpportunityById(Id opportunityId) {
        List<Opportunity> opportunities = [
                select Id, Region__c, RecordTypeId, AccountId, Type, Pricebook2Id, RecordType.DeveloperName, Name,
                        Account.Name
                from Opportunity
                where Id = :opportunityId
        ];
        if (opportunities.size() != 0) {
            return opportunities.get(0);
        }
        return null;
    }

    private Map<Id, Contract> findActiveContracts(Id opportunityId) {
        if (String.isBlank(opportunityId)) {
            return new Map<Id, Contract>();
        }

        return new Map<Id, Contract>([
                select Id, Name
                from Contract
                where AccountId = :opportunity.AccountId
                and Pricebook2Id = :opportunity.Pricebook2Id
                and (Status = 'Activated' OR Status = 'Live')
                order by CreatedDate desc
        ]);
    }

    private Map<Id, Event> findViewings(Id opportunityId) {
        if (String.isBlank(opportunityId)) {
            return new Map<Id, Event>();
        }
        return new Map<Id, Event>([
                SELECT Id, Property__c, WhoId, Subject
                FROM Event
                WHERE IsChild = false
                and RecordType.DeveloperName = 'Viewing'
                and Status__c = 'Completed'
                and WhatId = :opportunityId
        ]);
    }

    private Map<String, Id> findProperties() {
        Map<String, Id> nameIdMap = new Map<String, Id>();
        for (Property__c property : [select Id, Name from Property__c where Active__c = true]) {
            nameIdMap.put(property.Name, property.Id);
        }
        return nameIdMap;
    }

    private Map<Id, Contact> findContacts(Opportunity opportunity) {
        if (opportunity == null || opportunity.AccountId == null) {
            return new Map<Id, Contact>();
        }

        List<AccountContactRelation> accountContacts = new List<AccountContactRelation>(
        [SELECT Id, ContactId, Contact.LastName, Contact.FirstName, Contact.Name FROM AccountContactRelation WHERE Contact.Active__c = true
            AND AccountId = :opportunity.AccountId
            AND IsActive = true]);

        Set<Id> contactIds = SObjectUtils.getIdSetFromObjects(accountContacts, 'ContactId');

        return new Map<Id, Contact> ([SELECT Id, Name FROM Contact WHERE Id IN : contactIds]);
    }

    public void next() {
        if (currentView.isValidToGoNext(this)) {
            currentView = currentView.goNext(String.isBlank(selectedViewingId), contractOption);
            if (currentView.name == DONE) {
                quote = generateQuote();
            }
        }
    }

    public void back() {
        if (currentView.previousView != null) {
            currentView = currentView.previousView;
        }
    }

    public PageReference finish() {
        return new PageReference('/' + quote.Id);
    }

    public List<SelectOption> getContractOptions() {
        List<SelectOption> contractsOptions = new List<SelectOption>();
        for (Id contractId : contractsMap.keySet()) {
            contractsOptions.add(new SelectOption(contractId, contractsMap.get(contractId).Name));
        }
        return contractsOptions;
    }

    public List<SelectOption> getSelectedContractOptions() {
        List<SelectOption> contractsOptions = new List<SelectOption>();
        for (Id contractId : selectedContractsIds) {
            contractsOptions.add(new SelectOption(contractId, contractsMap.get(contractId).Name));
        }
        return contractsOptions;
    }

    public List<SelectOption> getViewingOptions() {
        List<SelectOption> viewingOptions = new List<SelectOption>();
        for (Id viewingId : viewingsMap.keySet()) {
            viewingOptions.add(new SelectOption(viewingId, viewingsMap.get(viewingId).Subject));
        }
        viewingOptions.add(new SelectOption('', 'No Viewing Required'));
        return viewingOptions;
    }

    public Set<String> getProperties() {
        return propertyMap.keySet();
    }

    public List<SelectOption> getContactOptions() {
        List<SelectOption> contactOptions = new List<SelectOption>();
        for (Id contactId : contactMap.keySet()) {
            contactOptions.add(new SelectOption(contactId, contactMap.get(contactId).Name));
        }
        return contactOptions;
    }

    private SBQQ__Quote__c generateQuote() {
        if (contractOption != NEW_DEAL) {// we have to generate quote from contracts
            return QuoteFromContractCreator.generate(opportunity, selectMasterContract, selectedContractsIds, contractOption);
        }
        SBQQ__Quote__c generatedQuote = new SBQQ__Quote__c();
        generatedQuote.Property__c = propertyMap.get(selectedProperty);
        generatedQuote.SBQQ__Type__c = contractOption;
        generatedQuote.Surrender_Premium__c = null; //TODO: Why do we need to clear these fields?
        generatedQuote.Surrender_deed_due_date__c = null;
        generatedQuote.Surrender_deed_weeks__c = null;
        generatedQuote.RecordTypeId = RecordTypeHelper.getSbqqQuoteRtIdByDeveloperName(opportunity.RecordType.DeveloperName);
        generatedQuote.SBQQ__Opportunity2__c = opportunity.Id;
        if (selectedViewingId == null) {
            generatedQuote.No_Viewing_Required_Comment__c = noViewingComment;
            generatedQuote.SBQQ__PrimaryContact__c = selectedContactId;
        } else {
            generatedQuote.Property__c = viewingsMap.get(selectedViewingId).Property__c;
            Id primaryContact = viewingsMap.get(selectedViewingId).WhoId;
            if (primaryContact != null && Contact.getSObjectType() == primaryContact.getSobjectType()) {
                generatedQuote.SBQQ__PrimaryContact__c = primaryContact;
            }
        }
        insert generatedQuote;
        return generatedQuote;
    }

    private class View {
        public String name { get; set; }
        public View previousView { get; set; }

        public View(String name) {
            this.name = name;
            previousView = null;
        }

        public View(String name, View view) {
            this.name = name;
            previousView = view;
        }

        public View goNext(Boolean noViewingRequired, String contractOption) {
            String newViewName = '';

            if (name == CONTRACT_OPTIONS) {
                if (contractOption == NEW_DEAL) {
                    newViewName = VIEWING_SELECTION;
                } else {
                    newViewName = SELECT_CONTRACTS;
                }
            }

            if (name == VIEWING_SELECTION) {
                if (noViewingRequired) {
                    newViewName = NO_VIEWING_COMMENT;
                } else {
                    newViewName = DONE;
                }
            }
            if (name == SELECT_CONTRACTS) {
                newViewName = SELECT_MASTER_CONTRACT;
            }

            if (name == SELECT_MASTER_CONTRACT || name == PROPERTY_CONTACT_SELECTION) {
                newViewName = DONE;
            }

            if (name == NO_VIEWING_COMMENT) {
                newViewName = PROPERTY_CONTACT_SELECTION;
            }

            return new View(newViewName, this);
        }

        private Boolean isValidToGoNext(GenerateQuoteController c) {
            if (name == PROPERTY_CONTACT_SELECTION && c.propertyMap.get(c.selectedProperty) == null) {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ' Please select valid property'));
                return false;
            }
            if (name == PROPERTY_CONTACT_SELECTION && String.isBlank(c.selectedContactId)) {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ' Please select a contact'));
                return false;
            }
            if (name == SELECT_CONTRACTS && c.selectedContractsIds.IsEmpty()) {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ' Please select a contract'));
                return false;
            }
            return true;
        }
    }

    private void setInitialView() {
        if (opportunity.Type == 'Existing Customer') {
            currentView = new View(CONTRACT_OPTIONS);
        } else {
            currentView = opportunity.RecordType.DeveloperName == 'Virtual' ? new View(PROPERTY_CONTACT_SELECTION) : new View(VIEWING_SELECTION);
        }
    }
}