src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Registered_Name__c</fullName>
        <label>Registered Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/c2g__AllocationFilter__c.object
<CustomObject>
    <customHelpPage>c2g__codahelpallocationfilter</customHelpPage>
    <description>Stores the queries for selecting and filtering allocation data for the allocation template.</description>
    <fields>
        <fullName>c2g__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Allocation Filter</label>
    <nameField>
        <displayFormat>AF{000000}</displayFormat>
        <label>Allocation Filter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Allocation Filters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Company_Address__c</fullName>
        <formula>Company__r.c2g__ShortStreet__c + &apos;, &apos; + Company__r.c2g__City__c + &apos;, &apos; + Company__r.c2g__ZipPostCode__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Company Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Logo__c</fullName>
        <formula>Company__r.c2g__LogoURL__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Company Logo</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Name__c</fullName>
        <formula>Company__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Company Name</label>
        <type>Text</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>BW_Signature__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BW Signature</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Quotes (BW Signature)</relationshipLabel>
        <relationshipName>BW_Signed_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
        <inlineHelpText>The customer account for this quote. Defaults to the account for the opportunity when creating a quote.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <label>Term</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>New_Annual_Average__c</fullName>
        <label>New Annual Average (£)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Quote Lines (Property)</relationshipLabel>
        <relationshipName>QuoteLines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__ProductCode__c</fullName>
        <description>Code for the product referenced by this line.</description>
        <formula>SBQQ__Product__r.ProductCode</formula>
        <inlineHelpText>Code for the product referenced by this line.</inlineHelpText>
        <label>Product Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <label>Term</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CarParkingLicenceDocumentGenerator.cls
public class CarParkingLicenceDocumentGenerator {

    public static final String CAR_PARKING_LICENSE_PRODUCT_CODE = 'CarParkLicense';
    public static final String CAR_SPACE_PRODUCT_CODE = 'CarSpace';
    public SBQQ__Quote__c quote { get; set; }
    public List<SBQQ__QuoteLine__c> carParkingLicensesAndSpaces { get; set; }
    public SBQQ__QuoteLine__c carParkingLicense { get; set; }
    public Integer carParkingSpacesQuantity { get; set; }

    public CarParkingLicenceDocumentGenerator() {
        Id quoteId = (Id) ApexPages.currentPage().getParameters().get('id');
        carParkingSpacesQuantity = 0;
        if (quoteId != NULL) {
            quote = [
                    SELECT Id, Property__r.Company_Name__c, SBQQ__Account__r.Registered_Name__c,
                            Property__r.Name, Property__r.Company_Logo__c,
                            Property__r.Company_Address__c, SBQQ__Account__r.ShippingStreet,
                            SBQQ__Account__r.ShippingCity, SBQQ__Account__r.ShippingPostalCode,
                            BW_Signature__r.Name
                    FROM SBQQ__Quote__c
                    WHERE Id = :quoteId
            ];
        }
        carParkingLicensesAndSpaces = [
                SELECT Id, New_Annual_Average__c, Start_Date__c, Term__c,
                        SBQQ__ProductCode__c
                FROM SBQQ__QuoteLine__c
                WHERE SBQQ__Quote__c = :quoteId
                AND (SBQQ__ProductCode__c = :CAR_PARKING_LICENSE_PRODUCT_CODE
                        OR SBQQ__ProductCode__c = :CAR_SPACE_PRODUCT_CODE)
        ];
        calculateTotalAnnualAverageAndQuantity(carParkingLicensesAndSpaces);
    }

    private void calculateTotalAnnualAverageAndQuantity(List<SBQQ__QuoteLine__c> carParkingLicenseSpaceList) {
        for (SBQQ__QuoteLine__c carParkingLicenseSpace : carParkingLicenseSpaceList) {
            if (carParkingLicenseSpace.SBQQ__ProductCode__c == CAR_PARKING_LICENSE_PRODUCT_CODE) {
                carParkingLicense = carParkingLicenseSpace;
            } else {
                carParkingSpacesQuantity += 1;
            }
        }
    }
}