src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 4) OR (1 AND 2 AND 3)</booleanFilter>
            <filterItems>
                <field>Inventory__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Actual Suite, Proposed Suite</value>
            </filterItems>
            <filterItems>
                <field>Inventory__c.Property__c</field>
                <operation>equals</operation>
                <valueField>$Source.Property__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Project Works Request Case</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Project Works Request Case</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Inventory__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReasonForLoss__c</fullName>
        <label>Reason for Loss</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>Used for list view filtering</description>
        <formula>Text(Inventory__r.Property__r.Region__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Used for list view filtering</inlineHelpText>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Case</fullName>
        <active>true</active>
        <businessProcess>Ordinary Case</businessProcess>
        <label>Case</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>Text( Property__r.Region__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Quote from which this Contract was created.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Inventory__c.object
<CustomObject>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Inventories</relationshipLabel>
        <relationshipName>Inventories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR (3 AND 4) OR (5 AND 6) OR 7</booleanFilter>
            <errorMessage>Please select the Product that meets the Inventory Record Type</errorMessage>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Actual Suite, Proposed Suite</value>
            </filterItems>
            <filterItems>
                <field>Product2.ProductCode</field>
                <operation>equals</operation>
                <value>OfficeRent, LabSpace, RetailRent, Storage, BSLF, BSDL</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Desk</value>
            </filterItems>
            <filterItems>
                <field>Product2.ProductCode</field>
                <operation>equals</operation>
                <value>BSCW</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Car Parking</value>
            </filterItems>
            <filterItems>
                <field>Product2.ProductCode</field>
                <operation>equals</operation>
                <value>CarSpace</value>
            </filterItems>
            <filterItems>
                <field>Product2.ProductCode</field>
                <operation>equals</operation>
                <value>BSHD, PreEmptionAgreement</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Inventories</relationshipLabel>
        <relationshipName>Suites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipName>Suites</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>Used for list views, should be kept off report types and page layouts to where the property region is used to avoid confusion</description>
        <formula>Text(Property__r.Region__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <label>Inventory</label>
    <nameField>
        <label>Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Products</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Region</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Property_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Properties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Region</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Quotes (Contract)</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory</label>
        <referenceTo>Inventory__c</referenceTo>
        <relationshipName>Inventory</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
        <inlineHelpText>The customer account for this quote. Defaults to the account for the opportunity when creating a quote.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CaseTriggerHandlerTest.cls
@IsTest
private class CaseTriggerHandlerTest {
    @isTest static void testCaseInventory() {
        Account newAccount = RecordDmlTest.createAccount();
        Contact newContact = new Contact(AccountId = newAccount.Id, FirstName = 'Sidor', LastName = 'Sidorov', Email = 'test@test.com');
        insert newContact;

        SBQQ__Quote__c newQuote = RecordDmlTest.generateConventionalQuoteWithLines(ProductService.PRODUCT_CODE_OFFICE_RENT);

        Case testCase;
        Test.startTest();
        testCase = new Case(
                AccountId = newAccount.Id,
                ContactId = newContact.Id,
                RecordTypeId = RecordTypeHelper.getCaseRtIdByDeveloperName(CaseService.LEASE_TRANSACTION_RECORD_TYPE),
                Quote__c = newQuote.Id,
                Status = 'New',
                ReasonForLoss__c = 'Test',
                Origin = 'Email'
        );
        insert testCase;

        testCase = [SELECT Id, Inventory__c FROM Case WHERE Id = :testCase.Id];
        System.assert(testCase.Inventory__c != null);

        Test.stopTest();
    }

    @isTest static void createCaseUpdateContract() {
        Case testCase = prepareTestCase(Constants.STATUS_CLOSED_LOST);
        Id quote = testCase.Quote__c;
        SBQQ__Quote__c testQuote = [SELECT Id, Contract__r.Status FROM SBQQ__Quote__c WHERE Id = :quote];
        System.assertEquals(Constants.STATUS_NOT_COMPLETED, testQuote.Contract__r.Status);
    }

    @isTest
    static void givenCasesWithOpenTasksWhenCaseCompletedThenCaseNotUpdated() {
        Case caseWithOpenTask = new Case(Subject = 'Test Case', Status = 'Open');
        Case caseWithoutOpenTask = new Case(Subject = 'Test Case', Status = 'Open');
        insert caseWithOpenTask;
        insert caseWithoutOpenTask;

        Task openTask = new Task(Status = 'Open', WhatId = caseWithOpenTask.Id);
        Task completedTask = new Task(Status = 'Completed', WhatId = caseWithoutOpenTask.Id);
        insert openTask;
        insert completedTask;

        caseWithOpenTask.Status = 'Completed';
        caseWithoutOpenTask.Status = 'Completed';


        update caseWithoutOpenTask;
        try {
            update caseWithOpenTask;
        } catch (Exception e) {
            System.debug(e.getMessage());
        }

        System.assertEquals('Open', [SELECT Id, Status FROM Case WHERE Id = :caseWithOpenTask.Id].Status);
        System.assertEquals('Completed',[SELECT Id, Status FROM Case WHERE Id = :caseWithoutOpenTask.Id].Status);
    }

    /*@isTest
    static void givenAccountwhenSLACaseCreatedThenEntitlementPopulatedFromAccount() {
        //given TODO: UNCOMMENT
        Property__c property = RecordDmlTest.createProperty();

        SBQQ__Quote__c quote = RecordDmlTest.createCPQQuote();
        quote.Property__c = property.Id;
        upsert quote;

        Id slaCaseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Lease Transaction').getRecordTypeId();

        System.assertEquals(1, [select count() from Entitlement]);

        Case testCase = new Case(
                AccountId = quote.SBQQ__Account__c,
                Quote__c = quote.Id,
                recordTypeId = slaCaseRecordTypeId,
                Status = 'New',
                Origin = 'Email');
        insert testCase;

        testCase = [select id, EntitlementId from Case where id = :testCase.id];

        System.assertNotEquals(null, testCase.EntitlementId);
    }*/

    private static Case prepareTestCase(String status) {
        Id caseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Lease Transaction').getRecordTypeId();

        User testUser = RecordDmlTest.createUser('bwstandarduser', 'BW Standard User');
        insert testUser;

        Account newAccount = new Account(Name = 'Test Company', Industry = 'Banking');
        insert newAccount;

        Contact newContact = new Contact(AccountId = newAccount.Id, FirstName = 'Sidor', LastName = 'Sidorov',
                Email = 'test@test.com');
        insert newContact;

        Opportunity newOpportunity = new Opportunity(AccountId = newAccount.Id, Name = 'Test Opportunity',
                Type = 'Existing Customer', StageName = 'Qualified', CloseDate = System.today() + 10, Product__c = 'Office',
                Region__c = 'Manchester City Centre', LeadSource = 'Advertisement');
        insert newOpportunity;

        Property__c newProperty = new Property__c(Name = 'Test property', Property_Manager__c = testUser.id,
                Region__c = 'Manchester City Centre', Street__c = 'TestStreet');
        insert newProperty;

        SBQQ__Quote__c newQuote = RecordDmlTest.createQuote(newProperty, newOpportunity, OpportunityService.CONVENTIONAL_RECORD_TYPE);

        Contract newContract = RecordDmlTest.createContract(newQuote, newProperty);

        newQuote.Contract__c = newContract.Id;

        update newQuote;

        Case testCase = new Case(
                AccountId = newAccount.Id,
                ContactId = newContact.Id,
                recordTypeId = caseRecordTypeId,

                Quote__c = newQuote.Id,
                Status = 'New',
                ReasonForLoss__c = 'Test',
                Origin = 'Email');
        insert testCase;
        testCase.Status = status;
        update testCase;
        return testCase;
    }
}