src/objects/Ad_hoc_Revenue__c.object
<CustomObject>
    <description>Custom Object to capture ad-hoc revenue that does not require a contract</description>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Currency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>GBP</fullName>
                    <default>true</default>
                    <label>GBP</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ad-hoc Revenue</relationshipLabel>
        <relationshipName>Ad_hoc_Revenue</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Reference__c</fullName>
        <label>Customer Reference</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <label>Document Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Invoice</fullName>
                </value>
                <value>
                    <fullName>Credit Note</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>From_Date__c</fullName>
        <label>From Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_Description__c</fullName>
        <label>Invoice Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Legal_Entity__c</fullName>
        <description>FinancialForce Company Name</description>
        <label>Legal Entity</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Period__c</fullName>
        <label>Period</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Ad-hoc Revenue</relationshipLabel>
        <relationshipName>Ad_hoc_Revenue</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Ad-hoc Revenue</relationshipLabel>
        <relationshipName>Ad_hoc_Revenue</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tax_Code__c</fullName>
        <label>Tax Code</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>To_Date__c</fullName>
        <label>To Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Ad-hoc Revenue</label>
    <nameField>
        <displayFormat>AdRev{00000000}</displayFormat>
        <label>Ad-hoc Revenue Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ad-hoc Revenue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/c2g__codaCompany__c.object
<CustomObject>
    <customHelpPage>c2g__codahelpcompany</customHelpPage>
    <description>Stores the FinancialForce company details.</description>
    <fields>
        <fullName>c2g__ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Company</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/c2g__codaTaxCode__c.object
<CustomObject>
    <customHelpPage>c2g__codahelptaxcode</customHelpPage>
    <description>Stores details on tax codes.</description>
    <fields>
        <fullName>c2g__ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Tax Code</label>
    <nameField>
        <label>Tax Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tax Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Meeting_Room_Booking__c.object
<CustomObject>
    <fields>
        <fullName>Ad_hoc_Revenue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ad-hoc Revenue</label>
        <referenceTo>Ad_hoc_Revenue__c</referenceTo>
        <relationshipName>Meeting_Room_Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Code__c</fullName>
        <description>A unique booking code used to refer to the booking</description>
        <externalId>true</externalId>
        <label>Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Created_Date__c</fullName>
        <description>The date on which the booking was created</description>
        <label>Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Customer_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Meeting_Room_Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Email__c</fullName>
        <description>The customer’s email address</description>
        <label>Customer Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <description>The customer’s full name</description>
        <label>Customer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Paid_Total__c</fullName>
        <description>The total amount the customer has paid on the order</description>
        <label>Order Paid Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Order_Sub_Total__c</fullName>
        <description>The sub-total of all charges added to the order</description>
        <label>Order Sub Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Order_Tax_Total__c</fullName>
        <description>The sum of all taxes applied to the order</description>
        <label>Order Tax Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Order_Total__c</fullName>
        <description>The total of all charges and taxes added to the order</description>
        <label>Order Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The current status code of the booking</description>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Meeting Room Booking</label>
    <nameField>
        <displayFormat>MRB-{000000000}</displayFormat>
        <label>Meeting Room Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meeting Room Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CreateAdHocRecordsController.cls
public with sharing class CreateAdHocRecordsController {
    public static final String ERROR_MESSAGE = 'An Ad-hoc Revenue record has already been created for the selected meeting room booking';
    public static final String TAX_CODE_NAME = 'GB-O-STD';
    public static final String COMPANY_NAME = 'Bruntwood Meeting Rooms Limited';

    public List<MeetingPaymentInfo> adHocRecords { get; set; }

    private Set<Id> recordIds;

    public CreateAdHocRecordsController(ApexPages.StandardSetController stdSetController) {
        List<Meeting_Room_Booking__c> selectedRecords = (List<Meeting_Room_Booking__c>) stdSetController.getSelected();
        this.recordIds = new Map<Id, sObject>(selectedRecords).keySet();
        this.adHocRecords = new List<MeetingPaymentInfo>();
    }

    public CreateAdHocRecordsController(ApexPages.StandardController stdController) {
        this.recordIds = new Set<Id>{
                stdController.getId()
        };
        this.adHocRecords = new List<MeetingPaymentInfo>();
    }

    public PageReference createRecords() {
        PageReference thePage;
        this.adHocRecords = this.createAdHocRecords(this.recordIds);

        if (this.adHocRecords.size() == 1 && !this.adHocRecords.get(0).hasError()) {
            thePage = new PageReference('/' + this.adHocRecords.get(0).adHocRecord.Id);
            thePage.setRedirect(true);
        }
        return thePage;
    }

    private List<MeetingPaymentInfo> createAdHocRecords(Set<Id> meetingIds) {
        List<Meeting_Room_Booking__c> meetings = this.getMeetingRoomPayments(meetingIds);
        C2G__codaTaxCode__c taxCode = this.getTaxCode();
        C2G__codaCompany__c company = this.getCompany();

        Map<Id, MeetingPaymentInfo> outputMap = new Map<Id, MeetingPaymentInfo>();
        List<Ad_hoc_Revenue__c> adHocRecords = new List<Ad_hoc_Revenue__c>();
        List<Id> meetingIdsToUpdate = new List<Id>();

        for (Meeting_Room_Booking__c meeting : meetings) {
            MeetingPaymentInfo info = new MeetingPaymentInfo(meeting);
            outputMap.put(meeting.Id, info);

            if (!info.hasError()) {
                Ad_hoc_Revenue__c adHocRecord = this.generateAdHocRecord(meeting, taxCode, company);
                info.adHocRecord = adHocRecord;
                adHocRecords.add(adHocRecord);
                meetingIdsToUpdate.add(meeting.Id);
            }
        }

        List<Meeting_Room_Booking__c> meetingRoomsToUpdate = new List<Meeting_Room_Booking__c>();
        List<Database.SaveResult> saveResults = Database.insert(adHocRecords, false);
        for (Integer order = 0; order < saveResults.size(); order++) {
            Database.SaveResult sr = saveResults.get(order);
            Id meetingId = meetingIdsToUpdate.get(order);

            if (!sr.isSuccess()) {
                List<String> errs = new List<String>();
                for (Database.Error err : sr.getErrors()) {
                    errs.add(err.getMessage());
                }
                outputMap.get(meetingId).message = String.join(errs, '\n');
            } else {
                outputMap.get(meetingId).meeting.Ad_hoc_Revenue__c = sr.getId();
                meetingRoomsToUpdate.add(outputMap.get(meetingId).meeting);
            }
        }
        update meetingRoomsToUpdate;
        return outputMap.values();
    }

    private Ad_hoc_Revenue__c generateAdHocRecord(Meeting_Room_Booking__c meeting, C2G__codaTaxCode__c taxCode, C2G__codaCompany__c company) {
        Date createdDate = meeting.Created_Date__c != null ? meeting.Created_Date__c.date() : null;

        return new Ad_hoc_Revenue__c(
                Legal_Entity__c = company.Name,
                Customer_Account__c = meeting.Customer_Account__c,
                Customer_Reference__c = meeting.Code__c,
                CurrencyIsoCode = meeting.CurrencyIsoCode,
                Currency__c = 'GBP',
                //Property__c = tempProperty.Id, //TODO: will be implemented after Tobie answer in 1628 story
                Due_Date__c = createdDate,
                Invoice_Date__c = createdDate,
                //Invoice_Description__c = 'Invoice Description', //TODO: will be implemented after Tobie answer in 1628 story
                //Period__c = 'Period', //TODO: will be implemented after Tobie answer in 873 and 1628 story
                //Product__c = tempProduct2.Id, //TODO: will be implemented after Tobie answer in 1628 story
                Quantity__c = 1.0,
                Unit_Price__c = meeting.Order_Paid_Total__c,
                //Document_Type__c = 'Invoice', //TODO: will be implemented after Tobie answer in 1628 story
                //From_Date__c = Date.today(), //TODO: will be implemented after Tobie answer in 1628 story
                //To_Date__c = Date.today() //TODO: will be implemented after Tobie answer in 1628 story
                Tax_Code__c = taxCode.Name
        );
    }

    private List<Meeting_Room_Booking__c> getMeetingRoomPayments(Set<Id> meetingIds) {
        return [
                SELECT Id, Name, CurrencyIsoCode, Code__c, Created_Date__c, Customer_Email__c, Customer_Name__c, Order_Paid_Total__c,
                        Order_Sub_Total__c, Order_Tax_Total__c, Order_Total__c, Status__c, Customer_Account__c, Ad_hoc_Revenue__c
                FROM Meeting_Room_Booking__c
                WHERE Id IN:meetingIds
        ];
    }

    private C2G__codaTaxCode__c getTaxCode() {
        C2G__codaTaxCode__c record = new C2G__codaTaxCode__c();
        List<C2G__codaTaxCode__c> taxCodes = [
                SELECT Id, Name, c2g__ExternalId__c
                FROM C2G__codaTaxCode__c
                WHERE Name = :TAX_CODE_NAME
                LIMIT 1
        ];
        if (!taxCodes.isEmpty()) {
            record = taxCodes.get(0);
        }
        return record;
    }

    private C2G__codaCompany__c getCompany() {
        C2G__codaCompany__c company = new C2G__codaCompany__c();
        List<C2G__codaCompany__c> companies = [SELECT Id, Name FROM C2G__codaCompany__c WHERE Name = :COMPANY_NAME];
        if (!companies.isEmpty()) {
            company = companies.get(0);
        }
        return company;
    }

    public class MeetingPaymentInfo {
        public Meeting_Room_Booking__c meeting { get; set; }
        public Ad_hoc_Revenue__c adHocRecord { get; set; }
        public String message { get; set; }

        public MeetingPaymentInfo(Meeting_Room_Booking__c meeting) {
            this.meeting = meeting;
            if (this.meeting.Ad_hoc_Revenue__c != null) {
                this.message = ERROR_MESSAGE;
            }
        }

        public Boolean hasError() {
            return String.isNotBlank(this.message);
        }
    }
}