src/objects/Ad_hoc_Revenue__c.object
<CustomObject>
    <description>Custom Object to capture ad-hoc revenue that does not require a contract</description>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Ad-hoc Revenue</relationshipLabel>
        <relationshipName>Ad_hoc_Revenue</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ad-hoc Revenue</label>
    <nameField>
        <displayFormat>AdRev{00000000}</displayFormat>
        <label>Ad-hoc Revenue Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ad-hoc Revenue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/c2g__codaCompany__c.object
<CustomObject>
    <customHelpPage>c2g__codahelpcompany</customHelpPage>
    <description>Stores the FinancialForce company details.</description>
    <label>Company</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/c2g__codaTaxCode__c.object
<CustomObject>
    <customHelpPage>c2g__codahelptaxcode</customHelpPage>
    <description>Stores details on tax codes.</description>
    <label>Tax Code</label>
    <nameField>
        <label>Tax Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tax Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>c2g__CODATaxCode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Output VAT/GST Code</label>
        <referenceTo>c2g__codaTaxCode__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ValidateAdHocRevenueCtrlTest.cls
@isTest
public class ValidateAdHocRevenueCtrlTest {

    @isTest
    static void testIsTaxCodeFound() {
        String testTaxCode = 'testTaxCode';
        RecordDmlTest.createTaxCode(testTaxCode);
        System.assertEquals(true, ValidateAdHocRevenueCtrl.isTaxCodeFound(testTaxCode));
    }

    @isTest
    static void testIsNotFoundTaxCode() {
        String testTaxCode = 'testTaxCode';
        System.assertEquals(false, ValidateAdHocRevenueCtrl.isTaxCodeFound(testTaxCode));
    }

    @isTest
    static void testIsCompanyFound() {
        String testCompany = 'testCompany';
        RecordDmlTest.createCompany(testCompany);
        System.assertEquals(true, ValidateAdHocRevenueCtrl.isCompanyFound(testCompany));
    }

    @isTest
    static void testIsNotFoundCompany() {
        String testCompany = 'testCompany';
        System.assertEquals(false, ValidateAdHocRevenueCtrl.isCompanyFound(testCompany));
    }

    @isTest
    static void testValuesNotFound() {
        RecordDmlTest.createProducts();
        Product2 suiteProduct = [SELECT Id FROM Product2 WHERE Family = 'suite' AND ProductCode = 'OfficeRent' LIMIT 1];

        c2g__codaTaxCode__c taxCode = RecordDmlTest.createTaxCode(CreateAdHocRecordsController.TAX_CODE_NAME);
        c2g__codaCompany__c company = RecordDmlTest.createCompany(CreateAdHocRecordsController.COMPANY_NAME);
        Property__c prop = RecordDmlTest.createProperty();

        Account testAccount = RecordDmlTest.createAccount();

        List<Ad_hoc_Revenue__c> revenues = RecordDmlTest.createAdHocRevenues(testAccount, taxCode, prop, company, suiteProduct);
        insert revenues;

        company.Name = 'New Name';
        update company;

        Test.startTest();
        try {
            ValidateAdHocRevenueCtrl.validateFields(revenues.get(0).Id);
            System.assert(false, 'the exception was not thrown out');
        } catch (AuraHandledException e) {
            System.assert(e.getMessage().containsIgnoreCase(ValidateAdHocRevenueCtrl.VALUES_NOT_FOUND_ERROR_MSG));
        }
        Test.stopTest();
    }

    @isTest
    static void testRecordNotFound() {
        String adHocId = Schema.SObjectType.Ad_hoc_Revenue__c.getSObjectType().getDescribe().getKeyPrefix() + '0'.repeat(11) + '1';
        Test.startTest();
        try {
            ValidateAdHocRevenueCtrl.validateFields(adHocId);
            System.assert(false, 'the exception was not thrown out');
        } catch (AuraHandledException e) {
            System.assert(e.getMessage().containsIgnoreCase(ValidateAdHocRevenueCtrl.RECORD_NOT_FOUND_ERROR_MSG));
        }
        Test.stopTest();
    }

}