src/objects/Ad_hoc_Revenue__c.object
<CustomObject>
    <description>Custom Object to capture ad-hoc revenue that does not require a contract</description>
    <fields>
        <fullName>Customer_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ad-hoc Revenue</relationshipLabel>
        <relationshipName>Ad_hoc_Revenue</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Ad-hoc Revenue</relationshipLabel>
        <relationshipName>Ad_hoc_Revenue</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ad-hoc Revenue</label>
    <nameField>
        <displayFormat>AdRev{00000000}</displayFormat>
        <label>Ad-hoc Revenue Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ad-hoc Revenue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/c2g__codaCompany__c.object
<CustomObject>
    <customHelpPage>c2g__codahelpcompany</customHelpPage>
    <description>Stores the FinancialForce company details.</description>
    <label>Company</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/c2g__codaTaxCode__c.object
<CustomObject>
    <customHelpPage>c2g__codahelptaxcode</customHelpPage>
    <description>Stores details on tax codes.</description>
    <label>Tax Code</label>
    <nameField>
        <label>Tax Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tax Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Meeting_Room_Booking__c.object
<CustomObject>
    <fields>
        <fullName>Ad_hoc_Revenue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ad-hoc Revenue</label>
        <referenceTo>Ad_hoc_Revenue__c</referenceTo>
        <relationshipName>Meeting_Room_Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Code__c</fullName>
        <description>A unique booking code used to refer to the booking</description>
        <externalId>true</externalId>
        <label>Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Created_Date__c</fullName>
        <description>The date on which the booking was created</description>
        <label>Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Customer_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Meeting_Room_Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Paid_Total__c</fullName>
        <description>The total amount the customer has paid on the order</description>
        <label>Order Paid Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Order_Sub_Total__c</fullName>
        <description>The sub-total of all charges added to the order</description>
        <label>Order Sub Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Order_Tax_Total__c</fullName>
        <description>The sum of all taxes applied to the order</description>
        <label>Order Tax Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Order_Total__c</fullName>
        <description>The total of all charges and taxes added to the order</description>
        <label>Order Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Meeting Room Booking</label>
    <nameField>
        <displayFormat>MRB-{000000000}</displayFormat>
        <label>Meeting Room Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meeting Room Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>c2g__CODATaxCode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Output VAT/GST Code</label>
        <referenceTo>c2g__codaTaxCode__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CreateAdHocRecordsControllerTest.cls
@isTest
private class CreateAdHocRecordsControllerTest {

    @testSetup
    public static void createTestData() {
        Test.startTest();

        RecordDmlTest.createProducts();
        Product2 suiteProduct = [SELECT Id FROM Product2 WHERE Family = 'suite' AND ProductCode = 'OfficeRent' LIMIT 1];

        c2g__codaTaxCode__c taxCode = RecordDmlTest.createTaxCode(CreateAdHocRecordsController.TAX_CODE_NAME);
        c2g__codaCompany__c company = RecordDmlTest.createCompany(CreateAdHocRecordsController.COMPANY_NAME);
        Property__c prop = RecordDmlTest.createProperty();

        Account testAccount = RecordDmlTest.createAccount();

        List<Ad_hoc_Revenue__c> revenues = RecordDmlTest.createAdHocRevenues(testAccount, taxCode, prop, company, suiteProduct);
        insert revenues;

        List<Meeting_Room_Booking__c> rooms = new List<Meeting_Room_Booking__c>();
        for (Integer i = 1; i <= 6; i++) {
            rooms.add(
                    generateMeetingRoom(testAccount, i)
            );
        }
        rooms.get(2).Ad_hoc_Revenue__c = revenues.get(0).Id;
        rooms.get(4).Ad_hoc_Revenue__c = revenues.get(0).Id;
        insert rooms;
        Test.stopTest();
    }

    @isTest static void testBulkCreation() {
        List<Meeting_Room_Booking__c> rooms = [SELECT Id FROM Meeting_Room_Booking__c];
        ApexPages.StandardSetController stdSetController = new ApexPages.StandardSetController(rooms);
        stdSetController.setSelected(rooms);

        Test.startTest();
        CreateAdHocRecordsController controller = new CreateAdHocRecordsController(stdSetController);
        PageReference thePage = controller.createRecords();
        System.assert(thePage == null);
        System.assert(rooms.size() == [SELECT COUNT() FROM Ad_hoc_Revenue__c]);
        System.assert(rooms.size() == controller.adHocRecords.size());
        Test.stopTest();
    }

    @isTest static void testSingleRecordCreation() {
        Meeting_Room_Booking__c room = [SELECT Id FROM Meeting_Room_Booking__c WHERE Ad_hoc_Revenue__c = null LIMIT 1];
        ApexPages.StandardController stdController = new ApexPages.StandardController(room);

        Test.startTest();
        CreateAdHocRecordsController controller = new CreateAdHocRecordsController(stdController);
        PageReference thePage = controller.createRecords();
        System.assert(thePage != null);
        System.assert(3 == [SELECT COUNT() FROM Ad_hoc_Revenue__c]);
        System.assert(1 == controller.adHocRecords.size());
        System.assert(String.isBlank(controller.adHocRecords.get(0).message));
        Test.stopTest();
    }

    private static Meeting_Room_Booking__c generateMeetingRoom(Account testAccount, Integer i) {
        return new Meeting_Room_Booking__c(
                Code__c = String.valueOf(i),
                Created_Date__c = Date.today().addDays(-i),
                Customer_Account__c = testAccount.Id,
                Order_Paid_Total__c = 4.5 * i,
                Order_Sub_Total__c = 3.5 * i,
                Order_Tax_Total__c = 2.5 * i,
                Order_Total__c = 1.5 * i
        );
    }
}