src/objects/c2g__codaCompany__c.object
<CustomObject>
    <customHelpPage>c2g__codahelpcompany</customHelpPage>
    <description>Stores the FinancialForce company details.</description>
    <fields>
        <fullName>Direct_Debit_Form_Developer_Name__c</fullName>
        <description>Developer Name of the Document that contains Direct Debit form PDF.  It will be pushed into an quote related to the company.</description>
        <inlineHelpText>Developer Name of the Document that contains Direct Debit form PDF.  It will be pushed into an quote related to the company.</inlineHelpText>
        <label>Direct Debit Form Developer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Company</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Customer_Confidential_Documentation__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Confidential Documentations</relationshipLabel>
        <relationshipName>Customer_Confidential_Documentations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Direct_Debit_Signature__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Direct Debit Signature</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Customer Confidential Documentations</relationshipLabel>
        <relationshipName>Customer_Confidential_Documentations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Envelope_Id__c</fullName>
        <externalId>true</externalId>
        <label>Envelope Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legal_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Legal Entity</label>
        <referenceTo>c2g__codaCompany__c</referenceTo>
        <relationshipLabel>Customer Confidential Documentations</relationshipLabel>
        <relationshipName>Customer_Confidential_Documentations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ_Quote_Document__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote Document</label>
        <referenceTo>SBQQ__QuoteDocument__c</referenceTo>
        <relationshipLabel>Customer Confidential Documentations</relationshipLabel>
        <relationshipName>Customer_Confidential_Documentations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Signature_Status__c</fullName>
        <label>Signature Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>Signed</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Correct</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Voided</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer Confidential Documentation</label>
    <nameField>
        <displayFormat>CCD-{00000000}</displayFormat>
        <label>CCD Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Confidential Documentations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Direct_Debit_Form_Developer_Name__c</fullName>
        <formula>Company__r.Direct_Debit_Form_Developer_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Direct Debit Form Developer Name</label>
        <type>Text</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Quote_Template_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Stores details about which Quote Template Id should be applied for a particular sales process</description>
    <fields>
        <fullName>Ad_Hoc_Direct_Debit_Form_Template_Id__c</fullName>
        <label>Ad Hoc Direct Debit Form Template Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Quote Template Settings</label>
</CustomObject>

src/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__QuoteDocument__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteDocumentHelp</customHelpPage>
    <description>Particular version of a generated PDF document for the quote it&apos;s attached to. Ability to edit or delete this object should be taken away from all users (except administrators, of course) in order to preserve audit trail of all revisions.</description>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this Quote Document belongs.</description>
        <inlineHelpText>Quote to which this Quote Document belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Documents</relationshipLabel>
        <relationshipName>R00N70000001lX7YEAU</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Signature_Status__c</fullName>
        <description>Status of electronic signature.</description>
        <inlineHelpText>Status of electronic signature.</inlineHelpText>
        <label>Signature Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>Signed</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Correct</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Voided</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SendDDFormQuickActionController.cls
public with sharing class SendDDFormQuickActionController {

    private static final Quote_Template_Settings__c TEMPLATE_SETTINGS = Quote_Template_Settings__c.getOrgDefaults();
    private static final String DEFAULT_SUBJECT = 'Please DocuSign: Direct Debit Form';

    private static final String AC_DD_FORM_TEMPLATE_ID { get; set; }

    static {
        AC_DD_FORM_TEMPLATE_ID = TEMPLATE_SETTINGS.Ad_Hoc_Direct_Debit_Form_Template_Id__c;
    }

    @AuraEnabled
    public static void sendDDForm(Id recordId, Id contactId, Id accountId, String emailBody) {
        Customer_Confidential_Documentation__c ddForm = [SELECT SBQQ_Quote_Document__r.SBQQ__Quote__r.Property__r.Direct_Debit_Form_Developer_Name__c, Account__c,
                                                                Legal_Entity__r.Direct_Debit_Form_Developer_Name__c
                                                         FROM Customer_Confidential_Documentation__c
                                                         WHERE Id = :recordId];
        if ( ddForm.SBQQ_Quote_Document__c == null && ddForm.Legal_Entity__c == null ) {
            throw new AuraHandledException('Please populate Legal Entity on the record');
        }
        Contact selectedContact = [SELECT Name, Email FROM Contact WHERE Id = :contactId];
        String ddFormDeveloperName = String.isNotBlank(ddForm.SBQQ_Quote_Document__r.SBQQ__Quote__r.Property__r.Direct_Debit_Form_Developer_Name__c) ? ddForm.SBQQ_Quote_Document__r.SBQQ__Quote__r.Property__r.Direct_Debit_Form_Developer_Name__c : ddForm.Legal_Entity__r.Direct_Debit_Form_Developer_Name__c;
        if ( String.isBlank(ddFormDeveloperName) ) {
            throw new AuraHandledException('Please specify Direct Debit Form Developer Name on Legal Entity record');
        }
        List<Document> documents = [SELECT Name FROM Document WHERE DeveloperName = :ddFormDeveloperName LIMIT 1];
        if ( !documents.isEmpty() ) {
            ddForm.Account__c = ddForm.Account__c == null ? accountId : ddForm.Account__c;
            ddForm.Signature_Status__c = 'Pending';
            String envelopeId = DocuSignIntegrator.sendEnvelope(selectedContact.Name, selectedContact.Email, DEFAULT_SUBJECT, emailBody, AC_DD_FORM_TEMPLATE_ID, documents[0].Name, documents[0].Id, recordId);
            ddForm.Envelope_Id__c = envelopeId;
            ddForm.OwnerId = UserInfo.getUserId();
            ddForm.Direct_Debit_Signature__c = contactId;
            update ddForm;
        }
    }
}