src/objects/c2g__codaCompany__c.object
<CustomObject>
    <customHelpPage>c2g__codahelpcompany</customHelpPage>
    <description>Stores the FinancialForce company details.</description>
    <fields>
        <fullName>Direct_Debit_Form_Developer_Name__c</fullName>
        <description>Developer Name of the Document that contains Direct Debit form PDF.  It will be pushed into an quote related to the company.</description>
        <inlineHelpText>Developer Name of the Document that contains Direct Debit form PDF.  It will be pushed into an quote related to the company.</inlineHelpText>
        <label>Direct Debit Form Developer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Company</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>c2g__codaCompany__c</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>Properties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Direct_Debit_Form_Developer_Name__c</fullName>
        <formula>Company__r.Direct_Debit_Form_Developer_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Direct Debit Form Developer Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Region</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>Pay_by_BACs_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The system field (not for users) will be checked when Pay by BACs request is approved.</description>
        <label>Pay by BACs Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Pay_by_BACs__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Once a user checks the field, Pay by BACs approval process will be started.</description>
        <label>Pay by BACs</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__RelatedContent__c.object
<CustomObject>
    <description>Links certain marketing content (datasheets, specifications, case study) to a product or a template.</description>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote related to this content.</description>
        <inlineHelpText>Quote related to this content.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipName>RelatedContent</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Additional Document</label>
    <nameField>
        <label>Additional Document</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Additional Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ServicedQuoteDocumentGeneratorTest.cls
@isTest
public class ServicedQuoteDocumentGeneratorTest {

    @testSetup
    public static void initData() {
        Test.startTest();
        Document directDebitForm = new Document(
                Body = Blob.valueOf('Test Document'),
                ContentType = 'application/pdf',
                DeveloperName = 'Direct_Debit_1',
                IsPublic = true,
                Name = 'Direct Debit',
                FolderId = [SELECT Id FROM Folder WHERE DeveloperName = 'Quote_Documents'].id);
        insert directDebitForm;

        c2g__codaCompany__c ffCompany = new c2g__codaCompany__c(
                Direct_Debit_Form_Developer_Name__c = directDebitForm.DeveloperName);
        insert ffCompany;

        Property__c property = new Property__c(
                Name = 'Test Property',
                Region__c = 'Alderley Park',
		            Street__c = 'Test',
                Company__c = ffCompany.Id);
        insert property;

        SBQQ__Quote__c quote = RecordDmlTest.generateServicedQuoteWithLines();
        quote.Property__c = property.id;
        update quote;
        Test.stopTest();
    }

    @isTest
    static void givenSBQQ_QuoteAndDocumentGenerator_whenAdditionalDocumentsUpdated_thenDirectDebitFormShouldBeGenerated() {
        //given
        SBQQ__Quote__c quote = [SELECT Id, Property__c, Pay_by_BACs__c, Pay_by_BACs_Approved__c FROM SBQQ__Quote__c LIMIT 1];
        QuoteDocumentGenerator documentGenerator = new ServicedQuoteDocumentGenerator();

        //when
        Test.startTest();
        documentGenerator.updateAdditionalDocuments(quote);
        Test.stopTest();

        //then
        System.assertEquals(1, [SELECT COUNT() FROM SBQQ__RelatedContent__c WHERE SBQQ__Quote__c = :quote.Id AND Name = :ServicedQuoteDocumentGenerator.DIRECT_DEBIT_DOCUMENT_NAME], 'Direct Debit document has not been created');
    }

    @isTest
    static void givenSBQQ_QuoteAndDocumentGenerator_whenAdditionalDocumentsUpdated_thenPricingAndLicenceAgreementShouldBeGenerated() {
        //given
        SBQQ__Quote__c quote = [SELECT Id, Property__c, Pay_by_BACs__c, Pay_by_BACs_Approved__c FROM SBQQ__Quote__c LIMIT 1];
        QuoteDocumentGenerator documentGenerator = new ServicedQuoteDocumentGenerator();

        //when
        Test.startTest();
        documentGenerator.updateAdditionalDocuments(quote);
        Test.stopTest();

        //then
        System.assertEquals(1, [SELECT COUNT() FROM SBQQ__RelatedContent__c WHERE SBQQ__Quote__c = :quote.Id AND Name = :ServicedQuoteDocumentGenerator.PRICING_DOCUMENT_NAME], 'Pricing Document has not been created');
        System.assertEquals(1, [SELECT COUNT() FROM SBQQ__RelatedContent__c WHERE SBQQ__Quote__c = :quote.Id AND Name = :ServicedQuoteDocumentGenerator.LICENCE_AGREEMENT_DOCUMENT_NAME], 'Licence Agreement document has not been created');
    }

    @isTest
    static void givenSBQQ_QuoteAndDocumentGenerator_whenAdditionalDocumentsUpdatedSecondTime_thenDirectDebitFormShouldBeUpdatedWithNewVersions() {
        //given
        SBQQ__Quote__c quote = [SELECT Id, Property__c, Pay_by_BACs__c, Pay_by_BACs_Approved__c FROM SBQQ__Quote__c LIMIT 1];
        QuoteDocumentGenerator documentGenerator = new ServicedQuoteDocumentGenerator();

        //when
        Test.startTest();
        documentGenerator.updateAdditionalDocuments(quote);
        //Doesn't create a new documents, the previous document versions should be updated
        documentGenerator.updateAdditionalDocuments(quote);
        Test.stopTest();

        //then
        System.assertEquals(1, [SELECT COUNT() FROM SBQQ__RelatedContent__c WHERE SBQQ__Quote__c = :quote.Id AND Name = :ServicedQuoteDocumentGenerator.DIRECT_DEBIT_DOCUMENT_NAME], 'Direct Debit document has not been created or has been created twice');
    }

    @isTest
    static void givenSBQQ_QuoteAndDocumentGenerator_whenAdditionalDocumentsUpdatedSecondTime_thenPricingAndLicenceAgreementShouldBeUpdatedWithNewVersions() {
        //given
        SBQQ__Quote__c quote = [SELECT Id, Property__c, Pay_by_BACs__c, Pay_by_BACs_Approved__c FROM SBQQ__Quote__c LIMIT 1];
        QuoteDocumentGenerator documentGenerator = new ServicedQuoteDocumentGenerator();

        //when
        Test.startTest();
        documentGenerator.updateAdditionalDocuments(quote);
        //Doesn't create a new documents, the previous document versions should be updated
        documentGenerator.updateAdditionalDocuments(quote);
        Test.stopTest();

        //then
        System.assertEquals(1, [SELECT COUNT() FROM SBQQ__RelatedContent__c WHERE SBQQ__Quote__c = :quote.Id AND Name = :ServicedQuoteDocumentGenerator.PRICING_DOCUMENT_NAME], 'Pricing Document has not been created or has been created twice');
        System.assertEquals(1, [SELECT COUNT() FROM SBQQ__RelatedContent__c WHERE SBQQ__Quote__c = :quote.Id AND Name = :ServicedQuoteDocumentGenerator.LICENCE_AGREEMENT_DOCUMENT_NAME], 'Licence Agreement document has not been created or has been created twice');
    }
}