src/objects/c2g__codaCompany__c.object
<CustomObject>
    <customHelpPage>c2g__codahelpcompany</customHelpPage>
    <description>Stores the FinancialForce company details.</description>
    <label>Company</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Customer_Confidential_Documentation__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Confidential Documentations</relationshipLabel>
        <relationshipName>Customer_Confidential_Documentations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Bank_Building_Society_Account_Number__c</fullName>
        <label>Bank / Building Society Account Number</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Branch_Sort_Code__c</fullName>
        <label>Branch Sort Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Collections_File_Sequence_Number__c</fullName>
        <defaultValue>&quot;0N&quot;</defaultValue>
        <label>Collections File Sequence number</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0N</fullName>
                    <default>true</default>
                    <label>0N</label>
                </value>
                <value>
                    <fullName>0C</fullName>
                </value>
                <value>
                    <fullName>00</fullName>
                </value>
                <value>
                    <fullName>01</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DDF_Acc_Num_1__c</fullName>
        <label>DDF Acc Num 1</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DDF_Acc_Num_2__c</fullName>
        <label>DDF Acc Num 2</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DDF_Acc_Num_3__c</fullName>
        <label>DDF Acc Num 3</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DDF_Acc_Num_4__c</fullName>
        <label>DDF Acc Num 4</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DDF_Acc_Num_5__c</fullName>
        <label>DDF Acc Num 5</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DDF_Acc_Num_6__c</fullName>
        <label>DDF Acc Num 6</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DDF_Acc_Num_7__c</fullName>
        <label>DDF Acc Num 7</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DDF_Acc_Num_8__c</fullName>
        <label>DDF Acc Num 8</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_Signed__c</fullName>
        <label>Date Signed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Legal_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Legal Entity</label>
        <referenceTo>c2g__codaCompany__c</referenceTo>
        <relationshipLabel>Customer Confidential Documentations</relationshipLabel>
        <relationshipName>Customer_Confidential_Documentations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name_Of_Account_Holder__c</fullName>
        <label>Name(s) Of Account Holder(s)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Signature_Status__c</fullName>
        <label>Signature Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>Signed</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Correct</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Voided</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer Confidential Documentation</label>
    <nameField>
        <displayFormat>CCD-{00000000}</displayFormat>
        <label>CCD Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Confidential Documentations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SendDDFormQuickActionControllerTest.cls
/**
 * @description Test class fro SendDDFormQuickActionController class
 */
@isTest
public class SendDDFormQuickActionControllerTest {

    @testSetup
    public static void setupData() {
        RecordDmlTest.createDocusignSettings();
        RecordDmlTest.createContact();
        RecordDmlTest.createProperty();
        c2g__codaCompany__c testCompany = [SELECT Id FROM c2g__codaCompany__c LIMIT 1];
        Account testAccount = RecordDmlTest.createAccount();
        Customer_Confidential_Documentation__c ddForm = new Customer_Confidential_Documentation__c(
                Account__c = testAccount.Id,
                Name_Of_Account_Holder__c = 'Test Account',
                Branch_Sort_Code__c = '123456',
                Legal_Entity__c = testCompany.Id,
                Collections_File_Sequence_Number__c = CustomerConfidentialDocumentationService.DEFAULT_VALUE_FOR_COLLECTIONS_FILE_SEQUENCE_NUMBER
        );
        insert ddForm;
    }

    @isTest
    public static void testSendDDForm() {
        Contact testContact = [SELECT Name, Email FROM Contact LIMIT 1];
        Customer_Confidential_Documentation__c ddForm = [SELECT Account__c FROM Customer_Confidential_Documentation__c LIMIT 1];
        Test.setMock(HttpCalloutMock.class, new MockHttpDocuSignResponseGenerator());
        Test.startTest();
        SendDDFormQuickActionController.sendDDForm(ddForm.Id, testContact.Id, ddForm.Account__c, 'some text body');
        ddForm.Signature_Status__c = 'Completed';
        ddForm.DDF_Acc_Num_1__c = '1';
        ddForm.DDF_Acc_Num_2__c = '2';
        ddForm.DDF_Acc_Num_3__c = '3';
        ddForm.DDF_Acc_Num_4__c = '4';
        ddForm.DDF_Acc_Num_5__c = '5';
        ddForm.DDF_Acc_Num_6__c = '6';
        ddForm.DDF_Acc_Num_7__c = '7';
        ddForm.DDF_Acc_Num_8__c = '8';
        update ddForm;
        ddForm = [SELECT Bank_Building_Society_Account_Number__c, Date_Signed__c FROM Customer_Confidential_Documentation__c LIMIT 1];
        System.assertEquals('12345678', ddForm.Bank_Building_Society_Account_Number__c);
        System.assertEquals(Date.today(), ddForm.Date_Signed__c);
        Test.stopTest();
    }
}