src/objects/c2g__AllocationFilter__c.object
<CustomObject>
    <customHelpPage>c2g__codahelpallocationfilter</customHelpPage>
    <description>Stores the queries for selecting and filtering allocation data for the allocation template.</description>
    <fields>
        <fullName>c2g__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Allocation Filter</label>
    <nameField>
        <displayFormat>AF{000000}</displayFormat>
        <label>Allocation Filter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Allocation Filters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ContractToQuote__c.object
<CustomObject>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>ContractToQuotes</relationshipLabel>
        <relationshipName>ContractToQuotes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>ContractToQuotes</relationshipLabel>
        <relationshipName>ContractToQuotes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>ContractToQuote</label>
    <nameField>
        <label>ContractToQuote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ContractToQuotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Inventory__c.object
<CustomObject>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Inventories</relationshipLabel>
        <relationshipName>Inventories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipName>Suites</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rent_per_sq_ft_Annual__c</fullName>
        <formula>Rent_per_sq_ft__c * 12</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Rent per sq ft per annum</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <label>Inventory</label>
    <nameField>
        <label>Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Quotes (Contract)</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Estimated_Business_Rate_Per_Annum__c</fullName>
        <label>Estimated Business Rate Per Annum</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory</label>
        <referenceTo>Inventory__c</referenceTo>
        <relationshipName>Inventory</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rent_per_Sq_Ft_annual__c</fullName>
        <description>Rent per Sq. Ft. annual (£)</description>
        <label>Rent per Sq. Ft. annual (£)</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SBQQ__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
        <inlineHelpText>The customer account for this quote. Defaults to the account for the opportunity when creating a quote.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Surrender_deed_due_date__c</fullName>
        <defaultValue>ADDMONTHS(TODAY(),1)</defaultValue>
        <label>Surrender deed due date</label>
        <type>Date</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>Break_Date__c</fullName>
        <label>Break Date</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Break_Penalty__c</fullName>
        <label>Break Penalty (£)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory</label>
        <referenceTo>Inventory__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>Quote_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Maximum_Notice__c</fullName>
        <label>Maximum Notice</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Minimum_Notice__c</fullName>
        <label>Minimum Notice</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Quote Lines (Property)</relationshipLabel>
        <relationshipName>QuoteLines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rent_per_Sq_Ft_annual__c</fullName>
        <description>Rent per Sq. Ft. annual (£)</description>
        <label>Rent per Sq. Ft. annual (£)</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SBQQ__Bundle__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether this line item represents a package; meaning, it includes other line items in this quote.</description>
        <inlineHelpText>Indicates whether this line item represents a package; meaning, it includes other line items in this quote.</inlineHelpText>
        <label>Package</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__ProductCode__c</fullName>
        <description>Code for the product referenced by this line.</description>
        <formula>SBQQ__Product__r.ProductCode</formula>
        <inlineHelpText>Code for the product referenced by this line.</inlineHelpText>
        <label>Product Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__ProductFamily__c</fullName>
        <description>How you would categorize/group/organize this within Salesforce (whether it&apos;s a new or existing Product Family). Additionally, this field can be used during product selection to filter to the correct product or product SKU.</description>
        <formula>TEXT(SBQQ__Product__r.Family)</formula>
        <inlineHelpText>How you would categorize/group/organize this within Salesforce (whether it&apos;s a new or existing Product Family). Additionally, this field can be used during product selection to filter to the correct product or product SKU.</inlineHelpText>
        <label>Product Family</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SBQQ__RequiredBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Links this line to another line in the same quote whose product requires this line&apos;s product.</description>
        <inlineHelpText>Indicates which other product on this quote requires it.</inlineHelpText>
        <label>Required By</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>Quote_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Square_Footage__c</fullName>
        <label>Square Footage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SBQQ__Subscription__c.object
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <fields>
        <fullName>Break_Date__c</fullName>
        <formula>IF(ISBLANK(SBQQ__QuoteLine__r.Break_Date__c), NULL, ADDMONTHS(SBQQ__StartDate__c, SBQQ__QuoteLine__r.Break_Date__c))</formula>
        <label>Break Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Break_Penalty__c</fullName>
        <label>Break Penalty (£)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory</label>
        <referenceTo>Inventory__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Maximum_Notice__c</fullName>
        <label>Maximum Notice</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Minimum_Notice__c</fullName>
        <label>Minimum Notice</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account that owns this subscription. This relationship is used for volume discount calculations.</description>
        <inlineHelpText>Account that owns this subscription. This relationship is used for volume discount calculations.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Bundle__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether this line item represents a package; meaning, it includes other line items in this quote.</description>
        <inlineHelpText>Indicates whether this line item represents a package; meaning, it includes other line items in this quote.</inlineHelpText>
        <label>Package</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contract that governs this subscription.</description>
        <inlineHelpText>Contract that governs this subscription.</inlineHelpText>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__QuoteLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote line that generated this subscription.</description>
        <inlineHelpText>Quote line that generated this subscription.</inlineHelpText>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Square_Footage__c</fullName>
        <label>Square Footage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ConventionalTermDocumentGenerator.cls
public class ConventionalTermDocumentGenerator extends QuoteDocumentParams {
    public SBQQ__Quote__c quoteDetail { get; private set; }
    public SBQQ__QuoteLine__c qLI { get; set; }
    public List<SBQQ__QuoteLine__c> qliList { get; set; }
    public List<Map<String, SBQQ__QuoteLine__c>> bundleProducts { get; set; }
    public Map<String, BreakOptions> bundleBreakOptions { get; set; }
    public Map<String, BreakOptions> bundleSupplierBreakOptions { get; set; }
    public Map<String, List<SBQQ__QuoteLine__c>> bundleRentReviewMap { get; set; }
    public Map<String, List<SBQQ__QuoteLine__c>> bundlePreEmptionMap { get; set; }
    public Map<String, List<SBQQ__QuoteLine__c>> bundleFreeRentMap { get; set; }
    public Map<String, List<SBQQ__QuoteLine__c>> bundleHalfRentMap { get; set; }
    public Map<String, List<SBQQ__QuoteLine__c>> bundleRentMap { get; set; }
    public Map<String, List<SBQQ__QuoteLine__c>> bundleSteppedRentMap { get; set; }
    public Map<String, String> keyList { get; set; }
    public Map<String, String> suiteTypesMap { get; set; }
    public String accountFullAddress { set; }
    public Boolean fitOutAdded { get; set; }
    public Boolean suiteAdded { get; set; }
    public Integer numCarParkingLeases { get; set; }
    public Integer numCarParkingLicenses { get; set; }
    public Map<String, Decimal> businessRatesPerSqFtMap { get; set; }
    public String legacyContractsInventories { get; set; }
    public String legacyContractProperty { get; set; }
    public String legacyContractDateX { get; set; }
    public String legacyContractWeeksX { get; set; }
    public String surrenderDeedCompletionDate { get; set; }
    public Double VAT { get; set; }

    protected String quoteId;

    public Boolean surrenderWasRendered;

    private class BreakOptions {
        public String breakDates { get; set; }
        public String noticedDates { get; set; }
        public String breakPenalty { get; set; }
        public Boolean breakPenaltyExists { get; set; }

        public BreakOptions() {
            breakDates = '';
            noticedDates = '';
            breakPenalty = '';
            breakPenaltyExists = false;
        }
    }


    public ConventionalTermDocumentGenerator() {
        quoteId = ApexPages.currentPage().getParameters().get('id');
        keyList = new Map<String, String>();
        fitOutAdded = false;
        suiteAdded = false;
        businessRatesPerSqFtMap = new Map<String, Decimal>();
        suiteTypesMap = new Map<String, String>();
        VAT = Constants.VAT_TAX;
    }

    public PageReference init() {

        quoteDetail = DocumentGenerationHelper.getQuoteDetails(quoteId);
        qliList = DocumentGenerationHelper.getQuoteLines(quoteId);
        bundleProducts = getBundleProducts(qliList);
        bundleBreakOptions = getMapBreakOptions(QuoteProductCodes.CUSTOMER_BREAK_OPTION);
        bundleSupplierBreakOptions = getMapBreakOptions(QuoteProductCodes.SUPPLIER_BREAK_OPTION);
        numCarParkingLeases = getNumCarParking(ProductService.PRODUCT_CODE_CAR_PARKING_LEASE);
        numCarParkingLicenses = getNumCarParking(ProductService.PRODUCT_CODE_CAR_PARKING_LICENSE);
        bundleRentReviewMap = DocumentGenerationHelper.getBundleProductMap(ProductService.PRODUCT_CODE_RENT_REVIEW, qliList);
        bundlePreEmptionMap = DocumentGenerationHelper.getBundleProductMap(ProductService.PRODUCT_CODE_PRE_EMPTION_AGREEMENT, qliList);
        bundleFreeRentMap = DocumentGenerationHelper.getBundleProductMap(ProductService.PRODUCT_CODE_FREE_RENT, qliList);
        bundleHalfRentMap = DocumentGenerationHelper.getBundleProductMap(ProductService.PRODUCT_CODE_HALF_RENT, qliList);
        bundleSteppedRentMap = DocumentGenerationHelper.getBundleProductMap(ProductService.PRODUCT_CODE_STEPPED_RENT, qliList);
        bundleRentMap = getSortedByTermRents(bundleFreeRentMap,bundleHalfRentMap);
        legacyContractsInventories = getLContractsInventories();
        surrenderDeedCompletionDate = generateSurrenderDeedCompletionDate();


        return null;
    }

    private String getLContractsInventories() {
        List<ContractToQuote__c> contractsToQuote = [select Contract__c from ContractToQuote__c where Quote__c = :quoteDetail.Id];
        Set<Id> contractIds = new Set<Id>();
        for (ContractToQuote__c contractToQuote : contractsToQuote) {
            contractIds.add(contractToQuote.Contract__c);
        }
        List<SBQQ__Subscription__c> subscriptions = [
                select Id, Inventory__r.Name, Inventory__r.Property__r.Name
                from SBQQ__Subscription__c
                where SBQQ__Contract__c in:contractIds
                and SBQQ__QuoteLine__r.SBQQ__Bundle__c = true and SBQQ__QuoteLine__r.SBQQ__ProductFamily__c = : ProductService.PRODUCT_FAMILY_SUITE
        ];

        Map<String, List<String>> propertyInventoryMap = new Map<String, List<String>>();
        for (SBQQ__Subscription__c subscription : subscriptions) {
            if (subscription.Inventory__c != null && String.isNotBlank(subscription.Inventory__r.Name)) {
                if (propertyInventoryMap.get(subscription.Inventory__r.Property__r.Name) == null) {
                    propertyInventoryMap.put(subscription.Inventory__r.Property__r.Name, new List<String>());
                }
                propertyInventoryMap.get(subscription.Inventory__r.Property__r.Name).add(subscription.Inventory__r.Name);
            }
        }

        List<String> propertyWithInventories = new List<String>();
        for (String propertyName : propertyInventoryMap.keySet()) {
            propertyWithInventories.add(String.join(propertyInventoryMap.get(propertyName), ', ') + ' - ' + propertyName);
        }
        return String.join(propertyWithInventories, '; ');
    }

    public Boolean getQuoteWithoutSuites() {
        return !haveIntersection(suiteTypesMap.values(), QuoteFromContractCreator.HEADLINE_PRODUCT_CODES);
    }

    public Boolean getSurrenderWasRendered() {
        if (surrenderWasRendered == null) {
            surrenderWasRendered = true;
            return false;
        } else {

            return surrenderWasRendered;
        }
    }

    private Boolean haveIntersection(List<String> firstList, List<String> secondList) {
        for (String testString : firstList) {
            if (secondList.contains(testString)) {
                return true;
            }
        }
        return false;
    }

    private List<Map<String, SBQQ__QuoteLine__c>> getBundleProducts(List<SBQQ__QuoteLine__c> quoteLines) {
        List<Map<String, SBQQ__QuoteLine__c>> qliByBundles = new List<Map<String, SBQQ__QuoteLine__c>>();

        for (SBQQ__QuoteLine__c qliHead : quoteLines) {
            if (DocumentGenerationHelper.isSuiteBundle(qliHead)) {
                Map<String, SBQQ__QuoteLine__c> qliByCode = new Map<String, SBQQ__QuoteLine__c>();
                String ks = '';
                Decimal businesRates = 0;
                for (SBQQ__QuoteLine__c qLI : quoteLines) {
                    if (qli.SBQQ__RequiredBy__c == qliHead.Id && !String.isBlank(qli.SBQQ__RequiredBy__c)
                            || (qliHead.SBQQ__ProductCode__c != ProductService.PRODUCT_CODE_STORAGE
                            && qli.SBQQ__ProductFamily__c == ProductService.PRODUCT_FAMILY_PARKING)) {
                        if (!qliByCode.containsKey(qLI.SBQQ__ProductCode__c)) {
                            kS += ' ' + qLI.SBQQ__ProductCode__c + ',';
                        }

                        if (qli.SBQQ__ProductCode__c == ProductService.PRODUCT_CODE_FIT_OUT_SUPPLIER) {
                            fitOutAdded = true;
                        }

                        qliByCode.put(qLI.SBQQ__ProductCode__c, qLI);

                    }
                }
                qliByCode.put('Suite', qliHead);
                ks += ' Suite,';
                suiteAdded = true;
                keyList.put(qliHead.Id, ks);
                suiteTypesMap.put(qliHead.Id, qliHead.SBQQ__ProductCode__c);
                qliByBundles.add(qliByCode);
                if (qliHead.Square_Footage__c != NULL
                        && qliHead.Square_Footage__c != 0
                        && quoteDetail.Estimated_Business_Rate_Per_Annum__c != NULL
                        ) {
                    businesRates = (quoteDetail.Estimated_Business_Rate_Per_Annum__c / qliHead.Square_Footage__c).setScale(2);
                }
                //businesRates = qliHead.Rent_per_Sq_Ft_annual__c.setScale(2);
                //System.debug(businesRates + ' ' + qliHead.id);
                businessRatesPerSqFtMap.put(qliHead.id, businesRates);

            }
        }

        return qliByBundles;
    }

    public String getAccountFullAddress() {

        String address;
        address = String.isNotBlank(quoteDetail.SBQQ__Account__r.ShippingStreet) ? quoteDetail.SBQQ__Account__r.ShippingStreet + ' ' : '';
        address += String.isNotBlank(quoteDetail.SBQQ__Account__r.ShippingCity) ? quoteDetail.SBQQ__Account__r.ShippingCity + ' ' : '';
        address += String.isNotBlank(quoteDetail.SBQQ__Account__r.ShippingPostalCode) ? quoteDetail.SBQQ__Account__r.ShippingPostalCode + ' ' : '';
        address += String.isNotBlank(quoteDetail.SBQQ__Account__r.ShippingCountry) ? quoteDetail.SBQQ__Account__r.ShippingCountry : '';
        return address;

    }

    public Integer getNumCarParking(String code) {
        Integer numCP = 0;
        for (SBQQ__QuoteLine__c qli : qliList) {
            numCP += qli.SBQQ__ProductCode__c == code ? 1 : 0;
        }

        return numCP;
    }

    public Map<String, BreakOptions> getMapBreakOptions(String productCode) {

        Map<String, BreakOptions> mapBreakOptions = new Map<String, BreakOptions>();

        for (SBQQ__QuoteLine__c qlHead : qliList) {
            //search for Headline
            if (DocumentGenerationHelper.isSuiteBundle(qlHead)) {
                BreakOptions breakOpt = new BreakOptions();
                for (SBQQ__QuoteLine__c ql : qliList) {
                    //search related Break products and build formatted strings
                    if (ql.SBQQ__ProductCode__c == productCode &&
                            ql.SBQQ__RequiredBy__c == qlHead.Id) {

                        if (breakOpt.BreakDates.length() == 0) {

                            breakOpt.breakDates = String.valueOf(ql.Break_Date__c.setScale(0));
                            if (ql.Minimum_Notice__c != NULL && ql.Maximum_Notice__c != NULL) {
                                breakOpt.noticedDates = ql.Minimum_Notice__c.setScale(0) + ' and ' + ql.Maximum_Notice__c.setScale(0);
                            }
                            breakOpt.breakPenalty = ql.Break_Penalty__c == null ? '' : String.valueOf(ql.Break_Penalty__c.format());
                            if (ql.Break_Penalty__c > 0) {
                                breakOpt.breakPenaltyExists = true;
                            }

                        } else {

                            breakOpt.breakDates += ', ' + ql.Break_Date__c.setScale(0);

                        }
                    }

                }

                mapBreakOptions.put(qlHead.Id, breakOpt);
            }
        }

        return mapBreakOptions;
    }

    private Map<String, List<SBQQ__QuoteLine__c>> getSortedByTermRents(Map<String, List<SBQQ__QuoteLine__c>> bundleFreeRent,
            Map<String, List<SBQQ__QuoteLine__c>> bundleHalfRent) {
        Map<String, List<SBQQ__QuoteLine__c>> sortedMergedBundle = new Map<String, List<SBQQ__QuoteLine__c>>();

        for (String key: bundleFreeRent.keySet()) {

            if (bundleHalfRent.containsKey(key)) {
                List<SBQQ__QuoteLine__c> qLineListToSort = new List<SBQQ__QuoteLine__c>();
                qLineListToSort.addAll(bundleFreeRent.get(key));
                qLineListToSort.addAll(bundleHalfRent.get(key));
                SortSobs.ascending(qLineListToSort, DocumentGenerationHelper.START_CONCESSION_TERM_FIELD);
                sortedMergedBundle.put(key, qLineListToSort);
            } else {
                SortSobs.ascending(bundleFreeRent.get(key), DocumentGenerationHelper.START_CONCESSION_TERM_FIELD);
                sortedMergedBundle.put(key, bundleFreeRent.get(key));
            }
        }

        for (String key: bundleHalfRent.keySet()) {
            if (!sortedMergedBundle.containsKey(key)) {
                SortSobs.ascending(bundleHalfRent.get(key), DocumentGenerationHelper.START_CONCESSION_TERM_FIELD);
                sortedMergedBundle.put(key, bundleHalfRent.get(key));
            }
        }

        return sortedMergedBundle;
    }

    public String generateSurrenderDeedCompletionDate() {
        if (quoteDetail.Surrender_deed_due_date__c != null) {
            return 'The surrender deed will complete on ' + quoteDetail.Surrender_deed_due_date__c.format() + ' date.';
        } else if (quoteDetail.Surrender_deed_weeks__c != null) {
            return 'The surrender deed will complete ' + quoteDetail.Surrender_deed_weeks__c + ' weeks after completion of the lease.';
        } else {
            return 'The surrender deed will complete on the same date as the lease.';
        }
    }

}