src/objects/c2g__codaCompany__c.object
<CustomObject>
    <customHelpPage>c2g__codahelpcompany</customHelpPage>
    <description>Stores the FinancialForce company details.</description>
    <fields>
        <fullName>RecordTypeDeveloperName__c</fullName>
        <label>RecordTypeDeveloperName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Company</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CodaCompanyTriggerHandlerTest.cls
@isTest
public with sharing class CodaCompanyTriggerHandlerTest {
    @isTest
    public static void whenCompanyCreatedRTSetFromField() {
        c2g__codaCompany__c company1 = new c2g__codaCompany__c();
        company1.RecordTypeDeveloperName__c = 'SUT';

        c2g__codaCompany__c company2 = new c2g__codaCompany__c();
        company2.RecordTypeDeveloperName__c = 'VAT';

        insert new List<c2g__codaCompany__c>{
                company1, company2
        };

        for (c2g__codaCompany__c company : [select RecordType.DeveloperName, RecordTypeDeveloperName__c from c2g__codaCompany__c c]) {
            System.assertEquals(company.RecordType.DeveloperName, company.RecordTypeDeveloperName__c);
        }
    }
}