src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Case</fullName>
        <active>true</active>
        <businessProcess>Ordinary Case</businessProcess>
        <label>Case</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>SBQQ__Status__c</fullName>
        <description>Status indicating where quote is in its lifecycle.</description>
        <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Presented</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Pending Approval - Offline Edit</fullName>
                </value>
                <value>
                    <fullName>Awaiting Approval - Offline Edit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SpringCMGenerateContractBtnControllerTst.cls
/**
 * @description Test class for SpringCMGenerateContractBtnController class
 */
@isTest
public class SpringCMGenerateContractBtnControllerTst {
    @testSetup
    public static void setupData() {
        SBQQ__Quote__c quote = RecordDmlTest.generateConventionalQuoteWithLines(QuoteProductCodes.OFFICE_RENT);
    }

    @isTest
    public static void testButton() {
        Test.startTest();
        SBQQ__Quote__c updateQuote = [SELECT Id FROM SBQQ__Quote__c LIMIT 1];
        updateQuote.SBQQ__Status__c = SBQQ_QuoteConstants.STATUS_ACCEPTED;
        update updateQuote;
        Case ltCase = [
                SELECT CaseNumber, Account.Name, Opportunity__r.Name, Quote__r.Name
                FROM Case
                WHERE RecordTypeId = :RecordTypeHelper.getCaseRtIdByDeveloperName(CaseService.LEASE_TRANSACTION_RECORD_TYPE)
                LIMIT 1
        ];
        ApexPages.StandardController stdController = new ApexPages.StandardController(ltCase);
        SpringCMGenerateContractBtnController btnContoller = new SpringCMGenerateContractBtnController(stdController);
        PageReference pageRef = btnContoller.redirectToSpringCM();
        System.assertNotEquals(null, pageRef);
        System.assertEquals(true, pageRef.getUrl().contains(ltCase.Id));
    }
}