src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Break_Penalty_Premium__c</fullName>
        <label>Break Penalty Premium</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Budget_Dilapidations__c</fullName>
        <label>Budget Dilapidations</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contract_Surrender__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract Surrender</label>
        <referenceTo>Contract_Surrender__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Final_Dilapidations__c</fullName>
        <label>Final Dilapidations</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Interim_Dilapidations__c</fullName>
        <label>Interim Dilapidations</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Is_the_customer_liable_for_Service_Chrg__c</fullName>
        <description>Is the customer liable for Service Charge Reconciliation?</description>
        <inlineHelpText>Is the customer liable for Service Charge Reconciliation?</inlineHelpText>
        <label>Customer liable for Service Charge</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No_Value_Set</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_the_customer_liable_for_electricity__c</fullName>
        <description>Is the customer liable for electricity costs post completion?</description>
        <inlineHelpText>Is the customer liable for electricity costs post completion?</inlineHelpText>
        <label>Customer liable for electricity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No_Value_Set</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Proposed_date_of_surrender__c</fullName>
        <label>Proposed date of surrender</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Suite_Restoration__c</fullName>
        <label>Suite Restoration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Surrender_Premium__c</fullName>
        <label>Surrender Premium</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Terminal_Dilapidations__c</fullName>
        <label>Terminal Dilapidations</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <recordTypes>
        <fullName>Case</fullName>
        <active>true</active>
        <businessProcess>Ordinary Case</businessProcess>
        <label>Case</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Opportunity from which this Contract was created.</description>
        <inlineHelpText>The Opportunity from which this Contract was created.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Quote from which this Contract was created.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract_Surrender__c.object
<CustomObject>
    <fields>
        <fullName>Break_Penalty_Premium__c</fullName>
        <label>Break Penalty Premium</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Budget_Dilapidations__c</fullName>
        <label>Budget Dilapidations</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Carpet_Cleaning__c</fullName>
        <label>Carpet Cleaning</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contract Surrenders</relationshipLabel>
        <relationshipName>Contract_Surrenders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_Surrender_Triggered__c</fullName>
        <label>Date Surrender Triggered</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deposit__c</fullName>
        <label>Deposit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Final_Dilapidations__c</fullName>
        <label>Final Dilapidations</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Interim_Dilapidations__c</fullName>
        <label>Interim Dilapidations</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Is_the_customer_liable_for_Service_Chrg__c</fullName>
        <description>Is the customer liable for Service Charge Reconciliation?</description>
        <inlineHelpText>Is the customer liable for Service Charge Reconciliation?</inlineHelpText>
        <label>Customer liable for Service Charge</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No_Value_Set</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_the_customer_liable_for_electricity__c</fullName>
        <description>Is the customer liable for electricity costs post completion?</description>
        <inlineHelpText>Is the customer liable for electricity costs post completion?</inlineHelpText>
        <label>Customer liable for electricity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No_Value_Set</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Other_Costs__c</fullName>
        <label>Other Costs</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Painting_Decorating__c</fullName>
        <label>Painting &amp; Decorating</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Proposed_date_of_surrender__c</fullName>
        <label>Proposed date of surrender</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&apos;New&apos;</defaultValue>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Suite_Restoration__c</fullName>
        <label>Suite Restoration</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Surrender_Premium__c</fullName>
        <label>Surrender Premium</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Terminal_Dilapidations__c</fullName>
        <label>Terminal Dilapidations</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Contract Surrender</label>
    <nameField>
        <label>Contract Surrender Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Surrenders</pluralLabel>
    <recordTypes>
        <fullName>Conventional</fullName>
        <active>true</active>
        <label>Conventional</label>
    </recordTypes>
    <recordTypes>
        <fullName>Serviced</fullName>
        <active>true</active>
        <label>Serviced</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Pricebook2.object
<CustomObject>
    <recordTypes>
        <fullName>Conventional</fullName>
        <active>true</active>
        <label>Conventional</label>
    </recordTypes>
    <recordTypes>
        <fullName>Serviced</fullName>
        <active>true</active>
        <label>Serviced</label>
    </recordTypes>
    <recordTypes>
        <fullName>Virtual</fullName>
        <active>true</active>
        <label>Virtual</label>
    </recordTypes>
    <sharingModel>ReadSelect</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Is_Deposit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Deposit</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Quotes (Contract)</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deposit__c</fullName>
        <description>Total Deposit % on the Quote</description>
        <formula>Deposit_Payment__c / SBQQ__NetAmount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Total Deposit % on the Quote.</inlineHelpText>
        <label>Deposit %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Surrender_Premium__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Surrender Premium</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <recordTypes>
        <fullName>Conventional</fullName>
        <active>true</active>
        <label>Conventional</label>
    </recordTypes>
    <recordTypes>
        <fullName>Serviced</fullName>
        <active>true</active>
        <label>Serviced</label>
    </recordTypes>
    <recordTypes>
        <fullName>Virtual</fullName>
        <active>true</active>
        <label>Virtual</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__Subscription__c.object
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <fields>
        <fullName>SBQQ__Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contract that governs this subscription.</description>
        <inlineHelpText>Contract that governs this subscription.</inlineHelpText>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product used to sell this subscription.</description>
        <inlineHelpText>Product used to sell this subscription.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__UnitCost__c</fullName>
        <description>Unit Cost for this Subscription.</description>
        <inlineHelpText>Unit Cost for this Subscription.</inlineHelpText>
        <label>Unit Cost</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SurrenderContractController.cls
public with sharing class SurrenderContractController {
    public static String CONVENTIONAL_RECORD_TYPE_NAME = 'Conventional';
    public static String SERVICED_RECORD_TYPE_NAME = 'Serviced';

    public Contract contract { get; set; }
    public Contract_Surrender__c surrender { get; set; }
    public String errorMessage { get; set; }
    public Boolean isMessageRendered { get; set; }
    public Boolean isServicedRT { get; set; }

    public SurrenderContractController(ApexPages.StandardController stdController) {
        Id contractId = ApexPages.currentPage().getParameters().get('contractId');

        this.surrender = (Contract_Surrender__c) stdController.getRecord();
        this.contract = this.findContractById(contractId);
        this.isMessageRendered = false;

        if (this.contract == null) {
            this.errorMessage = 'Invalid Contract, please try again from Contract detail page';
            this.isMessageRendered = true;
            return;
        }

        Id recordTypeId = this.getRecordTypeId(this.contract);
        if (recordTypeId == null) {
            this.errorMessage = 'It is not possible to create a Surrender Contract for Virtual Sales.';
            this.isMessageRendered = true;
            return;
        }

        this.initSurrender(recordTypeId);
    }

    private void initSurrender(Id recordTypeId) {
        List<Contract_Surrender__c> surrenders = [SELECT Id, Name, RecordTypeId FROM Contract_Surrender__c WHERE Contract__c = :contract.Id];
        if (surrenders.size() > 0) {
            this.surrender = surrenders.get(0);
            this.isServicedRT = this.surrender.RecordTypeId == Schema.SObjectType.Contract_Surrender__c.getRecordTypeInfosByName().get(SERVICED_RECORD_TYPE_NAME).getRecordTypeId();
        }

        if (this.surrender.Id == null) {
            this.surrender.RecordTypeId = recordTypeId;
            this.surrender.Date_Surrender_Triggered__c = Date.today();
            this.surrender.Contract__c = this.contract.Id;
            this.surrender.Name = ('Surrender: ' + this.contract.Name);
            this.surrender.Deposit__c = this.calculateDeposit(this.contract.Id);
            this.surrender.Status__c = 'New';
            this.isServicedRT = this.surrender.RecordTypeId == Schema.SObjectType.Contract_Surrender__c.getRecordTypeInfosByName().get(SERVICED_RECORD_TYPE_NAME).getRecordTypeId();
            this.calculateTerminalDilapidations();
        }
    }

    public void calculateTerminalDilapidations() {
        if (this.isServicedRT) {

            Decimal painting = this.surrender.Painting_Decorating__c != null ? this.surrender.Painting_Decorating__c : 0;
            Decimal cleansing = this.surrender.Carpet_Cleaning__c != null ? this.surrender.Carpet_Cleaning__c : 0;
            Decimal other = this.surrender.Other_Costs__c != null ? this.surrender.Other_Costs__c : 0;
            System.debug(painting + ' + ' + cleansing + ' + ' + other);
            this.surrender.Terminal_Dilapidations__c = painting + cleansing + other;
        }
    }

    public Boolean getSurrenderExists() {
        return this.surrender.Id != null;
    }

    public PageReference cancelSurrender() {
        PageReference thePage = new PageReference('/' + this.contract.Id);
        thePage.setRedirect(true);
        return thePage;
    }

    public PageReference saveSurrender() {
        try {
            insert surrender;
            if (!this.isServicedRT) {
                Case surrenderCase = this.createSurrenderCase(contract, surrender);
                PageReference thePage = new PageReference('/' + surrenderCase.Id);
                thePage.setRedirect(true);
                return thePage;
            }

            return cancelSurrender();
        } catch (DmlException e) {
            this.errorMessage = '';
            for (Integer var = 0; var < e.getNumDml(); var++) {
                this.errorMessage = +e.getDmlMessage(var);
            }
            this.isMessageRendered = true;
        }
        return null;
    }

    private Contract findContractById(Id contractId) {
        List<Contract> contracts = [SELECT Id, Name, AccountId, Pricebook2Id, Pricebook2.Name, SBQQ__Quote__c, SBQQ__Opportunity__c 
                                    FROM Contract WHERE Id = :contractId];
        if (contracts.size() != 0) {
            return contracts.get(0);
        }
        return null;
    }

    private Id getRecordTypeId(Contract contract) {
        Id recordTypeId = null;
        if (contract != null && contract.Pricebook2Id != null) {
            if (contract.Pricebook2.Name.contains(CONVENTIONAL_RECORD_TYPE_NAME)) {
                recordTypeId = Schema.SObjectType.Contract_Surrender__c.getRecordTypeInfosByName().get(CONVENTIONAL_RECORD_TYPE_NAME).getRecordTypeId();
            } else if (contract.Pricebook2.Name.contains(SERVICED_RECORD_TYPE_NAME)) {
                recordTypeId = Schema.SObjectType.Contract_Surrender__c.getRecordTypeInfosByName().get(SERVICED_RECORD_TYPE_NAME).getRecordTypeId();
            }
        }
        return recordTypeId;
    }

    private Decimal calculateDeposit(Id contractId) {
        List<SBQQ__Subscription__c> subscriptions = [
                SELECT Id, SBQQ__UnitCost__c
                FROM SBQQ__Subscription__c
                WHERE SBQQ__Contract__c = :contractId AND SBQQ__Product__r.Is_Deposit__c = TRUE
        ];

        Decimal outputValue = 0;
        for (SBQQ__Subscription__c subscription : subscriptions) {
            outputValue += NumberUtils.convertNullToZero(subscription.SBQQ__UnitCost__c);
        }
        return outputValue;
    }

    private Case createSurrenderCase(Contract contract, Contract_Surrender__c surrender) {
        String recordTypeName = this.isServicedRT ? CaseService.SERVICED_SURRENDER_RECORD_TYPE : CaseService.CONVENTIONAL_SURRENDER_RECORD_TYPE;
        Id recordTypeId = RecordTypeHelper.getCaseRtIdByDeveloperName(recordTypeName);
        Case surrenderCase =
                new Case(SuppliedName = 'Surrender & ' + contract.Name,
                        AccountId = contract.AccountId,
                        Opportunity__c = contract.SBQQ__Opportunity__c,
                        Quote__c = contract.SBQQ__Quote__c,
                        Contract__c = contract.Id,
                        Contract_Surrender__c = surrender.Id,
                        Proposed_date_of_surrender__c = surrender.Proposed_date_of_surrender__c,
                        Final_Dilapidations__c = surrender.Final_Dilapidations__c,
                        Surrender_Premium__c = surrender.Surrender_Premium__c,
                        Budget_Dilapidations__c = surrender.Budget_Dilapidations__c,
                        Interim_Dilapidations__c = surrender.Interim_Dilapidations__c,
                        Terminal_Dilapidations__c = surrender.Terminal_Dilapidations__c,
                        Break_Penalty_Premium__c = surrender.Break_Penalty_Premium__c,
                        Suite_Restoration__c = surrender.Suite_Restoration__c,
                        Is_the_customer_liable_for_electricity__c = surrender.Is_the_customer_liable_for_electricity__c,
                        Is_the_customer_liable_for_Service_Chrg__c = surrender.Is_the_customer_liable_for_Service_Chrg__c,
                        RecordTypeId = recordTypeId
                );
        insert surrenderCase;
        return surrenderCase;
    }
}