src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Case</fullName>
        <active>true</active>
        <businessProcess>Ordinary Case</businessProcess>
        <label>Case</label>
    </recordTypes>
    <recordTypes>
        <fullName>Design</fullName>
        <active>true</active>
        <businessProcess>Design Case</businessProcess>
        <label>Design</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>SBQQ__Opportunity2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity associated with this Quote.</description>
        <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>SBQQ__ProductCode__c</fullName>
        <description>Code for the product referenced by this line.</description>
        <formula>SBQQ__Product__r.ProductCode</formula>
        <inlineHelpText>Code for the product referenced by this line.</inlineHelpText>
        <label>Product Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Suite_Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Suite Inventory</label>
        <referenceTo>Inventory__c</referenceTo>
        <relationshipLabel>Quote Lines (Suite Inventory)</relationshipLabel>
        <relationshipName>Quote_Lines2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CustomDesignCase.cls
public class CustomDesignCase {

    public static Id getDesignRecordType() {
        Id designRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Design').getRecordTypeId();
        return designRecordTypeId;
    }

    public static Id getFitOutDesignRecordType() {
        Id designFitOutRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Fit Out Design').getRecordTypeId();
        return designFitOutRecordTypeId;
    }

    public static Id getDesignTeamQueue() {
        Id designTeamId;
        List<Group> queueList = [SELECT Id FROM Group WHERE DeveloperName = 'Design_Team' AND Type = 'Queue'];
        if (queueList.size() > 0) {
            designTeamId = queueList.get(0).Id;
        }
        return designTeamId;
    }

    public String getQuoteId() {
        return ApexPages.currentPage().getParameters().get('QuoteId');
    }

    public Boolean getHaveErrors() {
        Boolean haveErrors = false;
        Id quoteId = getQuoteId();
        String errFitOut = 'Please add a Fit Out product to the quote to create a design case';
        String errInventory = 'Please, select Inventory (Suite) first!';
        List<SBQQ__QuoteLine__c> quoteLines = new List<SBQQ__QuoteLine__c>();
        quoteLines = [
                SELECT Id, Suite_Inventory__c
                FROM SBQQ__QuoteLine__c
                WHERE SBQQ__Quote__c = :quoteId
                AND SBQQ__ProductCode__c = 'FitOut'
        ];
        if (quoteLines.size() > 0) {
            if (quoteLines.get(0).Suite_Inventory__c == null) {
                haveErrors = true;
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, errInventory));
            }
        } else {
            haveErrors = true;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, errFitOut));
        }
        return haveErrors;
    }

    public String getCaseId() {
        Id caseId = null;
        Id quoteId = getQuoteId();
        List<Id> recordTypeIds = new List<Id>();
        recordTypeIds.add(getDesignRecordType());
        recordTypeIds.add(getFitOutDesignRecordType());
        List<Case> cases = [
                SELECT Id
                FROM Case
                WHERE Quote__c = :quoteId
                AND RecordTypeId IN :recordTypeIds
        ];
        if (cases.size() > 0) {
            caseId = cases.get(0).Id;
        }
        return caseId;
    }

    @AuraEnabled
    public static CreateDesignCase getCaseParams(Id quoteId) {
        Id quoteLineId = null;
        Id opportunityId = null;
        Id accountId = null;
        Id inventoryId = null;
        List<SBQQ__QuoteLine__c> quoteLines = [
                SELECT Id,
                    Suite_Inventory__c, 
                    SBQQ__Quote__r.SBQQ__Opportunity2__r.AccountId
                FROM SBQQ__QuoteLine__c
                WHERE SBQQ__Quote__c = :quoteId
                AND SBQQ__ProductCode__c = 'FitOut'
        ];
        if (quoteLines.size() > 0) {
            quoteLineId = quoteLines.get(0).Id;
            opportunityId = quoteLines.get(0).SBQQ__Quote__r.SBQQ__Opportunity2__c;
            accountId = quoteLines.get(0).SBQQ__Quote__r.SBQQ__Opportunity2__r.AccountId;
            inventoryId = quoteLines.get(0).Suite_Inventory__c;
        }

        CreateDesignCase createCase = new CreateDesignCase();
        createCase.quoteId = quoteId;
        createCase.quoteLineId = quoteLineId;
        createCase.recordTypeId = getDesignRecordType();
        createCase.accountId = accountId;
        createCase.opportunityId = opportunityId;
        createCase.inventoryId = inventoryId;
        createCase.ownerId = getDesignTeamQueue();
        return createCase;
    }

    public class CreateDesignCase {
        @AuraEnabled
        public String quoteId { get; set; }
        @AuraEnabled
        public String quoteLineId { get; set; }
        @AuraEnabled
        public String recordTypeId { get; set; }
        @AuraEnabled
        public String accountId { get; set; }
        @AuraEnabled
        public String opportunityId { get; set; }
        @AuraEnabled
        public String inventoryId { get; set; }
        @AuraEnabled
        public String ownerId { get; set; }
    }
}