src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Briefing_Statement__c</fullName>
        <label>Briefing Statement</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Car_Parkings__c</fullName>
        <label>Car Parking Spaces</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Commencement_Date__c</fullName>
        <label>Commencement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 4) OR (1 AND 2 AND 3)</booleanFilter>
            <filterItems>
                <field>Inventory__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Actual Suite, Proposed Suite</value>
            </filterItems>
            <filterItems>
                <field>Inventory__c.Property__c</field>
                <operation>equals</operation>
                <valueField>$Source.Property__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Project Works Request Case</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Project Works Request Case</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Inventory__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_Phones__c</fullName>
        <label>Number of phones taken</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Cases (Sales Contact)</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Storage_1_Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Storage 1 Inventory</label>
        <referenceTo>Inventory__c</referenceTo>
        <relationshipLabel>Cases (Storage 1 Inventory)</relationshipLabel>
        <relationshipName>Cases3</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Case</fullName>
        <active>true</active>
        <businessProcess>Ordinary Case</businessProcess>
        <label>Case</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <inlineHelpText>Hold the &apos;ctrl&apos; key to select multiple types.</inlineHelpText>
        <label>Contact Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Billing Contact</fullName>
                </value>
                <value>
                    <fullName>In Life Property Contact</fullName>
                </value>
                <value>
                    <fullName>Sales Contact</fullName>
                </value>
                <value>
                    <fullName>Out of Hours Contact</fullName>
                </value>
                <value>
                    <fullName>Legal Contact</fullName>
                </value>
                <value>
                    <fullName>Project Management Contact</fullName>
                </value>
                <value>
                    <fullName>Director Contact</fullName>
                </value>
                <value>
                    <fullName>Remittance - Finance</fullName>
                </value>
                <value>
                    <fullName>Statement - Finance</fullName>
                </value>
                <value>
                    <fullName>Purchase Ledger - Finance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Inventory__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Inventories</relationshipLabel>
        <relationshipName>Inventories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipName>Suites</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quanta__c</fullName>
        <label>Quanta</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Lab</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Office</fullName>
                </value>
                <value>
                    <fullName>Storage</fullName>
                </value>
                <value>
                    <fullName>SerLic</fullName>
                </value>
                <value>
                    <fullName>DedLic</fullName>
                </value>
                <value>
                    <fullName>DeskLic</fullName>
                </value>
                <value>
                    <fullName>CPL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Inventory</label>
    <nameField>
        <label>Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Briefing_Statement__c</fullName>
        <description>Additional information to the property management team.</description>
        <inlineHelpText>Additional information to the property management team.</inlineHelpText>
        <label>Briefing Statement</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <recordTypes>
        <fullName>Conventional</fullName>
        <active>true</active>
        <businessProcess>Conventional Sales Process</businessProcess>
        <label>Conventional</label>
    </recordTypes>
    <recordTypes>
        <fullName>Serviced</fullName>
        <active>true</active>
        <businessProcess>Serviced Sales Process</businessProcess>
        <label>Serviced</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Property_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Properties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Serviced_Space_Coordinator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Serviced Space Coordinator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Properties4</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory</label>
        <referenceTo>Inventory__c</referenceTo>
        <relationshipName>Inventory</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Opportunity2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity associated with this Quote.</description>
        <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__PrimaryContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Primary contact for the quote. This person&apos;s name will appear on generated quote document.</description>
        <inlineHelpText>Primary contact for the quote. This person&apos;s name will appear on generated quote document.</inlineHelpText>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Status__c</fullName>
        <description>Status indicating where quote is in its lifecycle.</description>
        <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Presented</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Pending Approval - Offline Edit</fullName>
                </value>
                <value>
                    <fullName>Awaiting Approval - Offline Edit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <recordTypes>
        <fullName>Conventional</fullName>
        <active>true</active>
        <label>Conventional</label>
    </recordTypes>
    <recordTypes>
        <fullName>Serviced</fullName>
        <active>true</active>
        <label>Serviced</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>Bundle_Code__c</fullName>
        <label>Bundle Code</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Car_Parking_Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Car Parking Inventory</label>
        <referenceTo>Inventory__c</referenceTo>
        <relationshipLabel>Quote Lines (Car Parking Inventory)</relationshipLabel>
        <relationshipName>Quote_Lines1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comparable_ID_for_Calculator__c</fullName>
        <label>Comparable ID for Calculator</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory</label>
        <referenceTo>Inventory__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>Quote_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Quote Lines (Property)</relationshipLabel>
        <relationshipName>QuoteLines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quantity__c</fullName>
        <description>Quantity being quoted.</description>
        <inlineHelpText>Quantity being quoted.</inlineHelpText>
        <label>Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/NewCaseFromQuoteTest.cls
@IsTest
private class NewCaseFromQuoteTest {

    @IsTest
    static void givenSerQuoteWhenQuoteAcceptedThenCasesCreated() {
        //given
        SBQQ__Quote__c quote = RecordDmlTest.preGenerateQuote('Serviced');

        Opportunity opportunity = [SELECT AccountId FROM Opportunity WHERE Id = :quote.SBQQ__Opportunity2__c];
        opportunity.Briefing_Statement__c = 'test statement';
        upsert opportunity;

        Contact contact = new Contact(AccountId = opportunity.AccountId, Contact_Type__c = 'In Life Property Contact', LastName = 'Test Contact');
        insert contact;

        User propertyManager = RecordDmlTest.createUser();

        Property__c property = [SELECT Id, Property_Manager__c FROM Property__c WHERE Id = :quote.Property__c];
        property.Serviced_Space_Coordinator__c = propertyManager.Id;
        upsert property;

        //TODO:extract and eliminate code duplication
        List<Product2> products = new List<Product2>();
        Product2 storageProduct = new Product2(Name = 'Storage', Family = 'Suite', ProductCode='Storage');
        products.add(storageProduct);
        Product2 officeRentProduct = new Product2(Name = 'Office Rent', Family = 'Suite', ProductCode='OfficeRent');
        products.add(officeRentProduct);
        Product2 carSpaceProduct = new Product2(Name = 'Car Space', Family = 'Parking', ProductCode='CarSpace');
        products.add(carSpaceProduct);
        Product2 carParkingLicenseProduct = new Product2(Name = 'Car Parking License', Family = 'Parking', ProductCode='CarParkLicense');
        products.add(carParkingLicenseProduct);
        Product2 handset = new Product2(Name = 'Handsets', ProductCode = 'BSHD', Family = '');
        products.add(handset);
        insert products;

        Inventory__c storageInventory = RecordDmlTest.createActualSuiteInventory(storageProduct, property);
        Inventory__c officeRentInventory = RecordDmlTest.createActualSuiteInventory(officeRentProduct, property);
        Inventory__c carParkingInventory = RecordDmlTest.createActualCarParkingInventory(carSpaceProduct, property);
        Inventory__c handSetInventory = RecordDmlTest.createActualCarParkingInventory(handset, property);

        SBQQ__QuoteLine__c suite = RecordDmlTest.generateLine(officeRentProduct, quote.Id, officeRentInventory.Id, null);
        SBQQ.TriggerControl.disable();
        insert suite;

        SBQQ__QuoteLine__c storage = RecordDmlTest.generateLine(storageProduct, quote.Id, storageInventory.Id, null);
        storage.Comparable_ID_for_Calculator__c = 'STR-1';
        storage.Bundle_Code__c = ProductService.PRODUCT_CODE_STORAGE;

        SBQQ__QuoteLine__c parking = RecordDmlTest.generateLine(carSpaceProduct, quote.Id, carParkingInventory.Id, null);
        parking.Car_Parking_Inventory__c = carParkingInventory.Id;

        SBQQ__QuoteLine__c handsetLine = RecordDmlTest.generateLine(handset, quote.Id, handSetInventory.Id, suite.Id);
        handsetLine.SBQQ__Quantity__c = 3;

        SBQQ.TriggerControl.disable();
        insert new List<SBQQ__QuoteLine__c>{
                storage, parking, handsetLine
        };

        Test.startTest();
        SBQQ_QuoteService.cleanup();
        ContactService.cleanup();
        //when
        quote.SBQQ__Status__c = 'Accepted';
        update quote;
        Test.stopTest();

        //then
        Case parentCase = [
                SELECT Id, OwnerId, AccountId, ContactId, Briefing_Statement__c, BusinessHoursId, CurrencyIsoCode,
                        Sales_Contact__c, Property__c, Quote__c, RecordTypeId, Status,
                        Storage_1_Inventory__c, Inventory__c, Commencement_Date__c, Car_Parkings__c, Opportunity__c, Number_of_Phones__c
                FROM Case
                WHERE OwnerId = :propertyManager.Id AND
                RecordTypeId = :RecordTypeHelper.getCaseRtIdByDeveloperName(CaseService.SERVICED_SPACE_ONBOARDING_RECORD_TYPE)
        ];

        System.assertEquals(propertyManager.Id, parentCase.OwnerId);
        System.assertEquals(CaseService.getDefaultBusinessHours().Id, parentCase.BusinessHoursId);
        System.assertEquals(opportunity.Briefing_Statement__c, parentCase.Briefing_Statement__c);
        System.assertEquals('GBP', parentCase.CurrencyIsoCode);
        System.assertEquals(contact.Id, parentCase.ContactId);
        System.assertEquals(quote.SBQQ__PrimaryContact__c, parentCase.Sales_Contact__c);
        System.assertEquals(quote.Property__c, parentCase.Property__c);
        System.assertEquals(quote.Id, parentCase.Quote__c);
        System.assertEquals(RecordTypeHelper.getCaseRtIdByDeveloperName(CaseService.SERVICED_SPACE_ONBOARDING_RECORD_TYPE), parentCase.RecordTypeId);
        System.assertEquals('New', parentCase.Status);
        System.assertEquals(officeRentInventory.Id, parentCase.Inventory__c);
        System.assertNotEquals(null, parentCase.Commencement_Date__c);
        System.assertEquals(opportunity.AccountId, parentCase.AccountId);
        System.assertEquals(opportunity.Id, parentCase.Opportunity__c);
        System.assertEquals(handsetLine.SBQQ__Quantity__c, parentCase.Number_of_Phones__c);
        System.assert(String.isNotBlank(parentCase.Car_Parkings__c));
    }

    @IsTest
    static void givenConQuoteWhenQuoteAcceptedThenCasesCreated() {
        //given
        SBQQ__Quote__c quote = RecordDmlTest.preGenerateQuote('Conventional');

        Opportunity opportunity = [SELECT AccountId FROM Opportunity WHERE Id = :quote.SBQQ__Opportunity2__c];
        opportunity.Briefing_Statement__c = 'test statement';
        update opportunity;

        Contact contact = new Contact(AccountId = opportunity.AccountId, Contact_Type__c = 'In Life Property Contact', LastName = 'Test Contact');
        insert contact;

        User propertyManager = RecordDmlTest.createUser();

        Property__c property = [SELECT Id, Property_Manager__c FROM Property__c WHERE Id = :quote.Property__c];
        property.Property_Manager__c = propertyManager.Id;
        upsert property;

        List<Product2> products = new List<Product2>();
        Product2 storageProduct = new Product2(Name = 'Storage', Family = 'Suite', ProductCode='Storage' );
        products.add(storageProduct);
        Product2 officeRentProduct = new Product2(Name = 'Office Rent', Family = 'Suite', ProductCode='OfficeRent');
        products.add(officeRentProduct);
        Product2 carParkingLicenseProduct = new Product2(Name = 'Car Parking License', Family = 'Parking', ProductCode='CarParkLicense');
        products.add(carParkingLicenseProduct);
        Product2 carSpaceProduct = new Product2(Name = 'Car Space', Family = 'Parking', ProductCode='CarSpace');
        products.add(carSpaceProduct);
        insert products;

        Inventory__c storageInventory = RecordDmlTest.createActualSuiteInventory(storageProduct, property);
        Inventory__c officeRentInventory = RecordDmlTest.createActualSuiteInventory(officeRentProduct, property);
        Inventory__c carParkingInventory = RecordDmlTest.createActualCarParkingInventory(carSpaceProduct, property);

        SBQQ__QuoteLine__c suite = RecordDmlTest.generateLine(officeRentProduct, quote.Id, officeRentInventory.Id, null);
        suite.Quanta__c = 'suite';

        SBQQ__QuoteLine__c storage = RecordDmlTest.generateLine(storageProduct, quote.Id, storageInventory.Id, null);
        storage.Comparable_ID_for_Calculator__c = 'STR-1';
        storage.Bundle_Code__c = ProductService.PRODUCT_CODE_STORAGE;

        SBQQ__QuoteLine__c parking = RecordDmlTest.generateLine(carSpaceProduct, quote.Id, carParkingInventory.Id, null);
        parking.Car_Parking_Inventory__c = carParkingInventory.Id;

        SBQQ.TriggerControl.disable();
        insert new List<SBQQ__QuoteLine__c>{
                suite, storage, parking
        };

        Test.startTest();
        SBQQ_QuoteService.cleanup();
        ContactService.cleanup();
        //when
        quote.SBQQ__Status__c = 'Accepted';
        update quote;
        Test.stopTest();

        //then
        Case parentCase = [
                SELECT Id, OwnerId, AccountId, ContactId, Briefing_Statement__c, BusinessHoursId, CurrencyIsoCode,
                        Sales_Contact__c, Property__c, Quote__c, RecordTypeId, Status,
                        Storage_1_Inventory__c, Inventory__c, Commencement_Date__c, Car_Parkings__c, Opportunity__c
                FROM Case
                WHERE OwnerId = :propertyManager.Id AND ParentId != null AND
                RecordTypeId = :RecordTypeHelper.getCaseRtIdByDeveloperName(CaseService.CONVENTIONAL_ONBOARDING_RECORD_TYPE)
        ];

        System.assertEquals(propertyManager.Id, parentCase.OwnerId);
        System.assertEquals(CaseService.getDefaultBusinessHours().Id, parentCase.BusinessHoursId);
        System.assertEquals(opportunity.Briefing_Statement__c, parentCase.Briefing_Statement__c);
        System.assertEquals('GBP', parentCase.CurrencyIsoCode);
        System.assertEquals(contact.Id, parentCase.ContactId);
        System.assertEquals(quote.SBQQ__PrimaryContact__c, parentCase.Sales_contact__c);
        System.assertEquals(quote.Property__c, parentCase.Property__c);
        System.assertEquals(quote.Id, parentCase.Quote__c);
        System.assertEquals(RecordTypeHelper.getCaseRtIdByDeveloperName(CaseService.CONVENTIONAL_ONBOARDING_RECORD_TYPE), parentCase.RecordTypeId);
        System.assertEquals('New', parentCase.Status);
        System.assertEquals(storageInventory.Id, parentCase.Storage_1_Inventory__c);
        System.assertEquals(officeRentInventory.Id, parentCase.Inventory__c);
        System.assertNotEquals(null, parentCase.Commencement_Date__c);
        System.assertEquals(opportunity.AccountId, parentCase.AccountId);
        System.assertEquals(opportunity.Id, parentCase.Opportunity__c);
        System.assert(String.isNotBlank(parentCase.Car_Parkings__c));
    }

}