src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Car_Parkings__c</fullName>
        <label>Car Parking Spaces</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 4) OR (1 AND 2 AND 3)</booleanFilter>
            <filterItems>
                <field>Inventory__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Actual Suite, Proposed Suite</value>
            </filterItems>
            <filterItems>
                <field>Inventory__c.Property__c</field>
                <operation>equals</operation>
                <valueField>$Source.Property__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Project Works Request Case</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Project Works Request Case</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Inventory__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_Phones__c</fullName>
        <label>Number of phones taken</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Storage_1_Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Storage 1 Inventory</label>
        <referenceTo>Inventory__c</referenceTo>
        <relationshipLabel>Cases (Storage 1 Inventory)</relationshipLabel>
        <relationshipName>Cases3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Storage_2_Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Storage 2 Inventory</label>
        <referenceTo>Inventory__c</referenceTo>
        <relationshipLabel>Cases (Storage 2 Inventory)</relationshipLabel>
        <relationshipName>Cases4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Storage_3_Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Storage 3 Inventory</label>
        <referenceTo>Inventory__c</referenceTo>
        <relationshipLabel>Cases (Storage 3 Inventory)</relationshipLabel>
        <relationshipName>Cases5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Storage_4_Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Storage 4 Inventory</label>
        <referenceTo>Inventory__c</referenceTo>
        <relationshipLabel>Cases (Storage 4 Inventory)</relationshipLabel>
        <relationshipName>Cases6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Storage_5_Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Storage 5 Inventory</label>
        <referenceTo>Inventory__c</referenceTo>
        <relationshipLabel>Cases (Storage 5 Inventory)</relationshipLabel>
        <relationshipName>Cases7</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Case</fullName>
        <active>true</active>
        <businessProcess>Ordinary Case</businessProcess>
        <label>Case</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Inventory__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR (3 AND 4) OR (5 AND 6) OR 7</booleanFilter>
            <errorMessage>Please select the Product that meets the Inventory Record Type</errorMessage>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Actual Suite, Proposed Suite</value>
            </filterItems>
            <filterItems>
                <field>Product2.ProductCode</field>
                <operation>equals</operation>
                <value>OfficeRent, LabSpace, RetailRent, Storage, BSLF, BSDL</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Desk</value>
            </filterItems>
            <filterItems>
                <field>Product2.ProductCode</field>
                <operation>equals</operation>
                <value>BSCW</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Car Parking</value>
            </filterItems>
            <filterItems>
                <field>Product2.ProductCode</field>
                <operation>equals</operation>
                <value>CarSpace</value>
            </filterItems>
            <filterItems>
                <field>Product2.ProductCode</field>
                <operation>equals</operation>
                <value>BSHD, PreEmptionAgreement</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Inventories</relationshipLabel>
        <relationshipName>Suites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipName>Suites</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Inventory</label>
    <nameField>
        <label>Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Products</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Property_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Properties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Serviced_Space_Coordinator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Serviced Space Coordinator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Properties4</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory</label>
        <referenceTo>Inventory__c</referenceTo>
        <relationshipName>Inventory</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Opportunity2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity associated with this Quote.</description>
        <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>Bundle_Code__c</fullName>
        <label>Bundle Code</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Car_Parking_Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Car Parking Inventory</label>
        <referenceTo>Inventory__c</referenceTo>
        <relationshipLabel>Quote Lines (Car Parking Inventory)</relationshipLabel>
        <relationshipName>Quote_Lines1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comparable_ID_for_Calculator__c</fullName>
        <label>Comparable ID for Calculator</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory</label>
        <referenceTo>Inventory__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>Quote_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Quote Lines (Property)</relationshipLabel>
        <relationshipName>QuoteLines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product quoted by this line item.</description>
        <inlineHelpText>Product quoted by this line item.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>R00N70000001lXB6EAM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quantity__c</fullName>
        <description>Quantity being quoted.</description>
        <inlineHelpText>Quantity being quoted.</inlineHelpText>
        <label>Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SBQQ__RequiredBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Links this line to another line in the same quote whose product requires this line&apos;s product.</description>
        <inlineHelpText>Indicates which other product on this quote requires it.</inlineHelpText>
        <label>Required By</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>Quote_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Suite_Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Suite Inventory</label>
        <referenceTo>Inventory__c</referenceTo>
        <relationshipLabel>Quote Lines (Suite Inventory)</relationshipLabel>
        <relationshipName>Quote_Lines2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/NewCaseFromQuote.cls
public with sharing class NewCaseFromQuote {

    private static Map<String, String> STORAGE_FIELDS_MAP = new Map<String, String>{
            'STR-1' => 'Storage_1_Inventory__c',
            'STR-2' => 'Storage_2_Inventory__c',
            'STR-3' => 'Storage_3_Inventory__c',
            'STR-4' => 'Storage_4_Inventory__c',
            'STR-5' => 'Storage_5_Inventory__c'
    };

    public static List<Case> createLeaseTransactionCases(List<SBQQ__Quote__c> quotes, Map<Id, Opportunity> opportunities, Map<Id, List<Contact>> legalContacts) {
        // Create Cases
        List<Case> casesForCreated = new List<Case>();
        for (SBQQ__Quote__c quote : quotes) {
            Opportunity theOpportunity = opportunities.get(quote.SBQQ__Opportunity2__c);

            //BWSFDC-1649
            if (!(theOpportunity.RecordTypeId == RecordTypeHelper.getOpportunityRtIdByDeveloperName(OpportunityService.SERVICED_RECORD_TYPE)
                    || theOpportunity.RecordTypeId == RecordTypeHelper.getOpportunityRtIdByDeveloperName(OpportunityService.VIRTUAL_RECORD_TYPE_NAME))) {

                Contact legalContact = legalContacts.containsKey(theOpportunity.AccountId)
                        && !legalContacts.get(theOpportunity.AccountId).isEmpty()
                        ? legalContacts.get(theOpportunity.AccountId).get(0)
                        : null;

                Case theCase = CaseService.generateDefaultLeaseTransactionCase(quote, theOpportunity);
                theCase.OwnerId = QueueHelper.getRtIdByDeveloperName(QueueHelper.LEASE_TRANSACTION_QUEUE);
                theCase.RecordTypeId = RecordTypeHelper.getCaseRtIdByDeveloperName(CaseService.LEASE_TRANSACTION_RECORD_TYPE);
                theCase.ContactId = legalContact != null ? legalContact.Id : null;
                casesForCreated.add(theCase);
            }
        }
        return casesForCreated;
    }

    public static List<Case> createConventionalOnboardingCases(List<SBQQ__Quote__c> quotes, Map<Id, Opportunity> opportunities, Map<Id, List<Contact>> inLifePropertyContacts, Map<Id, List<SBQQ__QuoteLine__c>> quoteLinesByQuoteIds, Map<Id, Property__c> propertiesByIds) {
        // STORAGE CODES
        Set<String> storageKeys = STORAGE_FIELDS_MAP.keySet();

        // Create Cases
        List<Case> casesForCreated = new List<Case>();
        for (SBQQ__Quote__c quote : quotes) {
            Opportunity theOpportunity = opportunities.get(quote.SBQQ__Opportunity2__c);
            Contact inLifeProperty = inLifePropertyContacts.containsKey(theOpportunity.AccountId)
                    && !inLifePropertyContacts.get(theOpportunity.AccountId).isEmpty()
                    ? inLifePropertyContacts.get(theOpportunity.AccountId).get(0)
                    : null;
            List<SBQQ__QuoteLine__c> quoteHeadLines = SBQQ_QuoteService.getHeadLinesFromQLI(quoteLinesByQuoteIds.get(quote.Id), quote.Id);

            Case theCase = CaseService.generateDefaultOnboardingCase(quote, quoteHeadLines, theOpportunity);
            theCase.OwnerId = propertiesByIds.get(quote.Property__c).Property_Manager__c;
            theCase.RecordTypeId = RecordTypeHelper.getCaseRtIdByDeveloperName(CaseService.CONVENTIONAL_ONBOARDING_RECORD_TYPE);
            theCase.ContactId = inLifeProperty != null ? inLifeProperty.Id : null;

            Set<String> carParkingInventoryNames = new Set<String>();
            for (SBQQ__QuoteLine__c quoteLine : quoteLinesByQuoteIds.get(quote.Id)) {
                String comparableId = quoteLine.Comparable_ID_for_Calculator__c;

                if (quoteLine.Suite_Inventory__c != NULL && quoteLine.SBQQ__RequiredBy__c == NULL) {
                    if (quoteLine.Bundle_Code__c == ProductService.PRODUCT_CODE_STORAGE
                            && String.isNotBlank(comparableId) && storageKeys.contains(comparableId)) {

                        theCase.put(STORAGE_FIELDS_MAP.get(comparableId), quoteLine.Suite_Inventory__c);
                    }

                    if (quoteLine.Bundle_Code__c != ProductService.PRODUCT_CODE_STORAGE
                            && quoteLine.Suite_Inventory__r.Product__c != null
                            && ProductService.isSuite(quoteLine.Suite_Inventory__r.Product__r)) {

                        theCase.Inventory__c = quoteLine.Suite_Inventory__c;
                    }
                }

                if (quoteLine.Car_Parking_Inventory__c != null) {
                    carParkingInventoryNames.add(quoteLine.Car_Parking_Inventory__r.Name);
                }
            }

            theCase.Car_Parkings__c = String.join((Iterable<String>) carParkingInventoryNames, ',');
            casesForCreated.add(theCase);
        }
        return casesForCreated;
    }

    public static List<Case> createServicedSpaceOnboardingCase(List<SBQQ__Quote__c> quotes, Map<Id, Opportunity> opportunities, Map<Id, List<Contact>> inLifePropertyContacts, Map<Id, List<SBQQ__QuoteLine__c>> quoteLinesByQuoteIds, Map<Id, Property__c> propertiesByIds) {
        // Create Cases
        List<Case> casesForCreated = new List<Case>();
        for (SBQQ__Quote__c quote : quotes) {

            Opportunity theOpportunity = opportunities.get(quote.SBQQ__Opportunity2__c);
            Contact inLifeProperty = inLifePropertyContacts.containsKey(theOpportunity.AccountId)
                    && !inLifePropertyContacts.get(theOpportunity.AccountId).isEmpty()
                    ? inLifePropertyContacts.get(theOpportunity.AccountId).get(0)
                    : null;
            List<SBQQ__QuoteLine__c> quoteHeadLines = SBQQ_QuoteService.getHeadLinesFromQLI(quoteLinesByQuoteIds.get(quote.Id), quote.Id);

            Case theCase = CaseService.generateDefaultOnboardingCase(quote, quoteHeadLines, theOpportunity);
            if (propertiesByIds.get(quote.Property__c).Serviced_Space_Coordinator__c != null) {
                theCase.OwnerId = propertiesByIds.get(quote.Property__c).Serviced_Space_Coordinator__c;
            } else {
                theCase.OwnerId = propertiesByIds.get(quote.Property__c).Property_Manager__c;
            }
            theCase.RecordTypeId = RecordTypeHelper.getCaseRtIdByDeveloperName(CaseService.SERVICED_SPACE_ONBOARDING_RECORD_TYPE);
            theCase.ContactId = inLifeProperty != null ? inLifeProperty.Id : null;

            Set<String> carParkingInventoryNames = new Set<String>();
            for (SBQQ__QuoteLine__c quoteLine : quoteLinesByQuoteIds.get(quote.Id)) {
                if (quoteLine.Suite_Inventory__c != NULL && quoteLine.SBQQ__RequiredBy__c == NULL &&
                        quoteLine.Bundle_Code__c != ProductService.PRODUCT_CODE_STORAGE &&
                        quoteLine.Suite_Inventory__r.Product__c != null &&
                        ProductService.isSuite(quoteLine.Suite_Inventory__r.Product__r)) {

                    theCase.Inventory__c = quoteLine.Suite_Inventory__c;
                }
                if (quoteLine.SBQQ__Product__c != null &&
                        quoteLine.SBQQ__Quantity__c != null &&
                        quoteLine.SBQQ__Product__r.Name.equalsIgnoreCase('Handsets')) {

                    theCase.Number_of_Phones__c = quoteLine.SBQQ__Quantity__c;
                }
                if (quoteLine.Car_Parking_Inventory__c != null) {
                    carParkingInventoryNames.add(quoteLine.Car_Parking_Inventory__r.Name);
                }
            }

            theCase.Car_Parkings__c = String.join((Iterable<String>) carParkingInventoryNames, ',');
            casesForCreated.add(theCase);
        }
        return casesForCreated;
    }

}