src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Contract_Surrender__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract Surrender</label>
        <referenceTo>Contract_Surrender__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Final_Dilapidations__c</fullName>
        <label>Final Dilapidations</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Is_the_customer_liable_for_Service_Chrg__c</fullName>
        <description>Is the customer liable for Service Charge Reconciliation?</description>
        <inlineHelpText>Is the customer liable for Service Charge Reconciliation?</inlineHelpText>
        <label>Customer liable for Service Charge</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No_Value_Set</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_the_customer_liable_for_electricity__c</fullName>
        <description>Is the customer liable for electricity costs post completion?</description>
        <inlineHelpText>Is the customer liable for electricity costs post completion?</inlineHelpText>
        <label>Customer liable for electricity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No_Value_Set</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Surrender_Premium__c</fullName>
        <label>Surrender Premium</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <recordTypes>
        <fullName>Case</fullName>
        <active>true</active>
        <businessProcess>Ordinary Case</businessProcess>
        <label>Case</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract_Surrender__c.object
<CustomObject>
    <fields>
        <fullName>Final_Dilapidations__c</fullName>
        <label>Final Dilapidations</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Is_the_customer_liable_for_Service_Chrg__c</fullName>
        <description>Is the customer liable for Service Charge Reconciliation?</description>
        <inlineHelpText>Is the customer liable for Service Charge Reconciliation?</inlineHelpText>
        <label>Customer liable for Service Charge</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No_Value_Set</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_the_customer_liable_for_electricity__c</fullName>
        <description>Is the customer liable for electricity costs post completion?</description>
        <inlineHelpText>Is the customer liable for electricity costs post completion?</inlineHelpText>
        <label>Customer liable for electricity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No_Value_Set</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Surrender_Premium__c</fullName>
        <label>Surrender Premium</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Contract Surrender</label>
    <nameField>
        <label>Contract Surrender Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Surrenders</pluralLabel>
    <recordTypes>
        <fullName>Conventional</fullName>
        <active>true</active>
        <label>Conventional</label>
    </recordTypes>
    <recordTypes>
        <fullName>Serviced</fullName>
        <active>true</active>
        <label>Serviced</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Pricebook2.object
<CustomObject>
    <recordTypes>
        <fullName>Conventional</fullName>
        <active>true</active>
        <label>Conventional</label>
    </recordTypes>
    <recordTypes>
        <fullName>Serviced</fullName>
        <active>true</active>
        <label>Serviced</label>
    </recordTypes>
    <recordTypes>
        <fullName>Virtual</fullName>
        <active>true</active>
        <label>Virtual</label>
    </recordTypes>
    <sharingModel>ReadSelect</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SurrenderContractControllerTest.cls
@IsTest
public with sharing class SurrenderContractControllerTest {
    @IsTest
    public static void testSErvicedSurrender() {
        Account account = RecordDmlTest.createAccount();
        Property__c property = RecordDmlTest.createProperty();
        Pricebook2 priceBook = RecordDmlTest.createPricebook('Serviced');
        Contract contract = new Contract(
            Name = 'TestName',
            AccountId = account.Id,
            Property__c = property.Id,
            Pricebook2Id = priceBook.Id
        );
        insert contract;

        PageReference surrenderPage = Page.SurrenderContract;
        Test.setCurrentPageReference(surrenderPage);
        ApexPages.currentPage().getParameters().put('contractId', contract.Id);
        //then contract found

        //when page opened
        SurrenderContractController controller = new SurrenderContractController(new ApexPages.StandardController(new Contract_Surrender__c()));
        System.assertNotEquals(null, controller.contract);
        controller.surrender.Surrender_Premium__c = 2;
        controller.surrender.Final_Dilapidations__c = 1;
        controller.surrender.Is_the_customer_liable_for_Service_Chrg__c = 'Yes';
        controller.surrender.Is_the_customer_liable_for_electricity__c = 'Yes';
        System.assert(!controller.getSurrenderExists());

        //when surrender
        controller.saveSurrender();

        //then Contract Surrender and Surrender Case created
        System.assertEquals(0, [select count() from Case]);
        System.assertEquals(1, [select count() from Contract_Surrender__c]);
        System.assertNotEquals(null, controller.cancelSurrender());
    }

    @IsTest
    public static void testConventionalSurrender() {
        Account account = RecordDmlTest.createAccount();
        Property__c property = RecordDmlTest.createProperty();
        Pricebook2 priceBook = RecordDmlTest.createPricebook('Conventional');
        Contract contract = new Contract(
            Name = 'TestName',
            AccountId = account.Id,
            Property__c = property.Id,
            Pricebook2Id = priceBook.Id
        );
        insert contract;

        PageReference surrenderPage = Page.SurrenderContract;
        Test.setCurrentPageReference(surrenderPage);
        ApexPages.currentPage().getParameters().put('contractId', contract.Id);
        //then contract found

        //when page opened
        SurrenderContractController controller = new SurrenderContractController(new ApexPages.StandardController(new Contract_Surrender__c()));
        System.assertNotEquals(null, controller.contract);
        controller.surrender.Surrender_Premium__c = 2;
        controller.surrender.Final_Dilapidations__c = 1;
        controller.surrender.Is_the_customer_liable_for_Service_Chrg__c = 'Yes';
        controller.surrender.Is_the_customer_liable_for_electricity__c = 'Yes';

        //when surrender
        controller.saveSurrender();

        //then Contract Surrender and Surrender Case created
        System.assertEquals(1, [select count() from Case]);
        System.assertEquals(1, [select count() from Contract_Surrender__c]);
        System.assertNotEquals(null, controller.cancelSurrender());
    }

    @IsTest
    public static void testErrors() {
        Account account = RecordDmlTest.createAccount();
        Property__c property = RecordDmlTest.createProperty();
        Pricebook2 priceBook = RecordDmlTest.createPricebook('Virtual Sales');
        Contract contract = new Contract(
            Name = 'TestName',
            AccountId = account.Id,
            Property__c = property.Id,
            Pricebook2Id = priceBook.Id
        );
        insert contract;

        PageReference surrenderPage = Page.SurrenderContract;
        Test.setCurrentPageReference(surrenderPage);
        ApexPages.currentPage().getParameters().put('contractId', contract.Id);
        //then contract found

        //when page opened
        SurrenderContractController controller = new SurrenderContractController(new ApexPages.StandardController(new Contract_Surrender__c()));
        System.assertNotEquals(null, controller.contract);
        //then Contract Surrender and Surrender Case created
        System.assert(controller.isMessageRendered);
        Test.setCurrentPageReference(surrenderPage);
        ApexPages.currentPage().getParameters().put('contractId', null);
        controller = new SurrenderContractController(new ApexPages.StandardController(new Contract_Surrender__c()));
        System.assert(controller.isMessageRendered);
    }
}