src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Case</fullName>
        <active>true</active>
        <businessProcess>Ordinary Case</businessProcess>
        <label>Case</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>Virtual</fullName>
        <active>true</active>
        <businessProcess>Virtual Sales Process</businessProcess>
        <label>Virtual</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <recordTypes>
        <fullName>Virtual</fullName>
        <active>true</active>
        <label>Virtual</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SpringCMEos__Environment__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Spring CM Environments</description>
    <fields>
        <fullName>SpringCMEos__Env_Prefix__c</fullName>
        <description>Environment prefix</description>
        <label>Environment Prefix</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SpringCMEos__SpringCM_Account_ID__c</fullName>
        <label>SpringCM Account ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Environment</label>
</CustomObject>

src/classes/SpringCMBtnController.cls
/**
 * @description General class for SpringCM buttons
 */
public with sharing virtual class SpringCMBtnController {

    private static final String URL_ENCODING = 'UTF-8';

    public static final String SPRING_CM_DEFAULT_ENDPOINT = 'na11.springcm.com';
    public static final String SPRING_CM_DOCUMENT_CREATOR = '/atlas/doclauncher/eos/Create Document';
    public static final String SPRING_CM_CONTRACT_CREATOR = '/atlas/doclauncher/eos/Create Lease';
    public static final String SPRING_CM_PARAMETERS = '?aid={0}&eos[0].Id={1}&eos[0].System=Salesforce&eos[0].Type=Case&eos[0].Name={2}&eos[0].ScmPath=/Salesforce/Accounts/{3}/Opportunities/{4}/Quotes/{5}/Cases';

    protected String springCMAction { get; set; }
    protected SpringCMEos__Environment__c springCMSettings { get; set; }
    protected Case theCase { get; set; }

    public SpringCMBtnController(ApexPages.StandardController stdController) {
        springCMSettings = !SpringCMEos__Environment__c.getAll().isEmpty() ? SpringCMEos__Environment__c.getAll().values()[0] : new SpringCMEos__Environment__c();
        if ( !Test.isRunningTest() ) {
            stdController.addFields(new List<String>{'CaseNumber', 'Account.Name', 'Opportunity__r.Name', 'Quote__r.Name'});
        }
        theCase = (Case)stdController.getRecord();
    }

    public PageReference redirectToSpringCM() {
        String endpoint = 'https://' + (String.isNotBlank(springCMSettings.SpringCMEos__Env_Prefix__c) ? springCMSettings.SpringCMEos__Env_Prefix__c : SPRING_CM_DEFAULT_ENDPOINT) + springCMAction;
        String formattedParameters = String.format(SPRING_CM_PARAMETERS, new List<String>{springCMSettings.SpringCMEos__SpringCM_Account_ID__c, theCase.Id, theCase.CaseNumber,
                                                                                          EncodingUtil.urlEncode(theCase.Account.Name, URL_ENCODING), EncodingUtil.urlEncode(theCase.Opportunity__r.Name, URL_ENCODING),
                                                                                          EncodingUtil.urlEncode(theCase.Quote__r.Name, URL_ENCODING)});
        String fullUrl = endpoint + formattedParameters;
        PageReference pageRef = new PageReference(endpoint + formattedParameters);
        return pageRef;
    }
}