src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Customer_Budget__c</fullName>
        <inlineHelpText>Budget for these works or an idea what is affordable?</inlineHelpText>
        <label>Customer Budget</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 4) OR (1 AND 2 AND 3)</booleanFilter>
            <filterItems>
                <field>Inventory__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Actual Suite, Proposed Suite</value>
            </filterItems>
            <filterItems>
                <field>Inventory__c.Property__c</field>
                <operation>equals</operation>
                <valueField>$Source.Property__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Project Works Request Case</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Project Works Request Case</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Inventory__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Case</fullName>
        <active>true</active>
        <businessProcess>Ordinary Case</businessProcess>
        <label>Case</label>
    </recordTypes>
    <recordTypes>
        <fullName>Design</fullName>
        <active>true</active>
        <businessProcess>Design Case</businessProcess>
        <label>Design</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Inventory__c.object
<CustomObject>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipName>Suites</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Inventory</label>
    <nameField>
        <label>Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory</label>
        <referenceTo>Inventory__c</referenceTo>
        <relationshipName>Inventory</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pay_by_BACs_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The system field (not for users) will be checked when Pay by BACs request is approved.</description>
        <label>Pay by BACs Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__PrimaryContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Primary contact for the quote. This person&apos;s name will appear on generated quote document.</description>
        <inlineHelpText>Primary contact for the quote. This person&apos;s name will appear on generated quote document.</inlineHelpText>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Status__c</fullName>
        <description>Status indicating where quote is in its lifecycle.</description>
        <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Presented</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Pending Approval - Offline Edit</fullName>
                </value>
                <value>
                    <fullName>Awaiting Approval - Offline Edit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Design</fullName>
        <active>true</active>
        <label>Design</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TaskTriggerHandlerTest.cls
@isTest
public class TaskTriggerHandlerTest {

    @testSetup
    public static void initData() {
        SBQQ__Quote__c quote = RecordDmlTest.generateServicedQuoteWithLines();
        List<Task> tasks = new List<Task>{
                new Task(Subject = 'Test', WhatId = quote.Id, Status = 'Open', System_Code__c = TaskService.PAY_BY_BACS_SYSTEM_CODE),
                new Task(Subject = TaskService.SUBJECT_SETUP_CD, WhatId = quote.Id, Status = 'Open', System_Code__c = TaskService.SETUP_CD_SYSTEM_CODE)
        };
        insert tasks;

    }

    @isTest
    static void givenCase_whenTaskCreated_thenFieldsPopulated() {
        Case newCase = RecordDmlTest.createCaseRelatedToInventory();
        Task newTask = new Task(Subject = 'Test Task', WhatId = newCase.Id);
        insert newTask;

        newTask = [SELECT Id, Property__c, Inventory__c FROM Task WHERE Id = :newTask.Id];
        System.assertEquals(newTask.Property__c, newCase.Property__c);
        System.assertEquals(newTask.Inventory__c, newCase.Inventory__c);
    }


    @isTest
    static void givenQuoteAndTask_whenTaskCompleted_thenQuoteUpdated() {
        //given
        Task task = [SELECT Id, Status FROM Task WHERE System_Code__c = :TaskService.PAY_BY_BACS_SYSTEM_CODE LIMIT 1];
        SBQQ__Quote__c quote = [SELECT Id, Pay_by_BACs_Approved__c FROM SBQQ__Quote__c LIMIT 1];
        System.assertEquals(false, quote.Pay_by_BACs_Approved__c);

        //when
        Test.startTest();
        task.Status = 'Completed';
        update task;

        //then
        quote = [select Id, Pay_by_BACs_Approved__c FROM SBQQ__Quote__c limit 1];
        System.assertEquals(true, quote.Pay_by_BACs_Approved__c, 'Pay by Bacs Approved field should be updated after the task completed');
        Test.stopTest();
    }

    @isTest
    private static void testAcceptQuotesForCompletedTasks() {
        //given
        Task setupCDTask = [SELECT Id, Status FROM Task WHERE System_Code__c = :TaskService.SETUP_CD_SYSTEM_CODE LIMIT 1];
        SBQQ__Quote__c quote = [SELECT Id, SBQQ__PrimaryContact__c FROM SBQQ__Quote__c LIMIT 1];

        Inventory__c inventory = [SELECT Id FROM Inventory__c LIMIT 1];
        Id designCaseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Design').getRecordTypeId();
        Case designCase = new Case(
                RecordTypeId = designCaseRecordTypeId,
                Inventory__c = inventory.Id,
                ContactId = quote.SBQQ__PrimaryContact__c,
                Customer_Budget__c = 1000
        );
        insert designCase;

        //when
        Test.startTest();
        setupCDTask.Status = 'Completed';
        update setupCDTask;

        //then
        quote = [select Id, SBQQ__Status__c FROM SBQQ__Quote__c LIMIT 1];
        System.assertEquals(SBQQ_QuoteConstants.STATUS_ACCEPTED, quote.SBQQ__Status__c);
        Test.stopTest();
    }
}