src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Case</fullName>
        <active>true</active>
        <businessProcess>Ordinary Case</businessProcess>
        <label>Case</label>
    </recordTypes>
    <recordTypes>
        <fullName>Lease_Transaction</fullName>
        <active>true</active>
        <businessProcess>SLA Process</businessProcess>
        <label>Lease Transaction</label>
    </recordTypes>
    <recordTypes>
        <fullName>Outsourced_Lease_Transaction</fullName>
        <active>true</active>
        <businessProcess>SLA Process</businessProcess>
        <description>Used when an external solicitor is being used for contract negotiations</description>
        <label>Outsourced Lease Transaction</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Inventory__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR (3 AND 4) OR (5 AND 6) OR 7</booleanFilter>
            <errorMessage>Please select the Product that meets the Inventory Record Type</errorMessage>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Actual Suite, Proposed Suite</value>
            </filterItems>
            <filterItems>
                <field>Product2.ProductCode</field>
                <operation>equals</operation>
                <value>OfficeRent, LabSpace, RetailRent, Storage, BSLF, BSDL</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Desk</value>
            </filterItems>
            <filterItems>
                <field>Product2.ProductCode</field>
                <operation>equals</operation>
                <value>BSCW</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Car Parking</value>
            </filterItems>
            <filterItems>
                <field>Product2.ProductCode</field>
                <operation>equals</operation>
                <value>CarSpace</value>
            </filterItems>
            <filterItems>
                <field>Product2.ProductCode</field>
                <operation>equals</operation>
                <value>BSHD, PreEmptionAgreement</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Inventories</relationshipLabel>
        <relationshipName>Suites</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Inventory</label>
    <nameField>
        <label>Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Event_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Event Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Products</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Use__c</fullName>
        <label>Use</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Product__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Banking/Professional/Travel</fullName>
                </value>
                <value>
                    <fullName>Bar</fullName>
                </value>
                <value>
                    <fullName>Betting/Gaming</fullName>
                </value>
                <value>
                    <fullName>Conference</fullName>
                </value>
                <value>
                    <fullName>Exam Space</fullName>
                </value>
                <value>
                    <fullName>Filming</fullName>
                </value>
                <value>
                    <fullName>Full Virtual</fullName>
                </value>
                <value>
                    <fullName>Hair &amp; Beauty</fullName>
                </value>
                <value>
                    <fullName>Health &amp; Fitness</fullName>
                </value>
                <value>
                    <fullName>Hot Food Takeaway</fullName>
                </value>
                <value>
                    <fullName>Hotel</fullName>
                </value>
                <value>
                    <fullName>Interviews</fullName>
                </value>
                <value>
                    <fullName>Mail Only</fullName>
                </value>
                <value>
                    <fullName>Mediation</fullName>
                </value>
                <value>
                    <fullName>Meeting</fullName>
                </value>
                <value>
                    <fullName>Nightclub</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Pop Up Food</fullName>
                </value>
                <value>
                    <fullName>Pop Up Retail</fullName>
                </value>
                <value>
                    <fullName>Restaurant/Cafe</fullName>
                </value>
                <value>
                    <fullName>Retail Shop</fullName>
                </value>
                <value>
                    <fullName>Social</fullName>
                </value>
                <value>
                    <fullName>Supermarket</fullName>
                </value>
                <value>
                    <fullName>Temporary Office Space</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Viewing_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Viewing Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Closed_Lost_Reason__c</fullName>
        <label>Closed Lost Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Too expensive</fullName>
                </value>
                <value>
                    <fullName>Space too big</fullName>
                </value>
                <value>
                    <fullName>Space too small</fullName>
                </value>
                <value>
                    <fullName>Unsuitable location</fullName>
                </value>
                <value>
                    <fullName>Feasibility study</fullName>
                </value>
                <value>
                    <fullName>Went to competitor</fullName>
                </value>
                <value>
                    <fullName>Requirement retracted</fullName>
                </value>
                <value>
                    <fullName>Lack of car parking</fullName>
                </value>
                <value>
                    <fullName>Unsuitable specification</fullName>
                </value>
                <value>
                    <fullName>See Closed Lost Comments</fullName>
                </value>
                <value>
                    <fullName>Inactivity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_Activated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contract Activated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contracts_Exchanged__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contracts Exchanged</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Event_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Event Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>HOTs_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>HOTs Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HOTs_Signed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>HOTs Signed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LA_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>LA Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LA_Signed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>LA Signed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LT_Case_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>LT Case Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity_Record_type_Conversion__c</fullName>
        <description>Hidden field for mapping recordtypes</description>
        <label>Opportunity Record type (Conversion)</label>
        <length>3900</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Products</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_for_conversion__c</fullName>
        <label>Product ( for conversion)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Use__c</fullName>
        <label>Use</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Product__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Banking/Professional/Travel</fullName>
                </value>
                <value>
                    <fullName>Bar</fullName>
                </value>
                <value>
                    <fullName>Betting/Gaming</fullName>
                </value>
                <value>
                    <fullName>Conference</fullName>
                </value>
                <value>
                    <fullName>Exam Space</fullName>
                </value>
                <value>
                    <fullName>Filming</fullName>
                </value>
                <value>
                    <fullName>Full Virtual</fullName>
                </value>
                <value>
                    <fullName>Hair &amp; Beauty</fullName>
                </value>
                <value>
                    <fullName>Health &amp; Fitness</fullName>
                </value>
                <value>
                    <fullName>Hot Food Takeaway</fullName>
                </value>
                <value>
                    <fullName>Hotel</fullName>
                </value>
                <value>
                    <fullName>Interviews</fullName>
                </value>
                <value>
                    <fullName>Mail Only</fullName>
                </value>
                <value>
                    <fullName>Mediation</fullName>
                </value>
                <value>
                    <fullName>Meeting</fullName>
                </value>
                <value>
                    <fullName>Nightclub</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Pop Up Food</fullName>
                </value>
                <value>
                    <fullName>Pop Up Retail</fullName>
                </value>
                <value>
                    <fullName>Restaurant/Cafe</fullName>
                </value>
                <value>
                    <fullName>Retail Shop</fullName>
                </value>
                <value>
                    <fullName>Social</fullName>
                </value>
                <value>
                    <fullName>Supermarket</fullName>
                </value>
                <value>
                    <fullName>Temporary Office Space</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Use_for_conversion__c</fullName>
        <label>Use ( for conversion)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Viewing_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Viewing Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>SBQQ__Opportunity2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity associated with this Quote.</description>
        <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Status__c</fullName>
        <description>Status indicating where quote is in its lifecycle.</description>
        <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Presented</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Pending Approval - Offline Edit</fullName>
                </value>
                <value>
                    <fullName>Awaiting Approval - Offline Edit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OpportunityTriggerHandler.cls
public with sharing class OpportunityTriggerHandler extends TriggerHandler {

    protected override void beforeInsert() {
        assignRT((List<Opportunity>) Trigger.new);
        mapLeadFields((List<Opportunity>) Trigger.new);
        assignPriceBookOnOpportunity((List<Opportunity>) Trigger.new);
        createTaskForCoordinator(Trigger.new, null);
    }

    protected override void beforeUpdate() {
        assignPriceBookOnOpportunity((List<Opportunity>) Trigger.new);
        changeStatusOnQuote((List<Opportunity>) Trigger.new, (Map<Id, Opportunity>) Trigger.oldMap);
        recalculateOpportunityStatusIfNeeded(Trigger.new, (Map<Id, Opportunity>) Trigger.oldMap);
        createTaskForCoordinator(Trigger.new, Trigger.oldMap);
    }

    protected override void afterUpdate() {
        pushCompletionNotification((List<Opportunity>) Trigger.new, (Map<Id, Opportunity>) Trigger.oldMap);
    }

    private void assignRT(List<Opportunity> opportunities) {
        for (Opportunity opportunity : opportunities) {
            RecordTypeInfo oppRecordTypeInfo = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get(opportunity.Opportunity_Record_type_Conversion__c);
            if (oppRecordTypeInfo != null) {
                opportunity.RecordTypeId = oppRecordTypeInfo.getRecordTypeId();
            }
        }
    }

    private void mapLeadFields(List<Opportunity> opportunities) {
        for (Opportunity opportunity : opportunities) {
            opportunity.Use__c = opportunity.Use__c == null ? opportunity.Use_for_conversion__c : opportunity.Use__c;
            opportunity.Product__c = opportunity.Product__c == null ? opportunity.Product_for_conversion__c : opportunity.Product__c;
        }
    }

    private void createTaskForCoordinator(List<sObject> opportunities, Map<Id, sObject> oldOpportunitiesMap) {
        List<sObject> virtualOpportunoities = SObjectUtils.filterRecordsByRecordType(opportunities, new Set<Id>{
                OpportunityService.VIRTUAL_RECORD_TYPE_ID
        });
        List<sObject> modifiedVirtuals = SObjectUtils.getModifiedObjects(new List<String>{
                'StageName'
        }, virtualOpportunoities, oldOpportunitiesMap);
        if (!modifiedVirtuals.isEmpty()) {
            OpportunityService.createTaskForCoordinator(modifiedVirtuals);
        }
    }

    private void assignPriceBookOnOpportunity(List<Opportunity> opportunities) {
        Map<String, Pricebook2> pricebooks = getPriceBooks();

        for (Opportunity opp : opportunities) {
            Pricebook2 pricebook = pricebooks.get(
                OpportunityService.getRecrodTypes().get(opp.RecordTypeId).DeveloperName
            );
            if (pricebook != null) {
                opp.Pricebook2Id = pricebook.Id;
            }
        }
    }

    private void changeStatusOnQuote(List<Opportunity> newOpportunities, Map<Id, Opportunity> oldOpportunities) {
        Map<Id, Opportunity> oppMap = new Map<Id, Opportunity>();
        Set<Id> quoteIds = new Set<Id>();
        List<Case> cases = new List<Case>();
        List<SBQQ__Quote__c> quotesUpdate = new List<SBQQ__Quote__c>();

        for (Opportunity opp : newOpportunities) {
            if (opp.StageName != oldOpportunities.get(opp.Id).StageName && opp.StageName == Constants.STAGENAME_CLOSED_LOST //TODO: move Stages to one place
                    && opp.Closed_Lost_Reason__c != null) {
                oppMap.put(opp.Id, opp);
            }
        }
        //Define all Quotes related with Opportunity
        List<SBQQ__Quote__c> quotes = [
                SELECT Id, SBQQ__Opportunity2__c, SBQQ__Status__c
                FROM SBQQ__Quote__c
                WHERE SBQQ__Opportunity2__c IN :oppMap.keySet()
        ];
        if (!quotes.isEmpty()) {
            for (SBQQ__Quote__c quote : quotes) {
                quoteIds.add(quote.id);
            }
        }
        //Define all Cases related with Quotes
        if (!quoteIds.isEmpty()) {
            cases = [
                    SELECT Id, Status, RecordType.DeveloperName, Quote__c
                    FROM Case
                    WHERE Quote__c IN :quoteIds
                    AND Status != :Constants.STATUS_CLOSED_LOST
                    AND RecordType.DeveloperName IN ('Lease_Transaction', 'Outsourced_Lease_Transaction')
            ];
            //On Quotes, change Status to Obsolete if all related Cases are 'Closed Lost'
            if (!cases.isEmpty()) {
                for (Opportunity opp : oppMap.values()) {
                    opp.addError('Close Lease Transaction Case first!');
                }
            } else {
                for (SBQQ__Quote__c quote : quotes) {
                    quote.SBQQ__Status__c = Constants.STATUS_OBSOLETE;
                    quotesUpdate.add(quote);
                }
            }
            if (!quotesUpdate.isEmpty()) {
                update quotesUpdate;
            }
        }
    }

    private Map<String, Pricebook2> getPriceBooks() {
        List<Pricebook2> priceBooks = [
                SELECT Id, RecordType.DeveloperName
                FROM Pricebook2
                WHERE RecordType.Id != null AND IsActive = TRUE
        ];
        Map<String, Pricebook2> priceBooksMap = new Map<String, Pricebook2>();
        for (Pricebook2 pricebook : priceBooks) {
            priceBooksMap.put(pricebook.RecordType.DeveloperName, pricebook);
        }
        return priceBooksMap;
    }

    private void recalculateOpportunityStatusIfNeeded(List<Opportunity> newOpportunities, Map<Id, Opportunity> oldMap) {
        Set<String> fieldsUsedInOppStatusCalculation = new Set<String>{
                'Viewing_Count__c', 'Event_Count__c', 'HOTs_Sent__c', 'HOTs_Signed__c', 'LA_Sent__c', 'LA_Signed__c', 'LT_Case_Completed__c',
                'Contracts_Exchanged__c', 'Contract_Activated__c', 'Compliance_Check_Complete__c', 'Virtual_Compliance_Approval_Complete__c',
                'Briefing_Statement__c', 'Deposit_Paid__c', 'Closed_Lost_Reason__c', 'Closed_Lost_Comments__c', 'Force_Status_Recalculation__c'
        };
        List<Opportunity> oppsForStatusCalculation = new List<Opportunity>();
        for (Opportunity theOpportunity : newOpportunities) {
            Opportunity oldOpportunity = oldMap.get(theOpportunity.Id);
            for (String fieldName : fieldsUsedInOppStatusCalculation) {
                if (theOpportunity.get(fieldName) != oldOpportunity.get(fieldName)) {
                    oppsForStatusCalculation.add(theOpportunity);
                }
            }
            theOpportunity.Force_Status_Recalculation__c = false;
        }
        OpportunityService.calculateOpportunitiesStatuses(oppsForStatusCalculation);
    }

    private void pushCompletionNotification(List<Opportunity> newOpportunities, Map<Id, Opportunity> oldOpportunitiesMap) {
        List<Opportunity> oppWithCompletionStatus = new List<Opportunity>();

        for (Opportunity theOpportunity : newOpportunities) {
            Opportunity oldOpportunity = oldOpportunitiesMap.get(theOpportunity.Id);
            if (oldOpportunity.StageName != theOpportunity.StageName
                    && (theOpportunity.StageName == OpportunityService.STATUS_COMPLETED //TODO: move Stages to one place
                    || theOpportunity.StageName == OpportunityService.STATUS_EXCHANGED
                    || theOpportunity.StageName == OpportunityService.STATUS_INSTRUCTED)
                    ) {
                oppWithCompletionStatus.add(theOpportunity);
            }
        }
        if (oppWithCompletionStatus.size() > 0) {
            pushChatterPostForCompletedOpportunity([SELECT Id, Account.Name, StageName, Completion_Notification__c, Owner.Name,
                    Type, LeadSource
                FROM Opportunity WHERE ID IN :oppWithCompletionStatus]);
        }

    }

    private void pushChatterPostForCompletedOpportunity(List<Opportunity> completedOpportunities) {
        List<String> feedItemsBodies = new List<String>();
        Map<String, SBQQ__Quote__c> primaryQuotesByOpportunities = OpportunityService.getPrimaryQuotesByOpportunities(completedOpportunities);

        for (Opportunity theOpportunity : completedOpportunities) {
            String opportunityUrl = URL.getSalesforceBaseUrl().toExternalForm() + '/' + theOpportunity.Id;
            String quoteUrl = '';
            if (primaryQuotesByOpportunities.containsKey(theOpportunity.Id)) {
                quoteUrl = URL.getSalesforceBaseUrl().toExternalForm() + '/' + primaryQuotesByOpportunities.get(theOpportunity.Id).Id ;
            }
            feedItemsBodies.add('<p> A deal has hit a milestone. ' +
                    +theOpportunity.Account.Name + '. The status it has moved to ' + theOpportunity.StageName + '.</p> <p> Opportunity: ' +
                    + opportunityUrl + '</p> <p> Quote: ' + quoteUrl + '</p>' +
                    +'<p> Property: ' + (primaryQuotesByOpportunities.get(theOpportunity.Id).Property_Name__c != null ?
                        primaryQuotesByOpportunities.get(theOpportunity.Id).Property_Name__c : '') + '</p>' +
                    +'<p> Inventory: ' + (primaryQuotesByOpportunities.get(theOpportunity.Id).Inventory__r.Name != null ?
                        primaryQuotesByOpportunities.get(theOpportunity.Id).Inventory__r.Name : '') + '</p>' +
                    +'<p> Opportunity Owner: ' + theOpportunity.Owner.Name + '</p>' +
                    +'<p> Lead Source: ' + theOpportunity.LeadSource + '</p>' +
                    +'<p> Net Fill: ' + (primaryQuotesByOpportunities.get(theOpportunity.Id).Net_Fill_Sq_ft__c != null ?
                        primaryQuotesByOpportunities.get(theOpportunity.Id).Net_Fill_Sq_ft__c : 0) + '</p>' +
                    +'<p> Total Deal Size: ' + (primaryQuotesByOpportunities.get(theOpportunity.Id).Total_deal_size_Sq_ft__c != null ?
                                primaryQuotesByOpportunities.get(theOpportunity.Id).Total_deal_size_Sq_ft__c : 0) + '</p>' +
                    +'<p> Deal Type: ' + (theOpportunity.Type != NULL ? theOpportunity.Type : '') + '</p>' +
                    +'<p> Term: ' + (primaryQuotesByOpportunities.get(theOpportunity.Id).Term__c != null ?
                        primaryQuotesByOpportunities.get(theOpportunity.Id).Term__c : 0)+ '</p>'
                    +'<p> Term Certain: ' + (primaryQuotesByOpportunities.get(theOpportunity.Id).Term_certain__c != null ?
                        primaryQuotesByOpportunities.get(theOpportunity.Id).Term_certain__c : 0)+ '</p>' +
                    +'<p> Rent per sq ft: ' + (primaryQuotesByOpportunities.get(theOpportunity.Id).Rent_per_Sq_Ft_annual__c != null ?
                        primaryQuotesByOpportunities.get(theOpportunity.Id).Rent_per_Sq_Ft_annual__c : 0) + '</p>' +
                    +'<p> Discount Term Certain: ' + (primaryQuotesByOpportunities.get(theOpportunity.Id).Discount_Term_Certain__c != null ?
                        primaryQuotesByOpportunities.get(theOpportunity.Id).Discount_Term_Certain__c : 0)+ '</p>' +
                    +'<p> Total parking spaces: ' + (primaryQuotesByOpportunities.get(theOpportunity.Id).Total_Parking_Spaces__c != null ?
                        primaryQuotesByOpportunities.get(theOpportunity.Id).Total_Parking_Spaces__c : 0)+ '</p>' +
                    +'<p> Completion Notification: ' + (theOpportunity.Completion_Notification__c != NULL ? theOpportunity.Completion_Notification__c : '') + '</p>'
                );

        }

        ChatterService.pushFeedItems(feedItemsBodies, ChatterService.findChatterGroupByName(Constants.OPPORTUNITY_NOTIFICATION_GROUP_NAME));
    }
}