src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Customer_Budget__c</fullName>
        <inlineHelpText>Budget for these works or an idea what is affordable?</inlineHelpText>
        <label>Customer Budget</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 4) OR (1 AND 2 AND 3)</booleanFilter>
            <filterItems>
                <field>Inventory__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Actual Suite, Proposed Suite</value>
            </filterItems>
            <filterItems>
                <field>Inventory__c.Property__c</field>
                <operation>equals</operation>
                <valueField>$Source.Property__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Project Works Request Case</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Project Works Request Case</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Inventory__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Case</fullName>
        <active>true</active>
        <businessProcess>Ordinary Case</businessProcess>
        <label>Case</label>
    </recordTypes>
    <recordTypes>
        <fullName>Fit_Out_Design</fullName>
        <active>true</active>
        <businessProcess>Fit Out Design Case</businessProcess>
        <label>Fit Out Design</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Inventory__c.object
<CustomObject>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipName>Suites</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sales_Status__c</fullName>
        <label>Sales Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                </value>
                <value>
                    <fullName>Terms Out</fullName>
                </value>
                <value>
                    <fullName>Reserved</fullName>
                </value>
                <value>
                    <fullName>Not Available</fullName>
                </value>
                <value>
                    <fullName>Not for Sale</fullName>
                </value>
                <value>
                    <fullName>Instructed</fullName>
                    <isActive>false</isActive>
                    <label>Instructed</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Inventory</label>
    <nameField>
        <label>Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory</label>
        <referenceTo>Inventory__c</referenceTo>
        <relationshipName>Inventory</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
        <inlineHelpText>The customer account for this quote. Defaults to the account for the opportunity when creating a quote.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__RelatedContent__c.object
<CustomObject>
    <description>Links certain marketing content (datasheets, specifications, case study) to a product or a template.</description>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote related to this content.</description>
        <inlineHelpText>Quote related to this content.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipName>RelatedContent</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Additional Document</label>
    <nameField>
        <label>Additional Document</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Additional Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ContentDocumentLinkHandlerTest.cls
@isTest
public class ContentDocumentLinkHandlerTest {

    @testSetup
    public static void initData() {
        Property__c property = new Property__c(Street__c = 'Test');
        insert property;

        Inventory__c inventory = new Inventory__c(Name = 'Test', Property__c = property.Id, Sales_Status__c = 'Available');
        insert inventory;

        SBQQ__Quote__c quote = RecordDmlTest.createCPQQuote();

        Case entityCase = new Case(
                RecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Fit_Out_Design' AND SobjectType = 'Case'].get(0).Id,
                Inventory__c = inventory.Id,
                Quote__c = quote.Id,
                AccountId = quote.SBQQ__Account__c,
                Customer_Budget__c = 1000);
        insert entityCase;

        ContentVersion contentVersion = new ContentVersion(
                Title = 'Test document',
                PathOnClient = 'Test.pdf',
                VersionData = Blob.valueOf('Test Content'),
                IsMajorVersion = true);
        insert contentVersion;

        ContentDocumentLink contentlink = new ContentDocumentLink(
                LinkedEntityId = entityCase.Id,
                ShareType = 'V',
                ContentDocumentId = [SELECT ContentDocumentId FROM ContentVersion LIMIT 1].get(0).ContentDocumentId);
        insert contentlink;

        ContentDocument contentDocument = [SELECT FileExtension FROM ContentDocument LIMIT 1];
    }

    @isTest
    public static void checkForQuoteDocumentExistence() {
        Case entityCase = [SELECT Id, Quote__c FROM Case LIMIT 1];
        System.assertEquals(1, [SELECT COUNT() FROM SBQQ__RelatedContent__c WHERE SBQQ__Quote__c = :entityCase.Quote__c], 'Additional document of the quote is not created');
    }

    @isTest
    public static void checkForInventoryDocumentExistence() {
        Inventory__c inventory = [SELECT Id FROM Inventory__c LIMIT 1];
        System.assertEquals(1, [SELECT COUNT() FROM ContentDocumentLink Where LinkedEntityId = :inventory.Id], 'Inventory document is not created');
    }

    @isTest
    public static void checkForAccountDocumentExistence() {
        Case entityCase = [SELECT Id, AccountId FROM Case LIMIT 1];
        System.assertEquals(1, [SELECT COUNT() FROM ContentDocumentLink Where LinkedEntityId = :entityCase.AccountId], 'Account document is not created');
    }
}