src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Case</fullName>
        <active>true</active>
        <businessProcess>Ordinary Case</businessProcess>
        <label>Case</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Preference__c</fullName>
        <label>Contact Preference</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Mobile</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <inlineHelpText>Hold the &apos;ctrl&apos; key to select multiple types.</inlineHelpText>
        <label>Contact Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Billing Contact</fullName>
                </value>
                <value>
                    <fullName>In Life Property Contact</fullName>
                </value>
                <value>
                    <fullName>Sales Contact</fullName>
                </value>
                <value>
                    <fullName>Out of Hours Contact</fullName>
                </value>
                <value>
                    <fullName>Legal Contact</fullName>
                </value>
                <value>
                    <fullName>Project Management Contact</fullName>
                </value>
                <value>
                    <fullName>Director Contact</fullName>
                </value>
                <value>
                    <fullName>Remittance - Finance</fullName>
                </value>
                <value>
                    <fullName>Statement - Finance</fullName>
                </value>
                <value>
                    <fullName>Purchase Ledger - Finance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>External</fullName>
        <active>true</active>
        <label>External</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Potential_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Potential Contacts</relationshipLabel>
        <relationshipName>Potential_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Preference__c</fullName>
        <label>Contact Preference</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <label>Contact Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Billing Contact</fullName>
                </value>
                <value>
                    <fullName>In Life Property Contact</fullName>
                </value>
                <value>
                    <fullName>Sales Contact</fullName>
                </value>
                <value>
                    <fullName>Out of Hours Contact</fullName>
                </value>
                <value>
                    <fullName>Legal Contact</fullName>
                </value>
                <value>
                    <fullName>Project Management Contact</fullName>
                </value>
                <value>
                    <fullName>Director Contact</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <label>Mobile</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Contact_Preference__c</fullName>
        <label>Contact Preference</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Contact_Type__c</fullName>
        <label>Contact Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Billing Contact</fullName>
                </value>
                <value>
                    <fullName>In Life Property Contact</fullName>
                </value>
                <value>
                    <fullName>Out of Hours Contact</fullName>
                </value>
                <value>
                    <fullName>Legal Contact</fullName>
                </value>
                <value>
                    <fullName>Project Management Contact</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>New_Email__c</fullName>
        <label>Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Mobile__c</fullName>
        <label>Mobile</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Phone__c</fullName>
        <label>Phone</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ_Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Potential Contacts</relationshipLabel>
        <relationshipName>Potential_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Potential Contact</label>
    <nameField>
        <displayFormat>PC-{000000000}</displayFormat>
        <label>Potential Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Potential Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ConvertPotentialContactController.cls
/**
 * @description Controller class for ConvertPotentialContact lightning component
 */
public with sharing class ConvertPotentialContactController {

    @AuraEnabled
    public static Id upsertPotentialContact(Id potentialContactId) {
        if ( String.isBlank(potentialContactId) ) {
            return null;
        }
        Potential_Contact__c potentialContact = [SELECT Account__c, First_Name__c, Last_Name__c, Email__c, Phone__c, Mobile__c, Contact_Preference__c, Contact_Type__c,
                                                        New_First_Name__c, New_Last_Name__c, New_Email__c, New_Phone__c, New_Mobile__c, New_Contact_Preference__c, New_Contact_Type__c,
                                                        SBQQ_Quote__c, SBQQ_Quote__r.Property__c
                                                 FROM Potential_Contact__c
                                                 WHERE Id = :potentialContactId];
        System.debug('potentialContact: ' + potentialContact);
        String firstName = String.isNotBlank(potentialContact.First_Name__c) ? String.escapeSingleQuotes(potentialContact.First_Name__c) : '';
        String lastName = String.isNotBlank(potentialContact.Last_Name__c) ? String.escapeSingleQuotes(potentialContact.New_First_Name__c) : '';
        String query = 'SELECT Contact_Type__c ' +
                       'FROM Contact ' +
                       'WHERE AccountId = \'' + potentialContact.Account__c + '\' AND ' +
                       '((FirstName = \'' + firstName + '\' AND LastName = \'' + lastName + '\' AND Email = \'' + potentialContact.Email__c + '\'';
        if ( String.isNotBlank(potentialContact.Phone__c) ) {
            query += ' AND Phone = \'' + potentialContact.Phone__c + '\'';
        }
        if ( String.isNotBlank(potentialContact.Mobile__c) ) {
            query += ' AND MobilePhone = \'' + potentialContact.Mobile__c + '\'';
        }
        query += ') OR (FirstName = \'' + String.escapeSingleQuotes(potentialContact.New_First_Name__c) + '\' AND LastName = \'' + String.escapeSingleQuotes(potentialContact.New_Last_Name__c) + '\' AND Email = \'' + potentialContact.New_Email__c + '\'';
        if ( String.isNotBlank(potentialContact.New_Phone__c) ) {
            query += ' AND Phone = \'' + potentialContact.New_Phone__c + '\'';
        }
        if ( String.isNotBlank(potentialContact.New_Mobile__c) ) {
            query += ' AND MobilePhone = \'' + potentialContact.New_Mobile__c + '\'';
        }
        query += '))';
        List<Contact> contacts = (List<Contact>)Database.query(query);
        Id externalContactRecordTypeId = [SELECT Id FROM RecordType WHERE SobjectType = 'Contact' AND DeveloperName = 'External'].Id;
        Contact contactToUpsert;
        if ( contacts.isEmpty() ) {
            contactToUpsert = new Contact();
        } else {
            contactToUpsert = contacts[0];
        }
        contactToUpsert.AccountId = potentialContact.Account__c;
        contactToUpsert.FirstName = potentialContact.New_First_Name__c;
        contactToUpsert.LastName = potentialContact.New_Last_Name__c;
        contactToUpsert.Email = potentialContact.New_Email__c;
        contactToUpsert.Phone = potentialContact.New_Phone__c;
        contactToUpsert.MobilePhone = potentialContact.New_Mobile__c;
        contactToUpsert.Contact_Preference__c = potentialContact.New_Contact_Preference__c;
        String contactType = String.isBlank(contactToUpsert.Contact_Type__c) ? potentialContact.Contact_Type__c : contactToUpsert.Contact_Type__c;
        contactType = !contactType.containsIgnoreCase(potentialContact.Contact_Type__c) ? contactType + ';' + potentialContact.Contact_Type__c : contactType;
        contactToUpsert.Contact_Type__c = contactType;
        contactToUpsert.RecordTypeId = externalContactRecordTypeId;
        contactToUpsert.Property__c = potentialContact.SBQQ_Quote__r.Property__c;

        Database.UpsertResult result = Database.upsert(contactToUpsert, false);
        if ( !result.isSuccess() ) {
            for ( Database.Error error : result.getErrors() ) {
                if ( error instanceof Database.DuplicateError ) {
                    DataCloud.DuplicateResult dupResult = ((Database.DuplicateError)error).getDuplicateResult();
                    Contact duplicateContact = (Contact)dupResult.getMatchResults()[0].getMatchRecords()[0].getRecord();
                    String duplicateContactLink = '<a href="/' + duplicateContact.Id + '">' + duplicateContact.Name + '</a>';
                    throw new AuraHandledException(duplicateContactLink);
                }
            }
        }

        List<Task> reviewPCTasks = [SELECT Id FROM Task WHERE WhatId = :potentialContactId AND System_Code__c = :TaskService.REVIEW_POTENTIAL_CONTACT_SYSTEM_CODE];
        if ( !reviewPCTasks.isEmpty() ) {
            reviewPCTasks[0].Status = 'Completed';
            update reviewPCTasks[0];
        }

        assignContactToCases(contactToUpsert, potentialContact.SBQQ_Quote__c);

        return contactToUpsert.Id;
    }

    private static void assignContactToCases(Contact contact, Id quoteId) {
        String typeParam = String.isNotBlank(contact.Contact_Type__c) ? contact.Contact_Type__c.toUpperCase(): '';
        Map<String, Set<Id>> recordTypesMap = getRecordTypesToFilter();

        if (recordTypesMap.containsKey(typeParam)) {
            Set<Id> caseRTypesToFilter = recordTypesMap.get(typeParam);
            List<Case> cases = [SELECT Id FROM Case WHERE Quote__c = :quoteId AND RecordTypeId  IN: caseRTypesToFilter];
            for ( Case theCase : cases ) {
                theCase.ContactId = contact.Id;
            }
            update cases;
        }
    }

    private static Map<String, Set<Id>> getRecordTypesToFilter() {
        Map<String, Set<Id>> recordTypesMap = new Map<String, Set<Id>>();

        recordTypesMap.put(
            SBQQ_QuoteConstants.CONTACT_TYPE_LC.toUpperCase(),
            new Set<Id> { RecordTypeHelper.getCaseRtIdByDeveloperName(CaseService.LEASE_TRANSACTION_RECORD_TYPE) }
        );

        recordTypesMap.put(
            SBQQ_QuoteConstants.CONTACT_TYPE_ILPC.toUpperCase(),
            new Set<Id> {
                RecordTypeHelper.getCaseRtIdByDeveloperName(CaseService.CONVENTIONAL_ONBOARDING_RECORD_TYPE),
                RecordTypeHelper.getCaseRtIdByDeveloperName(CaseService.SERVICED_SPACE_ONBOARDING_RECORD_TYPE)
            }
        );

        recordTypesMap.put(
            SBQQ_QuoteConstants.CONTACT_TYPE_PMC.toUpperCase(),
            new Set<Id> {
                RecordTypeHelper.getCaseRtIdByDeveloperName(CaseService.DESIGN_RECORD_TYPE),
                RecordTypeHelper.getCaseRtIdByDeveloperName(CaseService.FIT_OUT_DESIGN_RECORD_TYPE),
                RecordTypeHelper.getCaseRtIdByDeveloperName(CaseService.BUILDING_CONSTRUCTION_CASE_RECORD_TYPE)
            }
        );

        return recordTypesMap;
    }
}