src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Briefing_Statement__c</fullName>
        <label>Briefing Statement</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Customer_Budget__c</fullName>
        <inlineHelpText>Budget for these works or an idea what is affordable?</inlineHelpText>
        <label>Customer Budget</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Case</fullName>
        <active>true</active>
        <businessProcess>Ordinary Case</businessProcess>
        <label>Case</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <inlineHelpText>Hold the &apos;ctrl&apos; key to select multiple types.</inlineHelpText>
        <label>Contact Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Billing Contact</fullName>
                </value>
                <value>
                    <fullName>In Life Property Contact</fullName>
                </value>
                <value>
                    <fullName>Sales Contact</fullName>
                </value>
                <value>
                    <fullName>Out of Hours Contact</fullName>
                </value>
                <value>
                    <fullName>Legal Contact</fullName>
                </value>
                <value>
                    <fullName>Project Management Contact</fullName>
                </value>
                <value>
                    <fullName>Director Contact</fullName>
                </value>
                <value>
                    <fullName>Remittance - Finance</fullName>
                </value>
                <value>
                    <fullName>Statement - Finance</fullName>
                </value>
                <value>
                    <fullName>Purchase Ledger - Finance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Briefing_Statement__c</fullName>
        <description>Additional information to the property management team.</description>
        <inlineHelpText>Additional information to the property management team.</inlineHelpText>
        <label>Briefing Statement</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Property_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Properties</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Opportunity2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity associated with this Quote.</description>
        <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Status__c</fullName>
        <description>Status indicating where quote is in its lifecycle.</description>
        <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Presented</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Pending Approval - Offline Edit</fullName>
                </value>
                <value>
                    <fullName>Awaiting Approval - Offline Edit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DesignCasesUpdaterTest.cls
@IsTest
private class DesignCasesUpdaterTest {
    @IsTest
    static void givenDesignCaseWhenLeaseTransactionCaseCreatedThenDesignCaseChanged() {
        SBQQ__Quote__c quote = RecordDmlTest.generateConventionalQuoteWithServiceChargeCapLines();

        User propertyManager = RecordDmlTest.createUser();

        Property__c property = [SELECT Id, Property_Manager__c FROM Property__c WHERE Id = :quote.Property__c];
        property.Property_Manager__c = propertyManager.Id;
        upsert property;

        Opportunity opportunity = [SELECT AccountId FROM Opportunity WHERE Id = :quote.SBQQ__Opportunity2__c];
        opportunity.Briefing_Statement__c = 'test statement';
        update opportunity;

        Contact contact = new Contact(AccountId = opportunity.AccountId, Contact_Type__c = 'In Life Property Contact', LastName = 'Test Contact');
        insert contact;

        //given
        Case designCase = new Case(RecordTypeId = RecordTypeHelper.getCaseRtIdByDeveloperName(CaseService.FIT_OUT_DESIGN_RECORD_TYPE), Quote__c = quote.Id, Customer_Budget__c = 1000);
        insert designCase;

        Test.startTest();
        //when
        quote.SBQQ__Status__c = 'Accepted';
        update quote;
        Test.stopTest();

        designCase = [SELECT OwnerId, RecordTypeId, Status FROM Case WHERE Id = :designCase.Id];

        //then
        System.assertEquals(designCase.OwnerId, QueueHelper.getRtIdByDeveloperName(QueueHelper.B_C_QUEUE));
        System.assertEquals(designCase.RecordTypeId, RecordTypeHelper.getCaseRtIdByDeveloperName(CaseService.BUILDING_CONSTRUCTION_CASE_RECORD_TYPE));
        System.assertEquals(designCase.Status, 'Customer Confirmed');
    }
}