src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 4) OR (1 AND 2 AND 3)</booleanFilter>
            <filterItems>
                <field>Inventory__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Actual Suite, Proposed Suite</value>
            </filterItems>
            <filterItems>
                <field>Inventory__c.Property__c</field>
                <operation>equals</operation>
                <valueField>$Source.Property__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Project Works Request Case</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Project Works Request Case</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Inventory__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Case</fullName>
        <active>true</active>
        <businessProcess>Ordinary Case</businessProcess>
        <label>Case</label>
    </recordTypes>
    <recordTypes>
        <fullName>Fit_Out_Design</fullName>
        <active>true</active>
        <businessProcess>Fit Out Design Case</businessProcess>
        <label>Fit Out Design</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Inventory__c.object
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <label>Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory</label>
        <referenceTo>Inventory__c</referenceTo>
        <relationshipName>Inventory</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__RelatedContent__c.object
<CustomObject>
    <description>Links certain marketing content (datasheets, specifications, case study) to a product or a template.</description>
    <fields>
        <fullName>SBQQ__ExternalId__c</fullName>
        <description>ID of the record that contains the actual content. Eg: Document or Salesforce Content.</description>
        <inlineHelpText>Record ID that contains the content, such as document or Salesforce content.</inlineHelpText>
        <label>External Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote related to this content.</description>
        <inlineHelpText>Quote related to this content.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipName>RelatedContent</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Additional Document</label>
    <nameField>
        <label>Additional Document</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Additional Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ContentDocumentLinkHandler.cls
public class ContentDocumentLinkHandler extends TriggerHandler {

    //Salesforce CPQ supports only PDF format for Additional Documents
    private static final Set<String> sharedFileExtensions = new Set<String>{
            'pdf'
    };

    public override void afterInsert() {
        associateCaseDocumentsWithRelatedObjects((List<ContentDocumentLink>) Trigger.new);
    }

    private void associateCaseDocumentsWithRelatedObjects(List<ContentDocumentLink> documents) {
        //Associate case documents with related quote
        associateDocumentsWithQuote(documents);
        //Associate case documents with related inventory
        associateDocumentsWithInventory(documents);
        //Associate case documents with related account
        associateDocumentsWithAccount(documents);
    }

    private void associateDocumentsWithQuote(List<ContentDocumentLink> documents) {
        List<SBQQ__RelatedContent__c> quoteDocuments = new List<SBQQ__RelatedContent__c>();
        for (ContentDocumentLink cdl : documents) {
            if (isCase(cdl.LinkedEntityId)) {
                Case entityCase = [SELECT Id, Quote__c, RecordTypeId FROM Case WHERE Id = :cdl.LinkedEntityId];
                ContentDocument document = [SELECT Id, FileExtension, Title FROM ContentDocument WHERE Id = :cdl.ContentDocumentId];
                if (isFitOutDesignCase(entityCase) && String.isNotBlank(entityCase.Quote__c) && sharedFileExtensions.contains(document.FileExtension)) {
                    quoteDocuments.add(new SBQQ__RelatedContent__c(
                            SBQQ__ExternalId__c = document.Id, 
                            SBQQ__Quote__c = entityCase.Quote__c, 
                            Name = document.Title)
                    );
                }
            }
        }
        if (!quoteDocuments.isEmpty()) {
            insert quoteDocuments;
        }
    }

    private void associateDocumentsWithInventory(List<ContentDocumentLink> documents) {
        List<ContentDocumentLink> inventoryDocuments = new List<ContentDocumentLink>();
        for (ContentDocumentLink cdl : documents) {
            if (isCase(cdl.LinkedEntityId)) {
                Case entityCase = [SELECT Id, Quote__c, RecordTypeId, Inventory__c FROM Case WHERE Id = :cdl.LinkedEntityId];
                if (isFitOutDesignCase(entityCase) && String.isNotBlank(entityCase.Inventory__c)) {
                    inventoryDocuments.add(new ContentDocumentLink(ContentDocumentId = cdl.ContentDocumentId, LinkedEntityId = entityCase.Inventory__c, ShareType = 'V'));
                }
            }
        }
        if (!inventoryDocuments.isEmpty()) {
            insert inventoryDocuments;
        }
    }

    private void associateDocumentsWithAccount(List<ContentDocumentLink> documents) {
        List<ContentDocumentLink> accountDocuments = new List<ContentDocumentLink>();
        for (ContentDocumentLink cdl : documents) {
            if (isCase(cdl.LinkedEntityId)) {
                Case entityCase = [SELECT Id, AccountId, RecordTypeId FROM Case WHERE Id = :cdl.LinkedEntityId];
                if (isFitOutDesignCase(entityCase) && String.isNotBlank(entityCase.AccountId)) {
                    accountDocuments.add(new ContentDocumentLink(ContentDocumentId = cdl.ContentDocumentId, LinkedEntityId = entityCase.AccountId, ShareType = 'V'));
                }
            }
        }
        if (!accountDocuments.isEmpty()) {
            insert accountDocuments;
        }
    }

    private Boolean isFitOutDesignCase(Case entityCase) {
        RecordType recordType = [SELECT Id, DeveloperName FROM RecordType WHERE Id = :entityCase.RecordTypeId];
        return recordType.DeveloperName == 'Fit_Out_Design';
    }

    private Boolean isCase(Id entityId) {
        return String.isNotBlank(entityId) && String.valueOf(entityId).startsWith('500');
    }
}