src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Briefing_Statement__c</fullName>
        <label>Briefing Statement</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Commencement_Date__c</fullName>
        <label>Commencement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 4) OR (1 AND 2 AND 3)</booleanFilter>
            <filterItems>
                <field>Inventory__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Actual Suite, Proposed Suite</value>
            </filterItems>
            <filterItems>
                <field>Inventory__c.Property__c</field>
                <operation>equals</operation>
                <valueField>$Source.Property__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Project Works Request Case</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Project Works Request Case</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Inventory__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legacy_contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Legacy contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Cases (Legacy contract)</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Off_line_Edits__c</fullName>
        <description>Specifies which offline changes are made under quote documents</description>
        <inlineHelpText>Specifies which offline changes are made under quote documents</inlineHelpText>
        <label>Off-line Edits</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pre_Emption_Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pre-Emption Inventory</label>
        <referenceTo>Inventory__c</referenceTo>
        <relationshipLabel>Cases (Pre-Emption Inventory)</relationshipLabel>
        <relationshipName>Cases8</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Cases (Sales Contact)</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Building_Construction_Case</fullName>
        <active>true</active>
        <businessProcess>Building %26 Construction Case</businessProcess>
        <label>Building &amp; Construction Case</label>
    </recordTypes>
    <recordTypes>
        <fullName>Case</fullName>
        <active>true</active>
        <businessProcess>Ordinary Case</businessProcess>
        <label>Case</label>
    </recordTypes>
    <recordTypes>
        <fullName>Contract_Surrender_Conventional</fullName>
        <active>true</active>
        <businessProcess>Ordinary Case</businessProcess>
        <label>Contract Surrender Conventional</label>
    </recordTypes>
    <recordTypes>
        <fullName>Contract_Surrender_Serviced</fullName>
        <active>true</active>
        <businessProcess>Ordinary Case</businessProcess>
        <label>Contract Surrender Serviced</label>
    </recordTypes>
    <recordTypes>
        <fullName>Conventional_Onboarding</fullName>
        <active>true</active>
        <businessProcess>Ordinary Case</businessProcess>
        <label>Conventional Onboarding</label>
    </recordTypes>
    <recordTypes>
        <fullName>Design</fullName>
        <active>true</active>
        <businessProcess>Design Case</businessProcess>
        <label>Design</label>
    </recordTypes>
    <recordTypes>
        <fullName>Fit_Out_Design</fullName>
        <active>true</active>
        <businessProcess>Fit Out Design Case</businessProcess>
        <label>Fit Out Design</label>
    </recordTypes>
    <recordTypes>
        <fullName>Lease_Transaction</fullName>
        <active>true</active>
        <businessProcess>SLA Process</businessProcess>
        <label>Lease Transaction</label>
    </recordTypes>
    <recordTypes>
        <fullName>Outsourced_Lease_Transaction</fullName>
        <active>true</active>
        <businessProcess>SLA Process</businessProcess>
        <description>Used when an external solicitor is being used for contract negotiations</description>
        <label>Outsourced Lease Transaction</label>
    </recordTypes>
    <recordTypes>
        <fullName>Quote_Case</fullName>
        <active>true</active>
        <businessProcess>Inventory was removed from a Quote</businessProcess>
        <label>Quote Case</label>
    </recordTypes>
    <recordTypes>
        <fullName>Serviced_Space_Onboarding</fullName>
        <active>true</active>
        <businessProcess>Serviced Space Onboarding</businessProcess>
        <label>Serviced Space Onboarding</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Inventory__c.object
<CustomObject>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Inventories</relationshipLabel>
        <relationshipName>Inventories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Inventories</relationshipLabel>
        <relationshipName>Inventories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipName>Suites</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Inventory</label>
    <nameField>
        <label>Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Briefing_Statement__c</fullName>
        <description>Additional information to the property management team.</description>
        <inlineHelpText>Additional information to the property management team.</inlineHelpText>
        <label>Briefing Statement</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Quotes (Contract)</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory</label>
        <referenceTo>Inventory__c</referenceTo>
        <relationshipName>Inventory</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legacy_contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Legacy contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Quotes (Legacy contract)</relationshipLabel>
        <relationshipName>Quotes1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Off_line_Edits__c</fullName>
        <description>Specifies which offline changes are made under quote documents</description>
        <inlineHelpText>Specifies which offline changes are made under quote documents</inlineHelpText>
        <label>Off-line Edits</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__PrimaryContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Primary contact for the quote. This person&apos;s name will appear on generated quote document.</description>
        <inlineHelpText>Primary contact for the quote. This person&apos;s name will appear on generated quote document.</inlineHelpText>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory</label>
        <referenceTo>Inventory__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>Quote_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Quote Lines (Property)</relationshipLabel>
        <relationshipName>QuoteLines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__ProductCode__c</fullName>
        <description>Code for the product referenced by this line.</description>
        <formula>SBQQ__Product__r.ProductCode</formula>
        <inlineHelpText>Code for the product referenced by this line.</inlineHelpText>
        <label>Product Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CaseService.cls
public with sharing class CaseService {

    public static final String LEASE_TRANSACTION_RECORD_TYPE = 'Lease_Transaction';
    public static final String OUTSOURCED_LEASE_TRANSACTION_RECORD_TYPE = 'Outsourced_Lease_Transaction';
    public static final String CONVENTIONAL_ONBOARDING_RECORD_TYPE = 'Conventional_Onboarding';
    public static final String SERVICED_SPACE_ONBOARDING_RECORD_TYPE = 'Serviced_Space_Onboarding';
    public static final String DESIGN_RECORD_TYPE = 'Design';
    public static final String FIT_OUT_DESIGN_RECORD_TYPE = 'Fit_Out_Design';
    public static final String BUILDING_CONSTRUCTION_CASE_RECORD_TYPE = 'Building_Construction_Case';
    public static final String QUOTE_CASE_RECORD_TYPE = 'Quote_Case';
    public static final String CONVENTIONAL_SURRENDER_RECORD_TYPE = 'Contract_Surrender_Conventional';
    public static final String SERVICED_SURRENDER_RECORD_TYPE = 'Contract_Surrender_Serviced';

    public static final String STATUS_READY_TO_ONBOARD = 'Ready to Onboard';
    public static final String STATUS_CUSTOMER_CONFIRMED = 'Customer Confirmed';

    private static BusinessHours defaultBusinessHours;

    public static void setCaseInventory(List<Case> cases) {
        List<String> codesToFilter = new List<String>{
                ProductService.PRODUCT_CODE_OFFICE_RENT,
                ProductService.PRODUCT_CODE_LAB_SPACE,
                ProductService.PRODUCT_CODE_RETAIL_RENT
        };

        Map<Id, Case> quoteIdToCase = new Map<Id, Case>();
        for (Case theCase : cases) {
            if (theCase.Quote__c != null
                    && theCase.RecordTypeId == RecordTypeHelper.getCaseRtIdByDeveloperName(LEASE_TRANSACTION_RECORD_TYPE)) {
                quoteIdToCase.put(theCase.Quote__c, theCase);
            }
        }

        Map<Id, List<SBQQ__QuoteLine__c>> itemsMap = new Map<Id, List<SBQQ__QuoteLine__c>>();
        for (SBQQ__QuoteLine__c item : [
                SELECT Id, Inventory__c, SBQQ__Quote__c
                FROM SBQQ__QuoteLine__c
                WHERE SBQQ__Quote__c IN:quoteIdToCase.keySet() AND Inventory__c != null
                AND SBQQ__ProductCode__c IN :codesToFilter
        ]) {

            if (!itemsMap.containsKey(item.SBQQ__Quote__c)) {
                itemsMap.put(item.SBQQ__Quote__c, new List<SBQQ__QuoteLine__c>());
            }
            itemsMap.get(item.SBQQ__Quote__c).add(item);
        }

        for (Case theCase : quoteIdToCase.values()) {
            if (itemsMap.containsKey(theCase.Quote__c)) {
                theCase.Inventory__c = itemsMap.get(theCase.Quote__c).get(0).Inventory__c;
            }
        }
    }

    public static void setCasePreEmptionInventory(List<Case> cases) {

        Map<Id, Case> quoteIdToCase = new Map<Id, Case>();
        for (Case theCase : cases) {
            if (theCase.Quote__c != null
                    && theCase.RecordTypeId == RecordTypeHelper.getCaseRtIdByDeveloperName(LEASE_TRANSACTION_RECORD_TYPE)) {
                quoteIdToCase.put(theCase.Quote__c, theCase);
            }
        }

        Map<Id, List<SBQQ__QuoteLine__c>> itemsMap = new Map<Id, List<SBQQ__QuoteLine__c>>();
        for (SBQQ__QuoteLine__c item : [
                SELECT Id, Inventory__c, SBQQ__Quote__c
                FROM SBQQ__QuoteLine__c
                WHERE SBQQ__Quote__c IN:quoteIdToCase.keySet() AND Inventory__c != null
                AND SBQQ__ProductCode__c = :ProductService.PRODUCT_CODE_PRE_EMPTION_AGREEMENT
        ]) {

            if (!itemsMap.containsKey(item.SBQQ__Quote__c)) {
                itemsMap.put(item.SBQQ__Quote__c, new List<SBQQ__QuoteLine__c>());
            }
            itemsMap.get(item.SBQQ__Quote__c).add(item);
        }

        for (Case theCase : quoteIdToCase.values()) {
            if (itemsMap.containsKey(theCase.Quote__c)) {
                theCase.Pre_Emption_Inventory__c = itemsMap.get(theCase.Quote__c).get(0).Inventory__c;
            }
        }
    }

    public static BusinessHours getDefaultBusinessHours() {
        if (defaultBusinessHours == null) {
            defaultBusinessHours = [SELECT Id FROM BusinessHours WHERE IsDefault = true];
        }
        return defaultBusinessHours;
    }

    public static Case generateDefaultCase(SBQQ__Quote__c quote, Opportunity theOpportunity) {
        Case theCase = new Case();

        theCase.CurrencyIsoCode = 'GBP';
        theCase.BusinessHoursId = CaseService.getDefaultBusinessHours().Id;
        theCase.Briefing_Statement__c = theOpportunity.Briefing_Statement__c;
        theCase.AccountId = theOpportunity.AccountId;
        theCase.Opportunity__c = theOpportunity.Id;
        theCase.Property__c = quote.Property__c;
        theCase.Quote__c = quote.Id;
        return theCase;
    }

    public static Case generateDefaultOnboardingCase(SBQQ__Quote__c quote, List<SBQQ__QuoteLine__c> headlineQlis, Opportunity theOpportunity) {
        Case theCase = generateDefaultCase(quote, theOpportunity);
        theCase.Status = 'New';
        //theCase.Briefing_Statement__c = theOpportunity.Briefing_Statement__c;
        theCase.Sales_Contact__c = quote.SBQQ__PrimaryContact__c;
        for (SBQQ__QuoteLine__c headLine: headlineQlis) {
            if (headLine.Start_Date__c != null) {
                theCase.Commencement_Date__c = headLine.Start_Date__c;
            }
        }
        return theCase;
    }

    public static void setOffLineEdits(List<Case> cases) {
        Map<Id, List<Case>> casesMappedByQuoteId = SObjectUtils.getIdMapFromObjects(cases, 'Quote__c');
        List<SBQQ__Quote__c> quotes = [SELECT Id, Off_line_Edits__c FROM SBQQ__Quote__c WHERE Id = :casesMappedByQuoteId.keySet()];
        for (SBQQ__Quote__c quote : quotes) {
            for (Case c : casesMappedByQuoteId.get(quote.Id)) {
                c.Off_line_Edits__c = quote.Off_line_Edits__c;
            }
        }
    }

    public static Case generateDefaultLeaseTransactionCase(SBQQ__Quote__c quote, Opportunity theOpportunity) {
        Case theCase = generateDefaultCase(quote, theOpportunity);

        theCase.Status = 'Instructed';
        theCase.Legacy_contract__c = quote.Legacy_contract__c;
        theCase.Contract__c = quote.Contract__c;
        theCase.Sales_Contact__c = quote.SBQQ__PrimaryContact__c;
        return theCase;
    }
}