src/objects/Config_Version__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>CPQ_Version__c</fullName>
        <label>CPQ Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Config Version</label>
</CustomObject>

src/objects/SBQQ__LookupData__c.object
<CustomObject>
    <customHelpPage>SBQQ__LookupQueryHelp</customHelpPage>
    <fields>
        <fullName>CPQ_Config_Version__c</fullName>
        <label>CPQ Config Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Is_Old_Version__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is_Old_Version__c</label>
        <type>Checkbox</type>
    </fields>
    <label>Lookup Data</label>
    <nameField>
        <displayFormat>DATA-{0000}</displayFormat>
        <label>Lookup Data</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lookup Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/smagicinteract__incoming_lookup_config__c.object
<CustomObject>
    <fields>
        <fullName>Config_Version__c</fullName>
        <label>Config Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Is_Old_Version__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is_Old_Version__c</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>smagicinteract__objectName__c</fullName>
        <label>Lookup Object Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Incoming Lookup</label>
    <nameField>
        <displayFormat>I-{00000000}</displayFormat>
        <label>Incoming Lookup Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incoming_Lookup_Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MigrationScriptUtilsTest.cls
@isTest
public with sharing class MigrationScriptUtilsTest {
    @isTest
    public static void populateStatusAndVersionTest(){
        SBQQ__LookupData__c sbqqObject = new SBQQ__LookupData__c(Is_Old_Version__c = false);
        smagicinteract__incoming_lookup_config__c nonSbqqObject = new smagicinteract__incoming_lookup_config__c(Is_Old_Version__c = false, smagicinteract__objectName__c = 'test');
        Config_Version__c version = new Config_Version__c(CPQ_Version__c = 2, SetupOwnerId = UserInfo.getOrganizationId());
        insert version;
        insert sbqqObject;
        insert nonSbqqObject;
        MigrationScriptUtils.populateOldStatus(true);
        System.assertEquals(true, [SELECT Is_Old_Version__c FROM SBQQ__LookupData__c WHERE Id = :sbqqObject.Id][0].Is_Old_Version__c);
        System.assertEquals(true, [SELECT Is_Old_Version__c FROM smagicinteract__incoming_lookup_config__c WHERE Id = :nonSbqqObject.Id][0].Is_Old_Version__c);

        MigrationScriptUtils.setCurrentVersion();
        System.assertEquals(version.CPQ_Version__c, [SELECT CPQ_Config_Version__c FROM SBQQ__LookupData__c WHERE Id = :sbqqObject.Id][0].CPQ_Config_Version__c);

        MigrationScriptUtils.incrementVersion();
        System.assertEquals(version.CPQ_Version__c + 1, [SELECT Id, CPQ_Version__c FROM Config_Version__c WHERE SetupOwnerId = :UserInfo.getOrganizationId()].CPQ_Version__c);

        MigrationScriptUtils.removeOldRecords();
        System.assertEquals(0, [SELECT Id FROM SBQQ__LookupData__c WHERE Id = :sbqqObject.Id].size());
    }
}