src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Event.object
<CustomObject>
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <label>Event</label>
    </recordTypes>
    <recordTypes>
        <fullName>Viewing</fullName>
        <active>true</active>
        <label>Viewing</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Channel__c</fullName>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Lead_Channel</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Conventional</fullName>
        <active>true</active>
        <businessProcess>Conventional Sales Process</businessProcess>
        <label>Conventional</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/smagicinteract__Incoming_SMS__c.object
<CustomObject>
    <customHelpPage>smagicinteract__SMSMagicHelp</customHelpPage>
    <fields>
        <fullName>Mobile_Number_Formatted__c</fullName>
        <description>Converts UK mobile number to 07490168640 format (For example: 447490168640 -&gt; 07490168640).
The formatting needs for comparing the value with Mobile number fields on Contact/Lead object.</description>
        <formula>IF(BEGINS(smagicinteract__Mobile_Number__c, &apos;+44&apos;), &apos;0&apos; + MID(smagicinteract__Mobile_Number__c, 4, LEN(smagicinteract__Mobile_Number__c)), IF(BEGINS(smagicinteract__Mobile_Number__c, &apos;44&apos;), &apos;0&apos; + MID(smagicinteract__Mobile_Number__c, 3, LEN(smagicinteract__Mobile_Number__c)), smagicinteract__Mobile_Number__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Mobile Number Formatted</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>smagicinteract__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Incoming SMS</relationshipLabel>
        <relationshipName>Incoming_SMS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>smagicinteract__Inbound_Number__c</fullName>
        <description>You can receive incoming sms to this number.</description>
        <label>Inbound Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>smagicinteract__Mobile_Number__c</fullName>
        <label>Mobile Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>smagicinteract__SMS_Text__c</fullName>
        <label>SMS Text</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>smagicinteract__external_field__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>external field</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Incoming SMS</label>
    <nameField>
        <displayFormat>I-{00000000}</displayFormat>
        <label>Incoming SMS Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incoming SMS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/IncomingSMSHandlerTest.cls
@isTest
public class IncomingSMSHandlerTest {
    public IncomingSMSHandlerTest() {
        
    }
    @testSetup
    public static void initData(){
        
        Account testAccount = new Account(
            Name = 'Bruntwood');
        Database.insert(testAccount);

        Contact testContact = new Contact(
                FirstName = 'John',
                LastName = 'Brown',
                Email = 'test545343@test5663.com',
                MobilePhone = '07960744016',
                AccountId = testAccount.Id);
        Database.insert(testContact);

        Property__c testProperty = RecordDmlTest.createProperty();
        testProperty.Name = 'Hatch';
        update testProperty;


        Opportunity o = new Opportunity(AccountId = null, Name = 'opportunityName',
        StageName='Prospecting', CloseDate=Date.today(), Channel__c = 'Email');
        Database.insert(o);
        
        Product2 p2 = new Product2(Name='Test Product',isActive=true);
        Database.insert(p2);


        Id recordTypeId = Schema.SObjectType.Event.getRecordTypeInfosByName().get('Viewing').getRecordTypeId();
        Event testEvent = new Event(
            RecordTypeId = recordTypeId,
            Property__c = testProperty.Id,
            Status__c = 'Booked',
            Viewing_Arranged_by__c = 'Sales',
            Viewing_Conducted_by__c = 'Sales',
            OwnerId = UserInfo.getUserId(),
            WhoId = testContact.Id,
            WhatId = RecordDmlTest.createOpportunity('Conventional').Id,
            Viewing_Conducted_by_User__c = RecordDmlTest.createUser().Id,
            StartDateTime = Date.today().addDays(1),
            EndDateTime = Date.today().addDays(2));
        Database.insert(testEvent);
    }

    @isTest
    public static void testSMSHandlerYes(){

        List<smagicinteract__Incoming_SMS__c> smsList = new List<smagicinteract__Incoming_SMS__c>();        
        Contact testContact = [
            SELECT Name, MobilePhone, AccountId
            FROM Contact 
            LIMIT 1];

        Test.startTest();
        smagicinteract__Incoming_SMS__c testIncSMS = new smagicinteract__Incoming_SMS__c(
            smagicinteract__external_field__c = 'I-00000001',
            smagicinteract__Inbound_Number__c = '447960744016',
            smagicinteract__Mobile_Number__c = '447960744016',
            smagicinteract__SMS_Text__c = 'Yes',
            smagicinteract__Contact__c = testContact.Id);
        Database.insert(testIncSMS);
        testIncSMS = [SELECT Id, smagicinteract__Contact__c, smagicinteract__external_field__c, Mobile_Number_Formatted__c, smagicinteract__Inbound_Number__c, smagicinteract__Mobile_Number__c, smagicinteract__SMS_Text__c FROM smagicinteract__Incoming_SMS__c WHERE Id = :testIncSMS.Id];
        smsList.add(testIncSMS);
        IncomingSMSHandler.getConfirmationAction(smsList);
        Test.stopTest();

        Event testEvent = [SELECT Status__c, Status_Updated_By_Customer__c FROM Event LIMIT 1];
        System.assertEquals(Label.Viewing_SMS_Yes, testEvent.Status__c, 'Event status should be confirmed after receiving incoming sms with a YES answer');
        System.assertEquals(true, testEvent.Status_Updated_By_Customer__c, 'Event should be marked as updated with confirmation Yes');
    }

    @isTest
    public static void testSMSHandlerNo(){

        List<smagicinteract__Incoming_SMS__c> smsList = new List<smagicinteract__Incoming_SMS__c>();
        Contact testContact = [
            SELECT Name, MobilePhone, AccountId
            FROM Contact 
            LIMIT 1];

        Test.startTest();
        smagicinteract__Incoming_SMS__c testIncSMS = new smagicinteract__Incoming_SMS__c(
            smagicinteract__external_field__c = 'I-00000001',
            smagicinteract__Inbound_Number__c = '447960744016',
            smagicinteract__Mobile_Number__c = '447960744016',
            smagicinteract__SMS_Text__c = 'No',
            smagicinteract__Contact__c = testContact.Id);
        Database.insert(testIncSMS);
        testIncSMS = [SELECT Id, smagicinteract__Contact__c, smagicinteract__external_field__c, Mobile_Number_Formatted__c, smagicinteract__Inbound_Number__c, smagicinteract__Mobile_Number__c, smagicinteract__SMS_Text__c FROM smagicinteract__Incoming_SMS__c WHERE Id = :testIncSMS.Id];
        smsList.add(testIncSMS);
        IncomingSMSHandler.getConfirmationAction(smsList);
        Test.stopTest();

        Event testEvent = [SELECT Status__c, Status_Updated_By_Customer__c FROM Event LIMIT 1];
        System.assertEquals(Label.Viewing_SMS_No, testEvent.Status__c, 'Event status should be cancelled after receiving incoming sms with a NO answer');
        System.assertEquals(true, testEvent.Status_Updated_By_Customer__c, 'Event should be marked as updated with confirmation No');
    }

    @isTest
    public static void testSMSHandlerContact(){

        List<smagicinteract__Incoming_SMS__c> smsList = new List<smagicinteract__Incoming_SMS__c>();
        Contact testContact = [
            SELECT Name, MobilePhone, AccountId
            FROM Contact 
            LIMIT 1];
        Event testEvent = [SELECT WhoId FROM Event LIMIT 1];
        testEvent.WhoId = testContact.Id;
        Database.update(testEvent);

        Test.startTest();
        smagicinteract__Incoming_SMS__c testIncSMS = new smagicinteract__Incoming_SMS__c(
            smagicinteract__external_field__c = 'I-00000001',
            smagicinteract__Inbound_Number__c = '447960744016',
            smagicinteract__Mobile_Number__c = '447960744016',
            smagicinteract__SMS_Text__c = 'No',
            smagicinteract__Contact__c = testContact.Id);
        Database.insert(testIncSMS);
        testIncSMS = [SELECT Id, smagicinteract__Contact__c, smagicinteract__external_field__c, Mobile_Number_Formatted__c, smagicinteract__Inbound_Number__c, smagicinteract__Mobile_Number__c, smagicinteract__SMS_Text__c FROM smagicinteract__Incoming_SMS__c WHERE Id = :testIncSMS.Id];
        smsList.add(testIncSMS);
        IncomingSMSHandler.getConfirmationAction(smsList);        
        Test.stopTest();

        testEvent = [SELECT Status__c, Status_Updated_By_Customer__c FROM Event LIMIT 1];
        System.assertEquals(Label.Viewing_SMS_No, testEvent.Status__c, 'Event status should be cancelled after receiving incoming sms with a NO answer');
        System.assertEquals(true, testEvent.Status_Updated_By_Customer__c, 'Event should be marked as updated with confirmation');
    }
}