src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Quote from which this Contract was created.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Customer_Confidential_Documentation__c.object
<CustomObject>
    <fields>
        <fullName>SBQQ_Quote_Document__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote Document</label>
        <referenceTo>SBQQ__QuoteDocument__c</referenceTo>
        <relationshipLabel>Customer Confidential Documentations</relationshipLabel>
        <relationshipName>Customer_Confidential_Documentations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Confidential Documentation</label>
    <nameField>
        <displayFormat>CCD-{00000000}</displayFormat>
        <label>CCD Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Confidential Documentations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Quotes (Contract)</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__QuoteDocument__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteDocumentHelp</customHelpPage>
    <description>Particular version of a generated PDF document for the quote it&apos;s attached to. Ability to edit or delete this object should be taken away from all users (except administrators, of course) in order to preserve audit trail of all revisions.</description>
    <fields>
        <fullName>SBQQ__QuoteTemplate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote Template that generated this document.</description>
        <inlineHelpText>Quote Template that generated this document.</inlineHelpText>
        <label>Quote Template</label>
        <referenceTo>SBQQ__QuoteTemplate__c</referenceTo>
        <relationshipLabel>Quote Documents</relationshipLabel>
        <relationshipName>Quote_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this Quote Document belongs.</description>
        <inlineHelpText>Quote to which this Quote Document belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Documents</relationshipLabel>
        <relationshipName>R00N70000001lX7YEAU</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SBQQ__SignatureStatus__c</fullName>
        <description>Status of electronic signature.</description>
        <inlineHelpText>Status of electronic signature.</inlineHelpText>
        <label>Signature Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>Signed</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Correct</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Voided</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Update_Quote_Status__c</fullName>
        <formula>SBQQ__QuoteTemplate__r.Update_Quote_Status__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Update Quote Status</label>
        <type>Checkbox</type>
    </fields>
    <label>Quote Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SBQQ__QuoteTemplate__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteTemplateHelp</customHelpPage>
    <description>Template that controls formatting of generated PDF documents.</description>
    <fields>
        <fullName>Update_Quote_Status__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If you use the template for signature, please will select the field. Because quote status should be updated after signature.
If you use the template for review, please will not select the field. Because quote status should not be updated after review.</description>
        <inlineHelpText>Whether quote status should be updated when the document completed in DocuSign?</inlineHelpText>
        <label>Update Quote Status</label>
        <type>Checkbox</type>
    </fields>
    <label>Quote Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/QuoteAttachmentUtils.cls
public class QuoteAttachmentUtils {

    public static void associateAttachmentFromQuoteDocumentsWithRelatedContract(List<Attachment> attachments) {
        Map<Id, Attachment> parentIdAttachmentMap = filterAttachmentsByParentObject(attachments, SBQQ__QuoteDocument__c.getSObjectType());
        //create map id-QuoteDocuments with necessary conditions
        Map<Id, SBQQ__QuoteDocument__c> idsByDocuments = new Map<Id, SBQQ__QuoteDocument__c>([
                SELECT Id, SBQQ__Quote__r.Contract__c, SBQQ__SignatureStatus__c,
                        SBQQ__QuoteTemplate__r.Update_Quote_Status__c
                FROM SBQQ__QuoteDocument__c
                WHERE Id = :parentIdAttachmentMap.keySet()
                AND SBQQ__SignatureStatus__c = 'Completed'
                AND SBQQ__Quote__r.Contract__c != null
                AND SBQQ__QuoteTemplate__r.Update_Quote_Status__c != false
        ]);
        //copy the attachment from SBQQ__QuoteDocument__c in to Contract
        copyAttachedDocuments(parentIdAttachmentMap, getQuoteDocToContractIdMap(idsByDocuments.values()));
    }

    public static void copyAttachmentFromQuoteDocumentToSecureObject(List<Attachment> attachments) {
        Map<Id, Attachment> parentIdAttachmentMap = filterAttachmentsByParentObject(attachments, SBQQ__QuoteDocument__c.getSObjectType());
        cleanExistingDocuments(parentIdAttachmentMap);
        copyAttachedDocuments(parentIdAttachmentMap, getQuoteDocToCustomerConfDocMap(parentIdAttachmentMap.keySet()));
    }

    private static Map<Id, Attachment> filterAttachmentsByParentObject(List<Attachment> attachments, SObjectType thetype) {
        Map<Id, Attachment> parentIdAttachmentMap = new Map<Id, Attachment>();
        for (Attachment attachment : attachments) {
            if (attachment.ParentId.getSObjectType() == thetype) {
                parentIdAttachmentMap.put(attachment.ParentId, attachment);
            }
        }
        return parentIdAttachmentMap;
    }

    private static void copyAttachedDocuments(Map<Id, Attachment> parentIdAttachmentMap, Map<Id, Id> attachmentIdsMap) {
        List<Attachment> newAttachments = new List<Attachment>();
        for (Attachment attachment : parentIdAttachmentMap.values()) {
            if (attachmentIdsMap.containsKey(attachment.ParentId)) {
                Attachment newFile = attachment.clone();
                newFile.ParentId = attachmentIdsMap.get(attachment.ParentId);
                newAttachments.add(newFile);
            }
        }
        insert newAttachments;
    }

    private static void cleanExistingDocuments(Map<Id, Attachment> parentIdAttachmentMap) {
        Map<Id, Customer_Confidential_Documentation__c> secureObjectsMap = new Map<Id, Customer_Confidential_Documentation__c>([SELECT SBQQ_Quote_Document__c FROM Customer_Confidential_Documentation__c WHERE SBQQ_Quote_Document__c IN :parentIdAttachmentMap.keySet()]);
        List<Attachment> attachments = [SELECT Name, ParentId FROM Attachment WHERE ParentId IN :secureObjectsMap.keySet()];
        List<Attachment> attachmentsForDelete = new List<Attachment>();
        for ( Attachment theAttachment : attachments ) {
            Id relatedQuoteDocumentId = secureObjectsMap.get(theAttachment.ParentId).SBQQ_Quote_Document__c;
            if ( parentIdAttachmentMap.get(relatedQuoteDocumentId).Name == theAttachment.Name ) {
                attachmentsForDelete.add(theAttachment);
            }
        }
        delete attachmentsForDelete;
    }

    private static Map<Id, Id> getQuoteDocToContractIdMap(List<SBQQ__QuoteDocument__c> documents) {
        Map<Id, Id> attachmentIdsMap = new Map<Id, Id>();
        for ( SBQQ__QuoteDocument__c theDocument : documents ) {
            attachmentIdsMap.put(theDocument.Id, theDocument.SBQQ__Quote__r.Contract__c);
        }
        return attachmentIdsMap;
    }

    private static Map<Id, Id> getQuoteDocToCustomerConfDocMap(Set<Id> quoteDocumentIds) {
        Set<Id> servicedQuoteRecordTypeIds = SBQQ_QuoteService.getServicedRecordTypeIds();
        Set<Id> virtualQuoteRecordTypeIds = SBQQ_QuoteService.getVirtualRecordTypeIds();
        List<Customer_Confidential_Documentation__c> confDocuments = [SELECT SBQQ_Quote_Document__c
                                                                      FROM Customer_Confidential_Documentation__c
                                                                      WHERE SBQQ_Quote_Document__c IN :quoteDocumentIds
                                                                            AND (SBQQ_Quote_Document__r.SBQQ__Quote__r.RecordTypeId IN :servicedQuoteRecordTypeIds
                                                                                OR SBQQ_Quote_Document__r.SBQQ__Quote__r.RecordTypeId IN :virtualQuoteRecordTypeIds)
        ];
        Map<Id, Id> attachmentIdsMap = new Map<Id, Id>();
        for ( Customer_Confidential_Documentation__c confDoc : confDocuments ) {
            attachmentIdsMap.put(confDoc.SBQQ_Quote_Document__c, confDoc.Id);
        }
        return attachmentIdsMap;
    }

}