src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <inlineHelpText>Hold the &apos;ctrl&apos; key to select multiple types.</inlineHelpText>
        <label>Contact Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Billing Contact</fullName>
                </value>
                <value>
                    <fullName>In Life Property Contact</fullName>
                </value>
                <value>
                    <fullName>Sales Contact</fullName>
                </value>
                <value>
                    <fullName>Out of Hours Contact</fullName>
                </value>
                <value>
                    <fullName>Legal Contact</fullName>
                </value>
                <value>
                    <fullName>Project Management Contact</fullName>
                </value>
                <value>
                    <fullName>Director Contact</fullName>
                </value>
                <value>
                    <fullName>Remittance - Finance</fullName>
                </value>
                <value>
                    <fullName>Statement - Finance</fullName>
                </value>
                <value>
                    <fullName>Purchase Ledger - Finance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Potential_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Potential Contacts</relationshipLabel>
        <relationshipName>Potential_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <label>Contact Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Billing Contact</fullName>
                </value>
                <value>
                    <fullName>In Life Property Contact</fullName>
                </value>
                <value>
                    <fullName>Sales Contact</fullName>
                </value>
                <value>
                    <fullName>Out of Hours Contact</fullName>
                </value>
                <value>
                    <fullName>Legal Contact</fullName>
                </value>
                <value>
                    <fullName>Project Management Contact</fullName>
                </value>
                <value>
                    <fullName>Director Contact</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>New_Contact_Type__c</fullName>
        <label>Contact Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Billing Contact</fullName>
                </value>
                <value>
                    <fullName>In Life Property Contact</fullName>
                </value>
                <value>
                    <fullName>Out of Hours Contact</fullName>
                </value>
                <value>
                    <fullName>Legal Contact</fullName>
                </value>
                <value>
                    <fullName>Project Management Contact</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>New_Email__c</fullName>
        <label>Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ_QuoteDocument__c</fullName>
        <label>Quote Document</label>
        <referenceTo>SBQQ__QuoteDocument__c</referenceTo>
        <relationshipLabel>Potential Contacts</relationshipLabel>
        <relationshipName>Potential_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SBQQ_Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Potential Contacts</relationshipLabel>
        <relationshipName>Potential_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Potential Contact</label>
    <nameField>
        <displayFormat>PC-{000000000}</displayFormat>
        <label>Potential Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Potential Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__QuoteDocument__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteDocumentHelp</customHelpPage>
    <description>Particular version of a generated PDF document for the quote it&apos;s attached to. Ability to edit or delete this object should be taken away from all users (except administrators, of course) in order to preserve audit trail of all revisions.</description>
    <fields>
        <fullName>Account_Id__c</fullName>
        <formula>SBQQ__Quote__r.SBQQ__Account__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Owner_Id__c</fullName>
        <formula>SBQQ__Quote__r.SBQQ__Opportunity2__r.OwnerId</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity Owner Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this Quote Document belongs.</description>
        <inlineHelpText>Quote to which this Quote Document belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Documents</relationshipLabel>
        <relationshipName>R00N70000001lX7YEAU</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PotentialContactService.cls
/**
 * @description Class contains general functionality related to Potential_Contact__c object
 */
public with sharing class PotentialContactService {

    /**
     * @description Created Potential_Contact__c record for quote documents where contact information was updated
     */
    public void createPotentialContactsForUpdatedDocuments(Map<SBQQ__QuoteDocument__c, Set<String>> updatedDocumentsMap, Map<Id, SBQQ__QuoteDocument__c> oldDocumentsMap) {
        List<Potential_Contact__c> potentialContacts = new List<Potential_Contact__c>();
        for ( SBQQ__QuoteDocument__c theDocument : updatedDocumentsMap.keySet() ) {
            potentialContacts.addAll(createPotentialContactsForUpdatedDocument(theDocument, updatedDocumentsMap.get(theDocument), oldDocumentsMap));
        }
        insert potentialContacts;
        createRemindersForNewPotentialContacts(potentialContacts, oldDocumentsMap);
    }

    /**
     * @description Returns Potential_Contact__c record for quote documents where contact information was updated
     */
    private List<Potential_Contact__c> createPotentialContactsForUpdatedDocument(SBQQ__QuoteDocument__c quoteDocument, Set<String> contactTypes, Map<Id, SBQQ__QuoteDocument__c> oldDocumentsMap) {
        List<Potential_Contact__c> potentialContacts = new List<Potential_Contact__c>();
        Set<String> potentialContactUniqueIdentifier = new Set<String>();
        SBQQ__QuoteDocument__c oldDocument = oldDocumentsMap.get(quoteDocument.Id);
        for ( String contactType : contactTypes ) {
            Potential_Contact__c potentialContact = new Potential_Contact__c();
            String uniqueIdentifier = '';
            for ( String fieldName : SBQQ_QuoteConstants.FIELD_NAMES_MAP.keySet() ) {
                potentialContact.SBQQ_Quote__c = quoteDocument.SBQQ__Quote__c;
                potentialContact.SBQQ_QuoteDocument__c = quoteDocument.Id;
                potentialContact.Account__c = quoteDocument.Account_Id__c;
                potentialContact.put(fieldName, oldDocument.get(contactType + '_' + fieldName));
                potentialContact.put('New_' + fieldName, quoteDocument.get(contactType + '_' + fieldName));
                uniqueIdentifier += quoteDocument.get(contactType + '_' + fieldName) + '_';
            }
            uniqueIdentifier = uniqueIdentifier.toLowerCase();
            System.debug('uniqueIdentifier: ' + uniqueIdentifier);
            potentialContact.Contact_Type__c = SBQQ_QuoteConstants.PREFIX_TO_CONTACT_TYPE_MAP.get(contactType);
            potentialContact.New_Contact_Type__c = SBQQ_QuoteConstants.PREFIX_TO_CONTACT_TYPE_MAP.get(contactType);
            if ( !potentialContactUniqueIdentifier.contains(uniqueIdentifier)
                    && String.isNotBlank((String)potentialContact.get('New_Last_Name__c'))
                    && String.isNotBlank((String)potentialContact.get('New_First_Name__c'))
                    && String.isNotBlank((String)potentialContact.get('New_Email__c'))) {
                potentialContacts.add(potentialContact);
                potentialContactUniqueIdentifier.add(uniqueIdentifier);
            }
        }
        return potentialContacts;
    }

    private void createRemindersForNewPotentialContacts(List<Potential_Contact__c> potentialContacts, Map<Id, SBQQ__QuoteDocument__c> oldDocumentsMap) {
        List<Task> reminderTasks = new List<Task>();
        for ( Potential_Contact__c potentialContact : potentialContacts ) {
            reminderTasks.add(TaskService.generateReviewPCTask(oldDocumentsMap.get(potentialContact.SBQQ_QuoteDocument__c).Opportunity_Owner_Id__c, potentialContact.Id));
        }
        insert reminderTasks;
    }

}