src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Quote from which this Contract was created.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Surrender_Date__c</fullName>
        <inlineHelpText>This field will be updated when the proposed surrender date field is populated when the contract is surrender</inlineHelpText>
        <label>Surrender Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract_Surrender__c.object
<CustomObject>
    <fields>
        <fullName>Break_Penalty_Premium_Billing_Status__c</fullName>
        <label>Break Penalty Premium Billing Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Surrender_Billing_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Budget_Dilapidations_Billing_Status__c</fullName>
        <label>Budget Dilapidations Billing Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Surrender_Billing_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contract Surrenders</relationshipLabel>
        <relationshipName>Contract_Surrenders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_Surrender_Triggered__c</fullName>
        <label>Date Surrender Triggered</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deposit_Billing_Status__c</fullName>
        <label>Deposit Billing Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Surrender_Billing_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deposit_Interest_Billing_Status__c</fullName>
        <label>Deposit Interest Billing Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Surrender_Billing_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deposit__c</fullName>
        <label>Deposit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Final_Dilapidations_Billing_Status__c</fullName>
        <label>Final Dilapidations Billing Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Surrender_Billing_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Interim_Dilapidations_Billing_Status__c</fullName>
        <label>Interim Dilapidations Billing Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Surrender_Billing_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_the_customer_liable_for_Service_Chrg__c</fullName>
        <description>Is the customer liable for Service Charge Reconciliation?</description>
        <inlineHelpText>Is the customer liable for Service Charge Reconciliation?</inlineHelpText>
        <label>Customer liable for Service Charge</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No_Value_Set</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_the_customer_liable_for_electricity__c</fullName>
        <description>Is the customer liable for electricity costs post completion?</description>
        <inlineHelpText>Is the customer liable for electricity costs post completion?</inlineHelpText>
        <label>Customer liable for electricity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No_Value_Set</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Proposed_date_of_surrender__c</fullName>
        <label>Proposed date of surrender</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&apos;New&apos;</defaultValue>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Suite_Restoration_Billing_Status__c</fullName>
        <label>Suite Restoration Billing Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Surrender_Billing_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Surrender_Premium_Billing_Status__c</fullName>
        <label>Surrender Premium Billing Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Surrender_Billing_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Terminal_Dilapidations_Billing_Status__c</fullName>
        <label>Terminal Dilapidations Billing Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Surrender_Billing_Status</valueSetName>
        </valueSet>
    </fields>
    <label>Contract Surrender</label>
    <nameField>
        <label>Contract Surrender Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Surrenders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Quotes (Contract)</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deposit__c</fullName>
        <description>Total Deposit % on the Quote</description>
        <formula>Deposit_Payment__c / SBQQ__NetAmount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Total Deposit % on the Quote.</inlineHelpText>
        <label>Deposit %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ContractSurrenderTriggerHandlerTest.cls
@IsTest
public class ContractSurrenderTriggerHandlerTest {
    @TestSetup
    public static void init() {
        //Account account = RecordDmlTest.createAccount();
        Property__c property = RecordDmlTest.createProperty();
        Opportunity opportunity = RecordDmlTest.createOpportunity(OpportunityService.CONVENTIONAL_RECORD_TYPE);
        SBQQ__Quote__c quote = RecordDmlTest.createQuote(property,opportunity,OpportunityService.CONVENTIONAL_RECORD_TYPE);

        Contract contract = RecordDmlTest.createContract(quote, property);

        Contract_Surrender__c surrender = generateSurrender(contract);
        insert surrender;
    }

    @IsTest
    public static void givenSurrenderContractWhenCompletedThenContractFieldPopulated() {
        Contract contract = [SELECT Id, Surrender_Date__c FROM Contract];
        Contract_Surrender__c surrender = [SELECT Id, Proposed_date_of_surrender__c, Status__c FROM Contract_Surrender__c];

        System.assertEquals(1, [SELECT COUNT() FROM Contract WHERE Id = :contract.Id AND Surrender_Date__c = :surrender.Proposed_date_of_surrender__c]);

        contract.Surrender_Date__c = null;
        update contract;

        surrender.Status__c = 'New';
        update surrender;

        System.assertEquals(0, [SELECT COUNT() FROM Contract WHERE Id = :contract.Id AND Surrender_Date__c = :surrender.Proposed_date_of_surrender__c]);

        surrender.Status__c = 'Complete';
        update surrender;

        System.assertEquals(1, [SELECT COUNT() FROM Contract WHERE Id = :contract.Id AND Surrender_Date__c = :surrender.Proposed_date_of_surrender__c]);

    }

    @IsTest
    public static void givenSurrenderWhenSecondSurrenderCreatedThenErrorAdded() {
        Contract contract = [SELECT Id, Name, Surrender_Date__c FROM Contract];
        try {
            insert generateSurrender(contract);
        } catch (Exception e) {
            System.assert(e.getMessage().contains('already have a Surrender'));
        }
    }

    private static Contract_Surrender__c generateSurrender(Contract contract) {
        return new Contract_Surrender__c(
                Date_Surrender_Triggered__c = Date.today(),
                Proposed_date_of_surrender__c = Date.today(),
                Contract__c = contract.Id,
                Name = ('Surrender: ' + contract.Name),
                Deposit__c = 100,
                Status__c = 'Complete',
                Break_Penalty_Premium_Billing_Status__c = 'To be billed',
                Budget_Dilapidations_Billing_Status__c = 'To be billed',
                Deposit_Interest_Billing_Status__c = 'To be billed',
                Deposit_Billing_Status__c = 'To be billed',
                Final_Dilapidations_Billing_Status__c = 'To be billed',
                Interim_Dilapidations_Billing_Status__c = 'To be billed',
                Suite_Restoration_Billing_Status__c = 'To be billed',
                Terminal_Dilapidations_Billing_Status__c = 'To be billed',
                Surrender_Premium_Billing_Status__c = 'To be billed',
                Is_the_customer_liable_for_Service_Chrg__c = 'Yes',
                Is_the_customer_liable_for_electricity__c = 'Yes'
        );
    }
}