src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Customer_Feedback__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Customer Feedbacks</relationshipLabel>
        <relationshipName>Customer_Feedbacks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Member_Experience__c</fullName>
        <label>Team Member Experience</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Property_Quality__c</fullName>
        <label>Property Quality</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Good</fullName>
                </value>
                <value>
                    <fullName>Bad</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Customer Feedbacks</relationshipLabel>
        <relationshipName>Customer_Feedbacks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Feedback</label>
    <nameField>
        <label>Feedback Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Event.object
<CustomObject>
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <label>Event</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Feedback_Request__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Feedback Requests</relationshipLabel>
        <relationshipName>Feedback_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property1</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Feedback Requests</relationshipLabel>
        <relationshipName>Feedback_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Viewing1_Id__c</fullName>
        <label>Viewing1 Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Feedback Request</label>
    <nameField>
        <label>Feedback Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Feedback Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Feedback_Response__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Feedback Responses</relationshipLabel>
        <relationshipName>Feedback_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Feedback_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Feedback Request</label>
        <referenceTo>Feedback_Request__c</referenceTo>
        <relationshipLabel>Feedback Responses</relationshipLabel>
        <relationshipName>Feedback_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Member_Experience__c</fullName>
        <label>Team Member Experience</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Property1_Quality__c</fullName>
        <label>Property1 Quality</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property1</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Feedback Responses</relationshipLabel>
        <relationshipName>Feedback_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Feedback Response</label>
    <nameField>
        <label>Feedback Response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Feedback Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Region</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Conventional</fullName>
        <active>true</active>
        <businessProcess>Conventional Sales Process</businessProcess>
        <label>Conventional</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Region</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Feedback_ResponseTriggerHandlerTest.cls
@IsTest
private class Feedback_ResponseTriggerHandlerTest {
    static testMethod void givenPropertiesAndContact_whenNewFeedbackResponseCreated_thenCustomerFeedbacksCreatedAndLinked() {
        //given
        Property__c property = new Property__c(Name = '111 Piccadilly', Region__c = 'Alderley Park', Street__c = 'Property#1 address');
        insert property;
        Product2 p2 = RecordDmlTest.createProducts().get(0);
        Contact contact = new Contact(LastName = 'Last');
        insert contact;

        Opportunity opportunity = RecordDmlTest.createOpportunity('Conventional');
        Event viewing1 = RecordDmlTest.createViewingEvent(contact.id, opportunity.Id, property.Id);

        Feedback_Request__c feedbackRequest = new Feedback_Request__c(Viewing1_Id__c=viewing1.Id,Contact__c = contact.Id);
        insert feedbackRequest;

        //when
        Feedback_Response__c response = new Feedback_Response__c();
        response.Property1__c = property.Id;
        response.Property1_Quality__c = 'Good';
        response.Member_experience__c = 7;
        response.Contact__c = contact.Id;
        response.Feedback_Request__c=feedbackRequest.Id;
        insert response;

        //then
        List<Customer_Feedback__c> feedbacks = [select id, Contact__c,Property__c, Property_Quality__c, Member_experience__c from Customer_Feedback__c];

        System.assertEquals(1, feedbacks.size());
        System.assertEquals(contact.Id, feedbacks.get(0).Contact__c);
        System.assertEquals(property.Id, feedbacks.get(0).Property__c);
        System.assertEquals('Good', feedbacks.get(0).Property_Quality__c);
        System.assertEquals(7, feedbacks.get(0).Member_experience__c);
    }
}