src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Quote from which this Contract was created.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Event.object
<CustomObject>
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <label>Event</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Inventory__c.object
<CustomObject>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Inventories</relationshipLabel>
        <relationshipName>Inventories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipName>Suites</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rent_per_sq_ft_Annual__c</fullName>
        <formula>Rent_per_sq_ft__c * 12</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Rent per sq ft per annum</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <label>Inventory</label>
    <nameField>
        <label>Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Briefing_Statement__c</fullName>
        <description>Additional information to the property management team.</description>
        <inlineHelpText>Additional information to the property management team.</inlineHelpText>
        <label>Briefing Statement</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Closed_Lost_Comments__c</fullName>
        <label>Closed Lost Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Closed_Lost_Reason__c</fullName>
        <label>Closed Lost Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Too expensive</fullName>
                </value>
                <value>
                    <fullName>Space too big</fullName>
                </value>
                <value>
                    <fullName>Space too small</fullName>
                </value>
                <value>
                    <fullName>Unsuitable location</fullName>
                </value>
                <value>
                    <fullName>Feasibility study</fullName>
                </value>
                <value>
                    <fullName>Went to competitor</fullName>
                </value>
                <value>
                    <fullName>Requirement retracted</fullName>
                </value>
                <value>
                    <fullName>Lack of car parking</fullName>
                </value>
                <value>
                    <fullName>Unsuitable specification</fullName>
                </value>
                <value>
                    <fullName>See Closed Lost Comments</fullName>
                </value>
                <value>
                    <fullName>Inactivity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Compliance_Check_Complete__c</fullName>
        <label>Compliance Check Complete</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No_Value_Set</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_Activated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contract Activated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contracts_Exchanged__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contracts Exchanged</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Deposit_Paid__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Use this field to indicate that the deposit has been paid by the customer</description>
        <inlineHelpText>Use this field to indicate that the deposit has been paid by the customer</inlineHelpText>
        <label>Deposit Paid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Event_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Event Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>HOTs_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>HOTs Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HOTs_Signed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>HOTs Signed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LA_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>LA Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LA_Signed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>LA Signed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LT_Case_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>LT Case Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Event_ID__c</fullName>
        <label>Last Event ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Viewing_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Viewing Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Virtual_Compliance_Approval_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Virtual Compliance Approval Complete</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Conventional</fullName>
        <active>true</active>
        <businessProcess>Conventional Sales Process</businessProcess>
        <label>Conventional</label>
    </recordTypes>
    <recordTypes>
        <fullName>Serviced</fullName>
        <active>true</active>
        <businessProcess>Serviced Sales Process</businessProcess>
        <label>Serviced</label>
    </recordTypes>
    <recordTypes>
        <fullName>Virtual</fullName>
        <active>true</active>
        <businessProcess>Virtual Sales Process</businessProcess>
        <label>Virtual</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Serviced_Space_Coordinator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Serviced Space Coordinator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Properties4</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Quotes (Contract)</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Discount_Term_Certain__c</fullName>
        <label>Discount Term Certain (£)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory</label>
        <referenceTo>Inventory__c</referenceTo>
        <relationshipName>Inventory</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Net_Fill_Sq_ft__c</fullName>
        <label>Net Fill (Sq ft)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Property_Name__c</fullName>
        <formula>Property__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Property Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rent_per_Sq_Ft_annual__c</fullName>
        <description>Rent per Sq. Ft. annual (£)</description>
        <label>Rent per Sq. Ft. annual (£)</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SBQQ__Opportunity2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity associated with this Quote.</description>
        <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__PrimaryContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Primary contact for the quote. This person&apos;s name will appear on generated quote document.</description>
        <inlineHelpText>Primary contact for the quote. This person&apos;s name will appear on generated quote document.</inlineHelpText>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox which if checked designates the quote as the Primary Quote</description>
        <inlineHelpText>Select this checkbox to designate this quote as the primary one on the opportunity and sync quote line items with opportunity line items.</inlineHelpText>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Term_Certain__c</fullName>
        <label>Term Certain</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <label>Term</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Parking_Spaces__c</fullName>
        <label>Total Parking Spaces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_deal_size_Sq_ft__c</fullName>
        <label>Total deal size (Sq ft)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <recordTypes>
        <fullName>Conventional</fullName>
        <active>true</active>
        <label>Conventional</label>
    </recordTypes>
    <recordTypes>
        <fullName>Serviced</fullName>
        <active>true</active>
        <label>Serviced</label>
    </recordTypes>
    <recordTypes>
        <fullName>Virtual</fullName>
        <active>true</active>
        <label>Virtual</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OpportunityService.cls
public with sharing class OpportunityService {
    public static final String STATUS_MEETING_BOOKED = 'Meeting Booked';
    public static final String STATUS_TERMS_AGREED = 'Terms Agreed';
    public static final String STATUS_COMPLETED = 'Completed';
    public static final String STATUS_INSTRUCTED = 'Instructed';
    public static final String STATUS_EXCHANGED = 'Exchanged';
    public static final String STATUS_QUALIFIED = 'Qualified';

    public static final String VIRTUAL_RECORD_TYPE_NAME = 'Virtual';
    public static final String CONVENTIONAL_RECORD_TYPE = 'Conventional';
    public static final String SERVICED_RECORD_TYPE = 'Serviced';
    public static final Id VIRTUAL_RECORD_TYPE_ID;
    public static final Id CONVENTIONAL_RECORD_TYPE_ID;
    public static final Id SERVICED_RECORD_TYPE_ID;

    static {
        Map<String, RecordTypeInfo> recordTypeInfosMap = Schema.SObjectType.Opportunity.getRecordTypeInfosByName();
        VIRTUAL_RECORD_TYPE_ID = recordTypeInfosMap.get(VIRTUAL_RECORD_TYPE_NAME).getRecordTypeId();
        CONVENTIONAL_RECORD_TYPE_ID = recordTypeInfosMap.get(CONVENTIONAL_RECORD_TYPE).getRecordTypeId();
        SERVICED_RECORD_TYPE_ID = recordTypeInfosMap.get(SERVICED_RECORD_TYPE).getRecordTypeId();
    }

    private static Map<Id, RecordType> opportunityRecordTypes;
    public static Map<Id, RecordType> getRecrodTypes() {
        if (opportunityRecordTypes == null) {
            opportunityRecordTypes = new Map<Id, RecordType>(
                RecordTypeHelper.getRecordTypesForSObject(RecordTypeHelper.OPPORTUNITY_SOBJECT)
            );
        }
        return opportunityRecordTypes;
    }

    public static void createTaskForCoordinator(List<Opportunity> opportunities) {
        Map<Id, Opportunity> completedOpportunities = new Map<Id, Opportunity>();
        Map<String, Opportunity> meetingBookedOpportunities = new Map<String, Opportunity>();
        List<Task> tasksToCreate = new List<Task>();

        for (Opportunity theOpportunity: opportunities) {
            if (theOpportunity.StageName.equals(STATUS_COMPLETED) && theOpportunity.Deposit_Paid__c) {
                completedOpportunities.put(theOpportunity.Id, theOpportunity);
            }
            if (theOpportunity.StageName.equals(STATUS_MEETING_BOOKED) && theOpportunity.Last_Event_ID__c != null) {
                meetingBookedOpportunities.put(theOpportunity.Last_Event_ID__c, theOpportunity);
            }
        }

        if (!completedOpportunities.isEmpty()) {
            List<SBQQ__Quote__c> quotes = [SELECT Id, Name,
                        SBQQ__Opportunity2__c,
                        SBQQ__PrimaryContact__c,
                        SBQQ__PrimaryContact__r.Name,
                        Contract__c, Contract__r.StartDate,
                        Property__c,
                        Property__r.Serviced_Space_Coordinator__c
                    FROM SBQQ__Quote__c
                    WHERE SBQQ__Opportunity2__c IN :completedOpportunities.keySet() 
                        AND Property__r.Serviced_Space_Coordinator__c != null];

            for (SBQQ__Quote__c quote: quotes) {
                Id opportunityId = quote.SBQQ__Opportunity2__c;
                if (completedOpportunities.containsKey(opportunityId)) {
                    Opportunity theOpportunity = completedOpportunities.get(opportunityId);
                    tasksToCreate.add(TaskService.generateVirtualTask(theOpportunity, quote));
                }
            }
        }

        if (!meetingBookedOpportunities.isEmpty()) {
            List<Event> events = [
                SELECT Id, RecordTypeId, Property__c, Property__r.Serviced_Space_Coordinator__c, WhoId
                FROM Event
                WHERE Id IN: meetingBookedOpportunities.keySet()
                    AND Property__r.Serviced_Space_Coordinator__c != null
            ];

            for (Event theEvent: events) {
                Id eventID = theEvent.Id;

                if (meetingBookedOpportunities.containsKey(eventID)) {
                    Opportunity theOpportunity = meetingBookedOpportunities.get(eventID);
                    tasksToCreate.add(TaskService.generateVirtualMeetingTask(theOpportunity, theEvent));
                }
            }
        }
        insert tasksToCreate;
    }

    /**
     * @description Calculates Opportunity statuses
     */
    public static void calculateOpportunitiesStatuses(List<Opportunity> theOpportunities, Map<Id, Opportunity> theOldMap) {
        List<Opportunity> oppsForStatusCalculation = new List<Opportunity>();
        for ( Opportunity theOpportunity : theOpportunities ) {
            //Skip status calcualtion logic if manualy selected Lost status
            if ( theOldMap.get(theOpportunity.Id).StageName != theOpportunity.StageName && theOpportunity.StageName == ConventionalOppStatusCalculator.STAGE_LOST ) {
                continue;
            }
            oppsForStatusCalculation.add(theOpportunity);
        }
        calculateOpportunitiesStatuses(oppsForStatusCalculation);
    }

    /**
     * @description Calculates Opportunity statuses for specified Opportunities
     */
    public static void calculateOpportunitiesStatuses(List<Opportunity> theOpportunities) {
        Set<Id> automatedStatusCalculationRecordTypes = new Set<Id>{CONVENTIONAL_RECORD_TYPE_ID, SERVICED_RECORD_TYPE_ID, VIRTUAL_RECORD_TYPE_ID};
        for ( Opportunity theOpportunity : theOpportunities ) {
            if ( automatedStatusCalculationRecordTypes.contains(theOpportunity.RecordTypeId) ) {
                theOpportunity.StageName = OppStatusCalculatorFactory.getStatusCalculator(theOpportunity.RecordTypeId).calculateNewStatus(theOpportunity);
            }
        }
    }

    /**
     * @description Calculates Opportunity statuses for specified Opportunities Ids
     */
    public static void calculateOpportunitiesStatuses(Set<Id> theOpportunitiesIds) {
        List<Opportunity> oppsForStatusCalculation = [SELECT RecordTypeId, Viewing_Count__c, Event_Count__c, HOTs_Sent__c, HOTs_Signed__c, LA_Sent__c, LA_Signed__c, LT_Case_Completed__c,
                                                             Contracts_Exchanged__c, Contract_Activated__c, Compliance_Check_Complete__c, Virtual_Compliance_Approval_Complete__c,
                                                             Briefing_Statement__c, Deposit_Paid__c, Closed_Lost_Reason__c, Closed_Lost_Comments__c
                                                      FROM Opportunity WHERE Id IN :theOpportunitiesIds];
        calculateOpportunitiesStatuses(oppsForStatusCalculation);
        update oppsForStatusCalculation;
    }

    private static Map<Id, List<Opportunity>> getOpportunitiesMapByRecordTypeId(List<Opportunity> theOpportunities) {
        Map<Id, List<Opportunity>> opportunitiesMap = new Map<Id, List<Opportunity>>();
        for ( Opportunity theOpportunity : theOpportunities ) {
            if ( !opportunitiesMap.containsKey(theOpportunity.RecordTypeId) ) {
                opportunitiesMap.put(theOpportunity.RecordTypeId, new List<Opportunity>());
            }
            opportunitiesMap.get(theOpportunity.RecordTypeId).add(theOpportunity);
        }
        return opportunitiesMap;
    }

    public static Map<String,SBQQ__Quote__c> getPrimaryQuotesByOpportunities (List<Opportunity> opportunities) {
        Map<String,SBQQ__Quote__c> opportunityPrimaryQuoteMap = new Map<String, SBQQ__Quote__c>();

        List<SBQQ__Quote__c> primaryQuotes = [
                SELECT Id, SBQQ__Opportunity2__c, Inventory__r.Name, Inventory__c, Net_Fill_Sq_ft__c,
                        Total_deal_size_Sq_ft__c, Discount_Term_Certain__c, Total_Parking_Spaces__c, Term__c,
                        Term_Certain__c, Rent_per_Sq_Ft_annual__c, Property_Name__c
                FROM SBQQ__Quote__c
                WHERE SBQQ__Primary__c = true
                AND SBQQ__Opportunity2__c
                        IN :opportunities];

        for (SBQQ__Quote__c theQuote: primaryQuotes) {
            opportunityPrimaryQuoteMap.put(theQuote.SBQQ__Opportunity2__c, theQuote);
        }

        return opportunityPrimaryQuoteMap;
    }
}