src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Customer_Feedback__c.object
<CustomObject>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Customer Feedbacks</relationshipLabel>
        <relationshipName>Customer_Feedbacks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Feedback__c</fullName>
        <label>Feedback</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Customer Feedbacks</relationshipLabel>
        <relationshipName>Customer_Feedbacks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Member_Experience__c</fullName>
        <label>Team Member Experience</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Customer Feedbacks</relationshipLabel>
        <relationshipName>Customer_Feedbacks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property_Quality__c</fullName>
        <label>Property Quality</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Good</fullName>
                </value>
                <value>
                    <fullName>Bad</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Customer Feedbacks</relationshipLabel>
        <relationshipName>Customer_Feedbacks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Viewing_Id__c</fullName>
        <label>Viewing Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Customer Feedback</label>
    <nameField>
        <label>Feedback Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Event.object
<CustomObject>
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <label>Event</label>
    </recordTypes>
    <recordTypes>
        <fullName>Viewing</fullName>
        <active>true</active>
        <label>Viewing</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Feedback_Request__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Feedback Requests</relationshipLabel>
        <relationshipName>Feedback_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Feedback Requests</relationshipLabel>
        <relationshipName>Feedback_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Viewing10_Id__c</fullName>
        <label>Viewing10 Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Viewing1_Id__c</fullName>
        <label>Viewing1 Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Viewing2_Id__c</fullName>
        <label>Viewing2 Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Viewing3_Id__c</fullName>
        <label>Viewing3 Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Viewing4_Id__c</fullName>
        <label>Viewing4 Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Viewing5_Id__c</fullName>
        <label>Viewing5 Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Viewing6_Id__c</fullName>
        <label>Viewing6 Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Viewing7_Id__c</fullName>
        <label>Viewing7 Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Viewing8_Id__c</fullName>
        <label>Viewing8 Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Viewing9_Id__c</fullName>
        <label>Viewing9 Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Feedback Request</label>
    <nameField>
        <label>Feedback Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Feedback Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Feedback_Response__c.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Feedback Responses</relationshipLabel>
        <relationshipName>Feedback_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Feedback_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Feedback Request</label>
        <referenceTo>Feedback_Request__c</referenceTo>
        <relationshipLabel>Feedback Responses</relationshipLabel>
        <relationshipName>Feedback_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Feedback__c</fullName>
        <label>Feedback</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Feedback Responses</relationshipLabel>
        <relationshipName>Feedback_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Member_Experience__c</fullName>
        <label>Team Member Experience</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Feedback Response</label>
    <nameField>
        <label>Feedback Response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Feedback Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CustomerFeedbackService.cls
public with sharing class CustomerFeedbackService {

    public static void createFeedbacks(List<Feedback_Response__c> responses) {
        Set<Id>feedbackRequestIds = SObjectUtils.getIdSetFromObjects(responses, 'Feedback_Request__c');
        Map<Id, Feedback_Request__c> requestsMap = new Map<Id, Feedback_Request__c>([
            SELECT Id, Lead__c, Lead__r.Name, Contact__c, Contact__r.Name, 
                Viewing1_Id__c, Viewing2_Id__c, Viewing3_Id__c, Viewing4_Id__c, Viewing5_Id__c,
                Viewing6_Id__c, Viewing7_Id__c, Viewing8_Id__c, Viewing9_Id__c, Viewing10_Id__c
            FROM Feedback_Request__c
            WHERE Id in:feedbackRequestIds
        ]);

        Set<Id> propertyIds = new Set<Id>();
        Set<Id> viewingsIds = new Set<Id>();

        for (Feedback_Response__c response : responses) {
            Feedback_Request__c request = requestsMap.get(response.Feedback_Request__c);
            request = request == null ? new Feedback_Request__c() : request;

            for (Integer i = 1; i <= ScheduledViewingFeedbackEmailSending.MAXIMUM_VIEWINGS_IN_SESSION; i++) {
                Id propertyId = (Id) response.get('Property' + i + '__c');
                Id viewingId = (Id) request.get('Viewing' + i + '_Id__c');

                if (propertyId != null) {
                    propertyIds.add(propertyId);
                    viewingsIds.add(viewingId);
                } else {
                    break;//no more viewings
                }
            }
        }

        Map<Id, Property__c> propertiesMap = new Map<Id, Property__c>([SELECT Id, Name FROM Property__c WHERE Id IN: propertyIds]);
        Map<Id, Event> viewingsMap = new Map<id, Event>([SELECT Id, WhatId FROM Event WHERE id in :viewingsIds]);
        Set<Id> potentialOpportunitiesIds = SObjectUtils.getIdSetFromObjects(viewingsMap.values(), 'WhatId');
        Set<Id> opportunitiesIds = new Map<Id, Opportunity>([SELECT Id FROM Opportunity WHERE id in :potentialOpportunitiesIds]).keySet();

        List<Customer_Feedback__c> feedbacks = new List<Customer_Feedback__c>();
        for (Feedback_Response__c response : responses) {
            Feedback_Request__c request = requestsMap.get(response.Feedback_Request__c);
            request = request == null ? new Feedback_Request__c() : request;
            Decimal teamMemberExperience = response.Member_Experience__c;
            String feedbackText = response.Feedback__c;
            String commentText = response.Comments__c;

            for (Integer i = 1; i <= ScheduledViewingFeedbackEmailSending.MAXIMUM_VIEWINGS_IN_SESSION; i++) {
                Id propertyId = (Id) response.get('Property' + i + '__c');
                Id viewingId = (Id) request.get('Viewing' + i + '_Id__c');
                String propertyQuality = (String) response.get('Property' + i + '_Quality__c');

                if (propertyId != null && propertyQuality != null && viewingId != null) {
                    Customer_Feedback__c customerFeedback = CustomerFeedbackService.createCustomerFeedback(propertyId, propertyQuality, viewingId, teamMemberExperience, request.Contact__c, request.Lead__c);
                    customerFeedback.Name = propertiesMap.get(propertyId).Name + '-' + (request.Contact__c != null ? request.Contact__r.Name : request.Lead__r.Name);
                    customerFeedback.Comment__c = commentText;
                    customerFeedback.Feedback__c = feedbackText;
                    // add opportunity
                    Id potentialOpportunityId = viewingsMap.get(viewingId).WhatId;
                    if (opportunitiesIds.contains(potentialOpportunityId)) {
                        customerFeedback.Opportunity__c = potentialOpportunityId;
                    }
                    feedbacks.add(customerFeedback);
                } else {
                    break;//no more viewings
                }
            }
        }

        insert feedbacks;
    }

    public static Customer_Feedback__c createCustomerFeedback(Id propertyId, String quality, Id viewingId, Decimal teamMemberExperience, Id contactId, Id leadId) {
        Customer_Feedback__c customerFeedback = new Customer_Feedback__c(
                Property_Quality__c = quality,
                Property__c = propertyId,
                Member_Experience__c = teamMemberExperience,
                Contact__c = contactId,
                Lead__c = leadId,
                Viewing_Id__c = viewingId
        );
        return customerFeedback;
    }
}