src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Quote from which this Contract was created.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Activated</fullName>
        <active>true</active>
        <label>Activated</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contract_Activated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contract Activated</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Conventional</fullName>
        <active>true</active>
        <businessProcess>Conventional Sales Process</businessProcess>
        <label>Conventional</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <recordTypes>
        <fullName>Conventional</fullName>
        <active>true</active>
        <label>Conventional</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ContractTriggerHandlerTest.cls
@IsTest
public with sharing class ContractTriggerHandlerTest {

    @IsTest
    public static void givenContractWhenInsertOrUpdateThenRTIsSet() {
        Contract contract = RecordDmlTest.createContract();

        contract = [SELECT Id, RecordTypeId, Status FROM Contract WHERE Id = :contract.Id];
        System.assertEquals(contract.RecordTypeId, RecordTypeHelper.getRtIdByDeveloperName(ContractTriggerHandler.CONTRACT_API_NAME, ContractTriggerHandler.NOT_ACTIVATED_RT_DEV_NAME));

        contract.Status = 'Live';
        update contract;

        contract = [SELECT Id, RecordTypeId, Status FROM Contract WHERE Id = :contract.Id];
        System.assertEquals(contract.RecordTypeId, RecordTypeHelper.getRtIdByDeveloperName(ContractTriggerHandler.CONTRACT_API_NAME, ContractTriggerHandler.ACTIVATED_RT_DEV_NAME));

        contract.Status = 'Draft';
        update contract;

        contract = [SELECT Id, RecordTypeId, Status FROM Contract WHERE Id = :contract.Id];
        System.assertEquals(contract.RecordTypeId, RecordTypeHelper.getRtIdByDeveloperName(ContractTriggerHandler.CONTRACT_API_NAME, ContractTriggerHandler.NOT_ACTIVATED_RT_DEV_NAME));

        contract.Status = 'Activated';
        update contract;

        contract = [SELECT Id, RecordTypeId, Status FROM Contract WHERE Id = :contract.Id];
        System.assertEquals(contract.RecordTypeId, RecordTypeHelper.getRtIdByDeveloperName(ContractTriggerHandler.CONTRACT_API_NAME, ContractTriggerHandler.ACTIVATED_RT_DEV_NAME));

    }

    @IsTest
    public static void givenContractWhenActivatedThenRelatedOpportunityContractActiveFieldIsSet() {
        SBQQ.TriggerControl.disable();

        Property__c property = RecordDmlTest.createProperty();
        Opportunity opportunity = RecordDmlTest.createOpportunity('Conventional');
        SBQQ__Quote__c quote = RecordDmlTest.createQuote(property, opportunity, 'Conventional');

        Contract contract = RecordDmlTest.createContract();
        contract.SBQQ__Quote__c=quote.Id;

        contract.Status = 'Activated';
        update contract;

        System.assert([SELECT Contract_Activated__c FROM Opportunity WHERE Id = :opportunity.Id].Contract_Activated__c);
    }
}