src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Event.object
<CustomObject>
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <label>Event</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Briefing_Statement__c</fullName>
        <description>Additional information to the property management team.</description>
        <inlineHelpText>Additional information to the property management team.</inlineHelpText>
        <label>Briefing Statement</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Lead_Channel</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Compliance_Check_Complete__c</fullName>
        <label>Compliance Check Complete</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No_Value_Set</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deposit_Paid__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Use this field to indicate that the deposit has been paid by the customer</description>
        <inlineHelpText>Use this field to indicate that the deposit has been paid by the customer</inlineHelpText>
        <label>Deposit Paid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Event_ID__c</fullName>
        <label>Last Event ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Region</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Source__c</fullName>
        <label>Sub Source</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>LeadSource</controllingField>
            <restricted>true</restricted>
            <valueSetName>Sub_Source</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Conventional</fullName>
        <active>true</active>
        <businessProcess>Conventional Sales Process</businessProcess>
        <label>Conventional</label>
    </recordTypes>
    <recordTypes>
        <fullName>Virtual</fullName>
        <active>true</active>
        <businessProcess>Virtual Sales Process</businessProcess>
        <label>Virtual</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Pricebook2.object
<CustomObject>
    <recordTypes>
        <fullName>Conventional</fullName>
        <active>true</active>
        <label>Conventional</label>
    </recordTypes>
    <recordTypes>
        <fullName>Virtual</fullName>
        <active>true</active>
        <label>Virtual</label>
    </recordTypes>
    <sharingModel>ReadSelect</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Region</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Serviced_Space_Coordinator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Serviced Space Coordinator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Properties4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <recordTypes>
        <fullName>Conventional</fullName>
        <active>true</active>
        <label>Conventional</label>
    </recordTypes>
    <recordTypes>
        <fullName>Virtual</fullName>
        <active>true</active>
        <label>Virtual</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__QuoteDocument__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteDocumentHelp</customHelpPage>
    <description>Particular version of a generated PDF document for the quote it&apos;s attached to. Ability to edit or delete this object should be taken away from all users (except administrators, of course) in order to preserve audit trail of all revisions.</description>
    <fields>
        <fullName>Quote_Record_Type__c</fullName>
        <formula>SBQQ__Quote__r.RecordType.DeveloperName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Quote Record Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__ElectronicSignature__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates this document was generated for electronic signature.</description>
        <inlineHelpText>Field for the document to be signed electronically.</inlineHelpText>
        <label>Electronic Signature</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Opportunity that parents the Quote for this document. References the opportunity on the quote for this document, allowing the Opportunity Quote Documents Related List to reside on the Opportunity as well as the Quote.</description>
        <inlineHelpText>Choose the Opportunity that parents the Quote for this document.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quote Documents</relationshipLabel>
        <relationshipName>R00N700000029COgEAM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this Quote Document belongs.</description>
        <inlineHelpText>Quote to which this Quote Document belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Documents</relationshipLabel>
        <relationshipName>R00N70000001lX7YEAU</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Signature_Status__c</fullName>
        <description>Status of electronic signature.</description>
        <inlineHelpText>Status of electronic signature.</inlineHelpText>
        <label>Signature Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>Signed</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Correct</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Voided</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/OpportunityTriggerHandlerTest.cls
/**
 * Created by v2.nareyko on 19.1.18.
 */
@IsTest
private class OpportunityTriggerHandlerTest {
    private static final String TEST_DESCRIPTION = 'lorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem';

    @IsTest
    static void createTaskForCoordinator_Completed_Test() {
        Property__c testProperty = RecordDmlTest.createProperty();
        testProperty.Serviced_Space_Coordinator__c = UserInfo.getUserId();
        update testProperty;

        Opportunity testOpportunity = RecordDmlTest.createOpportunity(OpportunityService.VIRTUAL_RECORD_TYPE_NAME);
        SBQQ__Quote__c testQuote = RecordDmlTest.createQuote(testProperty, testOpportunity, 'Virtual');
        testOpportunity = [SELECT Id, StageName FROM Opportunity WHERE Id=: testOpportunity.Id];
        System.assertEquals(OpportunityService.STATUS_QUALIFIED, testOpportunity.StageName, 'Initial Opportunity.StageName: ' + OpportunityService.STATUS_QUALIFIED);

        Integer totalTasks = [SELECT COUNT() FROM Task];
        System.assertEquals(0, totalTasks);

        Test.startTest();
        testOpportunity.Deposit_Paid__c = true;
        testOpportunity.Briefing_Statement__c = TEST_DESCRIPTION;
        testOpportunity.StageName = OpportunityService.STATUS_TERMS_AGREED;
        testOpportunity.Compliance_Check_Complete__c = 'Yes';
        update testOpportunity;
        totalTasks = [SELECT COUNT() FROM Task];
        System.assertEquals(0, totalTasks, 'Tasks should not be created for Virtual Opportunity');

        testOpportunity.StageName = OpportunityService.STATUS_COMPLETED;
        update testOpportunity;
        Test.stopTest();

        List<Task> tasks = [SELECT Id, OwnerId, Description, Subject, Type, Property__c, Status, Priority FROM Task];
        System.assertEquals(1, tasks.size(), 'New Tasks should be created for Completed Virtual Opportunity');
        System.assertEquals(TaskService.TYPE_VIRTUAL_ONBOARDING, tasks.get(0).Type, 'Task type should be: ' + TaskService.TYPE_VIRTUAL_ONBOARDING);
        System.assertEquals(TaskService.STATUS_OPEN, tasks.get(0).Status, 'Task status should be: ' + TaskService.STATUS_OPEN);
        System.assertEquals(TEST_DESCRIPTION, tasks.get(0).Description, 'Task Description should be: ' + TEST_DESCRIPTION);
        System.assertEquals(testProperty.Id, tasks.get(0).Property__c);
        System.assertEquals(UserInfo.getUserId(), tasks.get(0).OwnerId);
    }

    @IsTest
    static void createTaskForCoordinator_MeetingBooked_Test() {
        Contact theContact = RecordDmlTest.createContact();
        Property__c testProperty = RecordDmlTest.createProperty();
        testProperty.Serviced_Space_Coordinator__c = UserInfo.getUserId();
        update testProperty;

        Opportunity testOpportunity = RecordDmlTest.createOpportunity(OpportunityService.VIRTUAL_RECORD_TYPE_NAME);
        Event theEvent = RecordDmlTest.createEvent();
        theEvent.Property__c = testProperty.Id;
        theEvent.WhoId = theContact.Id;
        update theEvent;
        testOpportunity = [SELECT Id, StageName FROM Opportunity WHERE Id=: testOpportunity.Id];
        System.assertEquals(OpportunityService.STATUS_QUALIFIED, testOpportunity.StageName, 'Initial Opportunity.StageName: ' + OpportunityService.STATUS_QUALIFIED);

        Integer totalTasks = [SELECT COUNT() FROM Task];
        System.assertEquals(0, totalTasks);

        Test.startTest();
        testOpportunity.Briefing_Statement__c = TEST_DESCRIPTION;
        testOpportunity.StageName = OpportunityService.STATUS_TERMS_AGREED;
        testOpportunity.Compliance_Check_Complete__c = 'Yes';
        testOpportunity.Last_Event_ID__c = theEvent.Id;
        update testOpportunity;
        totalTasks = [SELECT COUNT() FROM Task];
        System.assertEquals(0, totalTasks, 'Tasks should not be created for Virtual Opportunity');

        testOpportunity.StageName = OpportunityService.STATUS_MEETING_BOOKED;
        update testOpportunity;
        Test.stopTest();

        List<Task> tasks = [SELECT Id, OwnerId, Description, Subject, Type, Property__c, Status, Priority, WhoId FROM Task];
        System.assertEquals(1, tasks.size(), 'New Tasks should be created for Completed Virtual Opportunity');
        System.assertEquals(TaskService.SUBJECT_VIRTUAL_CUSTOMER_ID, tasks.get(0).Subject, 'Task Subject should be: ' + TaskService.SUBJECT_VIRTUAL_CUSTOMER_ID);
        System.assertEquals(TaskService.STATUS_OPEN, tasks.get(0).Status, 'Task status should be: ' + TaskService.STATUS_OPEN);
        System.assertEquals(testProperty.Id, tasks.get(0).Property__c);
        System.assertEquals(UserInfo.getUserId(), tasks.get(0).OwnerId);
        System.assertEquals(theContact.Id, tasks.get(0).WhoId);
    }

    @IsTest
    static void singleOpportunityInsertTest() {
        //Given
        Opportunity opportunity = generateOpportunities(1).get(0);

        //When
        insert opportunity;
        List<RecordType> pricebookRecordType = [
                SELECT Id
                FROM RecordType
                WHERE DeveloperName = 'Virtual'
                AND SobjectType = 'Pricebook2'
        ];
        List<Pricebook2> pricebooks = [
                SELECT Id
                FROM Pricebook2
                WHERE IsActive = TRUE
                AND RecordTypeId = :pricebookRecordType.get(0).Id
        ];

        //Then
        if(pricebooks.size() > 0) {
            System.assertEquals(pricebooks.get(0).Id, opportunity.Pricebook2Id);
        } else {
            System.assertEquals(null, opportunity.Pricebook2Id);
        }
    }

    @IsTest
    static void manyOpportunityInsertTest() {
        //Given
        List<Opportunity> opportunities = generateOpportunities(100);

        //When
        insert opportunities;
        List<Pricebook2> pricebooks = [SELECT Id FROM Pricebook2 WHERE RecordType.DeveloperName = 'Virtual'];

        //Then
        if(pricebooks.size() > 0 && pricebooks.size() == 1) {
            for(Opportunity opportunity: opportunities) {
                System.assertEquals(pricebooks.get(0).Id, opportunity.Pricebook2Id);
            }
        }
    }

    @IsTest
    private static void testConventionalOpportunityStatusCalculation() {
        //given
        Property__c testProperty = RecordDmlTest.createProperty();
        Opportunity testOpportunity = RecordDmlTest.createOpportunity(OpportunityService.CONVENTIONAL_RECORD_TYPE);
        SBQQ__Quote__c testQuote = RecordDmlTest.createQuote(testProperty, testOpportunity, 'Conventional');
        SBQQ__QuoteDocument__c quoteDocument = new SBQQ__QuoteDocument__c(
            SBQQ__Quote__c = testQuote.Id,
            SBQQ__ElectronicSignature__c = true
        );
        insert quoteDocument;
        quoteDocument = [SELECT SBQQ__ElectronicSignature__c, SBQQ__Opportunity__c, Quote_Record_Type__c, Signature_Status__c FROM SBQQ__QuoteDocument__c WHERE Id = :quoteDocument.Id];
        SBQQ_QuoteDocumentService theDocumentService = new SBQQ_QuoteDocumentService();
        Test.startTest();
        testOpportunity = [SELECT StageName FROM Opportunity WHERE Id = :testOpportunity.Id];
        System.assertEquals('Qualified', testOpportunity.StageName);
        quoteDocument.Signature_Status__c = 'Sent';
        theDocumentService.updateParentOpportunities(new List<SBQQ__QuoteDocument__c>{quoteDocument});
        testOpportunity = [SELECT StageName FROM Opportunity WHERE Id = :testOpportunity.Id];
        System.assertEquals('Terms Out', testOpportunity.StageName);
        quoteDocument.Signature_Status__c = 'Completed';
        theDocumentService.updateParentOpportunities(new List<SBQQ__QuoteDocument__c>{quoteDocument});
        testOpportunity = [SELECT StageName FROM Opportunity WHERE Id = :testOpportunity.Id];
        System.assertEquals('Instructed', testOpportunity.StageName);
        Test.stopTest();
    }

    @IsTest
    private static void testVirtualOpportunityStatusCalculation() {
        //given
        Property__c testProperty = RecordDmlTest.createProperty();
        Opportunity testOpportunity = RecordDmlTest.createOpportunity(OpportunityService.VIRTUAL_RECORD_TYPE_NAME);
        SBQQ__Quote__c testQuote = RecordDmlTest.createQuote(testProperty, testOpportunity, 'Virtual');
        SBQQ__QuoteDocument__c quoteDocument = new SBQQ__QuoteDocument__c(
            SBQQ__Quote__c = testQuote.Id,
            SBQQ__ElectronicSignature__c = true
        );
        insert quoteDocument;
        quoteDocument = [SELECT SBQQ__ElectronicSignature__c, SBQQ__Opportunity__c, Quote_Record_Type__c, Signature_Status__c FROM SBQQ__QuoteDocument__c WHERE Id = :quoteDocument.Id];
        SBQQ_QuoteDocumentService theDocumentService = new SBQQ_QuoteDocumentService();
        Test.startTest();
        testOpportunity = [SELECT StageName FROM Opportunity WHERE Id = :testOpportunity.Id];
        System.assertEquals('Qualified', testOpportunity.StageName);
        testOpportunity.Briefing_Statement__c = 'Test';
        testOpportunity.Compliance_Check_Complete__c = 'Yes';
        update testOpportunity;
        testOpportunity = [SELECT StageName FROM Opportunity WHERE Id = :testOpportunity.Id];
        System.assertEquals('Check Complete', testOpportunity.StageName);
        quoteDocument.Signature_Status__c = 'Completed';
        theDocumentService.updateParentOpportunities(new List<SBQQ__QuoteDocument__c>{quoteDocument});
        testOpportunity = [SELECT StageName FROM Opportunity WHERE Id = :testOpportunity.Id];
        System.assertEquals('Terms Agreed', testOpportunity.StageName);
        testOpportunity.Deposit_Paid__c = true;
        update testOpportunity;
        testOpportunity = [SELECT StageName FROM Opportunity WHERE Id = :testOpportunity.Id];
        System.assertEquals('Completed', testOpportunity.StageName);
        Test.stopTest();
    }

    private static List<Opportunity> generateOpportunities(Integer n) {
        List<Opportunity> result = new List<Opportunity>();
        Property__c property = new Property__c();
        property.Name = 'AssignPriceBookOnOpportunityTriggerTest';
        property.Active__c = true;
        property.Region__c = 'Leeds';
        property.Street__c = 'yl. Pupkina, d. 228';
        insert property;

        RecordType recordType = [SELECT Id, DeveloperName FROM RecordType
        WHERE DeveloperName = 'Virtual'
        AND IsActive = TRUE
        AND SobjectType = 'Opportunity'];

        while (n-- != 0) {
            Opportunity opportunity = new Opportunity();
            opportunity.Name = 'Assign PriceBook to Opportunity test ' + n;
            opportunity.StageName = 'Qualified';
            opportunity.Type = 'New Customer';
            opportunity.CloseDate = Date.valueOf('2020-01-01');
            opportunity.Region__c = 'Leeds';
            opportunity.LeadSource = 'Advertisement';
            opportunity.Sub_Source__c = 'Building Signage';
            opportunity.Channel__c = 'Email';
            opportunity.RecordTypeId = recordType.Id;
            opportunity.RecordType = recordType;
            result.add(opportunity);
        }
        return result;
    }
}