src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>Text( Property__r.Region__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Quote from which this Contract was created.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Inventory__c.object
<CustomObject>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Inventories</relationshipLabel>
        <relationshipName>Inventories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipName>Suites</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>Used for list views, should be kept off report types and page layouts to where the property region is used to avoid confusion</description>
        <formula>Text(Property__r.Region__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Status__c</fullName>
        <label>Sales Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                </value>
                <value>
                    <fullName>Terms Out</fullName>
                </value>
                <value>
                    <fullName>Reserved</fullName>
                </value>
                <value>
                    <fullName>Not Available</fullName>
                </value>
                <value>
                    <fullName>Not for Sale</fullName>
                </value>
                <value>
                    <fullName>Instructed</fullName>
                    <isActive>false</isActive>
                    <label>Instructed</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Inventory</label>
    <nameField>
        <label>Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Region</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Quotes (Contract)</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory</label>
        <referenceTo>Inventory__c</referenceTo>
        <relationshipName>Inventory</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <recordTypes>
        <fullName>Serviced</fullName>
        <active>true</active>
        <label>Serviced</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__QuoteDocument__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteDocumentHelp</customHelpPage>
    <description>Particular version of a generated PDF document for the quote it&apos;s attached to. Ability to edit or delete this object should be taken away from all users (except administrators, of course) in order to preserve audit trail of all revisions.</description>
    <fields>
        <fullName>SBQQ__QuoteTemplate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote Template that generated this document.</description>
        <inlineHelpText>Quote Template that generated this document.</inlineHelpText>
        <label>Quote Template</label>
        <referenceTo>SBQQ__QuoteTemplate__c</referenceTo>
        <relationshipLabel>Quote Documents</relationshipLabel>
        <relationshipName>Quote_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this Quote Document belongs.</description>
        <inlineHelpText>Quote to which this Quote Document belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Documents</relationshipLabel>
        <relationshipName>R00N70000001lX7YEAU</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SBQQ__Version__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Sequentially incremented version number.</description>
        <inlineHelpText>Sequentially incremented version number.</inlineHelpText>
        <label>Version</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Update_Quote_Status__c</fullName>
        <formula>SBQQ__QuoteTemplate__r.Update_Quote_Status__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Update Quote Status</label>
        <type>Checkbox</type>
    </fields>
    <label>Quote Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SBQQ__QuoteTemplate__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteTemplateHelp</customHelpPage>
    <description>Template that controls formatting of generated PDF documents.</description>
    <fields>
        <fullName>SBQQ__BorderColor__c</fullName>
        <defaultValue>&quot;000000&quot;</defaultValue>
        <description>Color of table borders expressed as a hexadecimal value.</description>
        <inlineHelpText>Color of table borders expressed as a hexadecimal value.</inlineHelpText>
        <label>Border Color</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__BottomMargin__c</fullName>
        <defaultValue>0.5</defaultValue>
        <description>Bottom margin on the page.</description>
        <inlineHelpText>Bottom margin on the page.</inlineHelpText>
        <label>Bottom Margin</label>
        <precision>6</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__DeploymentStatus__c</fullName>
        <description>Deployment status of this template. &quot;In Development&quot; templates are only visible to users with Customize Application permission.</description>
        <inlineHelpText>Deployment status of this template. Change to &quot;Deployed&quot; to make this template visible to non-admin users.</inlineHelpText>
        <label>Deployment Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Development</fullName>
                    <default>true</default>
                    <label>In Development</label>
                </value>
                <value>
                    <fullName>Deployed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__FontFamily__c</fullName>
        <description>Family of the font that should be applied to text in this template.</description>
        <inlineHelpText>Family of the font that should be applied to text in this template.</inlineHelpText>
        <label>Font Family</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Courier</fullName>
                </value>
                <value>
                    <fullName>Dosis</fullName>
                </value>
                <value>
                    <fullName>Droid Sans</fullName>
                </value>
                <value>
                    <fullName>Droid Serif</fullName>
                </value>
                <value>
                    <fullName>Helvetica</fullName>
                    <default>true</default>
                    <label>Helvetica</label>
                </value>
                <value>
                    <fullName>Merriweather</fullName>
                </value>
                <value>
                    <fullName>Montserrat</fullName>
                </value>
                <value>
                    <fullName>Noto Sans JP</fullName>
                </value>
                <value>
                    <fullName>Noto Sans KR</fullName>
                </value>
                <value>
                    <fullName>Noto Sans SC</fullName>
                </value>
                <value>
                    <fullName>Noto Sans TC</fullName>
                </value>
                <value>
                    <fullName>Open Sans</fullName>
                </value>
                <value>
                    <fullName>PT Sans</fullName>
                </value>
                <value>
                    <fullName>PT Serif</fullName>
                </value>
                <value>
                    <fullName>Roboto</fullName>
                </value>
                <value>
                    <fullName>Roboto Light</fullName>
                </value>
                <value>
                    <fullName>Times</fullName>
                </value>
                <value>
                    <fullName>Titillium Web</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__FontSize__c</fullName>
        <defaultValue>9</defaultValue>
        <description>Default font size for text in this quote document.</description>
        <inlineHelpText>Default font size for text in this quote document.</inlineHelpText>
        <label>Font Size</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__LeftMargin__c</fullName>
        <defaultValue>0.5</defaultValue>
        <description>Left margin on the page.</description>
        <inlineHelpText>Left margin on the page.</inlineHelpText>
        <label>Left Margin</label>
        <precision>6</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__PageHeight__c</fullName>
        <defaultValue>11</defaultValue>
        <description>Page height in inches.</description>
        <inlineHelpText>Page height in inches.</inlineHelpText>
        <label>Page Height</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__PageWidth__c</fullName>
        <defaultValue>8.5</defaultValue>
        <description>Page width in inches.</description>
        <inlineHelpText>Page width in inches.</inlineHelpText>
        <label>Page Width</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__RightMargin__c</fullName>
        <defaultValue>0.5</defaultValue>
        <description>Right margin on the page.</description>
        <inlineHelpText>Right margin setting on the page.</inlineHelpText>
        <label>Right Margin</label>
        <precision>6</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__ShadingColor__c</fullName>
        <defaultValue>&quot;FFFFFF&quot;</defaultValue>
        <description>Color of shading in column headers expressed as a hexadecimal.</description>
        <inlineHelpText>Color of shading in column headers expressed as a hexadecimal.</inlineHelpText>
        <label>Shading Color</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__TopMargin__c</fullName>
        <defaultValue>0.5</defaultValue>
        <description>Top margin on the page.</description>
        <inlineHelpText>Top margin on the page.</inlineHelpText>
        <label>Top Margin</label>
        <precision>6</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Update_Quote_Status__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If you use the template for signature, please will select the field. Because quote status should be updated after signature.
If you use the template for review, please will not select the field. Because quote status should not be updated after review.</description>
        <inlineHelpText>Whether quote status should be updated when the document completed in DocuSign?</inlineHelpText>
        <label>Update Quote Status</label>
        <type>Checkbox</type>
    </fields>
    <label>Quote Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AttachmentTriggerHandlerTest.cls
@IsTest
private class AttachmentTriggerHandlerTest {

    @testSetup
    public static void initData() {
        Property__c property = new Property__c(Name = 'Test property', Region__c = 'Manchester City Centre',
                Street__c = 'Test');
        insert property;

        Inventory__c inventory = new Inventory__c(Name = 'Test', Property__c = property.Id, Sales_Status__c = 'Available');
        insert inventory;

        SBQQ__Quote__c quote = RecordDmlTest.createCPQQuote();

        Contract contract = RecordDmlTest.createContract(quote, property);

        quote.Contract__c = contract.Id;
        quote.RecordTypeId = Schema.SObjectType.SBQQ__Quote__c.getRecordTypeInfosByName().get('Serviced').getRecordTypeId();
        update quote;

        SBQQ__QuoteTemplate__c quoteTemplate = new SBQQ__QuoteTemplate__c(Name = 'Test Template', SBQQ__DeploymentStatus__c = 'In Development',
                CurrencyIsoCode = 'GBP', SBQQ__PageWidth__c = 8.50, SBQQ__PageHeight__c = 11.00, SBQQ__TopMargin__c = 0.50,
                SBQQ__BottomMargin__c = 0.50, SBQQ__LeftMargin__c = 0.50, SBQQ__RightMargin__c = 0.50,
                SBQQ__FontFamily__c = 'Helvetica', SBQQ__FontSize__c = 9.0, SBQQ__ShadingColor__c = 'FFFFFF',
                SBQQ__BorderColor__c = '000000', Update_Quote_Status__c = true);
        insert quoteTemplate;

        SBQQ__QuoteDocument__c quoteDocument = new SBQQ__QuoteDocument__c(Name = 'Test Quote Document', SBQQ__Quote__c = quote.Id,
                SBQQ__Version__c = 1, CurrencyIsoCode = 'GBP', SBQQ__SignatureStatus__c = 'Completed', SBQQ__QuoteTemplate__c = quoteTemplate.Id);
        insert quoteDocument;

        Blob bodyBlob = Blob.valueOf('Test Attachment Body');

        Attachment attachment = new Attachment(Name = 'Unit Test Attachment', Body = bodyBlob, ParentId = quoteDocument.Id);
        insert attachment;
    }

    @isTest
    public static void checkAttachmentOnContract() {
        Contract entityContract = [SELECT Id FROM Contract LIMIT 1];
        List<Attachment> entityAttachments = [SELECT Id, Name FROM Attachment WHERE ParentId = :entityContract.Id];
        System.assertEquals(1, entityAttachments.size());
    }
}