src/objects/CustomerInactivitySettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Customer Inactivity Settings</label>
</CustomObject>

src/objects/Pricebook2.object
<CustomObject>
    <recordTypes>
        <fullName>Conventional</fullName>
        <active>true</active>
        <label>Conventional</label>
    </recordTypes>
    <recordTypes>
        <fullName>Serviced</fullName>
        <active>true</active>
        <label>Serviced</label>
    </recordTypes>
    <recordTypes>
        <fullName>Virtual</fullName>
        <active>true</active>
        <label>Virtual</label>
    </recordTypes>
    <sharingModel>ReadSelect</sharingModel>
</CustomObject>

src/objects/SBQQ__ConfigurationAttribute__c.object
<CustomObject>
    <customHelpPage>SBQQ__ConfigurationAttributeHelp</customHelpPage>
    <description>Product configuration attribute.</description>
    <fields>
        <fullName>SBQQ__ApplyToProductOptions__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Apply configuration attribute selection to product options.</description>
        <inlineHelpText>Select the checkbox to apply configuration attribute selection to product options.</inlineHelpText>
        <label>Apply To Product Options</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__ColumnOrder__c</fullName>
        <description>Columns are comprised of a picklist (of 1, 2, or 3) for each Configuration Attribute. A maximum of 3 columns is allowed.</description>
        <inlineHelpText>Columns are comprised of a picklist (of 1, 2, or 3) for each Configuration Attribute. A maximum of 3 columns is allowed.</inlineHelpText>
        <label>Column Order</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <default>true</default>
                    <label>1</label>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__DefaultField__c</fullName>
        <description>API of the target field on the default object for the default value of the attribute.</description>
        <inlineHelpText>API of the target field on the default object for the default value of the attribute.</inlineHelpText>
        <label>Default Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__DefaultObject__c</fullName>
        <description>Target object for the default value of the attribute.</description>
        <inlineHelpText>Target object for the default value of the attribute.</inlineHelpText>
        <label>Default Object</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Quote__c</fullName>
                    <label>Quote</label>
                </value>
                <value>
                    <fullName>QuoteLineGroup__c</fullName>
                    <label>Quote Line Group</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product being configured.</description>
        <inlineHelpText>Specify product on which you are creating the attribute.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Configuration Attributes</relationshipLabel>
        <relationshipName>ConfigurationAttributes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__TargetField__c</fullName>
        <description>Field on the Product Option that sources remaining metadata and holds the value.</description>
        <inlineHelpText>Specify field on Product Option that will hold this attribute&apos;s value.</inlineHelpText>
        <label>Target Field</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bundle_Code__c</fullName>
                </value>
                <value>
                    <fullName>Car_Parking_Inventory__c</fullName>
                </value>
                <value>
                    <fullName>Date__c</fullName>
                </value>
                <value>
                    <fullName>Deposit_Payment_Total__c</fullName>
                </value>
                <value>
                    <fullName>Deposit_Q_L__c</fullName>
                </value>
                <value>
                    <fullName>Discount_Amount__c</fullName>
                </value>
                <value>
                    <fullName>Discount_Amount_Total__c</fullName>
                </value>
                <value>
                    <fullName>Discount_Percent__c</fullName>
                </value>
                <value>
                    <fullName>Discount (%)</fullName>
                </value>
                <value>
                    <fullName>Discount (Amt)</fullName>
                </value>
                <value>
                    <fullName>Headline_Item_Subscription_Term__c</fullName>
                </value>
                <value>
                    <fullName>Indicative_Start_Date__c</fullName>
                </value>
                <value>
                    <fullName>Inventory__c</fullName>
                </value>
                <value>
                    <fullName>Lease_Start_Date__c</fullName>
                </value>
                <value>
                    <fullName>Licence_Start_Date__c</fullName>
                </value>
                <value>
                    <fullName>Monthly_Cost__c</fullName>
                </value>
                <value>
                    <fullName>Net_Subtotal__c</fullName>
                </value>
                <value>
                    <fullName>Net_Total__c</fullName>
                </value>
                <value>
                    <fullName>Product_for_Filter__c</fullName>
                </value>
                <value>
                    <fullName>Property__c</fullName>
                </value>
                <value>
                    <fullName>Property_for_Filter__c</fullName>
                </value>
                <value>
                    <fullName>Quanta__c</fullName>
                </value>
                <value>
                    <fullName>Quote_Record_Type__c</fullName>
                </value>
                <value>
                    <fullName>Quote_Type__c</fullName>
                </value>
                <value>
                    <fullName>SBQQ__Quantity__c</fullName>
                </value>
                <value>
                    <fullName>Start_Date__c</fullName>
                </value>
                <value>
                    <fullName>Status__c</fullName>
                </value>
                <value>
                    <fullName>Suite_Inventory__c</fullName>
                </value>
                <value>
                    <fullName>Term__c</fullName>
                </value>
                <value>
                    <fullName>Tolerance_State__c</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Configuration Attribute</label>
    <nameField>
        <label>Attribute Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Attributes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PostDeploySetupTest.cls
@isTest
public class PostDeploySetupTest {
    @isTest
    static void whenPostDeployThenConfigCreated() {
        //when
        PostDeploySetup.setup();

        //then
        System.assertEquals(1, [SELECT Id FROM CronTrigger WHERE CronJobDetail.Name = :PostDeploySetup.CUSTOMER_INACTIVITY_SCHEDULED_JOB_NAME].size());
        System.assertEquals(1, [SELECT Id FROM CronTrigger WHERE CronJobDetail.Name = :PostDeploySetup.VIEWING_FEEDBACK_SCHEDULED_JOB_NAME].size());
        System.assertNotEquals(null, CustomerInactivitySettings__c.getInstance(CustomerInactivityScheduledHandler.INSTANCE_INACTIVITY_EXP_TIME));
        //System.assertEquals(1, [select id from CaseTeamRole where Name = :'Default'].size());
    }

    @isTest
    static void whenPostDeployCaseTeamThenTeamCreated() {
        //when
        PostDeploySetup.setupCaseTeam();

        //then
        System.assertEquals(1, [select id from CaseTeamTemplate where Name = :CaseTriggerHandler.LEASE_TRANSACTION_CASE_TEAM].size());
    }

    @isTest
    static void givenPriceBookswhenAssignTRToPBThenAssigned() {
        RecordDmlTest.createPricebook('Conventional Sales');
        RecordDmlTest.createPricebook('Serviced Sales');
        RecordDmlTest.createPricebook('Virtual Sales');

        //when
        PostDeploySetup.assignRTToPriceBooks();

        //then
        List<Pricebook2> pricebooks = [select Id, Name, RecordTypeId from Pricebook2 where isStandard = false];
        for (Pricebook2 pricebook : pricebooks) {
            System.assertNotEquals(null, pricebook.RecordTypeId);
            System.assert(pricebook.Name.contains(Schema.SObjectType.Pricebook2.getRecordTypeInfosById().get(pricebook.RecordTypeId).Name));
        }
    }

    @isTest
    static void whenCleanConfigurationAttributesFieldsThenFieldsEmpty() {
        Product2 product2 = RecordDmlTest.createProducts().get(0);
        SBQQ__ConfigurationAttribute__c ca = new SBQQ__ConfigurationAttribute__c(
                SBQQ__PRODUCT__C = product2.Id, 
                SBQQ__DEFAULTOBJECT__C = 'Quote__c', 
                SBQQ__DEFAULTFIELD__C = 'Headline_Item_Subscription_Term__c',
                SBQQ__COLUMNORDER__C='1',
                SBQQ__TargetField__c='Term__c',
                SBQQ__ApplyToProductOptions__c=false);

        insert ca;
        //when
        PostDeploySetup.cleanConfigurationAttributesFields();

        //then
        System.assertEquals(0, [select id from SBQQ__ConfigurationAttribute__c where SBQQ__DEFAULTOBJECT__C != null or SBQQ__DEFAULTFIELD__C != null].size());
    }
}