src/objects/CustomerInactivitySettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Inactivity_Expiration_Time__c</fullName>
        <defaultValue>180</defaultValue>
        <description>This expiration time (in days) means closing Opportunity with no any customer activity after this count of days.</description>
        <label>Inactivity Expiration Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Customer Inactivity Settings</label>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Closed_Lost_Date__c</fullName>
        <label>Closed Lost Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Closed_Lost_Reason__c</fullName>
        <label>Closed Lost Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Too expensive</fullName>
                </value>
                <value>
                    <fullName>Space too big</fullName>
                </value>
                <value>
                    <fullName>Space too small</fullName>
                </value>
                <value>
                    <fullName>Unsuitable location</fullName>
                </value>
                <value>
                    <fullName>Feasibility study</fullName>
                </value>
                <value>
                    <fullName>Went to competitor</fullName>
                </value>
                <value>
                    <fullName>Requirement retracted</fullName>
                </value>
                <value>
                    <fullName>Lack of car parking</fullName>
                </value>
                <value>
                    <fullName>Unsuitable specification</fullName>
                </value>
                <value>
                    <fullName>See Closed Lost Comments</fullName>
                </value>
                <value>
                    <fullName>Inactivity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Days_since_last_customer_activity__c</fullName>
        <formula>MAX( TODAY() - IF( LastActivityDate &gt;=  DATEVALUE( LastModifiedDate ) ,  LastActivityDate , DATEVALUE( LastModifiedDate )), 0 )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Days since last customer activity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CustomerInactivityScheduledHandler.cls
public without sharing class CustomerInactivityScheduledHandler implements Schedulable {

    public  static final String INSTANCE_INACTIVITY_EXP_TIME = 'INACTIVITY_EXPIRATION_TIME';
    private static final Integer BATCH_SIZE = 50;
    private static final String QUERY_PATTERN = 'SELECT Id, ' +
            'Closed_Lost_Reason__c, StageName, ' +
            'Closed_Lost_Date__c, ' +
            'LastActivityDate, ' +
            'LastModifiedDate, ' +
            'CloseDate FROM Opportunity ' +
            'WHERE StageName NOT IN (\'Closed Lost\', \'Completed\') ' +
            'AND Days_since_last_customer_activity__c >= ';

    public void execute(SchedulableContext sc) {
        Decimal inactivityExpTime = CustomerInactivitySettings__c.getInstance(
                INSTANCE_INACTIVITY_EXP_TIME).Inactivity_Expiration_Time__c;

        String QUERY = QUERY_PATTERN + String.valueOf(inactivityExpTime);

        CustomerInactivityHandlerBatch batchCustomerInactivityHandler =
                new CustomerInactivityHandlerBatch(QUERY);

        Database.executeBatch(batchCustomerInactivityHandler, BATCH_SIZE);
    }
}