src/objects/Customer_Confidential_Documentation__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Confidential Documentations</relationshipLabel>
        <relationshipName>Customer_Confidential_Documentations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Bank_Building_Society_Account_Number__c</fullName>
        <label>Bank / Building Society Account Number</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Branch_Sort_Code__c</fullName>
        <label>Branch Sort Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Collections_File_Sequence_Number__c</fullName>
        <defaultValue>&quot;0N&quot;</defaultValue>
        <label>Collections File Sequence number</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0N</fullName>
                    <default>true</default>
                    <label>0N</label>
                </value>
                <value>
                    <fullName>0C</fullName>
                </value>
                <value>
                    <fullName>00</fullName>
                </value>
                <value>
                    <fullName>01</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DDF_Acc_Num_1__c</fullName>
        <label>DDF Acc Num 1</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DDF_Account_Name_1__c</fullName>
        <label>Account Name 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DDF_Account_Name_2__c</fullName>
        <label>Account Name 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DDF_Bank_Name__c</fullName>
        <label>Bank Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DDF_Branch_Sort_Code_6__c</fullName>
        <label>Branch Sort Code 6</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DDF_Reference__c</fullName>
        <label>Reference</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_Signed__c</fullName>
        <label>Date Signed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Legal_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Legal Entity</label>
        <referenceTo>c2g__codaCompany__c</referenceTo>
        <relationshipLabel>Customer Confidential Documentations</relationshipLabel>
        <relationshipName>Customer_Confidential_Documentations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Master__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Master</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Name_Of_Account_Holder__c</fullName>
        <label>Name(s) Of Account Holder(s)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name_and_Full_Postal_Address_Of_Bank__c</fullName>
        <label>Name and Full Postal Address Of Bank</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <label>Reference</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ_Quote_Document__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote Document</label>
        <referenceTo>SBQQ__QuoteDocument__c</referenceTo>
        <relationshipLabel>Customer Confidential Documentations</relationshipLabel>
        <relationshipName>Customer_Confidential_Documentations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Send_Customer_Acknowledgement_Letter__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send Customer Acknowledgement Letter</label>
        <type>Checkbox</type>
    </fields>
    <label>Customer Confidential Documentation</label>
    <nameField>
        <displayFormat>CCD-{00000000}</displayFormat>
        <label>CCD Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Confidential Documentations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>c2g__codaCompany__c</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>Properties</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
        <inlineHelpText>The customer account for this quote. Defaults to the account for the opportunity when creating a quote.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__QuoteDocument__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteDocumentHelp</customHelpPage>
    <description>Particular version of a generated PDF document for the quote it&apos;s attached to. Ability to edit or delete this object should be taken away from all users (except administrators, of course) in order to preserve audit trail of all revisions.</description>
    <fields>
        <fullName>Account_Id__c</fullName>
        <formula>SBQQ__Quote__r.SBQQ__Account__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DDF_Acc_Num_1__c</fullName>
        <label>Acc Num 1</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DDF_Account_Name_1__c</fullName>
        <label>Account Name 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DDF_Account_Name_2__c</fullName>
        <label>Account Name 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DDF_Bank_Name__c</fullName>
        <label>Bank Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DDF_Branch_Sort_Code_6__c</fullName>
        <label>Branch Sort Code 6</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DDF_City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DDF_Reference__c</fullName>
        <label>Reference</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this Quote Document belongs.</description>
        <inlineHelpText>Quote to which this Quote Document belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Documents</relationshipLabel>
        <relationshipName>R00N70000001lX7YEAU</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CustomerConfidentialDocumentationSrvTest.cls
/**
 * @description Test class for CustomerConfidentialDocumentationSrv
 */
@isTest
private class CustomerConfidentialDocumentationSrvTest {

    @testSetup
    public static void setupData() {
        //given
        Account testAccount = RecordDmlTest.createAccount();
        SBQQ__Quote__c quote = RecordDmlTest.generateConventionalQuoteWithLines(QuoteProductCodes.OFFICE_RENT);
        quote.SBQQ__Account__c = testAccount.Id;

        Test.startTest();
        SBQQ.TriggerControl.disable();
        update quote;
        SBQQ__QuoteDocument__c quoteDocument = new SBQQ__QuoteDocument__c(
                SBQQ__Quote__c = quote.Id
        );
        insert quoteDocument;
        quoteDocument = [
                SELECT Account_Id__c, SBQQ__Quote__r.Property__r.Company__c
                FROM SBQQ__QuoteDocument__c
                LIMIT 1
        ];
        Id legalEntity = quoteDocument.SBQQ__Quote__r.Property__r.Company__c;
        List<Customer_Confidential_Documentation__c> cdds = new List<Customer_Confidential_Documentation__c>();
        cdds.add(new Customer_Confidential_Documentation__c(
                Account__c = testAccount.Id,
                Legal_Entity__c = legalEntity,
                Collections_File_Sequence_Number__c = CustomerConfidentialDocumentationService.DEFAULT_VALUE_FOR_COLLECTIONS_FILE_SEQUENCE_NUMBER,
                Master__c = true
        ));
        cdds.add(new Customer_Confidential_Documentation__c(
                Account__c = testAccount.Id,
                Legal_Entity__c = legalEntity,
                Collections_File_Sequence_Number__c = CustomerConfidentialDocumentationService.DEFAULT_VALUE_FOR_COLLECTIONS_FILE_SEQUENCE_NUMBER
        ));
        insert cdds;
        Test.stopTest();
    }

    @isTest
    private static void testMoveDirectDebitFormFieldsToSecureObject() {
        SBQQ__QuoteDocument__c quoteDocument = [
                SELECT Account_Id__c, SBQQ__Quote__r.Property__r.Company__c
                FROM SBQQ__QuoteDocument__c
                LIMIT 1
        ];
        quoteDocument.DDF_Acc_Num_1__c = '1';
        quoteDocument.DDF_Branch_Sort_Code_6__c = '3';
        quoteDocument.DDF_Account_Name_1__c = 'Test';
        quoteDocument.DDF_Account_Name_2__c = 'Name';
        quoteDocument.DDF_Bank_Name__c = 'Bank';
        // quoteDocument.DDF_City__c = 'Manchester';
        quoteDocument.DDF_Reference__c = '12345';


        //when
        Test.startTest();
        CustomerConfidentialDocumentationService ccdService = new CustomerConfidentialDocumentationService();
        ccdService.moveDirectDebitFormFieldsToSecureObject(new List<SBQQ__QuoteDocument__c>{
                quoteDocument
        });
        Customer_Confidential_Documentation__c secureRecord = [
                SELECT Name_Of_Account_Holder__c, Bank_Building_Society_Account_Number__c, Branch_Sort_Code__c,
                        Name_and_Full_Postal_Address_Of_Bank__c, Reference__c, Date_Signed__c, Account__c,
                        Legal_Entity__c
                FROM Customer_Confidential_Documentation__c
                WHERE SBQQ_Quote_Document__c = :quoteDocument.Id
        ];
        System.assertNotEquals(null, secureRecord);
        System.assertNotEquals(null, secureRecord.Account__c);
        System.assertEquals('Test Name', secureRecord.Name_Of_Account_Holder__c);
        System.assertEquals('1', secureRecord.Bank_Building_Society_Account_Number__c);
        System.assertEquals('3', secureRecord.Branch_Sort_Code__c);
        System.assertEquals('Bank', secureRecord.Name_and_Full_Postal_Address_Of_Bank__c);
        System.assertEquals('12345', secureRecord.Reference__c);
        System.assertEquals(quoteDocument.SBQQ__Quote__r.Property__r.Company__c, secureRecord.Legal_Entity__c);
        Test.stopTest();
    }

    @IsTest
    private static void testCustomValidationCDD() {
        //when
        Test.startTest();
        try {
            Customer_Confidential_Documentation__c secureRecord = [
                    SELECT Id, Master__c
                    FROM Customer_Confidential_Documentation__c
                    WHERE Master__c = false
                    LIMIT 1
            ];
            secureRecord.Master__c = true;
            update secureRecord;
            System.assert(false, 'the exception was not thrown out');
        } catch (Exception e) {
            System.assertEquals(e.getMessage().contains(CustomerConfDocumentationTriggerHandler.ERROR_MSG_THERE_CAN_ONLY_BE_ONE_MASTER), true);
        }
        Test.stopTest();
    }

    @isTest
    private static void testAcknowledgementLetterGeneration() {
        SBQQ__QuoteDocument__c quoteDocument = [
            SELECT Account_Id__c, SBQQ__Quote__r.Property__r.Company__c
            FROM SBQQ__QuoteDocument__c
            LIMIT 1
        ];
        quoteDocument.DDF_Acc_Num_1__c = '1';
        quoteDocument.DDF_Branch_Sort_Code_6__c = '3';
        quoteDocument.DDF_Account_Name_1__c = 'Test';
        quoteDocument.DDF_Account_Name_2__c = 'Name';
        quoteDocument.DDF_Bank_Name__c = 'Bank';
        // quoteDocument.DDF_City__c = 'Manchester';
        quoteDocument.DDF_Reference__c = '12345';

        //when
        Test.startTest();
        new CustomerConfidentialDocumentationService().moveDirectDebitFormFieldsToSecureObject(new List<SBQQ__QuoteDocument__c>{
                quoteDocument
        });
        Customer_Confidential_Documentation__c secureRecord = [
                SELECT Name_Of_Account_Holder__c, Bank_Building_Society_Account_Number__c, Branch_Sort_Code__c,
                        Name_and_Full_Postal_Address_Of_Bank__c, Reference__c, Date_Signed__c, Account__c,
                        Legal_Entity__c
                FROM Customer_Confidential_Documentation__c
                WHERE SBQQ_Quote_Document__c = :quoteDocument.Id
        ];
        secureRecord.Send_Customer_Acknowledgement_Letter__c = true;
        update secureRecord;
        Test.stopTest();
        System.assertEquals(1, [SELECT COUNT() FROM Attachment WHERE ParentId =: secureRecord.Id]);
    }
}