src/objects/Inventory__c.object
<CustomObject>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipName>Suites</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Property_for_Filter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property for Filter</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Inventories (Property Lookup)</relationshipLabel>
        <relationshipName>Inventories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quanta__c</fullName>
        <label>Quanta</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Lab</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Office</fullName>
                </value>
                <value>
                    <fullName>Storage</fullName>
                </value>
                <value>
                    <fullName>SerLic</fullName>
                </value>
                <value>
                    <fullName>DedLic</fullName>
                </value>
                <value>
                    <fullName>DeskLic</fullName>
                </value>
                <value>
                    <fullName>CPL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rent_per_sq_ft_Annual__c</fullName>
        <formula>Rent_per_sq_ft__c * 12</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Rent per sq ft per annum</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Sales_Status__c</fullName>
        <label>Sales Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                </value>
                <value>
                    <fullName>Terms Out</fullName>
                </value>
                <value>
                    <fullName>Reserved</fullName>
                </value>
                <value>
                    <fullName>Not Available</fullName>
                </value>
                <value>
                    <fullName>Not for Sale</fullName>
                </value>
                <value>
                    <fullName>Instructed</fullName>
                    <isActive>false</isActive>
                    <label>Instructed</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Inventory</label>
    <nameField>
        <label>Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventories</pluralLabel>
    <recordTypes>
        <fullName>Actual_Suite</fullName>
        <active>true</active>
        <label>Actual Suite</label>
    </recordTypes>
    <recordTypes>
        <fullName>Car_Parking</fullName>
        <active>true</active>
        <label>Car Parking</label>
    </recordTypes>
    <recordTypes>
        <fullName>Desk</fullName>
        <active>true</active>
        <label>Desk</label>
    </recordTypes>
    <recordTypes>
        <fullName>Proposed_Suite</fullName>
        <active>true</active>
        <label>Proposed Suite</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>IsConcession__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Concession</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory</label>
        <referenceTo>Inventory__c</referenceTo>
        <relationshipName>Inventory</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rent_per_Sq_Ft_annual__c</fullName>
        <description>Rent per Sq. Ft. annual (£)</description>
        <label>Rent per Sq. Ft. annual (£)</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Term_Certain__c</fullName>
        <label>Term Certain</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <label>Term</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tolerance_State__c</fullName>
        <label>Tolerance State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Green</fullName>
                </value>
                <value>
                    <fullName>Yellow</fullName>
                </value>
                <value>
                    <fullName>Red</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>Half_Rent_Annualised_Amount__c</fullName>
        <formula>IF(
  AND (
    SBQQ__ProductCode__c == &apos;HalfRent&apos;,
    NOT(ISBLANK(SBQQ__RequiredBy__c)),
    NOT(ISBLANK(SBQQ__RequiredBy__r.Net_Total__c)),
    NOT(ISBLANK(SBQQ__RequiredBy__r.Term__c )),
    SBQQ__RequiredBy__r.Term__c &gt; 0
  ),
    ((SBQQ__RequiredBy__r.Net_Total__c / SBQQ__RequiredBy__r.Term__c) * 12 ) / 2,
    NULL
)</formula>
        <label>Half Rent Annualised Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Half_Rent_Annualised_text__c</fullName>
        <label>Half Rent Annualised Amount (Words)</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory</label>
        <referenceTo>Inventory__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>Quote_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsConcession__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Concession</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Quote Lines (Property)</relationshipLabel>
        <relationshipName>QuoteLines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property_for_Filter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property for Filter</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>Quote_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quanta__c</fullName>
        <label>Quanta</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Lab</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Office</fullName>
                </value>
                <value>
                    <fullName>Storage</fullName>
                </value>
                <value>
                    <fullName>CPL</fullName>
                </value>
                <value>
                    <fullName>SerLic</fullName>
                </value>
                <value>
                    <fullName>DedLic</fullName>
                </value>
                <value>
                    <fullName>DeskLic</fullName>
                </value>
                <value>
                    <fullName>suite</fullName>
                </value>
                <value>
                    <fullName>Car space</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Days</fullName>
                </value>
                <value>
                    <fullName>£</fullName>
                </value>
                <value>
                    <fullName>sqft</fullName>
                </value>
                <value>
                    <fullName>Qty</fullName>
                </value>
                <value>
                    <fullName>Desk</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rent_per_Sq_Ft_annual__c</fullName>
        <description>Rent per Sq. Ft. annual (£)</description>
        <label>Rent per Sq. Ft. annual (£)</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SBQQ__ProductCode__c</fullName>
        <description>Code for the product referenced by this line.</description>
        <formula>SBQQ__Product__r.ProductCode</formula>
        <inlineHelpText>Code for the product referenced by this line.</inlineHelpText>
        <label>Product Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product quoted by this line item.</description>
        <inlineHelpText>Product quoted by this line item.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>R00N70000001lXB6EAM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Term_Certain__c</fullName>
        <label>Term Certain</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Term_Concessions__c</fullName>
        <label>Term Concessions</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <label>Term</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tolerance_State__c</fullName>
        <label>Tolerance State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Updated_Price_per_sq_ft__c</fullName>
        <label>Monthly Updated Price per sq ft (£)</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SBQQ_QuoteLineTriggerHandler.cls
public class SBQQ_QuoteLineTriggerHandler extends TriggerHandler {

    private static final String INVENTORY_CAR_PARKING_DEVELOPER_NAME = 'Car_Parking';
    private static final String INVENTORY_ACTUAL_SUITE_DEVELOPER_NAME = 'Actual_Suite';
    private static final String INVENTORY_PROPOSED_SUITE_DEVELOPER_NAME = 'Proposed_Suite';
    private static final String INVENTORY_DESK_DEVELOPER_NAME = 'Desk';

    private static final Map<String, String> PRODUCT_CODE_TO_QUANTA_MAP =
            new Map<String, String>{
                    'OfficeRent' => 'Office',
                    'LabSpace' => 'Lab',
                    'RetailRent' => 'Retail',
                    'Storage' => 'Storage',
                    'BSLF' => 'SerLic',
                    'BSCW' => 'DedLic',
                    'BSDL' => 'DeskLic',
                    'CarParkingLease' => 'CPL',
                    'CarParkLicense' => 'CPL'
            };

    public override void beforeInsert() {
        copyProductFields(Trigger.new);
        setHalfRentAnnualisedAmountWords(Trigger.new);
        populatePropertyFromQuote(Trigger.new);
    }

    public override void beforeUpdate() {
        setHalfRentAnnualisedAmountWords(Trigger.new);
        populatePropertyFromQuote(Trigger.new);
    }

    public override void afterInsert() {
        updateSalesStatusOnRelatedInventories(Trigger.new);
        populateFieldsOnQuote(Trigger.new);
    }

    public override void afterUpdate() {
        updateSalesStatusOnRelatedInventories(Trigger.new);
        populateFieldsOnQuote(Trigger.new);
    }

    private void copyProductFields(List<SBQQ__QuoteLine__c> quoteLines) {
        Set<Id> productIds = SObjectUtils.getIdSetFromObjects(quoteLines, 'SBQQ__Product__c');
        Map<Id, Product2> products = new Map<Id, Product2>([
                SELECT Id, IsConcession__c, ProductCode
                FROM Product2
                WHERE Id IN:productIds
        ]);

        for (SBQQ__QuoteLine__c qLine : quoteLines) {
            if (qLine.SBQQ__Product__c != null) {
                qLine.IsConcession__c = products.get(qLine.SBQQ__Product__c).IsConcession__c;
                qLine.Quanta__c = getQuantaForProduct(products.get(qLine.SBQQ__Product__c));
            }
        }
    }

    private void populateFieldsOnQuote(List<SBQQ__QuoteLine__c> quoteLines) {
        Set<Id> quoteIds = SObjectUtils.getIdSetFromObjects(quoteLines, 'SBQQ__Quote__c');
        List<SBQQ__QuoteLine__c> headLines = SBQQ_QuoteService.getHeadLinesItems(quoteIds);
        Map<Id, List<SBQQ__QuoteLine__c>> headLinesByQuoteId = SObjectUtils.getIdMapFromObjects(headLines, 'SBQQ__Quote__c');
        List<SBQQ_QuoteApprovalHandler.ApprovalInfo> approvalInfos = SBQQ_QuoteApprovalHandler.getApprovalInfos(headLinesByQuoteId);
        Map<Id, SBQQ__Quote__c> quotesForUpdate = new Map<Id, SBQQ__Quote__c>();
        for (SBQQ_QuoteApprovalHandler.ApprovalInfo approvalInfo : approvalInfos) {
            quotesForUpdate.put(approvalInfo.quoteId,new SBQQ__Quote__c(Id = approvalInfo.quoteId, Tolerance_State__c = approvalInfo.toleranceState));
        }

        Map<Id, SBQQ__QuoteLine__c> inventoriesByQuote = getHeadQLIByQuote(headLinesByQuoteId);

        for (Id quoteId: inventoriesByQuote.keySet()) {
            if (quotesForUpdate.containsKey(quoteId)) {
                SBQQ__QuoteLine__c qLine = inventoriesByQuote.get(quoteId);
                quotesForUpdate.get(quoteId).Inventory__c = qLine.Inventory__c;
                quotesForUpdate.get(quoteId).Term__c = qLine.Term__c;
                quotesForUpdate.get(quoteId).Term_Certain__c = qLine.Term_Concessions__c != null ? qLine.Term_Concessions__c : 0;
                quotesForUpdate.get(quoteId).Rent_per_Sq_Ft_annual__c = qLine.Updated_Price_per_sq_ft__c != null ? qLine.Updated_Price_per_sq_ft__c * 12 : 0;
            } else  {
                quotesForUpdate.put(quoteId, new SBQQ__Quote__c(Id = quoteId, Inventory__c = inventoriesByQuote.get(quoteId).Inventory__c));
            }
        }

        if (!quotesForUpdate.isEmpty()) {
            update quotesForUpdate.values();
        }
    }


    private void updateSalesStatusOnRelatedInventories(List<SBQQ__QuoteLine__c> quoteLines) {
        Set<Id> inventoriesIds = new Set<Id>();
        for (SBQQ__QuoteLine__c quoteLine : quoteLines) {
            if (quoteLine.Inventory__c != null) {
                inventoriesIds.add(quoteLine.Inventory__c);
            }
        }
        updateSalesStatusOnInventories([SELECT Id, Sales_Status__c, RecordType.DeveloperName FROM Inventory__c WHERE Id IN :inventoriesIds]);
    }

    private void updateSalesStatusOnInventories(List<Inventory__c> inventories) {
        for (Inventory__c inventory : inventories) {
            if (inventory.RecordType.DeveloperName == INVENTORY_CAR_PARKING_DEVELOPER_NAME
                    || inventory.RecordType.DeveloperName == INVENTORY_DESK_DEVELOPER_NAME) {
                inventory.Sales_Status__c = Constants.INVENTORY_STATUS_RESERVED; //Updates Car Parkings and Desks with Reserved status
            } else if (inventory.RecordType.DeveloperName == INVENTORY_ACTUAL_SUITE_DEVELOPER_NAME
                    || inventory.RecordType.DeveloperName == INVENTORY_PROPOSED_SUITE_DEVELOPER_NAME) {
                inventory.Sales_Status__c = Constants.INVENTORY_STATUS_TERM_OUT; //Updates any others inventories with Instructed status
            }
        }
        update inventories;
    }

    private void setHalfRentAnnualisedAmountWords(List<SBQQ__QuoteLine__c> quoteLines) {
        NumberToWordsConverter.AbstractProcessor processor = new NumberToWordsConverter.BritishPoundsProcessor();
        for (SBQQ__QuoteLine__c quoteLine : quoteLines) {
            if (quoteLine.Half_Rent_Annualised_Amount__c != null) {
                quoteLine.Half_Rent_Annualised_text__c = processor.getName(quoteLine.Half_Rent_Annualised_Amount__c);
            }
        }
    }

    private void populatePropertyFromQuote(List<SBQQ__QuoteLine__c> quoteLines) {
        Set<Id> quotesIds = new Set<Id>();
        for (SBQQ__QuoteLine__c quoteLine : quoteLines) {
            quotesIds.add(quoteLine.SBQQ__Quote__c);
        }
        Map<Id, SBQQ__Quote__c> quoteMap = new Map<Id, SBQQ__Quote__c>([select Id, Property__c from SBQQ__Quote__c where Id in :quotesIds]);
        for (SBQQ__QuoteLine__c quoteLine : quoteLines) {
            quoteLine.Property_for_Filter__c = quoteMap.get(quoteLine.SBQQ__Quote__c).Property__c;
        }
    }

    private String getQuantaForProduct(Product2 product) {
        if (product == null || product.ProductCode == null || PRODUCT_CODE_TO_QUANTA_MAP.get(product.ProductCode) == null) {
            return 'None';
        }
        return PRODUCT_CODE_TO_QUANTA_MAP.get(product.ProductCode);
    }

    private Map<Id, SBQQ__QuoteLine__c> getHeadQLIByQuote (Map<Id, List<SBQQ__QuoteLine__c>> headLinesByQuoteId) {
        Map<Id, SBQQ__QuoteLine__c> inventoriesByQuote = new Map<Id, SBQQ__QuoteLine__c>();
        for (Id quoteId: headLinesByQuoteId.keySet()) {
            for (SBQQ__QuoteLine__c qLine: headLinesByQuoteId.get(quoteId)) {
                SBQQ__QuoteLine__c quoteLine = new SBQQ__QuoteLine__c();
                if(inventoriesByQuote.containsKey(quoteId)) {
                    quoteLine = inventoriesByQuote.get(quoteId);
                }

                if (qLine.SBQQ__ProductCode__c == ProductService.PRODUCT_CODE_OFFICE_RENT
                        || qLine.SBQQ__ProductCode__c == ProductService.PRODUCT_CODE_LAB_SPACE
                        || qLine.SBQQ__ProductCode__c == ProductService.PRODUCT_CODE_RETAIL_RENT
                        || qLine.SBQQ__ProductCode__c == ProductService.PRODUCT_CODE_SERVICED) {

                    quoteLine = qLine;

                } else if (qLine.SBQQ__ProductCode__c == ProductService.PRODUCT_CODE_STORAGE
                            && quoteLine.Inventory__c == null) {
                    quoteLine = qLine;
                }
                if (quoteLine.Inventory__c != null) {
                    inventoriesByQuote.put(quoteId,quoteLine);
                }
            }
        }
       return inventoriesByQuote;
    }
}