src/objects/Inventory__c.object
<CustomObject>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipName>Suites</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quanta__c</fullName>
        <label>Quanta</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Lab</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Office</fullName>
                </value>
                <value>
                    <fullName>Storage</fullName>
                </value>
                <value>
                    <fullName>SerLic</fullName>
                </value>
                <value>
                    <fullName>DedLic</fullName>
                </value>
                <value>
                    <fullName>DeskLic</fullName>
                </value>
                <value>
                    <fullName>CPL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Inventory</label>
    <nameField>
        <label>Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>IsConcession__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Concession</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Property_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Properties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Serviced_Space_Coordinator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Serviced Space Coordinator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Properties4</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>CapExpiryFullTerm__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cap Expiry Full Term</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory</label>
        <referenceTo>Inventory__c</referenceTo>
        <relationshipName>Inventory</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Net_Total__c</fullName>
        <label>Net Total (£)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Status__c</fullName>
        <description>Status indicating where quote is in its lifecycle.</description>
        <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Presented</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Pending Approval - Offline Edit</fullName>
                </value>
                <value>
                    <fullName>Awaiting Approval - Offline Edit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <label>Term</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Annualised_Cost_of_Parking_Spaces__c</fullName>
        <label>Total Annualised Cost of Parking Spaces</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Parking_Spaces__c</fullName>
        <label>Total Parking Spaces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <recordTypes>
        <fullName>Serviced</fullName>
        <active>true</active>
        <label>Serviced</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>Car_Parking_Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Car Parking Inventory</label>
        <referenceTo>Inventory__c</referenceTo>
        <relationshipLabel>Quote Lines (Car Parking Inventory)</relationshipLabel>
        <relationshipName>Quote_Lines1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Half_Rent_Annualised_Amount__c</fullName>
        <formula>IF(
  AND (
    SBQQ__ProductCode__c == &apos;HalfRent&apos;,
    NOT(ISBLANK(SBQQ__RequiredBy__c)),
    NOT(ISBLANK(SBQQ__RequiredBy__r.Net_Total__c)),
    NOT(ISBLANK(SBQQ__RequiredBy__r.Term__c )),
    SBQQ__RequiredBy__r.Term__c &gt; 0
  ),
    ((SBQQ__RequiredBy__r.Net_Total__c / SBQQ__RequiredBy__r.Term__c) * 12 ) / 2,
    NULL
)</formula>
        <label>Half Rent Annualised Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Half_Rent_Annualised_text__c</fullName>
        <label>Half Rent Annualised Amount (Words)</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory</label>
        <referenceTo>Inventory__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>Quote_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsConcession__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Concession</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Net_Total__c</fullName>
        <label>Net Total (£)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Quote Lines (Property)</relationshipLabel>
        <relationshipName>QuoteLines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quanta__c</fullName>
        <label>Quanta</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Lab</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Office</fullName>
                </value>
                <value>
                    <fullName>Storage</fullName>
                </value>
                <value>
                    <fullName>CPL</fullName>
                </value>
                <value>
                    <fullName>SerLic</fullName>
                </value>
                <value>
                    <fullName>DedLic</fullName>
                </value>
                <value>
                    <fullName>DeskLic</fullName>
                </value>
                <value>
                    <fullName>suite</fullName>
                </value>
                <value>
                    <fullName>Car space</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Days</fullName>
                </value>
                <value>
                    <fullName>£</fullName>
                </value>
                <value>
                    <fullName>sqft</fullName>
                </value>
                <value>
                    <fullName>Qty</fullName>
                </value>
                <value>
                    <fullName>Desk</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <label>Term</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SBQQ__Subscription__c.object
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <fields>
        <fullName>Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory</label>
        <referenceTo>Inventory__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsConcession__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Indicates that this line will create a negative line in FF Billing documents. For rent concessions only</inlineHelpText>
        <label>Is Concession</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__QuoteLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote line that generated this subscription.</description>
        <inlineHelpText>Quote line that generated this subscription.</inlineHelpText>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <label>Term</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SBQQ_QuoteServiceTest.cls
@IsTest
public class SBQQ_QuoteServiceTest {
    @IsTest
    static void testCallExpiryFullTermFieldFieldONQuoteFalseValue() {
        SBQQ__Quote__c quote = RecordDmlTest.generateConventionalQuoteWithLines(QuoteProductCodes.OFFICE_RENT);

        Test.startTest();
            quote.SBQQ__Status__c = SBQQ_QuoteConstants.STATUS_ACCEPTED;
            update quote;
        Test.stopTest();

        SBQQ__Quote__c testQuote = [SELECT Id, CapExpiryFullTerm__c FROM SBQQ__Quote__c WHERE Id=: quote.Id LIMIT 1];
        System.assert(!testQuote.CapExpiryFullTerm__c, 'The CapExpiryFullTerm__c is TRUE only when Quote has ServiceCharge and ServiceChargeCap products');
        System.assertNotEquals(null, ProductService.PRODUCT_CODE_SERVICE_CHARGE);
        System.assertNotEquals(null, ProductService.PRODUCT_CODE_SERVICE_CHARGE_CAP);
    }

    @IsTest
    static void testCallExpiryFullTermFieldFieldONQuoteTrueValue() {
        SBQQ.TriggerControl.disable();
        SBQQ__Quote__c quote = RecordDmlTest.generateConventionalQuoteWithServiceChargeCapLines();

        Test.startTest();
            quote.SBQQ__Status__c = SBQQ_QuoteConstants.STATUS_ACCEPTED;
            update quote;
        Test.stopTest();

        SBQQ__Quote__c testQuote = [SELECT Id, CapExpiryFullTerm__c FROM SBQQ__Quote__c WHERE Id=: quote.Id LIMIT 1];
        System.assert(testQuote.CapExpiryFullTerm__c, 'The CapExpiryFullTerm__c is TRUE only when Quote has ServiceCharge and ServiceChargeCap products');
    }

    @IsTest
    static void testConcessionLogic() {
        SBQQ.TriggerControl.disable();
        SBQQ__Quote__c quote = RecordDmlTest.generateConventionalQuoteWithServiceChargeCapLines();

        Test.startTest();
            quote.SBQQ__Status__c = SBQQ_QuoteConstants.STATUS_ACCEPTED;
            update quote;
        Test.stopTest();

        System.assert([SELECT COUNT() FROM SBQQ__QuoteLine__c WHERE IsConcession__c = TRUE] > 0, 'Concession products in QLI');
        System.assert([SELECT COUNT() FROM SBQQ__Subscription__c WHERE IsConcession__c = TRUE] > 0, 'Concession products in QLI');
    }

    @IsTest
    static void testParkingInfo() {
        //given
        SBQQ__Quote__c quote = RecordDmlTest.preGenerateQuote('Serviced');
        User propertyManager = RecordDmlTest.createUser();

        Property__c property = [SELECT Id, Property_Manager__c FROM Property__c WHERE Id = :quote.Property__c];
        property.Serviced_Space_Coordinator__c = propertyManager.Id;
        upsert property;
        //TODO:extract and eliminate code duplication
        List<Product2> products = new List<Product2>();
        Product2 officeRentProduct = new Product2(Name = 'Office Rent', Family = 'Suite', ProductCode='Storage');
        products.add(officeRentProduct);
        Product2 carParkingLicenseProduct = new Product2(Name = 'Car Parking License', Family = 'Parking', ProductCode='CarParkLicense');
        products.add(carParkingLicenseProduct);
        Product2 carSpaceProduct = new Product2(Name = 'Car Space', Family = 'Parking', ProductCode='CarSpace');
        products.add(carSpaceProduct);
        Product2 halfRent = new Product2(Name = 'Half Rent', ProductCode = 'HalfRent', Family = 'Days', IsConcession__c = true);
        products.add(halfRent);
        insert products;

        Inventory__c officeRentInventory = RecordDmlTest.createActualSuiteInventory(officeRentProduct, property);
        Inventory__c carParkingInventory = RecordDmlTest.createActualCarParkingInventory(carSpaceProduct, property);

        SBQQ__QuoteLine__c suite = RecordDmlTest.generateLine(officeRentProduct, quote.Id, officeRentInventory.Id, null);
        suite.Quanta__c = 'suite';
        suite.Net_Total__c = 100;
        suite.Term__c = 10;
        SBQQ.TriggerControl.disable();
        insert suite;

        SBQQ__QuoteLine__c parking = RecordDmlTest.generateLine(carSpaceProduct, quote.Id, carParkingInventory.Id, null);
        parking.Car_Parking_Inventory__c = carParkingInventory.Id;
        parking.Net_Total__c = 100;
        parking.Term__c = 10;
 
        SBQQ__QuoteLine__c halfRentLine = RecordDmlTest.generateLine(halfRent, quote.Id, officeRentInventory.Id, suite.Id);

        Test.startTest();
        SBQQ.TriggerControl.disable();
        insert new List<SBQQ__QuoteLine__c>{
            parking, halfRentLine
        };
        Test.stopTest();

        quote = [SELECT Id, Total_Parking_Spaces__c, Total_Annualised_Cost_of_Parking_Spaces__c FROM SBQQ__Quote__c WHERE Id =: quote.Id];
        halfRentLine = [SELECT Id, Half_Rent_Annualised_Amount__c, Half_Rent_Annualised_text__c FROM SBQQ__QuoteLine__c WHERE Id =: halfRentLine.Id];
        System.assertEquals(1, quote.Total_Parking_Spaces__c);
        System.assertEquals( ((parking.Net_Total__c / parking.Term__c) * 12) , quote.Total_Annualised_Cost_of_Parking_Spaces__c);
        System.assertEquals( ( ((suite.Net_Total__c / suite.Term__c) * 12 ) / 2 ), halfRentLine.Half_Rent_Annualised_Amount__c);
        System.assertNotEquals(null, halfRentLine.Half_Rent_Annualised_text__c);
    }
}