src/objects/Inventory__c.object
<CustomObject>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipName>Suites</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sales_Status__c</fullName>
        <label>Sales Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                </value>
                <value>
                    <fullName>Terms Out</fullName>
                </value>
                <value>
                    <fullName>Reserved</fullName>
                </value>
                <value>
                    <fullName>Not Available</fullName>
                </value>
                <value>
                    <fullName>Not for Sale</fullName>
                </value>
                <value>
                    <fullName>Instructed</fullName>
                    <isActive>false</isActive>
                    <label>Instructed</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Inventory</label>
    <nameField>
        <label>Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Proposed_to_Actual_Suite_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>Proposed_Suite__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Proposed Suite</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Proposed Suite should be with Proposed RecordType</errorMessage>
            <filterItems>
                <field>Inventory__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Proposed_Suite</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Inventory__c</referenceTo>
        <relationshipLabel>Proposed to Actual Suite Mappings</relationshipLabel>
        <relationshipName>Proposed_to_Actual_Suite_Mappings1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Proposed to Actual Suite Mapping</label>
    <nameField>
        <label>Proposed to Actual Suite Mapping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposed to Actual Suite Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PTASuiteMappingControllerTest.cls
@isTest
public with sharing class PTASuiteMappingControllerTest {
    @isTest
    static void testControllerLifecycle() {
        //given
        Property__c property1 = RecordDmlTest.createProperty();
        RecordDmlTest.createProducts();
        Product2 suiteProduct = [select id from Product2 where Family = 'suite' and ProductCode='OfficeRent' limit 1];

        Inventory__c actualInventory1 = RecordDmlTest.createActualSuiteInventory(suiteProduct, property1);
        actualInventory1.Sales_Status__c = 'Not Available';
        update actualInventory1;
        Inventory__c actualInventory2 = RecordDmlTest.createActualSuiteInventory(suiteProduct, property1);
        Inventory__c actualInventory3 = RecordDmlTest.createActualSuiteInventory(suiteProduct, property1);

        Inventory__c proposedInventory = RecordDmlTest.createProposedSuiteInventory(suiteProduct, property1);

        PageReference mappingPage = Page.ProposedToActualSuiteMapping;
        Test.setCurrentPageReference(mappingPage);
        ApexPages.currentPage().getParameters().put('proposedSuiteId', proposedInventory.Id);
        
        //when page opened
        ProposedToActualSuiteMappingController controller = new ProposedToActualSuiteMappingController();
        
        //then all Actual available inventories from the Property appears in the ActualSuites 
        System.assertEquals(2, controller.getActualSuites().size());
        System.assertEquals(0, controller.selectedSuitesIds.size());

        //when we save with selected suites
        controller.selectedSuitesIds.add(actualInventory2.Id);
        PageReference saveReference = controller.save();
        //then Mapping created
        System.assertEquals(1, [select count() from Proposed_to_Actual_Suite_Mapping__c]);
        //then user routed to proposed suite page
        System.assertEquals('/' + proposedInventory.Id, saveReference.getUrl());

        //when we reload page
        controller = new ProposedToActualSuiteMappingController();
        //then available suites the same, one selected
        System.assertEquals(2, controller.getActualSuites().size());
        System.assertEquals(1, controller.selectedSuitesIds.size());
        
        //when we saving mapping again
        controller.save();
        //then no duplicates created:
        System.assertEquals(1, [select count() from Proposed_to_Actual_Suite_Mapping__c]);
        
        //when we clear proposed suite
        controller.searchMapping.Proposed_Suite__c = null;
        //then no available suites shown
        System.assertEquals(0, controller.getActualSuites().size());

        //when rerender without selected proposed suite
        controller.rerenderActualSuites();
        //then still no available suites shown
        System.assertEquals(0, controller.getActualSuites().size());
        
        //when we try to save without proposed suite 
        saveReference = controller.save();
        //then error shown and reference is null
        System.assertEquals(ApexPages.Severity.ERROR, ApexPages.getMessages().get(0).getSeverity());
        System.assertEquals(null, saveReference);
        
        //when click on cancel
        controller = new ProposedToActualSuiteMappingController();
        PageReference cancelReference = controller.cancel();
        //then route to proposed suite page
        System.assertEquals('/' + proposedInventory.Id, cancelReference.getUrl());
    }
}