src/objects/Inventory__c.object
<CustomObject>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipName>Suites</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RecordTypeDeveloperName__c</fullName>
        <label>RecordTypeDeveloperName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Inventory</label>
    <nameField>
        <label>Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventories</pluralLabel>
    <recordTypes>
        <fullName>Actual_Suite</fullName>
        <active>true</active>
        <label>Actual Suite</label>
    </recordTypes>
    <recordTypes>
        <fullName>Proposed_Suite</fullName>
        <active>true</active>
        <label>Proposed Suite</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/InventoryTriggerHandlerTest.cls
@isTest
public with sharing class InventoryTriggerHandlerTest {
    @isTest
    public static void whenInventoryCreatedRTSetFromField() {
        Property__c testProperty = RecordDmlTest.createProperty();

        Product2 product = new Product2(Name = 'Test Product', IsActive = true, Family = 'Suite', ProductCode = 'OfficeRent');
        Database.insert(product);

        Inventory__c inventory1 = RecordDmlTest.createInventoryNoInsert(product, testProperty, null, 'Actual');
        inventory1.RecordTypeDeveloperName__c = 'Actual_Suite';

        Inventory__c inventory2 = RecordDmlTest.createInventoryNoInsert(product, testProperty, null, 'Proposed');
        inventory2.RecordTypeDeveloperName__c = 'Proposed_Suite';

        insert new List<Inventory__c>{
                inventory1, inventory2
        };

        for (Inventory__c inventory : [select RecordType.DeveloperName, RecordTypeDeveloperName__c from Inventory__c]) {
            System.assertEquals(inventory.RecordType.DeveloperName, inventory.RecordTypeDeveloperName__c);
        }
    }
}