src/objects/Meeting_Room_Booking__c.object
<CustomObject>
    <fields>
        <fullName>Booking_End_Date__c</fullName>
        <label>Booking End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Booking_Start_Date__c</fullName>
        <label>Booking Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Checkfront_Customer_ID__c</fullName>
        <label>Checkfront Customer ID</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Code__c</fullName>
        <description>A unique booking code used to refer to the booking</description>
        <externalId>true</externalId>
        <label>Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Created_Date__c</fullName>
        <description>The date on which the booking was created</description>
        <label>Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Customer_Email__c</fullName>
        <description>The customer’s email address</description>
        <label>Customer Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <description>The customer’s full name</description>
        <label>Customer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Paid_Total__c</fullName>
        <description>The total amount the customer has paid on the order</description>
        <label>Order Paid Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Order_Sub_Total__c</fullName>
        <description>The sub-total of all charges added to the order</description>
        <label>Order Sub Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Order_Tax_Total__c</fullName>
        <description>The sum of all taxes applied to the order</description>
        <label>Order Tax Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Order_Total__c</fullName>
        <description>The total of all charges and taxes added to the order</description>
        <label>Order Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Room__c</fullName>
        <label>Room</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The current status code of the booking</description>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Meeting Room Booking</label>
    <nameField>
        <displayFormat>MRB-{000000000}</displayFormat>
        <label>Meeting Room Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meeting Room Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CheckfrontDTO.cls
/**
 * @description Contains DTO classes to convert Checkfront request JSON to SObject
 */
public class CheckfrontDTO {

    public class CheckfrontRequest {
        public Booking booking { get; set; }
    }



    public class Booking {
        public String status { get; set; }
        public String code { get; set; }
        public Long created_date { get; set; }
        public Long start_date { get; set; }
        public Long end_date { get; set; }
        public Fields fields { get; set; }
        public  Customer customer { get; set; }
        public Order order { get; set; }



        public Meeting_Room_Booking__c convertToSObject() {
            Meeting_Room_Booking__c payment = new Meeting_Room_Booking__c();
            payment.Status__c = this.status;
            payment.Code__c = this.code;
            payment.Created_Date__c = DateTime.newInstance(created_date * 1000);
            payment.Booking_End_Date__c =DateTime.newInstance(end_date * 1000);
            payment.Booking_Start_Date__c = DateTime.newInstance(start_date * 1000);
            System.debug('is ok');
            if ( this.fields != null ) {
                payment.Customer_Name__c = this.fields.customer_name;
                payment.Customer_Email__c = this.fields.customer_email;
            }
            if ( this.customer != null) {
                payment.Checkfront_Customer_ID__c = this.customer.code;
            }
            if ( this.order != null ) {
                payment.Order_Sub_Total__c = order.sub_total;
                payment.Order_Paid_Total__c = order.paid_total;
                payment.Order_Tax_Total__c = order.tax_total;
                payment.Order_Total__c = order.total;
            }
            if ( this.order.items.item != null) {
                payment.Property__c = order.items.item.sku.substringBefore('-');
                payment.Room__c = order.items.item.sku.substringAfter('-');

            }
            return payment;
        }
    }

    public class Fields {
        public String customer_name { get; set; }
        public String customer_email { get; set; }

    }

    public class Customer {
        public String code { get; set; }
    }

    public class Order {
        public Decimal sub_total { get; set; }
        public Decimal paid_total { get; set; }
        public Decimal tax_total { get; set; }
        public Decimal total { get; set; }
        public Items items { get; set; }
    }

    public class Items {
        public Item item  { get; set; }
    }

    public class Item {
        public string sku { get; set; }
    }
}