src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Closed_Lost_Reason__c</fullName>
        <label>Closed Lost Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Too expensive</fullName>
                </value>
                <value>
                    <fullName>Space too big</fullName>
                </value>
                <value>
                    <fullName>Space too small</fullName>
                </value>
                <value>
                    <fullName>Unsuitable location</fullName>
                </value>
                <value>
                    <fullName>Feasibility study</fullName>
                </value>
                <value>
                    <fullName>Went to competitor</fullName>
                </value>
                <value>
                    <fullName>Requirement retracted</fullName>
                </value>
                <value>
                    <fullName>Lack of car parking</fullName>
                </value>
                <value>
                    <fullName>Unsuitable specification</fullName>
                </value>
                <value>
                    <fullName>See Closed Lost Comments</fullName>
                </value>
                <value>
                    <fullName>Inactivity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_Activated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contract Activated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contracts_Exchanged__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contracts Exchanged</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HOTs_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>HOTs Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HOTs_Signed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>HOTs Signed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LT_Case_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>LT Case Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Viewing_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Viewing Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>Conventional</fullName>
        <active>true</active>
        <businessProcess>Conventional Sales Process</businessProcess>
        <label>Conventional</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ConventionalOppStatusCalculator.cls
/**
 * @description Opportunity Status Calculator for Conventional Sales Record Type
 */
public with sharing class ConventionalOppStatusCalculator implements IStatusCalculator {

	private static final String STAGE_QUALIFIED = 'Qualified'; //TODO: move Stages to one place
	private static final String STAGE_VIEWVING = 'Viewing';
	private static final String STAGE_TERMS_OUT = 'Terms Out';
	public static final String STAGE_INSTRUCTED = 'Instructed';
	public static final String STAGE_EXCHANGED = 'Exchanged';
	public static final String STAGE_COMPLETED = 'Completed';
	public static final String STAGE_LOST = 'Closed Lost';

	/**
	 * @description Calculated Opportunity status
	 */
	public String calculateNewStatus(Opportunity theOpportunity) {
		String newStatus = STAGE_QUALIFIED;
		if ( theOpportunity.Viewing_Count__c > 0 ) {
			newStatus = STAGE_VIEWVING;
		}
		if ( theOpportunity.HOTs_Sent__c ) {
			newStatus = STAGE_TERMS_OUT;
		}
		if ( theOpportunity.HOTs_Sent__c && theOpportunity.HOTs_Signed__c ) {
			newStatus = STAGE_INSTRUCTED;
		}
		if ( theOpportunity.HOTs_Sent__c && theOpportunity.HOTs_Signed__c && theOpportunity.Contracts_Exchanged__c ) {
			newStatus = STAGE_EXCHANGED;
		}
		if ( theOpportunity.HOTs_Sent__c && theOpportunity.HOTs_Signed__c && theOpportunity.Contracts_Exchanged__c
			&& theOpportunity.Contract_Activated__c && theOpportunity.LT_Case_Completed__c ) {
			newStatus = STAGE_COMPLETED;
		}
		if ( String.isNotBlank(theOpportunity.Closed_Lost_Reason__c) ) {
			newStatus = STAGE_LOST;
		}
		return newStatus;
	}
}