src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Briefing_Statement__c</fullName>
        <description>Additional information to the property management team.</description>
        <inlineHelpText>Additional information to the property management team.</inlineHelpText>
        <label>Briefing Statement</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Closed_Lost_Reason__c</fullName>
        <label>Closed Lost Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Too expensive</fullName>
                </value>
                <value>
                    <fullName>Space too big</fullName>
                </value>
                <value>
                    <fullName>Space too small</fullName>
                </value>
                <value>
                    <fullName>Unsuitable location</fullName>
                </value>
                <value>
                    <fullName>Feasibility study</fullName>
                </value>
                <value>
                    <fullName>Went to competitor</fullName>
                </value>
                <value>
                    <fullName>Requirement retracted</fullName>
                </value>
                <value>
                    <fullName>Lack of car parking</fullName>
                </value>
                <value>
                    <fullName>Unsuitable specification</fullName>
                </value>
                <value>
                    <fullName>See Closed Lost Comments</fullName>
                </value>
                <value>
                    <fullName>Inactivity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Compliance_Check_Complete__c</fullName>
        <label>Compliance Check Complete</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No_Value_Set</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deposit_Paid__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Use this field to indicate that the deposit has been paid by the customer</description>
        <inlineHelpText>Use this field to indicate that the deposit has been paid by the customer</inlineHelpText>
        <label>Deposit Paid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Event_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Event Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>HOTs_Signed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>HOTs Signed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Virtual_Compliance_Approval_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Virtual Compliance Approval Complete</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Virtual</fullName>
        <active>true</active>
        <businessProcess>Virtual Sales Process</businessProcess>
        <label>Virtual</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/VirtualOppStatusCalculator.cls
/**
 * @description Opportunity Status Calculator for Virtual Sales Record Type
 */
public with sharing class VirtualOppStatusCalculator implements IStatusCalculator  {

	private static final String STAGE_QUALIFIED = 'Qualified';
	private static final String STAGE_MEETING_BOOKED = 'Meeting Booked';
	private static final String STAGE_CHECK_COMPLETE = 'Check Complete';
	private static final String STAGE_TERMS_AGREED = 'Terms Agreed';
	private static final String STAGE_COMPLETED = 'Completed';
	private static final String STAGE_LOST = 'Closed Lost';

	/**
	 * @description Calculated Opportunity status
	 */
	public String calculateNewStatus(Opportunity theOpportunity) {
		String newStatus = STAGE_QUALIFIED;
		if ( theOpportunity.Event_Count__c > 0 ) {
			newStatus = STAGE_MEETING_BOOKED;
		}
		Boolean complianceCheckComplete = theOpportunity.Compliance_Check_Complete__c == 'Yes' || (theOpportunity.Compliance_Check_Complete__c == 'No' && theOpportunity.Virtual_Compliance_Approval_Complete__c);
		if ( complianceCheckComplete ) {
			newStatus = STAGE_CHECK_COMPLETE;
		}
		if ( complianceCheckComplete && String.isNotBlank(theOpportunity.Briefing_Statement__c) && theOpportunity.HOTs_Signed__c ) {
			newStatus = STAGE_TERMS_AGREED;
		}
		if ( complianceCheckComplete && String.isNotBlank(theOpportunity.Briefing_Statement__c) && theOpportunity.HOTs_Signed__c && theOpportunity.Deposit_Paid__c ) {
			newStatus = STAGE_COMPLETED;
		}
		if ( String.isNotBlank(theOpportunity.Closed_Lost_Reason__c) ) {
			newStatus = STAGE_LOST;
		}
		return newStatus;
	}
}