src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Closed_Lost_Reason__c</fullName>
        <label>Closed Lost Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Too expensive</fullName>
                </value>
                <value>
                    <fullName>Space too big</fullName>
                </value>
                <value>
                    <fullName>Space too small</fullName>
                </value>
                <value>
                    <fullName>Unsuitable location</fullName>
                </value>
                <value>
                    <fullName>Feasibility study</fullName>
                </value>
                <value>
                    <fullName>Went to competitor</fullName>
                </value>
                <value>
                    <fullName>Requirement retracted</fullName>
                </value>
                <value>
                    <fullName>Lack of car parking</fullName>
                </value>
                <value>
                    <fullName>Unsuitable specification</fullName>
                </value>
                <value>
                    <fullName>See Closed Lost Comments</fullName>
                </value>
                <value>
                    <fullName>Inactivity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LA_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>LA Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LA_Signed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>LA Signed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary_Quote_Accepted__c</fullName>
        <formula>ISPICKVAL(SBQQ__PrimaryQuote__r.SBQQ__Status__c, &apos;Accepted&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Quote Accepted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Viewing_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Viewing Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>Serviced</fullName>
        <active>true</active>
        <businessProcess>Serviced Sales Process</businessProcess>
        <label>Serviced</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ServicedOppStatusCalculator.cls
/**
 * @description Opportunity Status Calculator for Serviced Sales Record Type
 */
public with sharing class ServicedOppStatusCalculator implements IStatusCalculator {

	private static final String STAGE_QUALIFIED = 'Qualified';
	private static final String STAGE_VIEWVING = 'Viewing';
	private static final String STAGE_LICENSE_OUT = 'Licence Out';
	private static final String STAGE_COMPLETED = 'Completed';
	private static final String STAGE_LOST = 'Closed Lost';

	/**
	 * @description Calculated Opportunity status
	 */
	public String calculateNewStatus(Opportunity theOpportunity) {
		String newStatus = STAGE_QUALIFIED;
		if ( theOpportunity.Viewing_Count__c > 0 ) {
			newStatus = STAGE_VIEWVING;
		}
		if ( theOpportunity.LA_Sent__c ) {
			newStatus = STAGE_LICENSE_OUT;
		}
		if ( theOpportunity.LA_Sent__c &&  theOpportunity.LA_Signed__c && theOpportunity.Primary_Quote_Accepted__c) {
			newStatus = STAGE_COMPLETED;
		}
		if ( String.isNotBlank(theOpportunity.Closed_Lost_Reason__c) ) {
			newStatus = STAGE_LOST;
		}
		return newStatus;
	}

}