src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Closed_Lost_Date__c</fullName>
        <label>Closed Lost Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Closed_Lost_Reason__c</fullName>
        <label>Closed Lost Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Too expensive</fullName>
                </value>
                <value>
                    <fullName>Space too big</fullName>
                </value>
                <value>
                    <fullName>Space too small</fullName>
                </value>
                <value>
                    <fullName>Unsuitable location</fullName>
                </value>
                <value>
                    <fullName>Feasibility study</fullName>
                </value>
                <value>
                    <fullName>Went to competitor</fullName>
                </value>
                <value>
                    <fullName>Requirement retracted</fullName>
                </value>
                <value>
                    <fullName>Lack of car parking</fullName>
                </value>
                <value>
                    <fullName>Unsuitable specification</fullName>
                </value>
                <value>
                    <fullName>See Closed Lost Comments</fullName>
                </value>
                <value>
                    <fullName>Inactivity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CustomerInactivityHandlerBatch.cls
/**
 * A batch apex class what close Opportunities with no any customer activity at set of period time.
 * It process a lot of Opportunities at a time.
 *
 * @author v2.nareyko
 * @since 9/1/18
 */

global without sharing class CustomerInactivityHandlerBatch implements Database.Batchable<sObject> {

    private String query;

    global CustomerInactivityHandlerBatch(String query) {
        this.query = query;
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext bc, List<Opportunity> scope) {
        for(Opportunity opportunity : scope) {
            closeInactiveOpportunity(opportunity);
        }
        update scope;
    }

    global void finish(Database.BatchableContext param1) {}

    private void closeInactiveOpportunity(Opportunity opportunity) {
        opportunity.Closed_Lost_Reason__c = 'Inactivity';
        opportunity.StageName = 'Closed Lost';
        opportunity.CloseDate = System.now().date();
        opportunity.Closed_Lost_Date__c = System.now().date();
    }
}