src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The quote where the order is created from.</description>
        <inlineHelpText>The quote where the order is created from.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Portfolio__c</fullName>
        <formula>CASE( TEXT(Region__c),
            &quot;Manchester City Centre&quot;,  &quot;Bruntwood&quot;,
            &quot;Liverpool&quot;, &quot;Bruntwood&quot;,
            &quot;Manchester Region&quot;, &quot;Bruntwood&quot;,
            &quot;Birmingham&quot;, &quot;Bruntwood&quot;,
            &quot;Leeds&quot;, &quot;Bruntwood&quot;,
            &quot;Manchester Science Partnerships&quot;, &quot;MSP&quot;,
            &quot;Salford Innovation Park&quot;, &quot;MSP&quot;,
            &quot;Alderley Park&quot;, &quot;Alderley Park&quot;,
            &quot;None&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Portfolio</label>
        <type>Text</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <label>Term</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>Break_Date__c</fullName>
        <label>Break Date</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Discount_Total__c</fullName>
        <label>Discount Total (£)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Monthly_Average__c</fullName>
        <label>Monthly Average (£)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Quote Lines (Property)</relationshipLabel>
        <relationshipName>QuoteLines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__ProductCode__c</fullName>
        <description>Code for the product referenced by this line.</description>
        <formula>SBQQ__Product__r.ProductCode</formula>
        <inlineHelpText>Code for the product referenced by this line.</inlineHelpText>
        <label>Product Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SBQQ__RequiredBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Links this line to another line in the same quote whose product requires this line&apos;s product.</description>
        <inlineHelpText>Indicates which other product on this quote requires it.</inlineHelpText>
        <label>Required By</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>Quote_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Term__c</fullName>
        <label>Start Term</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <label>Term</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ConventionalPricingDocumentGenerator.cls
public class ConventionalPricingDocumentGenerator {

    public SBQQ__Quote__c quote { get; set; }

    public List<SBQQ__QuoteLine__c> lineItems { get; set; }

    public Map<SBQQ__QuoteLine__c, List<SBQQ__QuoteLine__c>> bundles { get; set; }
    public Map<SBQQ__QuoteLine__c, Map<Integer, Decimal>> rentsByYears { get; set; }
    public Map<SBQQ__QuoteLine__c, String> breakOptions { get; set; }
    public Map<SBQQ__QuoteLine__c, Integer> rentYearsCount { get; set; }
    public Map<SBQQ__QuoteLine__c, String> rentYearsAndMonth { get; set; }

    public String actualPortfolio { get; set; }
    public Integer countOfBundels { get; set; }

    public ConventionalPricingDocumentGenerator() {
        rentYearsAndMonth = new Map<SBQQ__QuoteLine__c, String>();
        rentYearsCount = new Map<SBQQ__QuoteLine__c, Integer>();
        Id quoteId = (Id) ApexPages.currentPage().getParameters().get('id');
        quote = DocumentGenerationHelper.getQuoteDetails(quoteId);
        actualPortfolio = obtainActualPortfolio(quote);
        bundles = new Map<SBQQ__QuoteLine__c, List<SBQQ__QuoteLine__c>>();
        rentsByYears = new Map<SBQQ__QuoteLine__c, Map<Integer, Decimal>>();
        breakOptions = new Map<SBQQ__QuoteLine__c, String>();
        lineItems = DocumentGenerationHelper.getQuoteLines(quoteId);
        for (SBQQ__QuoteLine__c lineItem : lineItems) {
            if (DocumentGenerationHelper.isSuiteBundle(lineItem)) {
                bundles.put(lineItem, getBundleItems(lineItem));
                breakOptions.put(lineItem, getBreakOptionsString(lineItem));
                if (lineItem.Term__c != null) {

                    rentYearsAndMonth.put(lineItem, NumberUtils.convertMonthsToYears(Integer.valueOf(lineItem.Term__c)));
                    rentYearsCount.put(lineItem, Math.ceil(Integer.valueOf(lineItem.Term__c) / 12.0).intValue());
                    rentsByYears.put(lineItem, getRentsByYears(lineItem, Integer.valueOf(lineItem.Term__c)));
                }
            }
        }

        countOfBundels = bundles.size();
    }

    private String obtainActualPortfolio(SBQQ__Quote__c quote) {
        return String.isBlank(quote.Property__r.Portfolio__c) ? SBQQ_QuoteConstants.DEFAUL_PORTFOLIO_NAME : quote.Property__r.Portfolio__c;
    }

    private List<SBQQ__QuoteLine__c> getBundleItems(SBQQ__QuoteLine__c bundle) {
        List<SBQQ__QuoteLine__c> bundleItems = new List<SBQQ__QuoteLine__c>();
        for (SBQQ__QuoteLine__c lineItem : lineItems) {
            if (lineItem.SBQQ__RequiredBy__c == bundle.Id) {
                bundleItems.add(lineItem);
            }
        }
        return bundleItems;
    }

    private List<Integer> getBundleTerms(Decimal months) {
        Integer years = Math.ceil(months / 12.0).intValue();
        List<Integer> terms = new List<Integer>();
        for (Integer i = 1; i <= years; i++) {
            terms.add(i);
        }
        return terms;
    }

    private String getBreakOptionsString(SBQQ__QuoteLine__c bundle) {
        String breakOptionsString = '';
        List<Integer> yearsWhenBreakOptionApplied = getMonthWhenBreakOptionApplied(bundle);
        //The list should be sorted to display values in ascending order (For example: 1st, 2nd, 4th years)
        yearsWhenBreakOptionApplied.sort();
        for (Integer yearWhenBreakoptionApplied : yearsWhenBreakOptionApplied) {
            breakOptionsString += yearWhenBreakoptionApplied + NumberUtils.getOrdinalNumber(yearWhenBreakoptionApplied) + ', ';
        }
        if (!String.isBlank(breakOptionsString)) {
            //Removes extra comma
            breakOptionsString = breakOptionsString.removeEnd(', ');
            //If the string contains comma, it means there are several values in the string
            breakOptionsString += breakOptionsString.contains(',') ? ' months' : ' month';
        }
        return breakOptionsString;
    }

    private List<Integer> getMonthWhenBreakOptionApplied(SBQQ__QuoteLine__c bundle) {
        //Stores the list of years in which Break Option will be applied for specific bundle
        List<Integer> monthWhenBreakOptionApplied = new List<Integer>();
        for (SBQQ__QuoteLine__c lineItem : lineItems) {
            if (lineItem.SBQQ__RequiredBy__c == bundle.Id && lineItem.SBQQ__ProductCode__c == ProductService.PRODUCT_CODE_CUSTOMER_BREAK
                    && lineItem.Break_Date__c != null) {
                Integer breakDate = Math.ceil(lineItem.Break_Date__c).intValue();
                monthWhenBreakOptionApplied.add(breakDate);
            }
        }
        return monthWhenBreakOptionApplied;
    }

    private Set<SBQQ__QuoteLine__c> getConcessionLineItems(List<SBQQ__QuoteLine__c> lineItems) {
        Set<SBQQ__QuoteLine__c> concessionLineItems = new Set<SBQQ__QuoteLine__c>();
        for (SBQQ__QuoteLine__c lineItem : lineItems) {
            String productCode = lineItem.SBQQ__ProductCode__c;
            if (productCode == ProductService.PRODUCT_CODE_FREE_RENT
                    || productCode == ProductService.PRODUCT_CODE_HALF_RENT
                    || productCode == ProductService.PRODUCT_CODE_STEPPED_RENT) {
                concessionLineItems.add(lineItem);
            }
        }
        return concessionLineItems;
    }

    private Map<Integer, Decimal> getRentsByYears(SBQQ__QuoteLine__c bundle, Integer months) {
        Map<Integer, Double> rentsByYears = new Map<Integer, Double>();
        Set<SBQQ__QuoteLine__c> concessionLineItems = getConcessionLineItems(getBundleItems(bundle));
        for (Integer month = 1; month <= months; month++) {
            Integer year = Math.ceil(month / 12.0).intValue();
            if (!rentsByYears.containsKey(year)) {
                rentsByYears.put(year, bundle.Monthly_Average__c);
            } else {
                rentsByYears.put(year, rentsByYears.get(year) + bundle.Monthly_Average__c);
            }
            for (SBQQ__QuoteLine__c concessionLineItem : concessionLineItems) {
                rentsByYears.put(year, rentsByYears.get(year) - calculateConcessionForMonth(month, concessionLineItem));
            }
        }
        return rentsByYears;
    }

    private Double calculateConcessionForMonth(Integer month, SBQQ__QuoteLine__c concessionLineItem) {
        Double concessionForYear = 0;
        if (month > concessionLineItem.Start_Term__c && month <= concessionLineItem.Start_Term__c + concessionLineItem.Term__c) {
            concessionForYear = concessionLineItem.Discount_Total__c / concessionLineItem.Term__c;
        }
        return concessionForYear;
    }
}