src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The quote where the order is created from.</description>
        <inlineHelpText>The quote where the order is created from.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Direct_Debit_Form_Developer_Name__c</fullName>
        <formula>Company__r.Direct_Debit_Form_Developer_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Direct Debit Form Developer Name</label>
        <type>Text</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>Pay_by_BACs_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The system field (not for users) will be checked when Pay by BACs request is approved.</description>
        <label>Pay by BACs Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Pay_by_BACs__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Once a user checks the field, Pay by BACs approval process will be started.</description>
        <label>Pay by BACs</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Quote Lines (Property)</relationshipLabel>
        <relationshipName>QuoteLines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SBQQ__RelatedContent__c.object
<CustomObject>
    <description>Links certain marketing content (datasheets, specifications, case study) to a product or a template.</description>
    <fields>
        <fullName>SBQQ__DisplayOrder__c</fullName>
        <description>The order in which this item will appear to a sales user in the Related Content menu. If blank, the content will be sorted last.</description>
        <inlineHelpText>Set the order in which this item will appear to a sales user in the Related Content menu. If blank, the content will be sorted last.</inlineHelpText>
        <label>Display Order</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__ExternalId__c</fullName>
        <description>ID of the record that contains the actual content. Eg: Document or Salesforce Content.</description>
        <inlineHelpText>Record ID that contains the content, such as document or Salesforce content.</inlineHelpText>
        <label>External Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote related to this content.</description>
        <inlineHelpText>Quote related to this content.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipName>RelatedContent</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Additional Document</label>
    <nameField>
        <label>Additional Document</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Additional Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AbstractQuoteDocumentGenerator.cls
public abstract class AbstractQuoteDocumentGenerator extends QuoteVisualforceDocumentGenerator implements QuoteDocumentGenerator {

    public static final String CAR_PARKING_DOCUMENT_NAME = 'Car Parking Licence Document';
    public static final String DIRECT_DEBIT_DOCUMENT_NAME = 'Direct Debit Form';

    public abstract void updateAdditionalDocuments(SBQQ__Quote__c quote, Map<String, String> documentParams);

    public void updateAdditionalDocuments(SBQQ__Quote__c quote) {
        updateAdditionalDocuments(quote, new Map<String, String>());
    }

    protected SBQQ__RelatedContent__c generateNewDocumentVersion(SBQQ__Quote__c quote, Id documentId, String documentName) {
        return generateNewDocumentVersion(quote, documentId, documentName, 0);
    }

    protected SBQQ__RelatedContent__c generateNewDocumentVersion(SBQQ__Quote__c quote, Id documentId, String documentName, Integer order) {
        SBQQ__RelatedContent__c quoteDocument = new SBQQ__RelatedContent__c(Name = documentName, SBQQ__ExternalId__c = documentId, SBQQ__Quote__c = quote.Id, SBQQ__DisplayOrder__c = order);
        insert quoteDocument;
        return quoteDocument;
    }

    protected void removePreviousDocumentVersion(SBQQ__Quote__c quote, Set<String> documentNames) {
        for (String documentName : documentNames) {
            documentName += documentName + '.pdf';
        }
        delete [SELECT Id FROM Attachment WHERE parentId = :quote.Id AND Name IN :documentNames];
        delete [SELECT Id FROM SBQQ__RelatedContent__c WHERE SBQQ__Quote__c = :quote.Id AND Name IN :documentNames];
    }

    protected Boolean isSignatureProcess(Map<String, String> params) {
        if (params.containsKey(QuoteDocumentParams.SEND_FOR_KEY_NAME)) {
            return params.get(QuoteDocumentParams.SEND_FOR_KEY_NAME) == QuoteDocumentParams.SIGNATURE;
        }
        return false;
    }

    protected Boolean isOfflineDocumentSending(Map<String, String> params) {
        if (params.containsKey(QuoteDocumentParams.SEND_OFFLINE_DOCUMENT)) {
            return params.get(QuoteDocumentParams.SEND_OFFLINE_DOCUMENT) == QuoteDocumentParams.SEND_OFFLINE_DOCUMENT;
        }
        return false;
    }

    protected Boolean isDocumentRequired(Map<String, String> params){
        return !isOfflineDocumentSending(params) && isSignatureProcess(params);
    }

    protected void generateCarParkingLicenceDocument(SBQQ__Quote__c quote, List<SBQQ__QuoteLine__c> lines, Map<String, String> params, Integer order, Boolean required) {
        //Car Parking Licence Document should be generated only if Car Parking Licence is added
        if (SBQQ_QuoteService.isHeadLineProductAdded(lines, QuoteProductCodes.CAR_PARKING_LICENSE)) {
            generateNewDocumentVersion(quote, Page.CarParkingLicenceDocumentGenerator, CAR_PARKING_DOCUMENT_NAME, params, order, required);
        }
    }

    protected void generateNewDirectDebitDocument(SBQQ__Quote__c quote) {
        // Direct Debit form should be generated only if Pay by BACs option isn't selected.
        // If Pay by BACs option is selected and approved, a customer will not pay trough Direct Debit form.
        if (quote.Property__c != null && !(quote.Pay_by_BACs__c && quote.Pay_by_BACs_Approved__c)) {
            Property__c property = [SELECT Id, Direct_Debit_Form_Developer_Name__c FROM Property__c WHERE Id = :quote.Property__c];
            List<Document> documents = [SELECT Id FROM Document WHERE DeveloperName = :property.Direct_Debit_Form_Developer_Name__c LIMIT 1];
            if (!documents.isEmpty()) {
                generateNewDocumentVersion(quote, documents.get(0).Id, DIRECT_DEBIT_DOCUMENT_NAME, 2);
            }
        }
    }
}