src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The quote where the order is created from.</description>
        <inlineHelpText>The quote where the order is created from.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <recordTypes>
        <fullName>Virtual</fullName>
        <active>true</active>
        <label>Virtual</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__RelatedContent__c.object
<CustomObject>
    <description>Links certain marketing content (datasheets, specifications, case study) to a product or a template.</description>
    <fields>
        <fullName>Manual_Upload__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Determines if the document is manually uploaded by a user</description>
        <inlineHelpText>Determines if the document is manually uploaded by a user</inlineHelpText>
        <label>Manual Upload</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__DisplayOrder__c</fullName>
        <description>The order in which this item will appear to a sales user in the Related Content menu. If blank, the content will be sorted last.</description>
        <inlineHelpText>Set the order in which this item will appear to a sales user in the Related Content menu. If blank, the content will be sorted last.</inlineHelpText>
        <label>Display Order</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__ExternalId__c</fullName>
        <description>ID of the record that contains the actual content. Eg: Document or Salesforce Content.</description>
        <inlineHelpText>Record ID that contains the content, such as document or Salesforce content.</inlineHelpText>
        <label>External Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote related to this content.</description>
        <inlineHelpText>Quote related to this content.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipName>RelatedContent</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether this content as required for this product.</description>
        <inlineHelpText>Select the checkbox if this content is required for the product. Users must include it when generating a quote document.</inlineHelpText>
        <label>Required</label>
        <type>Checkbox</type>
    </fields>
    <label>Additional Document</label>
    <nameField>
        <label>Additional Document</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Additional Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/QuoteVisualforceDocumentGenerator.cls
public virtual class QuoteVisualforceDocumentGenerator {

    public void generateNewDocumentVersion(SBQQ__Quote__c quote, PageReference pdfTemplate, String documentName) {
        generateNewDocumentVersion(quote, pdfTemplate, documentName, new Map<String, String>());
    }

    public void generateNewDocumentVersion(SBQQ__Quote__c quote, PageReference pdfTemplate, String documentName, Integer order) {
        generateNewDocumentVersion(quote, pdfTemplate, documentName, new Map<String, String>(), order);
    }

    public void generateNewDocumentVersion(SBQQ__Quote__c quote, PageReference pdfTemplate, String documentName, Map<String, String> params) {
        generateNewDocumentVersion(quote, pdfTemplate, documentName, params, false);
    }

    public void generateNewDocumentVersion(SBQQ__Quote__c quote, PageReference pdfTemplate, String documentName, Map<String, String> params, Boolean required) {
        generateNewDocumentVersion(quote, pdfTemplate, documentName, params, 0, required);
    }

    public void generateNewDocumentVersion(SBQQ__Quote__c quote, PageReference pdfTemplate, String documentName, Map<String, String> params, Integer order) {
        generateNewDocumentVersion(quote, pdfTemplate, documentName, params, order, false);
    }

    public void generateNewDocumentVersion(SBQQ__Quote__c quote, PageReference pdfTemplate, String documentName, Map<String, String> params, Integer order, Boolean required) {
        pdfTemplate.getParameters().put('id', quote.Id);
        pdfTemplate.getParameters().putAll(params);
        Attachment attach = new Attachment(parentId = quote.Id, name = documentName + '.pdf', body = getContent(pdfTemplate));
        insert attach;
        SBQQ__RelatedContent__c quoteDocument;
        quoteDocument = new SBQQ__RelatedContent__c(Name = documentName, SBQQ__ExternalId__c = attach.Id, SBQQ__Quote__c = quote.Id, SBQQ__DisplayOrder__c = order, SBQQ__Required__c = required, Manual_Upload__c = false);
        insert quoteDocument;
    }


    private Blob getContent(PageReference pdfTemplate) {
        Blob templateContent;
        // getContent() method isn't supported over tests
        if (!Test.IsRunningTest()) {
            templateContent = pdfTemplate.getContent();
        } else {
            templateContent = Blob.valueOf('Unit Test');
        }
        return templateContent;
    }
}