src/objects/Potential_Contact__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Potential Contact</label>
    <nameField>
        <displayFormat>PC-{000000000}</displayFormat>
        <label>Potential Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Potential Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>SBQQ__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
        <inlineHelpText>The customer account for this quote. Defaults to the account for the opportunity when creating a quote.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__QuoteDocument__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteDocumentHelp</customHelpPage>
    <description>Particular version of a generated PDF document for the quote it&apos;s attached to. Ability to edit or delete this object should be taken away from all users (except administrators, of course) in order to preserve audit trail of all revisions.</description>
    <fields>
        <fullName>BC_Contact_Preference__c</fullName>
        <label>BC Contact Preference</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Contact_Communication_Channel</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>BC_Email__c</fullName>
        <label>BC Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BC_First_Name__c</fullName>
        <label>BC First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BC_Last_Name__c</fullName>
        <label>BC Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BC_Mobile__c</fullName>
        <label>BC Mobile</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BC_Phone__c</fullName>
        <label>BC Phone</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ILPC_Contact_Preference__c</fullName>
        <label>ILPC Contact Preference</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Contact_Communication_Channel</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ILPC_Email__c</fullName>
        <label>ILPC Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ILPC_First_Name__c</fullName>
        <label>ILPC First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ILPC_Last_Name__c</fullName>
        <label>ILPC Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ILPC_Mobile__c</fullName>
        <label>ILPC Mobile</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ILPC_Phone__c</fullName>
        <label>ILPC Phone</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LC_Contact_Preference__c</fullName>
        <label>LC Contact Preference</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Contact_Communication_Channel</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>LC_Email__c</fullName>
        <label>LC Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LC_First_Name__c</fullName>
        <label>LC First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LC_Last_Name__c</fullName>
        <label>LC Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LC_Mobile__c</fullName>
        <label>LC Mobile</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LC_Phone__c</fullName>
        <label>LC Phone</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OOHC_Contact_Preference__c</fullName>
        <label>OOHC Contact Preference</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Contact_Communication_Channel</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>OOHC_Email__c</fullName>
        <label>OOHC Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OOHC_First_Name__c</fullName>
        <label>OOHC First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OOHC_Last_Name__c</fullName>
        <label>OOHC Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OOHC_Mobile__c</fullName>
        <label>OOHC Mobile</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OOHC_Phone__c</fullName>
        <label>OOHC Phone</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Owner_Id__c</fullName>
        <formula>SBQQ__Quote__r.SBQQ__Opportunity2__r.OwnerId</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity Owner Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_Contact_Preference__c</fullName>
        <label>PMC Contact Preference</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Contact_Communication_Channel</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMC_Email__c</fullName>
        <label>PMC Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_First_Name__c</fullName>
        <label>PMC First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_Last_Name__c</fullName>
        <label>PMC Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_Mobile__c</fullName>
        <label>PMC Mobile</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PMC_Phone__c</fullName>
        <label>PMC Phone</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this Quote Document belongs.</description>
        <inlineHelpText>Quote to which this Quote Document belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Documents</relationshipLabel>
        <relationshipName>R00N70000001lX7YEAU</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PotentialContactServiceTest.cls
/**
 * @description Test class fro PotentialContactService
 */
@isTest
private class PotentialContactServiceTest {

    @testSetup
    public static void setupData() {
        Account testAccount = RecordDmlTest.createAccount();
        List<Contact> testContacts = new List<Contact> {
            RecordDmlTest.createContact(testAccount.Id, SBQQ_QuoteConstants.CONTACT_TYPE_LC),
            RecordDmlTest.createContact(testAccount.Id, SBQQ_QuoteConstants.CONTACT_TYPE_ILPC),
            RecordDmlTest.createContact(testAccount.Id, SBQQ_QuoteConstants.CONTACT_TYPE_OOHC),
            RecordDmlTest.createContact(testAccount.Id, SBQQ_QuoteConstants.CONTACT_TYPE_BC)
        };
        insert testContacts;
        SBQQ__Quote__c quote = RecordDmlTest.generateConventionalQuoteWithLines(QuoteProductCodes.OFFICE_RENT);

        Test.startTest();
        SBQQ.TriggerControl.disable();
        quote.SBQQ__Account__c = testAccount.Id;
        update quote;
        SBQQ__QuoteDocument__c quoteDocument = new SBQQ__QuoteDocument__c(
            SBQQ__Quote__c= quote.Id
        );
        insert quoteDocument;
        Test.stopTest();    
    }

    @isTest
    private static void testCreatioOfPotentialCustomers() {
        //given
        SBQQ__Quote__c quote = [SELECT Id, SBQQ__Account__c FROM SBQQ__Quote__c LIMIT 1];
        Map<Id, SBQQ__QuoteDocument__c> quoteDocumentsMap = new Map<Id, SBQQ__QuoteDocument__c>([SELECT LC_First_Name__c, LC_Last_Name__c, LC_Email__c, LC_Phone__c, LC_Mobile__c, LC_Contact_Preference__c,
                                                                                                        BC_First_Name__c, BC_Last_Name__c, BC_Email__c, BC_Phone__c, BC_Mobile__c, BC_Contact_Preference__c,
                                                                                                        PMC_First_Name__c, PMC_Last_Name__c, PMC_Email__c, PMC_Phone__c, PMC_Mobile__c, PMC_Contact_Preference__c,
                                                                                                        ILPC_First_Name__c, ILPC_Last_Name__c, ILPC_Email__c, ILPC_Phone__c, ILPC_Mobile__c, ILPC_Contact_Preference__c,
                                                                                                        OOHC_First_Name__c, OOHC_Last_Name__c, OOHC_Email__c, OOHC_Phone__c, OOHC_Mobile__c, OOHC_Contact_Preference__c,
                                                                                                        SBQQ__Quote__c, Opportunity_Owner_Id__c
                                                                                                FROM SBQQ__QuoteDocument__c]);
        List<SBQQ__QuoteDocument__c> newQuoteDocuments = quoteDocumentsMap.values().deepClone(true);
        for ( SBQQ__QuoteDocument__c theDocument : newQuoteDocuments ) {
            theDocument.LC_First_Name__c = 'Test new';
            theDocument.LC_Last_Name__c = 'Contact';
            theDocument.BC_Email__c = 'test@test.com';
            theDocument.BC_Phone__c = '987654321';
        }
        SBQQ_QuoteDocumentService theDocumentService = new SBQQ_QuoteDocumentService();
        Map<SBQQ__QuoteDocument__c, Set<String>> updatedDocumentsMap = theDocumentService.getDocumentsWithUpdatedContactInfo(quoteDocumentsMap, newQuoteDocuments);

        //when
        Test.startTest();
        PotentialContactService thePotentialContactService = new PotentialContactService();
        thePotentialContactService.createPotentialContactsForUpdatedDocuments(updatedDocumentsMap, quoteDocumentsMap);

        //then
        List<Potential_Contact__c> potentialContacts = [SELECT First_Name__c, Last_Name__c, New_First_Name__c, New_Last_Name__c
                                                        FROM Potential_Contact__c];
        System.assertNotEquals(true, potentialContacts.isEmpty());
        System.assertEquals(2, potentialContacts.size());
        Test.stopTest();
    }

    @isTest
    private static void testCreatioOfSamePotentialCustomers() {
        SBQQ__Quote__c quote = [SELECT Id, SBQQ__Account__c FROM SBQQ__Quote__c LIMIT 1];
        Map<Id, SBQQ__QuoteDocument__c> quoteDocumentsMap = new Map<Id, SBQQ__QuoteDocument__c>([SELECT LC_First_Name__c, LC_Last_Name__c, LC_Email__c, LC_Phone__c, LC_Mobile__c, LC_Contact_Preference__c,
                                                                                                        BC_First_Name__c, BC_Last_Name__c, BC_Email__c, BC_Phone__c, BC_Mobile__c, BC_Contact_Preference__c,
                                                                                                        PMC_First_Name__c, PMC_Last_Name__c, PMC_Email__c, PMC_Phone__c, PMC_Mobile__c, PMC_Contact_Preference__c,
                                                                                                        ILPC_First_Name__c, ILPC_Last_Name__c, ILPC_Email__c, ILPC_Phone__c, ILPC_Mobile__c, ILPC_Contact_Preference__c,
                                                                                                        OOHC_First_Name__c, OOHC_Last_Name__c, OOHC_Email__c, OOHC_Phone__c, OOHC_Mobile__c, OOHC_Contact_Preference__c,
                                                                                                        SBQQ__Quote__c, Opportunity_Owner_Id__c
                                                                                                FROM SBQQ__QuoteDocument__c]);
        List<SBQQ__QuoteDocument__c> newQuoteDocuments = quoteDocumentsMap.values().deepClone(true);
        for ( SBQQ__QuoteDocument__c theDocument : newQuoteDocuments ) {
            theDocument.LC_First_Name__c = 'Test new';
            theDocument.LC_Last_Name__c = 'Contact';
            theDocument.LC_Email__c = 'test@email.com';
            theDocument.BC_First_Name__c = 'Test new';
            theDocument.BC_Last_Name__c = 'Contact';
            theDocument.BC_Email__c = 'test@email.com';
        }
        SBQQ_QuoteDocumentService theDocumentService = new SBQQ_QuoteDocumentService();
        Map<SBQQ__QuoteDocument__c, Set<String>> updatedDocumentsMap = theDocumentService.getDocumentsWithUpdatedContactInfo(quoteDocumentsMap, newQuoteDocuments);

        //when
        Test.startTest();
        PotentialContactService thePotentialContactService = new PotentialContactService();
        thePotentialContactService.createPotentialContactsForUpdatedDocuments(updatedDocumentsMap, quoteDocumentsMap);

        //then
        List<Potential_Contact__c> potentialContacts = [SELECT First_Name__c, Last_Name__c, New_First_Name__c, New_Last_Name__c
                                                        FROM Potential_Contact__c];
        System.assertNotEquals(true, potentialContacts.isEmpty());
        System.assertEquals(1, potentialContacts.size());
        Test.stopTest();
    }
}