src/objects/PriceRule__c.object
<CustomObject>
    <description>Rule that affects pricing for an option or quote line</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether this rule is active or not.</description>
        <inlineHelpText>Indicates whether this rule is active or not.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AdvancedCondition__c</fullName>
        <description>Can only be entered if the Conditions Met is Custom. Enter a combination of the Price Condition Index #s, AND, OR, and parenthesis (e.g. (123 AND 124) AND 125).</description>
        <inlineHelpText>Can only be entered if the Conditions Met is Custom. Enter a combination of the Price Condition Index #s, AND, OR, and parenthesis (e.g. (123 AND 124) AND 125).</inlineHelpText>
        <label>Advanced Condition</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CPQ_Config_Version__c</fullName>
        <label>CPQ Config Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ConditionsMet__c</fullName>
        <description>Choose the behavior for your conditions: All is AND, Any is OR, Custom is a combination of AND/OR.</description>
        <inlineHelpText>Choose the behavior for your conditions: All is AND, Any is OR, Custom is a combination of AND/OR.</inlineHelpText>
        <label>Conditions Met</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>All</fullName>
                    <default>true</default>
                    <label>All</label>
                </value>
                <value>
                    <fullName>Any</fullName>
                </value>
                <value>
                    <fullName>Custom</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ConfiguratorEvaluationEvent__c</fullName>
        <description>Event that specifies when Price Rules should be fired.</description>
        <inlineHelpText>When None or Save is selected, the Configurator scoped price rules will fire on save.  When Edit is selected, the Configurator scoped price rules will fire on edit and save.</inlineHelpText>
        <label>Configurator Evaluation Event</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Save</fullName>
                </value>
                <value>
                    <fullName>Edit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EvaluationEvent__c</fullName>
        <description>Event that causes this rule to be evaluated.</description>
        <inlineHelpText>Specify when this rule should be evaluated. Only to be used when targeting Quote Line and not supported on legacy calculator.</inlineHelpText>
        <label>Calculator Evaluation Event</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>On Initialization</fullName>
                </value>
                <value>
                    <fullName>Before Calculate</fullName>
                </value>
                <value>
                    <fullName>On Calculate</fullName>
                    <default>true</default>
                    <label>On Calculate</label>
                </value>
                <value>
                    <fullName>After Calculate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EvaluationOrder__c</fullName>
        <description>Order in which this price rule is evaluated.</description>
        <inlineHelpText>Specify the order of evaluation for this price rule. Higher ordered rules are evaluated last which means they &quot;win&quot; in case of conflict.</inlineHelpText>
        <label>Evaluation Order</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Load_Id__c</fullName>
        <externalId>true</externalId>
        <label>Load Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LookupObject__c</fullName>
        <description>API Name of the Custom Object that stores the lookup data.</description>
        <inlineHelpText>API Name of the Custom Object that stores the lookup data.</inlineHelpText>
        <label>Lookup Object</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Car_Parking_Inventory__c</fullName>
                </value>
                <value>
                    <fullName>Inventory__c</fullName>
                </value>
                <value>
                    <fullName>Product2</fullName>
                </value>
                <value>
                    <fullName>Property__c</fullName>
                </value>
                <value>
                    <fullName>SBQQ__LookupData__c</fullName>
                </value>
                <value>
                    <fullName>SBQQ__Quote__c</fullName>
                </value>
                <value>
                    <fullName>SBQQ__QuoteLine__c</fullName>
                </value>
                <value>
                    <fullName>Suite_Inventory__c</fullName>
                </value>
                <value>
                    <fullName>Test__c</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Optional field that makes this rule specific to the product.</description>
        <inlineHelpText>Choose a product to associate to this rule.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Price Rules</relationshipLabel>
        <relationshipName>PriceRules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TargetObject__c</fullName>
        <description>Object that’s the target of the field update.</description>
        <inlineHelpText>Event during which this rule is evaluated.</inlineHelpText>
        <label>Evaluation Scope</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Configurator</fullName>
                </value>
                <value>
                    <fullName>Calculator</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Price Rule</label>
    <nameField>
        <label>Price Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>CPQ_Config_Version__c</fullName>
        <label>CPQ Config Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Load_Id__c</fullName>
        <externalId>true</externalId>
        <label>Load Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__PriceRule__c.object
<CustomObject>
    <customHelpPage>SBQQ__PriceRuleHelp</customHelpPage>
    <description>Rule that affects pricing for an option or quote line</description>
    <fields>
        <fullName>CPQ_Config_Version__c</fullName>
        <label>CPQ Config Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Load_Id__c</fullName>
        <externalId>true</externalId>
        <label>Load Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether this rule is active or not.</description>
        <inlineHelpText>Indicates whether this rule is active or not.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__AdvancedCondition__c</fullName>
        <description>Can only be entered if the Conditions Met is Custom. Enter a combination of the Price Condition Index #s, AND, OR, and parenthesis (e.g. (123 AND 124) AND 125).</description>
        <inlineHelpText>Can only be entered if the Conditions Met is Custom. Enter a combination of the Price Condition Index #s, AND, OR, and parenthesis (e.g. (123 AND 124) AND 125).</inlineHelpText>
        <label>Advanced Condition</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SBQQ__ConditionsMet__c</fullName>
        <description>Choose the behavior for your conditions: All is AND, Any is OR, Custom is a combination of AND/OR.</description>
        <inlineHelpText>Choose the behavior for your conditions: All is AND, Any is OR, Custom is a combination of AND/OR.</inlineHelpText>
        <label>Conditions Met</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>All</fullName>
                    <default>true</default>
                    <label>All</label>
                </value>
                <value>
                    <fullName>Any</fullName>
                </value>
                <value>
                    <fullName>Custom</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__ConfiguratorEvaluationEvent__c</fullName>
        <description>Event that specifies when Price Rules should be fired.</description>
        <inlineHelpText>When None or Save is selected, the Configurator scoped price rules will fire on save.  When Edit is selected, the Configurator scoped price rules will fire on edit and save.</inlineHelpText>
        <label>Configurator Evaluation Event</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Save</fullName>
                </value>
                <value>
                    <fullName>Edit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__EvaluationEvent__c</fullName>
        <description>Event that causes this rule to be evaluated.</description>
        <inlineHelpText>Specify when this rule should be evaluated. Only to be used when targeting Quote Line and not supported on legacy calculator.</inlineHelpText>
        <label>Calculator Evaluation Event</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>On Initialization</fullName>
                </value>
                <value>
                    <fullName>Before Calculate</fullName>
                </value>
                <value>
                    <fullName>On Calculate</fullName>
                    <default>true</default>
                    <label>On Calculate</label>
                </value>
                <value>
                    <fullName>After Calculate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__EvaluationOrder__c</fullName>
        <description>Order in which this price rule is evaluated.</description>
        <inlineHelpText>Specify the order of evaluation for this price rule. Higher ordered rules are evaluated last which means they &quot;win&quot; in case of conflict.</inlineHelpText>
        <label>Evaluation Order</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__LookupObject__c</fullName>
        <description>API Name of the Custom Object that stores the lookup data.</description>
        <inlineHelpText>API Name of the Custom Object that stores the lookup data.</inlineHelpText>
        <label>Lookup Object</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Car_Parking_Inventory__c</fullName>
                </value>
                <value>
                    <fullName>Inventory__c</fullName>
                </value>
                <value>
                    <fullName>Product2</fullName>
                </value>
                <value>
                    <fullName>Property__c</fullName>
                </value>
                <value>
                    <fullName>SBQQ__LookupData__c</fullName>
                </value>
                <value>
                    <fullName>SBQQ__Quote__c</fullName>
                </value>
                <value>
                    <fullName>SBQQ__QuoteLine__c</fullName>
                </value>
                <value>
                    <fullName>Suite_Inventory__c</fullName>
                </value>
                <value>
                    <fullName>Test__c</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Optional field that makes this rule specific to the product.</description>
        <inlineHelpText>Choose a product to associate to this rule.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Price Rules</relationshipLabel>
        <relationshipName>PriceRules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__TargetObject__c</fullName>
        <description>Object that’s the target of the field update.</description>
        <inlineHelpText>Event during which this rule is evaluated.</inlineHelpText>
        <label>Evaluation Scope</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Configurator</fullName>
                </value>
                <value>
                    <fullName>Calculator</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Price Rule</label>
    <nameField>
        <label>Price Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PriceRuleTriggerHandlerTest.cls
@IsTest
public class PriceRuleTriggerHandlerTest {
    @IsTest
    static void testInsert() {
        Product2 product = RecordDmlTest.createProducts().get(0);

        PriceRule__c priceRule = new PriceRule__c();

        priceRule.Load_Id__c = 'testLoadId';
        priceRule.Name = 'Test Name';
        priceRule.CurrencyIsoCode = 'GBP';
        priceRule.Active__c = true;
        priceRule.AdvancedCondition__c = '(10 AND (20 OR 30))';
        priceRule.ConditionsMet__c = 'Custom';
        priceRule.ConfiguratorEvaluationEvent__c = 'Empty';
        priceRule.EvaluationEvent__c = 'On Calculate';
        priceRule.EvaluationOrder__c = 500;
        priceRule.LookupObject__c = 'Product2';
        priceRule.Product__c = product.Id;
        priceRule.TargetObject__c = 'Calculator';
        priceRule.CPQ_Config_Version__c = 10;

        List<PriceRule__c> priceRules = new List<PriceRule__c>{
                priceRule
        };

        insert priceRules;

        // price rule created
        System.assertEquals(1, [SELECT COUNT() FROM SBQQ__PriceRule__c]);

        //migration objects removed
        System.assertEquals(0, [SELECT COUNT() FROM PriceRule__c]);

        SBQQ__PriceRule__c cpqPriceRule = [
                SELECT Id, Name, Load_Id__c, CurrencyIsoCode, SBQQ__Active__c, SBQQ__AdvancedCondition__c,
                        SBQQ__ConditionsMet__c, SBQQ__ConfiguratorEvaluationEvent__c, SBQQ__EvaluationEvent__c,
                        SBQQ__LookupObject__c, SBQQ__Product__c, SBQQ__EvaluationOrder__c, SBQQ__TargetObject__c,
                        CPQ_Config_Version__c
                FROM SBQQ__PriceRule__c
        ];

        //all fields populated
        System.assertEquals(priceRule.Load_Id__c, cpqPriceRule.Load_Id__c);
        System.assertEquals(priceRule.Name, cpqPriceRule.Name);
        System.assertEquals(priceRule.CurrencyIsoCode, cpqPriceRule.CurrencyIsoCode);
        System.assertEquals(priceRule.Active__c, cpqPriceRule.SBQQ__Active__c);
        System.assertEquals(priceRule.AdvancedCondition__c, cpqPriceRule.SBQQ__AdvancedCondition__c);
        System.assertEquals(priceRule.ConditionsMet__c, cpqPriceRule.SBQQ__ConditionsMet__c);
        System.assertEquals(priceRule.ConfiguratorEvaluationEvent__c, cpqPriceRule.SBQQ__ConfiguratorEvaluationEvent__c);
        System.assertEquals(priceRule.EvaluationEvent__c, cpqPriceRule.SBQQ__EvaluationEvent__c);
        System.assertEquals(priceRule.LookupObject__c, cpqPriceRule.SBQQ__LookupObject__c);
        System.assertEquals(priceRule.Product__c, cpqPriceRule.SBQQ__Product__c);
        System.assertEquals(priceRule.EvaluationOrder__c, cpqPriceRule.SBQQ__EvaluationOrder__c);
        System.assertEquals(priceRule.TargetObject__c, cpqPriceRule.SBQQ__TargetObject__c);
        System.assertEquals(priceRule.CPQ_Config_Version__c, cpqPriceRule.CPQ_Config_Version__c);
    }
}