src/objects/PriceRule__c.object
<CustomObject>
    <description>Rule that affects pricing for an option or quote line</description>
    <fields>
        <fullName>Load_Id__c</fullName>
        <externalId>true</externalId>
        <label>Load Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Price Rule</label>
    <nameField>
        <label>Price Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__PriceRule__c.object
<CustomObject>
    <customHelpPage>SBQQ__PriceRuleHelp</customHelpPage>
    <description>Rule that affects pricing for an option or quote line</description>
    <fields>
        <fullName>Load_Id__c</fullName>
        <externalId>true</externalId>
        <label>Load Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Price Rule</label>
    <nameField>
        <label>Price Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PriceRuleTriggerHandler.cls
public class PriceRuleTriggerHandler extends TriggerHandler {

    protected override void beforeInsert() {
        List<PriceRule__c> priceRules = Trigger.new;
        List<SBQQ__PriceRule__c> cpqPriceRules = new List<SBQQ__PriceRule__c>();
        for (PriceRule__c priceRule : priceRules) {
            cpqPriceRules.add((SBQQ__PriceRule__c) CpqObjectsTransformer.populateCPQObject(priceRule, new SBQQ__PriceRule__c()));
        }
        SBQQ.TriggerControl.disable();
        Database.upsert(cpqPriceRules, SBQQ__PriceRule__c.Load_Id__c);
    }

    protected override void afterInsert() {
        delete [select Id from PriceRule__c];
    }
}