src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>HoT_Type__c</fullName>
        <label>HoT Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Property_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Properties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reception__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reception</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Properties6</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EventTriggerHandlerTest.cls
/**
 * Created by v2.nareyko on 29.04.18.
 */

@IsTest
private class EventTriggerHandlerTest {

    @isTest
    static void givenPropertyWhenViewingCreatedThenEventRelationsCreated() {
        // given
        Property__c property = RecordDmlTest.createProperty();
        User propertyManager = RecordDmlTest.createUser();
        User receptionUser = RecordDmlTest.createUser();
        property.Reception__c = receptionUser.Id;
        property.Property_Manager__c = propertyManager.Id;
        update property;
        Product2 product = new Product2(Name = 'Car Parking License', Productcode = 'CarParkLicense', Family = 'Car space', HOT_TYPE__C = 'CarParkLicense', IsActive = true);
        insert product;
        Opportunity opportunity = RecordDmlTest.createOpportunity(OpportunityService.CONVENTIONAL_RECORD_TYPE);

        // when
        RecordDmlTest.createViewingEvent(RecordDmlTest.createContact().Id, opportunity.Id, property.Id);

        // then
        System.assertEquals(1, [SELECT Id FROM EventRelation WHERE RelationId = :propertyManager.Id].size());
        System.assertEquals(1, [SELECT Id FROM EventRelation WHERE RelationId = :receptionUser.Id].size());
    }
}