src/objects/ProductRule__c.object
<CustomObject>
    <description>Rule that governs valid product configurations.</description>
    <fields>
        <fullName>Load_Id__c</fullName>
        <externalId>true</externalId>
        <label>Load Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Product Rule</label>
    <nameField>
        <label>Product Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__ProductRule__c.object
<CustomObject>
    <customHelpPage>SBQQ__ProductRuleHelp</customHelpPage>
    <description>Rule that governs valid product configurations.</description>
    <fields>
        <fullName>Load_Id__c</fullName>
        <externalId>true</externalId>
        <label>Load Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Product Rule</label>
    <nameField>
        <label>Product Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProductRuleTriggerHandler.cls
public class ProductRuleTriggerHandler extends TriggerHandler {

    protected override void beforeInsert() {
        List<ProductRule__c> productRules = Trigger.new;
        List<SBQQ__ProductRule__c> cpqProductRules = new List<SBQQ__ProductRule__c>();
        for (ProductRule__c productRule : productRules) {
            cpqProductRules.add((SBQQ__ProductRule__c) CpqObjectsTransformer.populateCPQObject(productRule, new SBQQ__ProductRule__c(Name='TestName')));
        }
        SBQQ.TriggerControl.disable();
        Database.upsert(cpqProductRules, SBQQ__ProductRule__c.Load_Id__c);
    }

    protected override void afterInsert(){
        delete [select Id from ProductRule__c];
    }
}