src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>HoT_Type__c</fullName>
        <label>HoT Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>SBQQ__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
        <inlineHelpText>The customer account for this quote. Defaults to the account for the opportunity when creating a quote.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>Break_Date__c</fullName>
        <label>Break Date</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Break_Penalty__c</fullName>
        <label>Break Penalty (£)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Maximum_Notice__c</fullName>
        <label>Maximum Notice</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Minimum_Notice__c</fullName>
        <label>Minimum Notice</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product quoted by this line item.</description>
        <inlineHelpText>Product quoted by this line item.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>R00N70000001lXB6EAM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ConventionalTermDocumentGeneratorTest.cls
@isTest
public class ConventionalTermDocumentGeneratorTest {

    @isTest static void generateConventionalTermDocument() {

        SBQQ__Quote__c quote = RecordDmlTest.generateConventionalQuoteWithLines(QuoteProductCodes.OFFICE_RENT);
        Account acc = [
                SELECT Id, BillingStreet, BillingCity, BillingPostalCode, BillingCountry
                FROM Account
                WHERE Id = :quote.SBQQ__Account__c
        ];
        String address = '';
        address = String.isNotBlank(acc.BillingStreet) ? acc.BillingStreet + ' ' : '';
        address += String.isNotBlank(acc.BillingCity) ? acc.BillingCity + ' ' : '';
        address += String.isNotBlank(acc.BillingPostalCode) ? acc.BillingPostalCode + ' ' : '';
        address += String.isNotBlank(acc.BillingCountry) ? acc.BillingCountry : '';

        List<SBQQ__QuoteLine__c> qliList = [
                SELECT Id, Name, Break_Date__c, Minimum_Notice__c, Maximum_Notice__c, Break_Penalty__c
                FROM SBQQ__QuoteLine__c
                WHERE SBQQ__Quote__c = :quote.Id AND SBQQ__Product__r.Hot_Type__c = 'CustomerBreakOption'
        ];

        Test.StartTest();
        ApexPages.currentPage().getParameters().put('id', String.valueOf(quote.Id));
        ConventionalTermDocumentGenerator testTermDoc = new ConventionalTermDocumentGenerator();
        testTermDoc.init();
        System.assertEquals(address, testTermDoc.getAccountFullAddress());
        System.assertEquals(0, testTermDoc.getNumCarParking(ProductService.PRODUCT_CODE_CAR_PARKING_LICENSE));
        testTermDoc.getMapBreakOptions(QuoteProductCodes.CUSTOMER_BREAK_OPTION);
        testTermDoc.getMapBreakOptions(QuoteProductCodes.SUPPLIER_BREAK_OPTION);
        Test.StopTest();

    }

}