src/objects/Property__c.object
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__RelatedContent__c.object
<CustomObject>
    <description>Links certain marketing content (datasheets, specifications, case study) to a product or a template.</description>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote related to this content.</description>
        <inlineHelpText>Quote related to this content.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipName>RelatedContent</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Additional Document</label>
    <nameField>
        <label>Additional Document</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Additional Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ConventionalQuoteDocumentGeneratorTest.cls
@isTest
public class ConventionalQuoteDocumentGeneratorTest {

    @testSetup
    public static void initData() {
        SBQQ__Quote__c quote = RecordDmlTest.generateConventionalQuoteWithLines(QuoteProductCodes.OFFICE_RENT);
    }

    @isTest
    static void givenSBQQ_QuoteAndDocumentGenerator_whenAdditionalDocumentsUpdated_thenPricingAndTermsDocumentShouldBeGenerated() {
        //given
        SBQQ__Quote__c quote = [SELECT Id, Property__c FROM SBQQ__Quote__c LIMIT 1];
        QuoteDocumentGenerator documentGenerator = new ConventionalQuoteDocumentGenerator();

        //when
        documentGenerator.updateAdditionalDocuments(quote);

        //then
        System.assertEquals(1, [SELECT COUNT() FROM SBQQ__RelatedContent__c WHERE SBQQ__Quote__c = :quote.Id AND Name = :ConventionalQuoteDocumentGenerator.PRICING_DOCUMENT_NAME], 'Pricing document has not been created');
        System.assertEquals(1, [SELECT COUNT() FROM SBQQ__RelatedContent__c WHERE SBQQ__Quote__c = :quote.Id AND Name = :ConventionalQuoteDocumentGenerator.TERMS_DOCUMENT_NAME], 'Terms document has not been created');
    }

    @isTest
    static void givenSBQQ_QuoteAndDocumentGenerator_whenAdditionalDocumentsUpdatedSecondTime_thenPricingAndTermsDocumentShouldBeUpdatedWithNewVersions() {
        //given
        SBQQ__Quote__c quote = [SELECT Id, Property__c FROM SBQQ__Quote__c LIMIT 1];
        QuoteDocumentGenerator documentGenerator = new ConventionalQuoteDocumentGenerator();

        //when
        documentGenerator.updateAdditionalDocuments(quote);
        //Doesn't create a new documents, the previous document versions should be updated
        documentGenerator.updateAdditionalDocuments(quote);

        //then
        System.assertEquals(1, [SELECT COUNT() FROM SBQQ__RelatedContent__c WHERE SBQQ__Quote__c = :quote.Id AND Name = :ConventionalQuoteDocumentGenerator.PRICING_DOCUMENT_NAME], 'Pricing document has not been created or has been created twice');
        System.assertEquals(1, [SELECT COUNT() FROM SBQQ__RelatedContent__c WHERE SBQQ__Quote__c = :quote.Id AND Name = :ConventionalQuoteDocumentGenerator.TERMS_DOCUMENT_NAME], 'Terms document has not been created or has been created twice');
    }
}