src/objects/Property__c.object
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Quote_Template_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Stores details about which Quote Template Id should be applied for a particular sales process</description>
    <fields>
        <fullName>Conventional_Review_TemplateId__c</fullName>
        <label>Conventional Review Template Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Conventional_Signature_TemplateId__c</fullName>
        <label>Conventional Signature Template Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Serviced_Review_TemplateId__c</fullName>
        <label>Serviced Review Template Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Serviced_Signature_TemplateId__c</fullName>
        <label>Serviced Signature Template Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Virtual_Review_TemplateId__c</fullName>
        <label>Virtual Review Template Id</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Virtual_Signature_TemplateId__c</fullName>
        <label>Virtual Signature Template Id</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Quote Template Settings</label>
</CustomObject>

src/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>Pay_by_BACs_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The system field (not for users) will be checked when Pay by BACs request is approved.</description>
        <label>Pay by BACs Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Pay_by_BACs__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Once a user checks the field, Pay by BACs approval process will be started.</description>
        <label>Pay by BACs</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__QuoteTemplateId__c</fullName>
        <description>ID of quote template that must be used when generating documents from this quote.</description>
        <inlineHelpText>Stores a quote template ID if one is specified to use when generating quote PDF documents.</inlineHelpText>
        <label>Quote Template Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__Status__c</fullName>
        <description>Status indicating where quote is in its lifecycle.</description>
        <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Presented</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Pending Approval - Offline Edit</fullName>
                </value>
                <value>
                    <fullName>Awaiting Approval - Offline Edit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <recordTypes>
        <fullName>Conventional</fullName>
        <active>true</active>
        <label>Conventional</label>
    </recordTypes>
    <recordTypes>
        <fullName>Serviced</fullName>
        <active>true</active>
        <label>Serviced</label>
    </recordTypes>
    <recordTypes>
        <fullName>Virtual</fullName>
        <active>true</active>
        <label>Virtual</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Quote Lines (Property)</relationshipLabel>
        <relationshipName>QuoteLines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SBQQ__QuoteTemplate__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteTemplateHelp</customHelpPage>
    <description>Template that controls formatting of generated PDF documents.</description>
    <label>Quote Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__RelatedContent__c.object
<CustomObject>
    <description>Links certain marketing content (datasheets, specifications, case study) to a product or a template.</description>
    <fields>
        <fullName>Manual_Upload__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Determines if the document is manually uploaded by a user</description>
        <inlineHelpText>Determines if the document is manually uploaded by a user</inlineHelpText>
        <label>Manual Upload</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__QuoteTemplate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Template related to this content.</description>
        <inlineHelpText>Template related to this content.</inlineHelpText>
        <label>Quote Template</label>
        <referenceTo>SBQQ__QuoteTemplate__c</referenceTo>
        <relationshipLabel>Additional Documents</relationshipLabel>
        <relationshipName>ProductContent</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote related to this content.</description>
        <inlineHelpText>Quote related to this content.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipName>RelatedContent</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Additional Document</label>
    <nameField>
        <label>Additional Document</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Additional Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PreGenerateDocumentPageController.cls
public class PreGenerateDocumentPageController extends QuoteDocumentParams {

    public SBQQ__Quote__c quote { get; set; }
    private QuoteDocumentGenerator documentGenerator { get; set; }
    private ApexPages.StandardController stdController { get; set; }

    private Quote_Template_Settings__c templateSettings = Quote_Template_Settings__c.getOrgDefaults();

    public String sendFor { get; set; }
    public Boolean isOfflineDocumentAdded { get; set; }
    public Boolean isVirtualQuote { get; set; }

    public PreGenerateDocumentPageController(ApexPages.StandardController stdController) {
        this.stdController = stdController;
        quote = (SBQQ__Quote__c) stdController.getRecord();
        quote = [
                SELECT Id, SBQQ__QuoteTemplateId__c, RecordTypeId, RecordType.DeveloperName,
                        Property__c, Pay_by_BACs__c, Pay_by_BACs_Approved__c, (SELECT Id FROM SBQQ__LineItems__r)
                FROM SBQQ__Quote__c
                WHERE Id = :quote.Id
        ];
        loadDocumentGenerator(quote.RecordType.DeveloperName);
        isOfflineDocumentAdded = isOfflineDocumentAdded(quote);
        isVirtualQuote = quote.RecordType.DeveloperName == SBQQ_QuoteConstants.VIRTUAL_RECORD_TYPE
                || quote.RecordType.DeveloperName == SBQQ_QuoteConstants.VIRTUAL_LOCKED_RECORD_TYPE;
    }

    public PageReference redirectToQuote() {
        PageReference redirect = new PageReference('/' + quote.Id);
        redirect.setRedirect(true);
        return redirect;
    }

    public PageReference goToGenerateDocumentPage() {
        PageReference redirect;
        updateQuoteTemplate(quote.RecordType.DeveloperName);
        updateAdditionalDocuments();
        if (sendFor == GENERATE_OFFLINE_DOCUMENT) {
            update new SBQQ__Quote__c(Id = quote.Id, SBQQ__Status__c = SBQQ_QuoteConstants.STATUS_PENDING_APPROVAL_OFFLINE_EDIT);
            redirect = new PageReference('/apex/GenerateOfflineDocument?id=' + quote.Id);
        } else {
            redirect = new PageReference('/apex/SBQQ__GenerateDocument?id=' + quote.Id);
        }
        redirect.setRedirect(true);
        return redirect;
    }

    public void updateAdditionalDocuments() {
        Map<String, String> sendingOptions = new Map<String, String>();
        if (sendFor == SEND_OFFLINE_DOCUMENT || sendFor == GENERATE_OFFLINE_DOCUMENT) {
            sendingOptions.put(SEND_FOR_KEY_NAME, SIGNATURE);
            sendingOptions.put(SEND_OFFLINE_DOCUMENT, SEND_OFFLINE_DOCUMENT);
        } else {
            sendingOptions.put(SEND_FOR_KEY_NAME, sendFor);
        }
        documentGenerator.updateAdditionalDocuments(quote, sendingOptions);
    }

    private void loadDocumentGenerator(String recordTypeName) {
        if (recordTypeName.contains('Serviced')) {
            documentGenerator = new ServicedQuoteDocumentGenerator();
        } else if (recordTypeName.contains('Conventional')) {
            documentGenerator = new ConventionalQuoteDocumentGenerator();
        } else if (recordTypeName.contains('Virtual')) {
            documentGenerator = new VirtualQuoteDocumentGenerator();
        }
    }

    private void updateQuoteTemplate(String recordTypeName) {
        SBQQ__QuoteTemplate__c template;
        //Sending of offline documents should be done in frame of signature process
        if (!String.isBlank(sendFor)) {
            if (recordTypeName.contains('Serviced')) {
                if (sendFor == SIGNATURE || sendFor == SEND_OFFLINE_DOCUMENT) {
                    template = getTemplateById(templateSettings.Serviced_Signature_TemplateId__c);
                } else {
                    template = getTemplateById(templateSettings.Serviced_Review_TemplateId__c);
                }
            } else if (recordTypeName.contains('Conventional')) {
                if (sendFor == SIGNATURE || sendFor == SEND_OFFLINE_DOCUMENT) {
                    template = getTemplateById(templateSettings.Conventional_Signature_TemplateId__c);
                } else {
                    template = getTemplateById(templateSettings.Conventional_Review_TemplateId__c);
                }
            } else if (recordTypeName.contains('Virtual')) {
                if (sendFor == SIGNATURE || sendFor == SEND_OFFLINE_DOCUMENT) {
                    template = getTemplateById(templateSettings.Virtual_Signature_TemplateId__c);
                } else {
                    template = getTemplateById(templateSettings.Virtual_Review_TemplateId__c);
                }
            }
        }
        quote.SBQQ__QuoteTemplateId__c = template != null ? template.Id : null;
        update quote;
    }

    public static Boolean isOfflineDocumentAdded(SBQQ__Quote__c quote) {
        List<SBQQ__RelatedContent__c> additionalDocuments = [SELECT Id FROM SBQQ__RelatedContent__c WHERE SBQQ__Quote__c = :quote.Id AND Manual_Upload__c = true LIMIT 1];
        return additionalDocuments.size() == 1;
    }

    private SBQQ__QuoteTemplate__c getTemplateById(String templateId) {
        List<SBQQ__QuoteTemplate__c> templates = [SELECT Id FROM SBQQ__QuoteTemplate__c WHERE Id = :templateId LIMIT 1];
        if (!templates.isEmpty()) {
            return templates.get(0);
        }
        return null;
    }
}