src/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>Monthly_Average_Without_Discount__c</fullName>
        <label>Monthly Average Without Discount (£)</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Monthly_Cost__c</fullName>
        <label>Monthly Cost (£)</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SBQQ__ProductCode__c</fullName>
        <description>Code for the product referenced by this line.</description>
        <formula>SBQQ__Product__r.ProductCode</formula>
        <inlineHelpText>Code for the product referenced by this line.</inlineHelpText>
        <label>Product Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product quoted by this line item.</description>
        <inlineHelpText>Product quoted by this line item.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>R00N70000001lXB6EAM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quantity__c</fullName>
        <description>Quantity being quoted.</description>
        <inlineHelpText>Quantity being quoted.</inlineHelpText>
        <label>Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ServicedPricingDocumentGenerator.cls
public with sharing class ServicedPricingDocumentGenerator extends QuoteDocumentParams{
    public SBQQ__Quote__c quoteDetail {get; private set;}
    public List<SBQQ__QuoteLine__c> qliList {get;set;}
    public Map<String,List<SBQQ__QuoteLine__c>> qliTypeMap {get;set;}
    public Map<String, List<SBQQ__QuoteLine__c>> bundleSteppedRentMap { get; set; }
    public String keyString {get;set;}
    public String quoteId {get;set;}
    public Boolean isSuiteProductAdded { get; set; }
    public List<ProductRow> additionalProducts {set;}
    public String suiteType {get;set;}
    public Integer numberOfWorkstations { get; set; }

    public class ProductRow {
        public String ProductName {get;set;}
        public String ProductDescription {get;set;}

        public ProductRow(String ProductName, String ProductDescription) {
            this.ProductName = ProductName;
            this.ProductDescription = ProductDescription;
        }

    }
    public ServicedPricingDocumentGenerator() {
        quoteId = ApexPages.currentPage().getParameters().get('id');
    }

    public PageReference init() {
        quoteDetail = DocumentGenerationHelper.getQuoteDetails(quoteId);
        qliList = DocumentGenerationHelper.getQuoteLines(quoteId);
        qliTypeMap = DocumentGenerationHelper.obtainMapProducts(qliList);
        keyString = DocumentGenerationHelper.obtainCodes(qliTypeMap);
        suiteType = DocumentGenerationHelper.getSuiteType(qliList);
        isSuiteProductAdded = suiteType != null;
        bundleSteppedRentMap = DocumentGenerationHelper.getBundleProductMap(ProductService.PRODUCT_CODE_STEPPED_RENT, qliList);
        if (bundleSteppedRentMap.size() > 0) {
            qliTypeMap.put(ProductService.PRODUCT_CODE_STEPPED_RENT,
                    DocumentGenerationHelper.addFullPriceSteps(bundleSteppedRentMap.get(qliTypeMap.get(suiteType)[0].Id),
                            qliTypeMap.get(suiteType)[0]));
        }
//        for (SBQQ__QuoteLine__c allSteps : DocumentGenerationHelper.addFullPriceSteps(bundleSteppedRentMap.get(qliTypeMap.get(suiteType)[0].Id),
//                qliTypeMap.get(suiteType)[0])) {
//            System.debug('--->' + allSteps);
//        }
        numberOfWorkstations = calculateNumberOfWorkstations(qliList);

//        System.debug('keymap--->' + keyString + ' ++'+ suiteType);
//
//        for (String key: qliTypeMap.keySet()){
//            System.debug(key+ ' -> '+ qliTypeMap.get(key));
//        }

        return null;
    }

    public List<ProductRow>  getAdditionalProducts() {
        List<ProductRow> additionalProducts = new List<ProductRow>();
        for (String key: qliTypeMap.keySet()) {

            if (key == ProductService.PRODUCT_CODE_CAR_PARKING_LEASE) {
                additionalProducts.add(new ProductRow(qliTypeMap.get(key).get(0).SBQQ__Quantity__c.setScale(0) + ' car parking space(s):',
                        NumberUtils.convertToCurrency(qliTypeMap.get(key).get(0).Monthly_Cost__c) + ' per space pcm + VAT'));
            }


            if (key.contains('BSDM')) {
                additionalProducts.add(new ProductRow(qliTypeMap.get(key).get(0).SBQQ__Product__r.Name + ':',
                            NumberUtils.convertToCurrency(qliTypeMap.get(key).get(0).Monthly_Average_Without_Discount__c)  + ' pcm + VAT'));
                }

            if (key == 'BSII') {
                additionalProducts.add(new ProductRow(qliTypeMap.get(key).get(0).SBQQ__Product__r.Name + ':',
                        NumberUtils.convertToCurrency(qliTypeMap.get(key).get(0).Monthly_Average_Without_Discount__c) + ' per person pcm + VAT'));
            }

        }

        return additionalProducts;
    }

    private Integer calculateNumberOfWorkstations(List<SBQQ__QuoteLine__c> quoteLines) {
        Integer numberOfWorkstations = 0;
        Set<String> productCodesWithQuantity = new Set<String>{QuoteProductCodes.SERVICE_LICENCE_FEE, QuoteProductCodes.ADDITIONAL_DESKS, QuoteProductCodes.CO_WORKING_HOT_DESK_LICENCE_FEE};
        for ( SBQQ__QuoteLine__c quoteLine : quoteLines ) {
            if ( quoteLine.SBQQ__ProductCode__c == QuoteProductCodes.DEDICATED_DESK_SPACE ) {
                numberOfWorkstations += 1;
            } else if ( productCodesWithQuantity.contains(quoteLine.SBQQ__ProductCode__c) ) {
                numberOfWorkstations += Integer.valueOf(quoteLine.SBQQ__Quantity__c);
            }
        }
        return numberOfWorkstations;
    }


}