src/objects/SBQQ__ProductFeature__c.object
<CustomObject>
    <customHelpPage>SBQQ__ProductFeatureHelp</customHelpPage>
    <description>Feature of a configurable product that consists of one or more options. Features are configured by selecting one or more options.</description>
    <label>Product Feature</label>
    <nameField>
        <label>Feature Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Features</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__ProductOption__c.object
<CustomObject>
    <customHelpPage>SBQQ__ProductOptionHelp</customHelpPage>
    <description>Option for a configurable product.</description>
    <fields>
        <fullName>SBQQ__Feature__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Feature that selects this option.</description>
        <inlineHelpText>Enter or lookup the feature that includes this option. This will be dependent on the Configured SKU.</inlineHelpText>
        <label>Feature</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.SBQQ__ConfiguredSKU__c</field>
                <operation>equals</operation>
                <valueField>SBQQ__ProductFeature__c.SBQQ__ConfiguredSKU__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SBQQ__ProductFeature__c</referenceTo>
        <relationshipLabel>Product Options</relationshipLabel>
        <relationshipName>ProductOptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Option</label>
    <nameField>
        <displayFormat>PO-{000000}</displayFormat>
        <label>Option Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>SBQQ__ProductOption__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product option that generated this line (if any).</description>
        <inlineHelpText>Product option that generated this line (if any).</inlineHelpText>
        <label>Product Option</label>
        <referenceTo>SBQQ__ProductOption__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>Quote_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ServicedSpaceLicenceAgreementGenerator.cls
public class ServicedSpaceLicenceAgreementGenerator extends QuoteDocumentParams {

    public SBQQ__Quote__c quote { get; set; }
    public Map<String, List<SBQQ__QuoteLine__c>> mapProducts { get; set; }
    public String codes { get; set; }
    public Boolean isSuiteProductAdded { get; set; }
    public String callHandlingScheduleNames {get; set;}
    public Map<String, List<SBQQ__QuoteLine__c>> bundleSteppedRentMap { get; set; }
    public List<SBQQ__QuoteLine__c> carParkingLicences { get; set; }

    public ServicedSpaceLicenceAgreementGenerator() {
        Id quoteId = (Id) ApexPages.currentPage().getParameters().get('id');
        quote = DocumentGenerationHelper.getQuoteDetails(quoteId);
        List<SBQQ__QuoteLine__c> lineItems = DocumentGenerationHelper.getQuoteLines(quoteId);
        mapProducts = DocumentGenerationHelper.obtainMapProducts(lineItems);
        codes = DocumentGenerationHelper.obtainCodes(mapProducts);
        //carParkingLicences = obtainCarParkingLicences(lineItems);
        carParkingLicences = DocumentGenerationHelper.getBundleProductMap(ProductService.CAR_PARKING_LICENCE_CODE,
                lineItems).get(mapProducts.get(ProductService.PRODUCT_CODE_SERVICED)[0].Id);
        bundleSteppedRentMap = DocumentGenerationHelper.getBundleProductMap(ProductService.PRODUCT_CODE_STEPPED_RENT, lineItems);
        if (bundleSteppedRentMap.size() > 0) {
            mapProducts.put(ProductService.PRODUCT_CODE_STEPPED_RENT,
                    DocumentGenerationHelper.addFullPriceSteps(bundleSteppedRentMap.get(mapProducts.get(ProductService.PRODUCT_CODE_SERVICED)[0].Id),
                            mapProducts.get(ProductService.PRODUCT_CODE_SERVICED)[0]));
        }

        isSuiteProductAdded = DocumentGenerationHelper.getSuiteType(lineItems) != null;
        setCallHandlingScheduleNames();
    }

    public void setCallHandlingScheduleNames(){
        callHandlingScheduleNames = ' ';
        if (codes.contains(ProductService.CALL_HANDLING_CODE)){
            for (SBQQ__QuoteLine__c line : mapProducts.get(ProductService.CALL_HANDLING_CODE))
            {
                callHandlingScheduleNames += line.SBQQ__ProductOption__r.SBQQ__Feature__r.name;
            }
        }
    }

}