src/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>SBQQ__Bundle__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether this line item represents a package; meaning, it includes other line items in this quote.</description>
        <inlineHelpText>Indicates whether this line item represents a package; meaning, it includes other line items in this quote.</inlineHelpText>
        <label>Package</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__ProductCode__c</fullName>
        <description>Code for the product referenced by this line.</description>
        <formula>SBQQ__Product__r.ProductCode</formula>
        <inlineHelpText>Code for the product referenced by this line.</inlineHelpText>
        <label>Product Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ConventionalQuoteDocumentGenerator.cls
public class ConventionalQuoteDocumentGenerator extends AbstractQuoteDocumentGenerator {

    public static final String PRICING_DOCUMENT_NAME = 'Pricing Document';
    public static final String TERMS_DOCUMENT_NAME = 'Terms Document';

    public override void updateAdditionalDocuments(SBQQ__Quote__c quote, Map<String, String> documentParams) {
        List<SBQQ__QuoteLine__c> lines = [SELECT Id, SBQQ__ProductCode__c, SBQQ__Bundle__c FROM SBQQ__QuoteLine__c WHERE SBQQ__Quote__c = :quote.Id];
        removePreviousDocumentVersion(quote, new Set<String>{
                PRICING_DOCUMENT_NAME, TERMS_DOCUMENT_NAME, CAR_PARKING_DOCUMENT_NAME
        });
        if (SBQQ_QuoteService.getHeadLineSuiteItems(quote.Id).size() > 0) {
            generateNewDocumentVersion(quote, Page.ConventionalPricingDocumentGenerator, PRICING_DOCUMENT_NAME, 0);
            generateNewTermsDocument(quote, documentParams);
        }
        generateCarParkingLicenceDocument(quote, lines, documentParams, 2, true);
    }

    private void generateNewTermsDocument(SBQQ__Quote__c quote, Map<String, String> params) {
        generateNewDocumentVersion(quote, Page.ConventionalTermDocumentGenerator, TERMS_DOCUMENT_NAME, params, 1, isDocumentRequired(params) );
    }
}