src/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>SBQQ__ProductCode__c</fullName>
        <description>Code for the product referenced by this line.</description>
        <formula>SBQQ__Product__r.ProductCode</formula>
        <inlineHelpText>Code for the product referenced by this line.</inlineHelpText>
        <label>Product Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/VirtualLicAgreementGenerator.cls
public with sharing class VirtualLicAgreementGenerator extends QuoteDocumentParams {

    public static final String HEADLINE_PRODUCTS_CODES = 'BVLF,BVLM';

    public SBQQ__Quote__c quoteDetail {get; private set;}
    public List<SBQQ__QuoteLine__c> qliList {get; set;}
    public Map<String,List<SBQQ__QuoteLine__c>> qliTypeMap {get; set;}
    public String keyString {get; set;}
    public String quoteId {get; set;}
//    public Boolean isHeadlineProductAdded { get; set; }
    public SBQQ__QuoteLine__c headlineProductLine {get; set;}

    public VirtualLicAgreementGenerator() {
        quoteId = ApexPages.currentPage().getParameters().get('id');
    }

    public PageReference init() {
        quoteDetail = DocumentGenerationHelper.getQuoteDetails(quoteId);

        qliList = DocumentGenerationHelper.getQuoteLines(quoteId);

        qliTypeMap = getQuoteLineByType(qliList);

//        System.debug('keymap--->' + keyString);
//
//        for (String key: qliTypeMap.keySet()){
//            System.debug(key+ ' -> '+ qliTypeMap.get(key));
//        }

        return null;
    }

    private Map<String, List<SBQQ__QuoteLine__c>> getQuoteLineByType(List<SBQQ__QuoteLine__c> quoteLines){
        Map<String, List<SBQQ__QuoteLine__c>> qliByType = new Map<String, List<SBQQ__QuoteLine__c>>();
        keyString = ' ';
        for (SBQQ__QuoteLine__c qLI: quoteLines) {
            if(qliByType.containsKey(qLI.SBQQ__ProductCode__c)){
                List<SBQQ__QuoteLine__c> qList = qliByType.get(qLI.SBQQ__ProductCode__c);
                qList.add(qLI);
                qliByType.put(qLI.SBQQ__ProductCode__c,qList);
            } else {
                qliByType.put(qLI.SBQQ__ProductCode__c, new List<SBQQ__QuoteLine__c> {qLI});
                keyString += qLI.SBQQ__ProductCode__c +', ';
            }

            if (HEADLINE_PRODUCTS_CODES.contains(qLI.SBQQ__ProductCode__c)) {
                headlineProductLine = qLI;
            }

        }

        return qliByType;
    }

}