src/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__RelatedContent__c.object
<CustomObject>
    <description>Links certain marketing content (datasheets, specifications, case study) to a product or a template.</description>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote related to this content.</description>
        <inlineHelpText>Quote related to this content.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipName>RelatedContent</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Additional Document</label>
    <nameField>
        <label>Additional Document</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Additional Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PreGenerateDocumentPageControllerTest.cls
@isTest
public class PreGenerateDocumentPageControllerTest {
    @isTest
    static void testDocumentGenerationForServicedQuote() {
        //given
        SBQQ__Quote__c quote = RecordDmlTest.generateServicedQuoteWithLines();
        ApexPages.StandardController sc = new ApexPages.StandardController(quote);
        PreGenerateDocumentPageController documentController = new PreGenerateDocumentPageController(sc);
        documentController.sendFor = 'signature';

        //when
        documentController.goToGenerateDocumentPage();

        //then
        System.assertEquals(1, [SELECT COUNT() FROM SBQQ__RelatedContent__c WHERE SBQQ__Quote__c = :quote.Id AND Name = :ServicedQuoteDocumentGenerator.DIRECT_DEBIT_DOCUMENT_NAME], 'Direct Debit document has not been created');
    }

    @isTest
    static void testDocumentGenerationForVirtualQuote() {
        //given
        SBQQ__Quote__c quote = RecordDmlTest.generateVirtualQuoteWithLines();
        ApexPages.StandardController sc = new ApexPages.StandardController(quote);
        PreGenerateDocumentPageController documentController = new PreGenerateDocumentPageController(sc);
        documentController.sendFor = 'signature';

        //when
        documentController.goToGenerateDocumentPage();

        //then
        System.assertEquals(1, [SELECT COUNT() FROM SBQQ__RelatedContent__c WHERE SBQQ__Quote__c = :quote.Id AND Name = :VirtualQuoteDocumentGenerator.DIRECT_DEBIT_DOCUMENT_NAME], 'Direct Debit document has not been created');
    }

    @isTest
    static void testDocumentGenerationReviewForServicedQuote() {
        //given
        SBQQ__Quote__c quote = RecordDmlTest.generateServicedQuoteWithLines();
        ApexPages.StandardController sc = new ApexPages.StandardController(quote);
        PreGenerateDocumentPageController documentController = new PreGenerateDocumentPageController(sc);
        documentController.sendFor = 'review';

        //when
        documentController.goToGenerateDocumentPage();

        //then
        System.assertEquals(1, [SELECT COUNT() FROM SBQQ__RelatedContent__c WHERE SBQQ__Quote__c = :quote.Id AND Name = :ServicedQuoteDocumentGenerator.DIRECT_DEBIT_DOCUMENT_NAME], 'Direct Debit document has not been created');
    }

    @isTest
    static void testDocumentGenerationReviewForVirtualQuote() {
        //given
        SBQQ__Quote__c quote = RecordDmlTest.generateVirtualQuoteWithLines();
        ApexPages.StandardController sc = new ApexPages.StandardController(quote);
        PreGenerateDocumentPageController documentController = new PreGenerateDocumentPageController(sc);
        documentController.sendFor = 'review';

        //when
        documentController.goToGenerateDocumentPage();

        //then
        System.assertEquals(1, [SELECT COUNT() FROM SBQQ__RelatedContent__c WHERE SBQQ__Quote__c = :quote.Id AND Name = :VirtualQuoteDocumentGenerator.DIRECT_DEBIT_DOCUMENT_NAME], 'Direct Debit document has not been created');
    }

    @isTest
    static void testDocumentGenerationForConvQuote() {
        //given
        SBQQ__Quote__c quote = RecordDmlTest.generateConventionalQuoteWithLines(QuoteProductCodes.OFFICE_RENT);
        ApexPages.StandardController sc = new ApexPages.StandardController(quote);
        PreGenerateDocumentPageController documentController = new PreGenerateDocumentPageController(sc);
        documentController.sendFor = 'signature';

        //when
        documentController.goToGenerateDocumentPage();

        //then
        System.assertEquals(1, [SELECT COUNT() FROM SBQQ__RelatedContent__c WHERE SBQQ__Quote__c = :quote.Id AND Name = :ConventionalQuoteDocumentGenerator.PRICING_DOCUMENT_NAME], 'Pricing document has not been created');
    }

    @isTest
    static void testDocumentGenerationReviewForConvQuote() {
        //given
        SBQQ__Quote__c quote = RecordDmlTest.generateConventionalQuoteWithLines(QuoteProductCodes.OFFICE_RENT);
        ApexPages.StandardController sc = new ApexPages.StandardController(quote);
        PreGenerateDocumentPageController documentController = new PreGenerateDocumentPageController(sc);
        documentController.sendFor = 'review';

        //when
        documentController.goToGenerateDocumentPage();

        //then
        System.assertEquals(1, [SELECT COUNT() FROM SBQQ__RelatedContent__c WHERE SBQQ__Quote__c = :quote.Id AND Name = :ConventionalQuoteDocumentGenerator.PRICING_DOCUMENT_NAME], 'Pricing document has not been created');
    }
}