src/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <recordTypes>
        <fullName>Serviced</fullName>
        <active>true</active>
        <label>Serviced</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>SBQQ__Bundle__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether this line item represents a package; meaning, it includes other line items in this quote.</description>
        <inlineHelpText>Indicates whether this line item represents a package; meaning, it includes other line items in this quote.</inlineHelpText>
        <label>Package</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__ProductCode__c</fullName>
        <description>Code for the product referenced by this line.</description>
        <formula>SBQQ__Product__r.ProductCode</formula>
        <inlineHelpText>Code for the product referenced by this line.</inlineHelpText>
        <label>Product Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ServicedQuoteDocumentGenerator.cls
public class ServicedQuoteDocumentGenerator extends AbstractQuoteDocumentGenerator {

    public static final String PRICING_DOCUMENT_NAME = 'Pricing Document';
    public static final String LICENCE_AGREEMENT_DOCUMENT_NAME = 'Serviced Space Licence Agreement';
    public static final String DIRECT_DEBIT_DOCUMENT_NAME = 'Direct Debit Form';
    public static final String FAIR_USAGE_POLICY = 'Fair Usage Policy';
    public static final String CO_WORKING_DEDICATED_LICENCE_AGREEMENT_DOCUMENT_NAME = 'Co-Working Dedicated Licence Agreement';
    public static final String CO_WORKING_HOT_DESK_LICENCE_AGREEMENT_DOCUMENT_NAME = 'Co-Working Hot Desk Licence Agreement';

    public override void updateAdditionalDocuments(SBQQ__Quote__c quote, Map<String, String> documentParams) {
        List<SBQQ__QuoteLine__c> lines = [SELECT Id, SBQQ__ProductCode__c, SBQQ__Bundle__c FROM SBQQ__QuoteLine__c WHERE SBQQ__Quote__c = :quote.Id];
        removePreviousDocumentVersion(quote, new Set<String>{
                PRICING_DOCUMENT_NAME, LICENCE_AGREEMENT_DOCUMENT_NAME, DIRECT_DEBIT_DOCUMENT_NAME, FAIR_USAGE_POLICY, CO_WORKING_DEDICATED_LICENCE_AGREEMENT_DOCUMENT_NAME, CO_WORKING_HOT_DESK_LICENCE_AGREEMENT_DOCUMENT_NAME, CAR_PARKING_DOCUMENT_NAME
        });
        if (SBQQ_QuoteService.getHeadLineSuiteItems(quote.Id).size() > 0) {
            generateNewDocumentVersion(quote, Page.ServicedPricingDocumentGenerator, PRICING_DOCUMENT_NAME, 0);
        }
        generateNewLicenceAgreementDocument(quote, lines, documentParams);
        generateNewDirectDebitDocument(quote);
        generateNewFairUsagePolicyDocument(quote);
        generateCarParkingLicenceDocument(quote, lines, documentParams, 5, true);
        generateCoWorkingDedicatedLicenceAgreement(quote, lines, documentParams);
        generateCoWorkingHotDeskLicenceAgreement(quote, lines, documentParams);
    }

    private void generateNewLicenceAgreementDocument(SBQQ__Quote__c quote, List<SBQQ__QuoteLine__c> lines, Map<String, String> params) {
        if (SBQQ_QuoteService.isHeadLineProductAdded(lines, QuoteProductCodes.SERVICE_LICENCE_FEE)) {
            //For signature process, Licence Agreement Document should be required for sending
            generateNewDocumentVersion(quote, Page.ServicedSpaceLicenceAgreementPage, LICENCE_AGREEMENT_DOCUMENT_NAME, params, 1, isDocumentRequired(params));
        }
    }

    private void generateCoWorkingDedicatedLicenceAgreement(SBQQ__Quote__c quote, List<SBQQ__QuoteLine__c> lines, Map<String, String> params) {
        if (SBQQ_QuoteService.isHeadLineProductAdded(lines, QuoteProductCodes.CO_WORKING_DEDICATED_LICENCE_FEE)) {
            generateNewDocumentVersion(quote, Page.CoWorkingDedicatedLicenceAgreement, CO_WORKING_DEDICATED_LICENCE_AGREEMENT_DOCUMENT_NAME, params, isDocumentRequired(params));
        }
    }

    private void generateCoWorkingHotDeskLicenceAgreement(SBQQ__Quote__c quote, List<SBQQ__QuoteLine__c> lines, Map<String, String> params) {
        if (SBQQ_QuoteService.isHeadLineProductAdded(lines, QuoteProductCodes.CO_WORKING_HOT_DESK_LICENCE_FEE)) {
            generateNewDocumentVersion(quote, Page.CoWorkingHotDeskLicenceAgreement, CO_WORKING_HOT_DESK_LICENCE_AGREEMENT_DOCUMENT_NAME, params, isDocumentRequired(params));
        }
    }

    private void generateNewFairUsagePolicyDocument(SBQQ__Quote__c quote) {
        List<Document> documents = [SELECT Id FROM Document WHERE DeveloperName = 'Fair_Usage_Policy' LIMIT 1];
        if (!documents.isEmpty()) {
            generateNewDocumentVersion(quote, documents.get(0).Id, FAIR_USAGE_POLICY, 3);
        }
    }
}