src/objects/smagicinteract__Incoming_SMS__c.object
<CustomObject>
    <customHelpPage>smagicinteract__SMSMagicHelp</customHelpPage>
    <fields>
        <fullName>Mobile_Number_Formatted__c</fullName>
        <description>Converts UK mobile number to 07490168640 format (For example: 447490168640 -&gt; 07490168640).
The formatting needs for comparing the value with Mobile number fields on Contact/Lead object.</description>
        <formula>IF(BEGINS(smagicinteract__Mobile_Number__c, &apos;+44&apos;), &apos;0&apos; + MID(smagicinteract__Mobile_Number__c, 4, LEN(smagicinteract__Mobile_Number__c)), IF(BEGINS(smagicinteract__Mobile_Number__c, &apos;44&apos;), &apos;0&apos; + MID(smagicinteract__Mobile_Number__c, 3, LEN(smagicinteract__Mobile_Number__c)), smagicinteract__Mobile_Number__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Mobile Number Formatted</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>smagicinteract__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Incoming SMS</relationshipLabel>
        <relationshipName>Incoming_SMS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>smagicinteract__Inbound_Number__c</fullName>
        <description>You can receive incoming sms to this number.</description>
        <label>Inbound Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>smagicinteract__Mobile_Number__c</fullName>
        <label>Mobile Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>smagicinteract__SMS_Text__c</fullName>
        <label>SMS Text</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>smagicinteract__Sent_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sent By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Incoming_SMS</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Incoming SMS</label>
    <nameField>
        <displayFormat>I-{00000000}</displayFormat>
        <label>Incoming SMS Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incoming SMS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/IncomingSMSFlowAction.cls
public with sharing class IncomingSMSFlowAction {

    @InvocableMethod
    public static void incomingSMSFlowAction(List<Id> incSMSId) {
        //This method catch all incoming smsand start notification process to sales managers or update Viewing__c

        List<smagicinteract__Incoming_SMS__c> incSMS = [
                SELECT Id, smagicinteract__Contact__c, smagicinteract__Inbound_Number__c,
                        smagicinteract__Mobile_Number__c, smagicinteract__Sent_By__c, smagicinteract__SMS_Text__c, Mobile_Number_Formatted__c
                FROM smagicinteract__Incoming_SMS__c
                WHERE Id IN :incSMSId
                LIMIT 10000
        ];
        IncomingSMSHandler.getConfirmationAction(incSMS);
    }
}